package org.matheclipse.core.expression;

import org.matheclipse.core.interfaces.IBuiltInSymbol;

public enum BuiltIns {
 Abort( "abort", 0 ), //
 Abs( "abs", 1 ), //
 AbsArg( "absarg", 2 ), //
 Accumulate( "accumulate", 3 ), //
 AddTo( "addto", 4 ), //
 AlgebraicNumber( "algebraicnumber", 5 ), //
 Algebraics( "algebraics", 6 ), //
 All( "all", 7 ), //
 AllTrue( "alltrue", 8 ), //
 Alternatives( "alternatives", 9 ), //
 And( "and", 10 ), //
 AngleVector( "anglevector", 11 ), //
 AntihermitianMatrixQ( "antihermitianmatrixq", 12 ), //
 AntisymmetricMatrixQ( "antisymmetricmatrixq", 13 ), //
 AnyTrue( "anytrue", 14 ), //
 Apart( "apart", 15 ), //
 AppellF1( "appellf1", 16 ), //
 Append( "append", 17 ), //
 AppendTo( "appendto", 18 ), //
 Apply( "apply", 19 ), //
 ArcCos( "arccos", 20 ), //
 ArcCosh( "arccosh", 21 ), //
 ArcCot( "arccot", 22 ), //
 ArcCoth( "arccoth", 23 ), //
 ArcCsc( "arccsc", 24 ), //
 ArcCsch( "arccsch", 25 ), //
 ArcSec( "arcsec", 26 ), //
 ArcSech( "arcsech", 27 ), //
 ArcSin( "arcsin", 28 ), //
 ArcSinh( "arcsinh", 29 ), //
 ArcTan( "arctan", 30 ), //
 ArcTanh( "arctanh", 31 ), //
 Arg( "arg", 32 ), //
 Array( "array", 33 ), //
 ArrayDepth( "arraydepth", 34 ), //
 ArrayPad( "arraypad", 35 ), //
 ArrayQ( "arrayq", 36 ), //
 Assumptions( "assumptions", 37 ), //
 AtomQ( "atomq", 38 ), //
 Attributes( "attributes", 39 ), //
 Automatic( "automatic", 40 ), //
 Axes( "axes", 41 ), //
 AxesOrigin( "axesorigin", 42 ), //
 AxesStyle( "axesstyle", 43 ), //
 Background( "background", 44 ), //
 Begin( "begin", 45 ), //
 BeginPackage( "beginpackage", 46 ), //
 BellB( "bellb", 47 ), //
 BellY( "belly", 48 ), //
 BernoulliB( "bernoullib", 49 ), //
 BernoulliDistribution( "bernoullidistribution", 50 ), //
 BesselI( "besseli", 51 ), //
 BesselJ( "besselj", 52 ), //
 BesselK( "besselk", 53 ), //
 BesselY( "bessely", 54 ), //
 Beta( "beta", 55 ), //
 BetaRegularized( "betaregularized", 56 ), //
 BinCounts( "bincounts", 57 ), //
 Binomial( "binomial", 58 ), //
 BinomialDistribution( "binomialdistribution", 59 ), //
 BitLength( "bitlength", 60 ), //
 Blank( "blank", 61 ), //
 Block( "block", 62 ), //
 Boole( "boole", 63 ), //
 BooleanConvert( "booleanconvert", 64 ), //
 BooleanMinimize( "booleanminimize", 65 ), //
 BooleanQ( "booleanq", 66 ), //
 BooleanTable( "booleantable", 67 ), //
 BooleanVariables( "booleanvariables", 68 ), //
 Booleans( "booleans", 69 ), //
 BrayCurtisDistance( "braycurtisdistance", 70 ), //
 Break( "break", 71 ), //
 CDF( "cdf", 72 ), //
 CanberraDistance( "canberradistance", 73 ), //
 Cancel( "cancel", 74 ), //
 CarmichaelLambda( "carmichaellambda", 75 ), //
 CartesianProduct( "cartesianproduct", 76 ), //
 Cases( "cases", 77 ), //
 Catalan( "catalan", 78 ), //
 CatalanNumber( "catalannumber", 79 ), //
 Catch( "catch", 80 ), //
 Catenate( "catenate", 81 ), //
 Ceiling( "ceiling", 82 ), //
 CentralMoment( "centralmoment", 83 ), //
 CharacterEncoding( "characterencoding", 84 ), //
 CharacteristicPolynomial( "characteristicpolynomial", 85 ), //
 ChebyshevT( "chebyshevt", 86 ), //
 ChebyshevU( "chebyshevu", 87 ), //
 ChessboardDistance( "chessboarddistance", 88 ), //
 ChineseRemainder( "chineseremainder", 89 ), //
 CholeskyDecomposition( "choleskydecomposition", 90 ), //
 Chop( "chop", 91 ), //
 CirclePoints( "circlepoints", 92 ), //
 Clear( "clear", 93 ), //
 ClearAll( "clearall", 94 ), //
 ClearAttributes( "clearattributes", 95 ), //
 Clip( "clip", 96 ), //
 Coefficient( "coefficient", 97 ), //
 CoefficientList( "coefficientlist", 98 ), //
 CoefficientRules( "coefficientrules", 99 ), //
 Collect( "collect", 100 ), //
 Colon( "colon", 101 ), //
 Commonest( "commonest", 102 ), //
 Compile( "compile", 103 ), //
 Complement( "complement", 104 ), //
 Complex( "complex", 105 ), //
 ComplexExpand( "complexexpand", 106 ), //
 ComplexInfinity( "complexinfinity", 107 ), //
 Complexes( "complexes", 108 ), //
 ComplexityFunction( "complexityfunction", 109 ), //
 ComposeList( "composelist", 110 ), //
 Composition( "composition", 111 ), //
 CompoundExpression( "compoundexpression", 112 ), //
 Condition( "condition", 113 ), //
 Conjugate( "conjugate", 114 ), //
 ConjugateTranspose( "conjugatetranspose", 115 ), //
 Constant( "constant", 116 ), //
 ConstantArray( "constantarray", 117 ), //
 Continue( "continue", 118 ), //
 ContinuedFraction( "continuedfraction", 119 ), //
 ConvexHullMesh( "convexhullmesh", 120 ), //
 CoprimeQ( "coprimeq", 121 ), //
 Correlation( "correlation", 122 ), //
 Cos( "cos", 123 ), //
 CosIntegral( "cosintegral", 124 ), //
 Cosh( "cosh", 125 ), //
 CoshIntegral( "coshintegral", 126 ), //
 CosineDistance( "cosinedistance", 127 ), //
 Cot( "cot", 128 ), //
 Coth( "coth", 129 ), //
 Count( "count", 130 ), //
 Covariance( "covariance", 131 ), //
 Cross( "cross", 132 ), //
 Csc( "csc", 133 ), //
 Csch( "csch", 134 ), //
 CubeRoot( "cuberoot", 135 ), //
 Curl( "curl", 136 ), //
 D( "D", 137 ), //
 DSolve( "dsolve", 138 ), //
 Decrement( "decrement", 139 ), //
 Default( "default", 140 ), //
 Defer( "defer", 141 ), //
 Definition( "definition", 142 ), //
 Degree( "degree", 143 ), //
 Delete( "delete", 144 ), //
 DeleteCases( "deletecases", 145 ), //
 DeleteDuplicates( "deleteduplicates", 146 ), //
 Denominator( "denominator", 147 ), //
 Depth( "depth", 148 ), //
 Derivative( "derivative", 149 ), //
 DesignMatrix( "designmatrix", 150 ), //
 Det( "det", 151 ), //
 Diagonal( "diagonal", 152 ), //
 DiagonalMatrix( "diagonalmatrix", 153 ), //
 DiceDissimilarity( "dicedissimilarity", 154 ), //
 DigitQ( "digitq", 155 ), //
 Dimensions( "dimensions", 156 ), //
 DiracDelta( "diracdelta", 157 ), //
 DirectedInfinity( "directedinfinity", 158 ), //
 Direction( "direction", 159 ), //
 DiscreteDelta( "discretedelta", 160 ), //
 DiscreteUniformDistribution( "discreteuniformdistribution", 161 ), //
 Discriminant( "discriminant", 162 ), //
 Disputed( "disputed", 163 ), //
 Distribute( "distribute", 164 ), //
 Divergence( "divergence", 165 ), //
 Divide( "divide", 166 ), //
 DivideBy( "divideby", 167 ), //
 Divisible( "divisible", 168 ), //
 DivisorSigma( "divisorsigma", 169 ), //
 Divisors( "divisors", 170 ), //
 Do( "do", 171 ), //
 Dot( "dot", 172 ), //
 Drop( "drop", 173 ), //
 E( "E", 174 ), //
 EasterSunday( "eastersunday", 175 ), //
 Eigenvalues( "eigenvalues", 176 ), //
 Eigenvectors( "eigenvectors", 177 ), //
 Element( "element", 178 ), //
 ElementData( "elementdata", 179 ), //
 Eliminate( "eliminate", 180 ), //
 EllipticE( "elliptice", 181 ), //
 EllipticF( "ellipticf", 182 ), //
 EllipticPi( "ellipticpi", 183 ), //
 End( "end", 184 ), //
 EndPackage( "endpackage", 185 ), //
 Equal( "equal", 186 ), //
 Equivalent( "equivalent", 187 ), //
 Erf( "erf", 188 ), //
 Erfc( "erfc", 189 ), //
 Erfi( "erfi", 190 ), //
 ErlangDistribution( "erlangdistribution", 191 ), //
 EuclideanDistance( "euclideandistance", 192 ), //
 EulerE( "eulere", 193 ), //
 EulerGamma( "eulergamma", 194 ), //
 EulerPhi( "eulerphi", 195 ), //
 EvenQ( "evenq", 196 ), //
 ExactNumberQ( "exactnumberq", 197 ), //
 Except( "except", 198 ), //
 Exists( "exists", 199 ), //
 Exp( "exp", 200 ), //
 ExpIntegralE( "expintegrale", 201 ), //
 ExpIntegralEi( "expintegralei", 202 ), //
 Expand( "expand", 203 ), //
 ExpandAll( "expandall", 204 ), //
 Expectation( "expectation", 205 ), //
 Exponent( "exponent", 206 ), //
 ExponentialDistribution( "exponentialdistribution", 207 ), //
 Export( "export", 208 ), //
 ExtendedGCD( "extendedgcd", 209 ), //
 Extract( "extract", 210 ), //
 Factor( "factor", 211 ), //
 FactorInteger( "factorinteger", 212 ), //
 FactorSquareFree( "factorsquarefree", 213 ), //
 FactorSquareFreeList( "factorsquarefreelist", 214 ), //
 FactorTerms( "factorterms", 215 ), //
 Factorial( "factorial", 216 ), //
 Factorial2( "factorial2", 217 ), //
 False( "false", 218 ), //
 Fibonacci( "fibonacci", 219 ), //
 FindInstance( "findinstance", 220 ), //
 FindRoot( "findroot", 221 ), //
 First( "first", 222 ), //
 Fit( "fit", 223 ), //
 FixedPoint( "fixedpoint", 224 ), //
 FixedPointList( "fixedpointlist", 225 ), //
 Flat( "flat", 226 ), //
 Flatten( "flatten", 227 ), //
 FlattenAt( "flattenat", 228 ), //
 Floor( "floor", 229 ), //
 Fold( "fold", 230 ), //
 FoldList( "foldlist", 231 ), //
 For( "for", 232 ), //
 ForAll( "forall", 233 ), //
 FourierMatrix( "fouriermatrix", 234 ), //
 FractionalPart( "fractionalpart", 235 ), //
 FrechetDistribution( "frechetdistribution", 236 ), //
 FreeQ( "freeq", 237 ), //
 FresnelC( "fresnelc", 238 ), //
 FresnelS( "fresnels", 239 ), //
 FrobeniusSolve( "frobeniussolve", 240 ), //
 FromCharacterCode( "fromcharactercode", 241 ), //
 FromContinuedFraction( "fromcontinuedfraction", 242 ), //
 FromPolarCoordinates( "frompolarcoordinates", 243 ), //
 FullForm( "fullform", 244 ), //
 FullSimplify( "fullsimplify", 245 ), //
 Function( "function", 246 ), //
 GCD( "gcd", 247 ), //
 Gamma( "gamma", 248 ), //
 GammaDistribution( "gammadistribution", 249 ), //
 GammaRegularized( "gammaregularized", 250 ), //
 Gather( "gather", 251 ), //
 GegenbauerC( "gegenbauerc", 252 ), //
 GeometricDistribution( "geometricdistribution", 253 ), //
 GeometricMean( "geometricmean", 254 ), //
 Get( "get", 255 ), //
 Glaisher( "glaisher", 256 ), //
 GoldenRatio( "goldenratio", 257 ), //
 Graphics( "graphics", 258 ), //
 Graphics3D( "graphics3d", 259 ), //
 Greater( "greater", 260 ), //
 GreaterEqual( "greaterequal", 261 ), //
 GroebnerBasis( "groebnerbasis", 262 ), //
 GumbelDistribution( "gumbeldistribution", 263 ), //
 HarmonicNumber( "harmonicnumber", 264 ), //
 Haversine( "haversine", 265 ), //
 Head( "head", 266 ), //
 HeavisideTheta( "heavisidetheta", 267 ), //
 HermiteH( "hermiteh", 268 ), //
 HermitianMatrixQ( "hermitianmatrixq", 269 ), //
 HilbertMatrix( "hilbertmatrix", 270 ), //
 Hold( "hold", 271 ), //
 HoldAll( "holdall", 272 ), //
 HoldFirst( "holdfirst", 273 ), //
 HoldForm( "holdform", 274 ), //
 HoldRest( "holdrest", 275 ), //
 Horner( "horner", 276 ), //
 HornerForm( "hornerform", 277 ), //
 HurwitzZeta( "hurwitzzeta", 278 ), //
 Hypergeometric1F1( "hypergeometric1f1", 279 ), //
 Hypergeometric2F1( "hypergeometric2f1", 280 ), //
 HypergeometricDistribution( "hypergeometricdistribution", 281 ), //
 HypergeometricPFQ( "hypergeometricpfq", 282 ), //
 HypergeometricPFQRegularized( "hypergeometricpfqregularized", 283 ), //
 I( "I", 284 ), //
 Identity( "identity", 285 ), //
 IdentityMatrix( "identitymatrix", 286 ), //
 If( "if", 287 ), //
 Im( "im", 288 ), //
 Implies( "implies", 289 ), //
 Import( "import", 290 ), //
 Increment( "increment", 291 ), //
 Indeterminate( "indeterminate", 292 ), //
 Inequality( "inequality", 293 ), //
 InexactNumberQ( "inexactnumberq", 294 ), //
 Infinity( "infinity", 295 ), //
 Information( "information", 296 ), //
 Inner( "inner", 297 ), //
 Insert( "insert", 298 ), //
 Integer( "integer", 299 ), //
 IntegerExponent( "integerexponent", 300 ), //
 IntegerLength( "integerlength", 301 ), //
 IntegerPart( "integerpart", 302 ), //
 IntegerPartitions( "integerpartitions", 303 ), //
 IntegerQ( "integerq", 304 ), //
 Integers( "integers", 305 ), //
 Integrate( "integrate", 306 ), //
 InterpolatingFunction( "interpolatingfunction", 307 ), //
 InterpolatingPolynomial( "interpolatingpolynomial", 308 ), //
 Interpolation( "interpolation", 309 ), //
 Intersection( "intersection", 310 ), //
 Interval( "interval", 311 ), //
 Inverse( "inverse", 312 ), //
 InverseErf( "inverseerf", 313 ), //
 InverseErfc( "inverseerfc", 314 ), //
 InverseFunction( "inversefunction", 315 ), //
 InverseHaversine( "inversehaversine", 316 ), //
 InverseLaplaceTransform( "inverselaplacetransform", 317 ), //
 JaccardDissimilarity( "jaccarddissimilarity", 318 ), //
 JacobiMatrix( "jacobimatrix", 319 ), //
 JacobiSymbol( "jacobisymbol", 320 ), //
 JavaForm( "javaform", 321 ), //
 Join( "join", 322 ), //
 KOrderlessPartitions( "korderlesspartitions", 323 ), //
 KPartitions( "kpartitions", 324 ), //
 Khinchin( "khinchin", 325 ), //
 KroneckerDelta( "kroneckerdelta", 326 ), //
 Kurtosis( "kurtosis", 327 ), //
 LCM( "lcm", 328 ), //
 LUDecomposition( "ludecomposition", 329 ), //
 LaguerreL( "laguerrel", 330 ), //
 LaplaceTransform( "laplacetransform", 331 ), //
 Last( "last", 332 ), //
 LeafCount( "leafcount", 333 ), //
 LeastSquares( "leastsquares", 334 ), //
 LegendreP( "legendrep", 335 ), //
 LegendreQ( "legendreq", 336 ), //
 Length( "length", 337 ), //
 Less( "less", 338 ), //
 LessEqual( "lessequal", 339 ), //
 LetterQ( "letterq", 340 ), //
 Level( "level", 341 ), //
 LevelQ( "levelq", 342 ), //
 Limit( "limit", 343 ), //
 Line( "line", 344 ), //
 LinearModelFit( "linearmodelfit", 345 ), //
 LinearProgramming( "linearprogramming", 346 ), //
 LinearSolve( "linearsolve", 347 ), //
 LiouvilleLambda( "liouvillelambda", 348 ), //
 List( "list", 349 ), //
 ListConvolve( "listconvolve", 350 ), //
 ListCorrelate( "listcorrelate", 351 ), //
 ListQ( "listq", 352 ), //
 Listable( "listable", 353 ), //
 Literal( "literal", 354 ), //
 Log( "log", 355 ), //
 Log10( "log10", 356 ), //
 Log2( "log2", 357 ), //
 LogGamma( "loggamma", 358 ), //
 LogIntegral( "logintegral", 359 ), //
 LogNormalDistribution( "lognormaldistribution", 360 ), //
 LogicalExpand( "logicalexpand", 361 ), //
 LogisticSigmoid( "logisticsigmoid", 362 ), //
 LowerCaseQ( "lowercaseq", 363 ), //
 LowerTriangularize( "lowertriangularize", 364 ), //
 LucasL( "lucasl", 365 ), //
 MachineNumberQ( "machinenumberq", 366 ), //
 MangoldtLambda( "mangoldtlambda", 367 ), //
 ManhattanDistance( "manhattandistance", 368 ), //
 MantissaExponent( "mantissaexponent", 369 ), //
 Map( "map", 370 ), //
 MapAll( "mapall", 371 ), //
 MapAt( "mapat", 372 ), //
 MapThread( "mapthread", 373 ), //
 MatchQ( "matchq", 374 ), //
 MatchingDissimilarity( "matchingdissimilarity", 375 ), //
 MathMLForm( "mathmlform", 376 ), //
 MatrixForm( "matrixform", 377 ), //
 MatrixMinimalPolynomial( "matrixminimalpolynomial", 378 ), //
 MatrixPower( "matrixpower", 379 ), //
 MatrixQ( "matrixq", 380 ), //
 MatrixRank( "matrixrank", 381 ), //
 Max( "max", 382 ), //
 MaxIterations( "maxiterations", 383 ), //
 MaxPoints( "maxpoints", 384 ), //
 Mean( "mean", 385 ), //
 MeanDeviation( "meandeviation", 386 ), //
 Median( "median", 387 ), //
 MeijerG( "meijerg", 388 ), //
 MemberQ( "memberq", 389 ), //
 MersennePrimeExponent( "mersenneprimeexponent", 390 ), //
 MersennePrimeExponentQ( "mersenneprimeexponentq", 391 ), //
 MeshRange( "meshrange", 392 ), //
 MessageName( "messagename", 393 ), //
 Method( "method", 394 ), //
 Min( "min", 395 ), //
 MinimalPolynomial( "minimalpolynomial", 396 ), //
 Minus( "minus", 397 ), //
 Missing( "missing", 398 ), //
 MissingQ( "missingq", 399 ), //
 Mod( "mod", 400 ), //
 Module( "module", 401 ), //
 Modulus( "modulus", 402 ), //
 MoebiusMu( "moebiusmu", 403 ), //
 MonomialList( "monomiallist", 404 ), //
 Most( "most", 405 ), //
 Multinomial( "multinomial", 406 ), //
 MultiplicativeOrder( "multiplicativeorder", 407 ), //
 N( "N", 408 ), //
 NDSolve( "ndsolve", 409 ), //
 NFourierTransform( "nfouriertransform", 410 ), //
 NHoldAll( "nholdall", 411 ), //
 NHoldFirst( "nholdfirst", 412 ), //
 NHoldRest( "nholdrest", 413 ), //
 NIntegrate( "nintegrate", 414 ), //
 NMaximize( "nmaximize", 415 ), //
 NMinimize( "nminimize", 416 ), //
 NRoots( "nroots", 417 ), //
 NSolve( "nsolve", 418 ), //
 NakagamiDistribution( "nakagamidistribution", 419 ), //
 Names( "names", 420 ), //
 Nand( "nand", 421 ), //
 Nearest( "nearest", 422 ), //
 Negative( "negative", 423 ), //
 Nest( "nest", 424 ), //
 NestList( "nestlist", 425 ), //
 NestWhile( "nestwhile", 426 ), //
 NestWhileList( "nestwhilelist", 427 ), //
 NextPrime( "nextprime", 428 ), //
 NonCommutativeMultiply( "noncommutativemultiply", 429 ), //
 NonNegative( "nonnegative", 430 ), //
 NonPositive( "nonpositive", 431 ), //
 None( "none", 432 ), //
 NoneTrue( "nonetrue", 433 ), //
 Nonexistent( "nonexistent", 434 ), //
 Nor( "nor", 435 ), //
 Norm( "norm", 436 ), //
 Normal( "normal", 437 ), //
 NormalDistribution( "normaldistribution", 438 ), //
 Normalize( "normalize", 439 ), //
 Not( "not", 440 ), //
 NotApplicable( "notapplicable", 441 ), //
 NotAvailable( "notavailable", 442 ), //
 NotListQ( "notlistq", 443 ), //
 Null( "null", 444 ), //
 NullSpace( "nullspace", 445 ), //
 NumberFieldRootsOfUnity( "numberfieldrootsofunity", 446 ), //
 NumberQ( "numberq", 447 ), //
 Numerator( "numerator", 448 ), //
 NumericFunction( "numericfunction", 449 ), //
 NumericQ( "numericq", 450 ), //
 O( "O", 451 ), //
 OddQ( "oddq", 452 ), //
 OneIdentity( "oneidentity", 453 ), //
 Operate( "operate", 454 ), //
 Optional( "optional", 455 ), //
 Options( "options", 456 ), //
 Or( "or", 457 ), //
 Order( "order", 458 ), //
 OrderedQ( "orderedq", 459 ), //
 Ordering( "ordering", 460 ), //
 Orderless( "orderless", 461 ), //
 OrthogonalMatrixQ( "orthogonalmatrixq", 462 ), //
 Orthogonalize( "orthogonalize", 463 ), //
 Out( "out", 464 ), //
 Outer( "outer", 465 ), //
 PDF( "pdf", 466 ), //
 Package( "package", 467 ), //
 PadLeft( "padleft", 468 ), //
 PadRight( "padright", 469 ), //
 ParametricPlot( "parametricplot", 470 ), //
 Part( "part", 471 ), //
 Partition( "partition", 472 ), //
 PartitionsP( "partitionsp", 473 ), //
 PartitionsQ( "partitionsq", 474 ), //
 Pattern( "pattern", 475 ), //
 PatternTest( "patterntest", 476 ), //
 PerfectNumber( "perfectnumber", 477 ), //
 PerfectNumberQ( "perfectnumberq", 478 ), //
 Permutations( "permutations", 479 ), //
 Pi( "pi", 480 ), //
 Piecewise( "piecewise", 481 ), //
 Plot( "plot", 482 ), //
 Plot3D( "plot3d", 483 ), //
 PlotRange( "plotrange", 484 ), //
 Plus( "plus", 485 ), //
 Pochhammer( "pochhammer", 486 ), //
 Point( "point", 487 ), //
 PoissonDistribution( "poissondistribution", 488 ), //
 PolyGamma( "polygamma", 489 ), //
 PolyLog( "polylog", 490 ), //
 Polygon( "polygon", 491 ), //
 PolynomialExtendedGCD( "polynomialextendedgcd", 492 ), //
 PolynomialGCD( "polynomialgcd", 493 ), //
 PolynomialLCM( "polynomiallcm", 494 ), //
 PolynomialQ( "polynomialq", 495 ), //
 PolynomialQuotient( "polynomialquotient", 496 ), //
 PolynomialQuotientRemainder( "polynomialquotientremainder", 497 ), //
 PolynomialRemainder( "polynomialremainder", 498 ), //
 Position( "position", 499 ), //
 Positive( "positive", 500 ), //
 PossibleZeroQ( "possiblezeroq", 501 ), //
 Power( "power", 502 ), //
 PowerExpand( "powerexpand", 503 ), //
 PowerMod( "powermod", 504 ), //
 PreDecrement( "predecrement", 505 ), //
 PreIncrement( "preincrement", 506 ), //
 PrePlus( "preplus", 507 ), //
 Precision( "precision", 508 ), //
 PrecisionGoal( "precisiongoal", 509 ), //
 Prepend( "prepend", 510 ), //
 PrependTo( "prependto", 511 ), //
 Prime( "prime", 512 ), //
 PrimeOmega( "primeomega", 513 ), //
 PrimePi( "primepi", 514 ), //
 PrimePowerQ( "primepowerq", 515 ), //
 PrimeQ( "primeq", 516 ), //
 Primes( "primes", 517 ), //
 PrimitiveRootList( "primitiverootlist", 518 ), //
 Print( "print", 519 ), //
 Product( "product", 520 ), //
 ProductLog( "productlog", 521 ), //
 Projection( "projection", 522 ), //
 PseudoInverse( "pseudoinverse", 523 ), //
 Put( "put", 524 ), //
 QRDecomposition( "qrdecomposition", 525 ), //
 Quantile( "quantile", 526 ), //
 Quiet( "quiet", 527 ), //
 Quit( "quit", 528 ), //
 Quotient( "quotient", 529 ), //
 QuotientRemainder( "quotientremainder", 530 ), //
 RandomChoice( "randomchoice", 531 ), //
 RandomInteger( "randominteger", 532 ), //
 RandomReal( "randomreal", 533 ), //
 RandomSample( "randomsample", 534 ), //
 RandomVariate( "randomvariate", 535 ), //
 Range( "range", 536 ), //
 Rational( "rational", 537 ), //
 Rationalize( "rationalize", 538 ), //
 Rationals( "rationals", 539 ), //
 Re( "re", 540 ), //
 Real( "real", 541 ), //
 RealNumberQ( "realnumberq", 542 ), //
 Reals( "reals", 543 ), //
 Reap( "reap", 544 ), //
 Rectangle( "rectangle", 545 ), //
 Reduce( "reduce", 546 ), //
 Refine( "refine", 547 ), //
 Repeated( "repeated", 548 ), //
 RepeatedNull( "repeatednull", 549 ), //
 Replace( "replace", 550 ), //
 ReplaceAll( "replaceall", 551 ), //
 ReplaceList( "replacelist", 552 ), //
 ReplacePart( "replacepart", 553 ), //
 ReplaceRepeated( "replacerepeated", 554 ), //
 Rest( "rest", 555 ), //
 Resultant( "resultant", 556 ), //
 Return( "return", 557 ), //
 Reverse( "reverse", 558 ), //
 Riffle( "riffle", 559 ), //
 RogersTanimotoDissimilarity( "rogerstanimotodissimilarity", 560 ), //
 Root( "root", 561 ), //
 RootIntervals( "rootintervals", 562 ), //
 RootOf( "rootof", 563 ), //
 Roots( "roots", 564 ), //
 RotateLeft( "rotateleft", 565 ), //
 RotateRight( "rotateright", 566 ), //
 Round( "round", 567 ), //
 RowReduce( "rowreduce", 568 ), //
 Rule( "rule", 569 ), //
 RuleDelayed( "ruledelayed", 570 ), //
 RussellRaoDissimilarity( "russellraodissimilarity", 571 ), //
 SameQ( "sameq", 572 ), //
 SatisfiabilityCount( "satisfiabilitycount", 573 ), //
 SatisfiabilityInstances( "satisfiabilityinstances", 574 ), //
 SatisfiableQ( "satisfiableq", 575 ), //
 Scan( "scan", 576 ), //
 Sec( "sec", 577 ), //
 Sech( "sech", 578 ), //
 Second( "second", 579 ), //
 Select( "select", 580 ), //
 Sequence( "sequence", 581 ), //
 Series( "series", 582 ), //
 SeriesData( "seriesdata", 583 ), //
 Set( "set", 584 ), //
 SetAttributes( "setattributes", 585 ), //
 SetDelayed( "setdelayed", 586 ), //
 Share( "share", 587 ), //
 Show( "show", 588 ), //
 Sign( "sign", 589 ), //
 SignCmp( "signcmp", 590 ), //
 Simplify( "simplify", 591 ), //
 Sin( "sin", 592 ), //
 SinIntegral( "sinintegral", 593 ), //
 Sinc( "sinc", 594 ), //
 SingularValueDecomposition( "singularvaluedecomposition", 595 ), //
 Sinh( "sinh", 596 ), //
 SinhIntegral( "sinhintegral", 597 ), //
 Skewness( "skewness", 598 ), //
 Slot( "slot", 599 ), //
 SlotSequence( "slotsequence", 600 ), //
 SokalSneathDissimilarity( "sokalsneathdissimilarity", 601 ), //
 Solve( "solve", 602 ), //
 Sort( "sort", 603 ), //
 Sow( "sow", 604 ), //
 Span( "span", 605 ), //
 Split( "split", 606 ), //
 SplitBy( "splitby", 607 ), //
 Sqrt( "sqrt", 608 ), //
 SquareFreeQ( "squarefreeq", 609 ), //
 SquaredEuclideanDistance( "squaredeuclideandistance", 610 ), //
 StandardDeviation( "standarddeviation", 611 ), //
 Standardize( "standardize", 612 ), //
 StieltjesGamma( "stieltjesgamma", 613 ), //
 StirlingS1( "stirlings1", 614 ), //
 StirlingS2( "stirlings2", 615 ), //
 String( "string", 616 ), //
 StringDrop( "stringdrop", 617 ), //
 StringJoin( "stringjoin", 618 ), //
 StringLength( "stringlength", 619 ), //
 StringTake( "stringtake", 620 ), //
 StruveH( "struveh", 621 ), //
 StruveL( "struvel", 622 ), //
 StudentTDistribution( "studenttdistribution", 623 ), //
 Subfactorial( "subfactorial", 624 ), //
 Subscript( "subscript", 625 ), //
 Subsets( "subsets", 626 ), //
 Subsuperscript( "subsuperscript", 627 ), //
 Subtract( "subtract", 628 ), //
 SubtractFrom( "subtractfrom", 629 ), //
 Sum( "sum", 630 ), //
 Superscript( "superscript", 631 ), //
 Surd( "surd", 632 ), //
 SurfaceGraphics( "surfacegraphics", 633 ), //
 Switch( "switch", 634 ), //
 Symbol( "symbol", 635 ), //
 SymbolName( "symbolname", 636 ), //
 SymbolQ( "symbolq", 637 ), //
 SymmetricMatrixQ( "symmetricmatrixq", 638 ), //
 SyntaxLength( "syntaxlength", 639 ), //
 SyntaxQ( "syntaxq", 640 ), //
 Table( "table", 641 ), //
 Take( "take", 642 ), //
 Tally( "tally", 643 ), //
 Tan( "tan", 644 ), //
 Tanh( "tanh", 645 ), //
 TautologyQ( "tautologyq", 646 ), //
 Taylor( "taylor", 647 ), //
 TeXForm( "texform", 648 ), //
 TensorDimensions( "tensordimensions", 649 ), //
 TensorProduct( "tensorproduct", 650 ), //
 TensorRank( "tensorrank", 651 ), //
 Thread( "thread", 652 ), //
 Through( "through", 653 ), //
 Throw( "throw", 654 ), //
 TimeConstrained( "timeconstrained", 655 ), //
 Times( "times", 656 ), //
 TimesBy( "timesby", 657 ), //
 Timing( "timing", 658 ), //
 ToCharacterCode( "tocharactercode", 659 ), //
 ToPolarCoordinates( "topolarcoordinates", 660 ), //
 ToRadicals( "toradicals", 661 ), //
 ToString( "tostring", 662 ), //
 ToUnicode( "tounicode", 663 ), //
 ToeplitzMatrix( "toeplitzmatrix", 664 ), //
 Together( "together", 665 ), //
 TooLarge( "toolarge", 666 ), //
 Total( "total", 667 ), //
 Tr( "tr", 668 ), //
 Trace( "trace", 669 ), //
 Transpose( "transpose", 670 ), //
 Trig( "trig", 671 ), //
 TrigExpand( "trigexpand", 672 ), //
 TrigReduce( "trigreduce", 673 ), //
 TrigToExp( "trigtoexp", 674 ), //
 True( "true", 675 ), //
 TrueQ( "trueq", 676 ), //
 Tuples( "tuples", 677 ), //
 Unequal( "unequal", 678 ), //
 Unevaluated( "unevaluated", 679 ), //
 Union( "union", 680 ), //
 Unique( "unique", 681 ), //
 UnitStep( "unitstep", 682 ), //
 UnitVector( "unitvector", 683 ), //
 UnitaryMatrixQ( "unitarymatrixq", 684 ), //
 Unitize( "unitize", 685 ), //
 Unknown( "unknown", 686 ), //
 UnsameQ( "unsameq", 687 ), //
 Unset( "unset", 688 ), //
 UpSet( "upset", 689 ), //
 UpSetDelayed( "upsetdelayed", 690 ), //
 UpperCaseQ( "uppercaseq", 691 ), //
 UpperTriangularize( "uppertriangularize", 692 ), //
 ValueQ( "valueq", 693 ), //
 VandermondeMatrix( "vandermondematrix", 694 ), //
 Variable( "variable", 695 ), //
 Variables( "variables", 696 ), //
 Variance( "variance", 697 ), //
 VectorAngle( "vectorangle", 698 ), //
 VectorQ( "vectorq", 699 ), //
 WeibullDistribution( "weibulldistribution", 700 ), //
 Which( "which", 701 ), //
 While( "while", 702 ), //
 White( "white", 703 ), //
 With( "with", 704 ), //
 Xor( "xor", 705 ), //
 YuleDissimilarity( "yuledissimilarity", 706 ), //
 Zeta( "zeta", 707 );

	private final String name;
	private final int symbolID;
	private final static IBuiltInSymbol[] builtInSymbols = new IBuiltInSymbol[values().length];

	public static IBuiltInSymbol valueOf(BuiltIns sEnum) {
		IBuiltInSymbol symbol = F.initFinalSymbol(sEnum);
		builtInSymbols[sEnum.symbolID] = symbol;
		return symbol;
	}

	BuiltIns(String name, int symbolID) {
		this.name = name;
		this.symbolID = symbolID;
	}

	public static IBuiltInSymbol symbol(int id) {
		return builtInSymbols[id];
	}

	public final int id() {
		return symbolID;
	}

	public final String str() {
		return name;
	}
}

