package org.matheclipse.core.integrate.rubi45;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.ISymbol;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules78 { 
  public static IAST RULES = List( 
ISetDelayed(Int(Times(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT)))))),x_Symbol),
    Condition(Plus(Times(a,pa,x),Times(b,pb,Int(Sqr(Sec(Plus(c,Times(pd,x)))),x))),And(FreeQ(List(a,b,c,pd,pa,pb),x),ZeroQ(Plus(Times(pa,b),Times(a,pb)))))),
ISetDelayed(Int(Times(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT)))))),x_Symbol),
    Condition(Plus(Times(a,pa,x),Times(b,pb,Int(Sqr(Csc(Plus(c,Times(pd,x)))),x))),And(FreeQ(List(a,b,c,pd,pa,pb),x),ZeroQ(Plus(Times(pa,b),Times(a,pb)))))),
ISetDelayed(Int(Times(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT)))))),x_Symbol),
    Condition(Plus(Times(a,pa,x),Times(Plus(Times(pa,b),Times(a,pb)),Int(Sec(Plus(c,Times(pd,x))),x)),Times(b,pb,Int(Sqr(Sec(Plus(c,Times(pd,x)))),x))),And(And(FreeQ(List(a,b,c,pd,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),NonzeroQ(Plus(Times(pa,b),Times(a,pb)))))),
ISetDelayed(Int(Times(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT)))))),x_Symbol),
    Condition(Plus(Times(a,pa,x),Times(Plus(Times(pa,b),Times(a,pb)),Int(Csc(Plus(c,Times(pd,x))),x)),Times(b,pb,Int(Sqr(Csc(Plus(c,Times(pd,x)))),x))),And(And(FreeQ(List(a,b,c,pd,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),NonzeroQ(Plus(Times(pa,b),Times(a,pb)))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1)),x_Symbol),
    Condition(Plus(Times(pa,x,Power(a,CN1)),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb)),Power(a,CN1),Int(Times(Sec(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1)),x))),And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1)),x_Symbol),
    Condition(Plus(Times(pa,x,Power(a,CN1)),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb)),Power(a,CN1),Int(Times(Csc(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1)),x))),And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Plus(Times(pa,Int(Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),x)),Times(pb,Int(Times(Sec(Plus(pe,Times(f,x))),Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))))),x))),And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),ZeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Plus(Times(pa,Int(Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),x)),Times(pb,Int(Times(Csc(Plus(pe,Times(f,x))),Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))))),x))),And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),ZeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_)),x_Symbol),
    Condition(Plus(Times(b,pb,Tan(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(f,m),CN1)),Times(Power(m,CN1),Int(Times(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Simp(Plus(Times(a,pa,m),Times(Plus(Times(pa,b,m),Times(a,pb,Plus(Times(C2,m),Times(CN1,C1)))),Sec(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),ZeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m)),Greater(m,C1D2)),IntegerQ(Times(C2,m))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_)),x_Symbol),
    Condition(Plus(Times(CN1,b,pb,Cot(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(f,m),CN1)),Times(Power(m,CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Simp(Plus(Times(a,pa,m),Times(Plus(Times(pa,b,m),Times(a,pb,Plus(Times(C2,m),Times(CN1,C1)))),Csc(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),ZeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m)),Greater(m,C1D2)),IntegerQ(Times(C2,m))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Plus(Times(pa,Power(a,CN1),Int(Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),x)),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb)),Power(a,CN1),Int(Times(Sec(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),ZeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Plus(Times(pa,Power(a,CN1),Int(Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),x)),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb)),Power(a,CN1),Int(Times(Csc(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),ZeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_)),x_Symbol),
    Condition(Plus(Times(Plus(Times(pa,b),Times(CN1,a,pb)),Tan(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),m),Power(Times(b,f,Plus(Times(C2,m),C1)),CN1)),Times(Power(Times(Sqr(a),Plus(Times(C2,m),C1)),CN1),Int(Times(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(a,pa,Plus(Times(C2,m),C1)),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb)),Plus(m,C1),Sec(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),ZeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m)),Less(m,CN1D2)),IntegerQ(Times(C2,m))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_)),x_Symbol),
    Condition(Plus(Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb)),Cot(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),m),Power(Times(b,f,Plus(Times(C2,m),C1)),CN1)),Times(Power(Times(Sqr(a),Plus(Times(C2,m),C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(a,pa,Plus(Times(C2,m),C1)),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb)),Plus(m,C1),Csc(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),ZeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m)),Less(m,CN1D2)),IntegerQ(Times(C2,m))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),m_)),x_Symbol),
    Condition(Plus(Times(b,pb,Tan(Plus(c,Times(pd,x))),Power(Plus(a,Times(b,Sec(Plus(c,Times(pd,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,m),CN1)),Times(Power(m,CN1),Int(Times(Power(Plus(a,Times(b,Sec(Plus(c,Times(pd,x))))),Plus(m,Times(CN1,C2))),Simp(Plus(Times(Sqr(a),pa,m),Times(Plus(Times(Sqr(b),pb,Plus(m,Times(CN1,C1))),Times(C2,a,pa,b,m),Times(Sqr(a),pb,m)),Sec(Plus(c,Times(pd,x)))),Times(b,Plus(Times(pa,b,m),Times(a,pb,Plus(Times(C2,m),Times(CN1,C1)))),Sqr(Sec(Plus(c,Times(pd,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,c,pd,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m)),Greater(m,C1)))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),m_)),x_Symbol),
    Condition(Plus(Times(CN1,b,pb,Cot(Plus(c,Times(pd,x))),Power(Plus(a,Times(b,Csc(Plus(c,Times(pd,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,m),CN1)),Times(Power(m,CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(c,Times(pd,x))))),Plus(m,Times(CN1,C2))),Simp(Plus(Times(Sqr(a),pa,m),Times(Plus(Times(Sqr(b),pb,Plus(m,Times(CN1,C1))),Times(C2,a,pa,b,m),Times(Sqr(a),pb,m)),Csc(Plus(c,Times(pd,x)))),Times(b,Plus(Times(pa,b,m),Times(a,pb,Plus(Times(C2,m),Times(CN1,C1)))),Sqr(Csc(Plus(c,Times(pd,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,c,pd,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m)),Greater(m,C1)))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),m_)),x_Symbol),
    Condition(Plus(Times(CN1,b,Plus(Times(pa,b),Times(CN1,a,pb)),Tan(Plus(c,Times(pd,x))),Power(Plus(a,Times(b,Sec(Plus(c,Times(pd,x))))),Plus(m,C1)),Power(Times(a,pd,Plus(m,C1),Plus(Sqr(a),Times(CN1,Sqr(b)))),CN1)),Times(Power(Times(a,Plus(m,C1),Plus(Sqr(a),Times(CN1,Sqr(b)))),CN1),Int(Times(Power(Plus(a,Times(b,Sec(Plus(c,Times(pd,x))))),Plus(m,C1)),Simp(Plus(Times(pa,Plus(Sqr(a),Times(CN1,Sqr(b))),Plus(m,C1)),Times(CN1,a,Plus(Times(pa,b),Times(CN1,a,pb)),Plus(m,C1),Sec(Plus(c,Times(pd,x)))),Times(b,Plus(Times(pa,b),Times(CN1,a,pb)),Plus(m,C2),Sqr(Sec(Plus(c,Times(pd,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,c,pd,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m)),Less(m,CN1)))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(c_DEFAULT,Times(x_,pd_DEFAULT))))),m_)),x_Symbol),
    Condition(Plus(Times(b,Plus(Times(pa,b),Times(CN1,a,pb)),Cot(Plus(c,Times(pd,x))),Power(Plus(a,Times(b,Csc(Plus(c,Times(pd,x))))),Plus(m,C1)),Power(Times(a,pd,Plus(m,C1),Plus(Sqr(a),Times(CN1,Sqr(b)))),CN1)),Times(Power(Times(a,Plus(m,C1),Plus(Sqr(a),Times(CN1,Sqr(b)))),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(c,Times(pd,x))))),Plus(m,C1)),Simp(Plus(Times(pa,Plus(Sqr(a),Times(CN1,Sqr(b))),Plus(m,C1)),Times(CN1,a,Plus(Times(pa,b),Times(CN1,a,pb)),Plus(m,C1),Csc(Plus(c,Times(pd,x)))),Times(b,Plus(Times(pa,b),Times(CN1,a,pb)),Plus(m,C2),Sqr(Csc(Plus(c,Times(pd,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,c,pd,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m)),Less(m,CN1)))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Plus(Times(pa,Int(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2),x)),Times(pb,Int(Times(Sec(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Plus(Times(pa,Int(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2),x)),Times(pb,Int(Times(Csc(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(FreeQ(List(a,b,pe,f,pa,pb),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_)),x_Symbol),
    Condition(Plus(Times(pa,Int(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),m),x)),Times(pb,Int(Times(Sec(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),m)),x))),And(FreeQ(List(a,b,pe,f,pa,pb,m),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))))),
ISetDelayed(Int(Times(Plus(pa_,Times(pb_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_)),x_Symbol),
    Condition(Plus(Times(pa,Int(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),m),x)),Times(pb,Int(Times(Csc(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),m)),x))),And(FreeQ(List(a,b,pe,f,pa,pb,m),x),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb)))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Plus(Times(c,Power(a,CN1),Int(Power(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))),CN1D2),x)),Times(CN1,Plus(Times(b,c),Times(CN1,a,pd)),Power(a,CN1),Int(Times(Sec(Plus(pe,Times(f,x))),Power(Times(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Sqrt(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Plus(Times(c,Power(a,CN1),Int(Power(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))),CN1D2),x)),Times(CN1,Plus(Times(b,c),Times(CN1,a,pd)),Power(a,CN1),Int(Times(Csc(Plus(pe,Times(f,x))),Power(Times(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Sqrt(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Power(Plus(c_,Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),QQ(3L,2L))),x_Symbol),
    Condition(Plus(Times(pd,Power(b,CN1),Int(Sqrt(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x)))))),x)),Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(b,CN1),Int(Times(Sqrt(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x)))))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Power(Plus(c_,Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),QQ(3L,2L))),x_Symbol),
    Condition(Plus(Times(pd,Power(b,CN1),Int(Sqrt(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x)))))),x)),Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(b,CN1),Int(Times(Sqrt(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x)))))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Power(Times(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),CN1),x_Symbol),
    Condition(Plus(Times(Power(a,CN1),Int(Power(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))),CN1D2),x)),Times(CN1,b,Power(a,CN1),Int(Times(Sec(Plus(pe,Times(f,x))),Power(Times(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Sqrt(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Power(Times(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),CN1),x_Symbol),
    Condition(Plus(Times(Power(a,CN1),Int(Power(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))),CN1D2),x)),Times(CN1,b,Power(a,CN1),Int(Times(Csc(Plus(pe,Times(f,x))),Power(Times(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Sqrt(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Plus(c_,Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Times(CN2,Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Power(Times(c,f,Rt(Times(Plus(a,b),Power(Plus(c,pd),CN1)),C2),Tan(Plus(pe,Times(f,x)))),CN1),Sqrt(Times(Plus(Times(b,c),Times(CN1,a,pd)),Plus(C1,Sec(Plus(pe,Times(f,x)))),Power(Times(Plus(c,Times(CN1,pd)),Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),CN1))),Sqrt(Times(CN1,Plus(Times(b,c),Times(CN1,a,pd)),Plus(C1,Times(CN1,Sec(Plus(pe,Times(f,x))))),Power(Times(Plus(c,pd),Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),CN1))),EllipticPi(Times(a,Plus(c,pd),Power(Times(c,Plus(a,b)),CN1)),ArcSin(Times(Rt(Times(Plus(a,b),Power(Plus(c,pd),CN1)),C2),Sqrt(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x)))))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2))),Times(Plus(a,Times(CN1,b)),Plus(c,pd),Power(Times(Plus(a,b),Plus(c,Times(CN1,pd))),CN1)))),And(And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))),PosQ(Times(Plus(a,b),Power(Plus(c,pd),CN1)))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Plus(c_,Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Times(C2,Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Power(Times(c,f,Rt(Times(Plus(a,b),Power(Plus(c,pd),CN1)),C2),Cot(Plus(pe,Times(f,x)))),CN1),Sqrt(Times(Plus(Times(b,c),Times(CN1,a,pd)),Plus(C1,Csc(Plus(pe,Times(f,x)))),Power(Times(Plus(c,Times(CN1,pd)),Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),CN1))),Sqrt(Times(CN1,Plus(Times(b,c),Times(CN1,a,pd)),Plus(C1,Times(CN1,Csc(Plus(pe,Times(f,x))))),Power(Times(Plus(c,pd),Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),CN1))),EllipticPi(Times(a,Plus(c,pd),Power(Times(c,Plus(a,b)),CN1)),ArcSin(Times(Rt(Times(Plus(a,b),Power(Plus(c,pd),CN1)),C2),Sqrt(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x)))))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2))),Times(Plus(a,Times(CN1,b)),Plus(c,pd),Power(Times(Plus(a,b),Plus(c,Times(CN1,pd))),CN1)))),And(And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))),PosQ(Times(Plus(a,b),Power(Plus(c,pd),CN1)))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Plus(c_,Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Times(Sqrt(Plus(Times(CN1,c),Times(CN1,pd,Sec(Plus(pe,Times(f,x)))))),Power(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))),CN1D2),Int(Times(Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Plus(Times(CN1,c),Times(CN1,pd,Sec(Plus(pe,Times(f,x))))),CN1D2)),x)),And(And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))),NegQ(Times(Plus(a,b),Power(Plus(c,pd),CN1)))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Plus(c_,Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Times(Sqrt(Plus(Times(CN1,c),Times(CN1,pd,Csc(Plus(pe,Times(f,x)))))),Power(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))),CN1D2),Int(Times(Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Plus(Times(CN1,c),Times(CN1,pd,Csc(Plus(pe,Times(f,x))))),CN1D2)),x)),And(And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))),NegQ(Times(Plus(a,b),Power(Plus(c,pd),CN1)))))),
ISetDelayed(Int(Power(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),CN1),x_Symbol),
    Condition(Plus(Times(CN1,b,Power(a,CN1),Int(Times(Sec(Plus(pe,Times(f,x))),Power(Times(Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Sqrt(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))))),CN1)),x)),Times(Power(a,CN1),Int(Times(Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Power(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§cos"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§cos"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),CN1),x_Symbol),
    Condition(Plus(Times(CN1,b,Power(a,CN1),Int(Times(Csc(Plus(pe,Times(f,x))),Power(Times(Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Sqrt(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))))),CN1)),x)),Times(Power(a,CN1),Int(Times(Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Times(g_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(3L,2L))),x_Symbol),
    Condition(Plus(Times(pd,Power(b,CN1),Int(Times(Power(Times(g,Sec(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))),CN1D2)),x)),Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(b,CN1),Int(Times(Power(Times(g,Sec(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Times(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Sqrt(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Times(g_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(3L,2L))),x_Symbol),
    Condition(Plus(Times(pd,Power(b,CN1),Int(Times(Power(Times(g,Csc(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))),CN1D2)),x)),Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(b,CN1),Int(Times(Power(Times(g,Csc(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Times(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Sqrt(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Times(Power(Times(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),CN1),Power(Times(g_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(3L,2L))),x_Symbol),
    Condition(Times(C2,g,Sqrt(Times(g,Sec(Plus(pe,Times(f,x))))),Sqrt(Sec(Plus(pe,Times(f,x)))),Sqrt(Plus(CN1,Sec(Plus(pe,Times(f,x))))),Power(Times(f,Plus(a,b),Tan(Plus(pe,Times(f,x))),Sqrt(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))))),CN1),Sqrt(Times(Plus(C1,Sec(Plus(pe,Times(f,x)))),Power(Sec(Plus(pe,Times(f,x))),CN1))),Sqrt(Times(Plus(c,Times(pd,Sec(Plus(pe,Times(f,x))))),Power(Times(Plus(c,pd),Sec(Plus(pe,Times(f,x)))),CN1))),EllipticPi(Times(C2,a,Power(Plus(a,b),CN1)),ArcSin(Times(Sqrt(Plus(CN1,Sec(Plus(pe,Times(f,x))))),Power(Times(CSqrt2,Sqrt(Sec(Plus(pe,Times(f,x))))),CN1))),Times(C2,c,Power(Plus(c,pd),CN1)))),And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd))))))),
ISetDelayed(Int(Times(Power(Times(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Plus(c_,Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))))),CN1),Power(Times(g_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(3L,2L))),x_Symbol),
    Condition(Times(CN2,g,Sqrt(Times(g,Csc(Plus(pe,Times(f,x))))),Sqrt(Csc(Plus(pe,Times(f,x)))),Sqrt(Plus(CN1,Csc(Plus(pe,Times(f,x))))),Power(Times(f,Plus(a,b),Cot(Plus(pe,Times(f,x))),Sqrt(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))))),CN1),Sqrt(Times(Plus(C1,Csc(Plus(pe,Times(f,x)))),Power(Csc(Plus(pe,Times(f,x))),CN1))),Sqrt(Times(Plus(c,Times(pd,Csc(Plus(pe,Times(f,x))))),Power(Times(Plus(c,pd),Csc(Plus(pe,Times(f,x)))),CN1))),EllipticPi(Times(C2,a,Power(Plus(a,b),CN1)),ArcSin(Times(Sqrt(Plus(CN1,Csc(Plus(pe,Times(f,x))))),Power(Times(CSqrt2,Sqrt(Csc(Plus(pe,Times(f,x))))),CN1))),Times(C2,c,Power(Plus(c,pd),CN1)))),And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),NonzeroQ(Plus(Sqr(c),Times(CN1,Sqr(pd)))))))
  );
}
