package org.matheclipse.core.integrate.rubi45;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.ISymbol;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules26 { 
  public static IAST RULES = List( 
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_DEFAULT)),x_Symbol),
    Condition(Int(Times(Power(x,m),Power(Times(Plus(a,b,c),Power(x,pn)),p)),x),And(And(FreeQ(List(a,b,c,m,pn,p),x),ZeroQ(Plus(q,Times(CN1,pn)))),ZeroQ(Plus(r,Times(CN1,pn)))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_DEFAULT)),x_Symbol),
    Condition(Int(Times(Power(x,Plus(m,Times(p,q))),Power(Plus(a,Times(b,Power(x,Plus(pn,Times(CN1,q)))),Times(c,Power(x,Times(C2,Plus(pn,Times(CN1,q)))))),p)),x),And(And(And(FreeQ(List(a,b,c,m,pn,q),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),IntegerQ(p)),PosQ(Plus(pn,Times(CN1,q)))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),CN1D2)),x_Symbol),
    Condition(Times(Power(x,Times(C1D2,q)),Sqrt(Plus(a,Times(b,Power(x,Plus(pn,Times(CN1,q)))),Times(c,Power(x,Times(C2,Plus(pn,Times(CN1,q))))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),CN1D2),Int(Times(Power(x,Plus(m,Times(CN1,C1D2,q))),Power(Plus(a,Times(b,Power(x,Plus(pn,Times(CN1,q)))),Times(c,Power(x,Times(C2,Plus(pn,Times(CN1,q)))))),CN1D2)),x)),And(And(And(FreeQ(List(a,b,c,m,pn,q),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Or(And(And(ZeroQ(Plus(m,Times(CN1,C1))),ZeroQ(Plus(pn,Times(CN1,C3)))),ZeroQ(Plus(q,Times(CN1,C2)))),And(And(Or(Or(Or(ZeroQ(Plus(m,C1D2)),ZeroQ(Plus(m,Times(CN1,QQ(3L,2L))))),ZeroQ(Plus(m,Times(CN1,C1D2)))),ZeroQ(Plus(m,Times(CN1,QQ(5L,2L))))),ZeroQ(Plus(pn,Times(CN1,C3)))),ZeroQ(Plus(q,Times(CN1,C1)))))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),QQ(-3L,2L))),x_Symbol),
    Condition(Times(CN2,Power(x,Times(C1D2,Plus(pn,Times(CN1,C1)))),Plus(b,Times(C2,c,x)),Power(Times(Plus(Sqr(b),Times(CN1,C4,a,c)),Sqrt(Plus(Times(a,Power(x,Plus(pn,Times(CN1,C1)))),Times(b,Power(x,pn)),Times(c,Power(x,Plus(pn,C1)))))),CN1)),And(And(And(And(FreeQ(List(a,b,c,pn),x),ZeroQ(Plus(m,Times(CN1,C3,C1D2,Plus(pn,Times(CN1,C1)))))),ZeroQ(Plus(q,Times(CN1,pn),C1))),ZeroQ(Plus(r,Times(CN1,pn),Times(CN1,C1)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),QQ(-3L,2L))),x_Symbol),
    Condition(Times(Power(x,Times(C1D2,Plus(pn,Times(CN1,C1)))),Plus(Times(C4,a),Times(C2,b,x)),Power(Times(Plus(Sqr(b),Times(CN1,C4,a,c)),Sqrt(Plus(Times(a,Power(x,Plus(pn,Times(CN1,C1)))),Times(b,Power(x,pn)),Times(c,Power(x,Plus(pn,C1)))))),CN1)),And(And(And(And(FreeQ(List(a,b,c,pn),x),ZeroQ(Plus(m,Times(CN1,C1D2,Plus(Times(C3,pn),Times(CN1,C1)))))),ZeroQ(Plus(q,Times(CN1,pn),C1))),ZeroQ(Plus(r,Times(CN1,pn),Times(CN1,C1)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,Times(CN1,pn))),Power(Plus(Times(a,Power(x,Plus(pn,Times(CN1,C1)))),Times(b,Power(x,pn)),Times(c,Power(x,Plus(pn,C1)))),Plus(p,C1)),Power(Times(C2,c,Plus(p,C1)),CN1)),Times(CN1,b,Power(Times(C2,c),CN1),Int(Times(Power(x,Plus(m,Times(CN1,C1))),Power(Plus(Times(a,Power(x,Plus(pn,Times(CN1,C1)))),Times(b,Power(x,pn)),Times(c,Power(x,Plus(pn,C1)))),p)),x))),And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Equal(Plus(m,Times(p,Plus(pn,Times(CN1,C1))),Times(CN1,C1)),C0)))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,Times(CN1,pn),q,C1)),Plus(b,Times(C2,c,Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p),Power(Times(C2,c,Plus(pn,Times(CN1,q)),Plus(Times(C2,p),C1)),CN1)),Times(CN1,p,Plus(Sqr(b),Times(CN1,C4,a,c)),Power(Times(C2,c,Plus(Times(C2,p),C1)),CN1),Int(Times(Power(x,Plus(m,q)),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,Times(CN1,C1)))),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Greater(p,C0)),Equal(Plus(m,Times(p,q),C1),Plus(pn,Times(CN1,q)))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,Times(CN1,pn),q,C1)),Plus(Times(b,Plus(pn,Times(CN1,q)),p),Times(c,Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(Times(C2,p),Times(CN1,C1))),C1),Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p),Power(Times(c,Plus(m,Times(p,Plus(Times(C2,pn),Times(CN1,q))),C1),Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(Times(C2,p),Times(CN1,C1))),C1)),CN1)),Times(Plus(pn,Times(CN1,q)),p,Power(Times(c,Plus(m,Times(p,Plus(Times(C2,pn),Times(CN1,q))),C1),Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(Times(C2,p),Times(CN1,C1))),C1)),CN1),Int(Times(Power(x,Plus(m,Times(CN1,Plus(pn,Times(CN1,C2,q))))),Simp(Plus(Times(CN1,a,b,Plus(m,Times(p,q),Times(CN1,pn),q,C1)),Times(Plus(Times(C2,a,c,Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(Times(C2,p),Times(CN1,C1))),C1)),Times(CN1,Sqr(b),Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(p,Times(CN1,C1))),C1))),Power(x,Plus(pn,Times(CN1,q))))),x),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,Times(CN1,C1)))),x))),And(And(And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Greater(p,C0)),Greater(Plus(m,Times(p,q),C1),Plus(pn,Times(CN1,q)))),Unequal(Plus(m,Times(p,Plus(Times(C2,pn),Times(CN1,q))),C1),C0)),Unequal(Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(Times(C2,p),Times(CN1,C1))),C1),C0)))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p),Power(Plus(m,Times(p,q),C1),CN1)),Times(CN1,Plus(pn,Times(CN1,q)),p,Power(Plus(m,Times(p,q),C1),CN1),Int(Times(Power(x,Plus(m,pn)),Plus(b,Times(C2,c,Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,Times(CN1,C1)))),x))),And(And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Greater(p,C0)),LessEqual(Plus(m,Times(p,q),C1),Plus(Times(CN1,Plus(pn,Times(CN1,q))),C1))),NonzeroQ(Plus(m,Times(p,q),C1))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p),Power(Plus(m,Times(p,Plus(Times(C2,pn),Times(CN1,q))),C1),CN1)),Times(Plus(pn,Times(CN1,q)),p,Power(Plus(m,Times(p,Plus(Times(C2,pn),Times(CN1,q))),C1),CN1),Int(Times(Power(x,Plus(m,q)),Plus(Times(C2,a),Times(b,Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,Times(CN1,C1)))),x))),And(And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Greater(p,C0)),Greater(Plus(m,Times(p,q),C1),Times(CN1,Plus(pn,Times(CN1,q))))),Unequal(Plus(m,Times(p,Plus(Times(C2,pn),Times(CN1,q))),C1),C0)))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(CN1,Power(x,Plus(m,Times(CN1,q),C1)),Plus(Sqr(b),Times(CN1,C2,a,c),Times(b,c,Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1)),Power(Times(a,Plus(pn,Times(CN1,q)),Plus(p,C1),Plus(Sqr(b),Times(CN1,C4,a,c))),CN1)),Times(Plus(Times(C2,a,c),Times(CN1,Sqr(b),Plus(p,C2))),Power(Times(a,Plus(p,C1),Plus(Sqr(b),Times(CN1,C4,a,c))),CN1),Int(Times(Power(x,Plus(m,Times(CN1,q))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1))),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Less(p,CN1)),Equal(Plus(m,Times(p,q),C1),Times(CN1,Plus(pn,Times(CN1,q)),Plus(Times(C2,p),C3)))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(CN1,Power(x,Plus(m,Times(CN1,C2,pn),q,C1)),Plus(Times(C2,a),Times(b,Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1)),Power(Times(Plus(pn,Times(CN1,q)),Plus(p,C1),Plus(Sqr(b),Times(CN1,C4,a,c))),CN1)),Times(Power(Times(Plus(pn,Times(CN1,q)),Plus(p,C1),Plus(Sqr(b),Times(CN1,C4,a,c))),CN1),Int(Times(Power(x,Plus(m,Times(CN1,C2,pn),q)),Plus(Times(C2,a,Plus(m,Times(p,q),Times(CN1,C2,Plus(pn,Times(CN1,q))),C1)),Times(b,Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(Times(C2,p),C1)),C1),Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1))),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Less(p,CN1)),Greater(Plus(m,Times(p,q),C1),Times(C2,Plus(pn,Times(CN1,q))))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(CN1,Power(x,Plus(m,Times(CN1,q),C1)),Plus(Sqr(b),Times(CN1,C2,a,c),Times(b,c,Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1)),Power(Times(a,Plus(pn,Times(CN1,q)),Plus(p,C1),Plus(Sqr(b),Times(CN1,C4,a,c))),CN1)),Times(Power(Times(a,Plus(pn,Times(CN1,q)),Plus(p,C1),Plus(Sqr(b),Times(CN1,C4,a,c))),CN1),Int(Times(Power(x,Plus(m,Times(CN1,q))),Plus(Times(Sqr(b),Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(p,C1)),C1)),Times(CN1,C2,a,c,Plus(m,Times(p,q),Times(C2,Plus(pn,Times(CN1,q)),Plus(p,C1)),C1)),Times(b,c,Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(Times(C2,p),C3)),C1),Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1))),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Less(p,CN1)),Less(Plus(m,Times(p,q),C1),Plus(pn,Times(CN1,q)))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,Times(CN1,pn),C1)),Plus(b,Times(C2,c,Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1)),Power(Times(Plus(pn,Times(CN1,q)),Plus(p,C1),Plus(Sqr(b),Times(CN1,C4,a,c))),CN1)),Times(CN1,Power(Times(Plus(pn,Times(CN1,q)),Plus(p,C1),Plus(Sqr(b),Times(CN1,C4,a,c))),CN1),Int(Times(Power(x,Plus(m,Times(CN1,pn))),Plus(Times(b,Plus(m,Times(p,q),Times(CN1,pn),q,C1)),Times(C2,c,Plus(m,Times(p,q),Times(C2,Plus(pn,Times(CN1,q)),Plus(p,C1)),C1),Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1))),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),Less(p,CN1)),Less(Less(Plus(pn,Times(CN1,q)),Plus(m,Times(p,q),C1)),Times(C2,Plus(pn,Times(CN1,q))))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,Times(CN1,C2,pn),q,C1)),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1)),Power(Times(C2,c,Plus(pn,Times(CN1,q)),Plus(p,C1)),CN1)),Times(CN1,b,Power(Times(C2,c),CN1),Int(Times(Power(x,Plus(m,Times(CN1,pn),q)),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p)),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),And(LessEqual(CN1,p),Less(p,C0))),Equal(Plus(m,Times(p,q),C1),Times(C2,Plus(pn,Times(CN1,q))))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(CN1,Power(x,Plus(m,Times(CN1,q),C1)),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1)),Power(Times(C2,a,Plus(pn,Times(CN1,q)),Plus(p,C1)),CN1)),Times(CN1,b,Power(Times(C2,a),CN1),Int(Times(Power(x,Plus(m,pn,Times(CN1,q))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p)),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),And(LessEqual(CN1,p),Less(p,C0))),Equal(Plus(m,Times(p,q),C1),Times(CN2,Plus(pn,Times(CN1,q)),Plus(p,C1)))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,Times(CN1,C2,pn),q,C1)),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1)),Power(Times(c,Plus(m,Times(p,q),Times(C2,Plus(pn,Times(CN1,q)),p),C1)),CN1)),Times(CN1,Power(Times(c,Plus(m,Times(p,q),Times(C2,Plus(pn,Times(CN1,q)),p),C1)),CN1),Int(Times(Power(x,Plus(m,Times(CN1,C2,Plus(pn,Times(CN1,q))))),Plus(Times(a,Plus(m,Times(p,q),Times(CN1,C2,Plus(pn,Times(CN1,q))),C1)),Times(b,Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(p,Times(CN1,C1))),C1),Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p)),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),And(LessEqual(CN1,p),Less(p,C0))),Greater(Plus(m,Times(p,q),C1),Times(C2,Plus(pn,Times(CN1,q))))))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,Times(CN1,q),C1)),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),Plus(p,C1)),Power(Times(a,Plus(m,Times(p,q),C1)),CN1)),Times(CN1,Power(Times(a,Plus(m,Times(p,q),C1)),CN1),Int(Times(Power(x,Plus(m,pn,Times(CN1,q))),Plus(Times(b,Plus(m,Times(p,q),Times(Plus(pn,Times(CN1,q)),Plus(p,C1)),C1)),Times(c,Plus(m,Times(p,q),Times(C2,Plus(pn,Times(CN1,q)),Plus(p,C1)),C1),Power(x,Plus(pn,Times(CN1,q))))),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p)),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),PosQ(Plus(pn,Times(CN1,q)))),Not(IntegerQ(p))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),PositiveIntegerQ(pn)),RationalQ(m,p,q)),And(LessEqual(CN1,p),Less(p,C0))),Less(Plus(m,Times(p,q),C1),C0)))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(x_,q_DEFAULT)),Times(c_DEFAULT,Power(x_,r_DEFAULT)),Times(b_DEFAULT,Power(x_,pn_DEFAULT))),p_)),x_Symbol),
    Condition(Times(Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p),Power(Times(Power(x,Times(p,q)),Power(Plus(a,Times(b,Power(x,Plus(pn,Times(CN1,q)))),Times(c,Power(x,Times(C2,Plus(pn,Times(CN1,q)))))),p)),CN1),Int(Times(Power(x,Plus(m,Times(p,q))),Power(Plus(a,Times(b,Power(x,Plus(pn,Times(CN1,q)))),Times(c,Power(x,Times(C2,Plus(pn,Times(CN1,q)))))),p)),x)),And(And(And(FreeQ(List(a,b,c,m,pn,p,q),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),Not(IntegerQ(p))),PosQ(Plus(pn,Times(CN1,q)))))),
ISetDelayed(Int(Times(Power(u_,m_DEFAULT),Power(Plus(Times(a_DEFAULT,Power(v_,q_DEFAULT)),Times(b_DEFAULT,Power(w_,pn_DEFAULT)),Times(c_DEFAULT,Power(z_,r_DEFAULT))),p_)),x_Symbol),
    Condition(Times(Power(Coefficient(u,x,C1),CN1),Subst(Int(Times(Power(x,m),Power(Plus(Times(a,Power(x,q)),Times(b,Power(x,pn)),Times(c,Power(x,Plus(Times(C2,pn),Times(CN1,q))))),p)),x),x,u)),And(And(And(And(And(And(FreeQ(List(a,b,c,m,pn,p,q),x),ZeroQ(Plus(r,Times(CN1,Plus(Times(C2,pn),Times(CN1,q)))))),ZeroQ(Plus(u,Times(CN1,v)))),ZeroQ(Plus(u,Times(CN1,w)))),ZeroQ(Plus(u,Times(CN1,z)))),LinearQ(u,x)),NonzeroQ(Plus(u,Times(CN1,x)))))),
ISetDelayed(Int(Times(Power(u_,p_DEFAULT),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Int(Times(Power(x,m),Power(ExpandToSum(u,x),p)),x),And(And(FreeQ(List(m,p),x),GeneralizedTrinomialQ(u,x)),Not(GeneralizedTrinomialMatchQ(u,x)))))
  );
}
