package org.matheclipse.core.integrate.rubi45;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.ISymbol;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules17 { 
  public static IAST RULES = List( 
ISetDelayed(Int(Times(Plus(pa_DEFAULT,Times(x_,pb_DEFAULT)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(Plus(Times(pa,pe),Times(CN1,pb,pd)),Power(Plus(pd,Times(pe,x)),Plus(m,C1)),Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Times(Plus(m,C1),Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe)))),CN1)),Times(Power(Times(Plus(m,C1),Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe)))),CN1),Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,C1)),Simp(Plus(Times(Plus(Times(pa,c,pd),Times(a,pb,pe)),Plus(m,C1)),Times(CN1,c,Plus(Times(pa,pe),Times(CN1,pb,pd)),Plus(m,Times(C2,p),C3),x)),x),Power(Plus(a,Times(c,Sqr(x))),p)),x))),And(And(And(FreeQ(List(a,c,pd,pe,pa,pb,m,p),x),NonzeroQ(Plus(Times(pb,pd),Times(CN1,pa,pe)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),If(RationalQ(m),Less(m,CN1),And(NonzeroQ(Plus(m,C1)),SumSimplerQ(m,C1)))))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_DEFAULT),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_DEFAULT)),x_Symbol),
    Condition(Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,p)),Power(Plus(f,Times(g,x)),pn),Power(Plus(Times(a,Power(pd,CN1)),Times(c,Power(pe,CN1),x)),p)),x),And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g,m,pn),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),IntegerQ(p)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_DEFAULT),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_DEFAULT)),x_Symbol),
    Condition(Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,p)),Power(Plus(f,Times(g,x)),pn),Power(Plus(Times(a,Power(pd,CN1)),Times(c,Power(pe,CN1),x)),p)),x),And(And(And(FreeQ(List(a,c,pd,pe,f,g,m,pn),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),IntegerQ(p)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Sqr(Plus(f_DEFAULT,Times(g_DEFAULT,x_))),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(g,Power(Plus(pd,Times(pe,x)),m),Plus(f,Times(g,x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(c,Plus(m,Times(C2,p),C3)),CN1)),Times(CN1,Power(Times(c,Sqr(pe),Plus(m,Times(C2,p),C3)),CN1),Int(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Simp(Plus(Times(b,pe,g,Plus(Times(pd,g),Times(pe,f,Plus(m,p,C1)))),Times(CN1,c,Plus(Times(Sqr(pd),Sqr(g)),Times(pd,pe,f,g,m),Times(Sqr(pe),Sqr(f),Plus(m,Times(C2,p),C3)))),Times(pe,g,Plus(Times(b,pe,g,Plus(m,p,C2)),Times(CN1,c,Plus(Times(pd,g,m),Times(pe,f,Plus(m,Times(C2,p),C4))))),x)),x)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f,g,m,p),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Sqr(Plus(f_DEFAULT,Times(g_DEFAULT,x_))),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(g,Power(Plus(pd,Times(pe,x)),m),Plus(f,Times(g,x)),Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Times(c,Plus(m,Times(C2,p),C3)),CN1)),Times(CN1,Power(Times(c,Sqr(pe),Plus(m,Times(C2,p),C3)),CN1),Int(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(a,Times(c,Sqr(x))),p),Simp(Plus(Times(CN1,c,Plus(Times(Sqr(pd),Sqr(g)),Times(pd,pe,f,g,m),Times(Sqr(pe),Sqr(f),Plus(m,Times(C2,p),C3)))),Times(CN1,c,pe,g,Plus(Times(pd,g,m),Times(pe,f,Plus(m,Times(C2,p),C4))),x)),x)),x))),And(And(FreeQ(List(a,c,pd,pe,f,g,m,p),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),x),And(And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g,pn),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Not(IntegerQ(p))),Or(PositiveIntegerQ(m),IntegersQ(m,pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn),Power(Plus(a,Times(c,Sqr(x))),p)),x),x),And(And(And(And(FreeQ(List(a,c,pd,pe,f,g,pn),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(p))),Or(PositiveIntegerQ(m),IntegersQ(m,pn))))),
ISetDelayed(Int(Times(Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Times(x_,pe_DEFAULT),m_)),x_Symbol),
    Condition(Times(Power(Times(pe,x),m),Power(Plus(Times(b,x),Times(c,Sqr(x))),p),Power(Times(Power(x,Plus(m,p)),Power(Plus(b,Times(c,x)),p)),CN1),Int(Times(Power(x,Plus(m,p)),Power(Plus(f,Times(g,x)),pn),Power(Plus(b,Times(c,x)),p)),x)),And(FreeQ(List(b,c,pe,f,g,m,pn),x),Not(IntegerQ(p))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_DEFAULT),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_DEFAULT)),x_Symbol),
    Condition(Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,p)),Power(Plus(f,Times(g,x)),pn),Power(Plus(Times(a,Power(pd,CN1)),Times(c,Power(pe,CN1),x)),p)),x),And(And(And(And(And(FreeQ(List(a,c,pd,pe,f,g,m,pn),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(p))),PositiveQ(a)),PositiveQ(pd)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Power(Times(Power(Plus(pd,Times(pe,x)),p),Power(Plus(Times(a,Power(pd,CN1)),Times(c,x,Power(pe,CN1))),p)),CN1),Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,p)),Power(Plus(f,Times(g,x)),pn),Power(Plus(Times(a,Power(pd,CN1)),Times(c,Power(pe,CN1),x)),p)),x)),And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g,m,pn),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Not(IntegerQ(p))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Times(Power(Plus(a,Times(c,Sqr(x))),p),Power(Times(Power(Plus(pd,Times(pe,x)),p),Power(Plus(Times(a,Power(pd,CN1)),Times(c,x,Power(pe,CN1))),p)),CN1),Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,p)),Power(Plus(f,Times(g,x)),pn),Power(Plus(Times(a,Power(pd,CN1)),Times(c,Power(pe,CN1),x)),p)),x)),And(And(And(FreeQ(List(a,c,pd,pe,f,g,m,pn),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),ZeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(p))))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),x),And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),IntegersQ(m,pn,p)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn),Power(Plus(a,Times(c,Sqr(x))),p)),x),x),And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),IntegersQ(m,pn,p)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Times(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),Plus(pd_DEFAULT,Times(x_,pe_DEFAULT))),CN1)),x_Symbol),
    Condition(Plus(Times(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))),Power(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g))),CN1),Int(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,Times(CN1,C1))),Power(Plus(pd,Times(pe,x)),CN1)),x)),Times(CN1,Power(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g))),CN1),Int(Times(Plus(Times(c,pd,f),Times(CN1,b,pe,f),Times(a,pe,g),Times(CN1,c,Plus(Times(pe,f),Times(CN1,pd,g)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,Times(CN1,C1))),Power(Plus(f,Times(g,x)),CN1)),x))),And(And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),FractionQ(p)),Greater(p,C0)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Times(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),Plus(pd_DEFAULT,Times(x_,pe_DEFAULT))),CN1)),x_Symbol),
    Condition(Plus(Times(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))),Power(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g))),CN1),Int(Times(Power(Plus(a,Times(c,Sqr(x))),Plus(p,Times(CN1,C1))),Power(Plus(pd,Times(pe,x)),CN1)),x)),Times(CN1,Power(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g))),CN1),Int(Times(Plus(Times(c,pd,f),Times(a,pe,g),Times(CN1,c,Plus(Times(pe,f),Times(CN1,pd,g)),x)),Power(Plus(a,Times(c,Sqr(x))),Plus(p,Times(CN1,C1))),Power(Plus(f,Times(g,x)),CN1)),x))),And(And(And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),FractionQ(p)),Greater(p,C0)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Module(List(Set(q,Denominator(m))),Times(q,Power(pe,CN1),Subst(Int(Times(Power(x,Plus(Times(q,Plus(m,C1)),Times(CN1,C1))),Power(Plus(Times(Plus(Times(pe,f),Times(CN1,pd,g)),Power(pe,CN1)),Times(g,Power(x,q),Power(pe,CN1))),pn),Power(Plus(Times(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))),Power(pe,CN2)),Times(CN1,Plus(Times(C2,c,pd),Times(CN1,b,pe)),Power(x,q),Power(pe,CN2)),Times(c,Power(x,Times(C2,q)),Power(pe,CN2))),p)),x),x,Power(Plus(pd,Times(pe,x)),Power(q,CN1))))),And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),IntegersQ(pn,p)),FractionQ(m)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Module(List(Set(q,Denominator(m))),Times(q,Power(pe,CN1),Subst(Int(Times(Power(x,Plus(Times(q,Plus(m,C1)),Times(CN1,C1))),Power(Plus(Times(Plus(Times(pe,f),Times(CN1,pd,g)),Power(pe,CN1)),Times(g,Power(x,q),Power(pe,CN1))),pn),Power(Plus(Times(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))),Power(pe,CN2)),Times(CN1,C2,c,pd,Power(x,q),Power(pe,CN2)),Times(c,Power(x,Times(C2,q)),Power(pe,CN2))),p)),x),x,Power(Plus(pd,Times(pe,x)),Power(q,CN1))))),And(And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),IntegersQ(pn,p)),FractionQ(m)))),
ISetDelayed(Int(Times(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Int(Times(Plus(a,Times(b,x)),Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn)),x),Times(c,Int(Times(Sqr(x),Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn)),x))),And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),RationalQ(m,pn)))),
ISetDelayed(Int(Times(Plus(a_,Times(c_DEFAULT,Sqr(x_))),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(a,Int(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn)),x)),Times(c,Int(Times(Sqr(x),Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn)),x))),And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),RationalQ(m,pn)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(g,Power(c,CN2),Int(Times(Simp(Plus(Times(C2,c,pe,f),Times(c,pd,g),Times(CN1,b,pe,g),Times(c,pe,g,x)),x),Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C2)))),x)),Times(Power(c,CN2),Int(Times(Simp(Plus(Times(Sqr(c),pd,Sqr(f)),Times(CN1,C2,a,c,pe,f,g),Times(CN1,a,c,pd,Sqr(g)),Times(a,b,pe,Sqr(g)),Times(Plus(Times(Sqr(c),pe,Sqr(f)),Times(C2,Sqr(c),pd,f,g),Times(CN1,C2,b,c,pe,f,g),Times(CN1,b,c,pd,Sqr(g)),Times(Sqr(b),pe,Sqr(g)),Times(CN1,a,c,pe,Sqr(g))),x)),x),Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C2))),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x))),And(And(And(And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Not(IntegerQ(m))),Not(IntegerQ(pn))),RationalQ(m,pn)),Greater(m,C0)),Greater(pn,C1)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(g,Power(c,CN1),Int(Times(Simp(Plus(Times(C2,pe,f),Times(pd,g),Times(pe,g,x)),x),Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C2)))),x)),Times(Power(c,CN1),Int(Times(Simp(Plus(Times(c,pd,Sqr(f)),Times(CN1,C2,a,pe,f,g),Times(CN1,a,pd,Sqr(g)),Times(Plus(Times(c,pe,Sqr(f)),Times(C2,c,pd,f,g),Times(CN1,a,pe,Sqr(g))),x)),x),Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C2))),Power(Plus(a,Times(c,Sqr(x))),CN1)),x))),And(And(And(And(And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(m))),Not(IntegerQ(pn))),RationalQ(m,pn)),Greater(m,C0)),Greater(pn,C1)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(pe,g,Power(c,CN1),Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C1)))),x)),Times(Power(c,CN1),Int(Times(Simp(Plus(Times(c,pd,f),Times(CN1,a,pe,g),Times(Plus(Times(c,pe,f),Times(c,pd,g),Times(CN1,b,pe,g)),x)),x),Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C1))),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x))),And(And(And(And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Not(IntegerQ(m))),Not(IntegerQ(pn))),RationalQ(m,pn)),Greater(m,C0)),Greater(pn,C0)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(pe,g,Power(c,CN1),Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C1)))),x)),Times(Power(c,CN1),Int(Times(Simp(Plus(Times(c,pd,f),Times(CN1,a,pe,g),Times(Plus(Times(c,pe,f),Times(c,pd,g)),x)),x),Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C1))),Power(Plus(a,Times(c,Sqr(x))),CN1)),x))),And(And(And(And(And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(m))),Not(IntegerQ(pn))),RationalQ(m,pn)),Greater(m,C0)),Greater(pn,C0)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(CN1,g,Plus(Times(pe,f),Times(CN1,pd,g)),Power(Plus(Times(c,Sqr(f)),Times(CN1,b,f,g),Times(a,Sqr(g))),CN1),Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),pn)),x)),Times(Power(Plus(Times(c,Sqr(f)),Times(CN1,b,f,g),Times(a,Sqr(g))),CN1),Int(Times(Simp(Plus(Times(c,pd,f),Times(CN1,b,pd,g),Times(a,pe,g),Times(c,Plus(Times(pe,f),Times(CN1,pd,g)),x)),x),Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x))),And(And(And(And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Not(IntegerQ(m))),Not(IntegerQ(pn))),RationalQ(m,pn)),Greater(m,C0)),Less(pn,CN1)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Plus(Times(CN1,g,Plus(Times(pe,f),Times(CN1,pd,g)),Power(Plus(Times(c,Sqr(f)),Times(a,Sqr(g))),CN1),Int(Times(Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),pn)),x)),Times(Power(Plus(Times(c,Sqr(f)),Times(a,Sqr(g))),CN1),Int(Times(Simp(Plus(Times(c,pd,f),Times(a,pe,g),Times(c,Plus(Times(pe,f),Times(CN1,pd,g)),x)),x),Power(Plus(pd,Times(pe,x)),Plus(m,Times(CN1,C1))),Power(Plus(f,Times(g,x)),Plus(pn,C1)),Power(Plus(a,Times(c,Sqr(x))),CN1)),x))),And(And(And(And(And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(m))),Not(IntegerQ(pn))),RationalQ(m,pn)),Greater(m,C0)),Less(pn,CN1)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1),x),x),And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g,m,pn),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Not(IntegerQ(m))),Not(IntegerQ(pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn)),Power(Plus(a,Times(c,Sqr(x))),CN1),x),x),And(And(And(FreeQ(List(a,c,pd,pe,f,g,m,pn),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(m))),Not(IntegerQ(pn))))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),CN1)),x_Symbol),
    Condition(Plus(Times(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))),Power(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g))),CN1),Int(Times(Power(Plus(f,Times(g,x)),Plus(pn,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,Times(CN1,C1))),Power(Plus(pd,Times(pe,x)),CN1)),x)),Times(CN1,Power(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g))),CN1),Int(Times(Power(Plus(f,Times(g,x)),pn),Plus(Times(c,pd,f),Times(CN1,b,pe,f),Times(a,pe,g),Times(CN1,c,Plus(Times(pe,f),Times(CN1,pd,g)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,Times(CN1,C1)))),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Not(IntegerQ(pn))),Not(IntegerQ(p))),RationalQ(pn,p)),Greater(p,C0)),Less(pn,CN1)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),CN1)),x_Symbol),
    Condition(Plus(Times(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))),Power(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g))),CN1),Int(Times(Power(Plus(f,Times(g,x)),Plus(pn,C1)),Power(Plus(a,Times(c,Sqr(x))),Plus(p,Times(CN1,C1))),Power(Plus(pd,Times(pe,x)),CN1)),x)),Times(CN1,Power(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g))),CN1),Int(Times(Power(Plus(f,Times(g,x)),pn),Plus(Times(c,pd,f),Times(a,pe,g),Times(CN1,c,Plus(Times(pe,f),Times(CN1,pd,g)),x)),Power(Plus(a,Times(c,Sqr(x))),Plus(p,Times(CN1,C1)))),x))),And(And(And(And(And(And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(pn))),Not(IntegerQ(p))),RationalQ(pn,p)),Greater(p,C0)),Less(pn,CN1)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),CN1)),x_Symbol),
    Condition(Plus(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g)),Power(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))),CN1),Int(Times(Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C1))),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(pd,Times(pe,x)),CN1)),x)),Times(Power(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))),CN1),Int(Times(Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C1))),Plus(Times(c,pd,f),Times(CN1,b,pe,f),Times(a,pe,g),Times(CN1,c,Plus(Times(pe,f),Times(CN1,pd,g)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x))),And(And(And(And(And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Not(IntegerQ(pn))),Not(IntegerQ(p))),RationalQ(pn,p)),Less(p,CN1)),Greater(pn,C0)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_DEFAULT,Times(x_,pe_DEFAULT)),CN1)),x_Symbol),
    Condition(Plus(Times(pe,Plus(Times(pe,f),Times(CN1,pd,g)),Power(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))),CN1),Int(Times(Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C1))),Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(pd,Times(pe,x)),CN1)),x)),Times(Power(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))),CN1),Int(Times(Power(Plus(f,Times(g,x)),Plus(pn,Times(CN1,C1))),Plus(Times(c,pd,f),Times(a,pe,g),Times(CN1,c,Plus(Times(pe,f),Times(CN1,pd,g)),x)),Power(Plus(a,Times(c,Sqr(x))),p)),x))),And(And(And(And(And(And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(pe,f),Times(CN1,pd,g)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Not(IntegerQ(pn))),Not(IntegerQ(p))),RationalQ(pn,p)),Less(p,CN1)),Greater(pn,C0)))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(pd_,Times(x_,pe_DEFAULT)),pn_DEFAULT)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(x,m),Power(Plus(pd,Times(pe,x)),pn),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),x),And(And(And(FreeQ(List(a,b,c,pd,pe,m,p),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),PositiveIntegerQ(pn)))),
ISetDelayed(Int(Times(Power(x_,m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(pd_,Times(x_,pe_DEFAULT)),pn_DEFAULT)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(x,m),Power(Plus(pd,Times(pe,x)),pn),Power(Plus(a,Times(c,Sqr(x))),p)),x),x),And(And(FreeQ(List(a,c,pd,pe,m,p),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),PositiveIntegerQ(pn)))),
ISetDelayed(Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),x),And(And(And(FreeQ(List(a,b,c,pd,pe,f,g),x),NonzeroQ(Plus(Sqr(b),Times(CN1,C4,a,c)))),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(CN1,b,pd,pe),Times(a,Sqr(pe))))),Or(Or(PositiveIntegerQ(m),PositiveIntegerQ(p)),IntegersQ(m,pn,p))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),pn_),Power(Plus(pd_,Times(x_,pe_DEFAULT)),m_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn),Power(Plus(a,Times(c,Sqr(x))),p)),x),x),And(And(FreeQ(List(a,c,pd,pe,f,g),x),NonzeroQ(Plus(Times(c,Sqr(pd)),Times(a,Sqr(pe))))),Or(Or(PositiveIntegerQ(m),PositiveIntegerQ(p)),IntegersQ(m,pn,p))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,w_),Times(c_DEFAULT,Sqr(z_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,v_)),pn_DEFAULT),Power(Plus(pd_DEFAULT,Times(u_,pe_DEFAULT)),m_DEFAULT)),x_Symbol),
    Condition(Times(Power(Coefficient(u,x,C1),CN1),Subst(Int(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),x,u)),And(And(And(And(And(FreeQ(List(a,b,c,pd,pe,f,g,m,pn,p),x),ZeroQ(Plus(u,Times(CN1,v)))),ZeroQ(Plus(u,Times(CN1,w)))),ZeroQ(Plus(u,Times(CN1,z)))),LinearQ(u,x)),NonzeroQ(Plus(u,Times(CN1,x)))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(z_))),p_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,v_)),pn_DEFAULT),Power(Plus(pd_DEFAULT,Times(u_,pe_DEFAULT)),m_DEFAULT)),x_Symbol),
    Condition(Times(Power(Coefficient(u,x,C1),CN1),Subst(Int(Times(Power(Plus(pd,Times(pe,x)),m),Power(Plus(f,Times(g,x)),pn),Power(Plus(a,Times(c,Sqr(x))),p)),x),x,u)),And(And(And(And(FreeQ(List(a,c,pd,pe,f,g,m,pn,p),x),ZeroQ(Plus(u,Times(CN1,v)))),ZeroQ(Plus(u,Times(CN1,z)))),LinearQ(u,x)),NonzeroQ(Plus(u,Times(CN1,x)))))),
ISetDelayed(Int(Times(Power(u_,m_DEFAULT),Power(v_,pn_DEFAULT),Power(w_,p_DEFAULT)),x_Symbol),
    Condition(Int(Times(Power(ExpandToSum(u,x),m),Power(ExpandToSum(v,x),pn),Power(ExpandToSum(w,x),p)),x),And(And(And(FreeQ(List(m,pn,p),x),LinearQ(List(u,v),x)),QuadraticQ(w,x)),Not(And(LinearMatchQ(List(u,v),x),QuadraticMatchQ(w,x))))))
  );
}
