package org.matheclipse.core.integrate.rubi45;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.ISymbol;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules61 { 
  public static IAST RULES = List( 
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Times(pa,Power(f,CN1),Subst(Int(Power(Plus(a,Times(b,x)),m),x),x,Tan(Plus(pe,Times(f,x))))),And(FreeQ(List(a,b,pe,f,pa,pc,m),x),ZeroQ(Plus(pa,Times(CN1,pc)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Times(CN1,pa,Power(f,CN1),Subst(Int(Power(Plus(a,Times(b,x)),m),x),x,Cot(Plus(pe,Times(f,x))))),And(FreeQ(List(a,b,pe,f,pa,pc,m),x),ZeroQ(Plus(pa,Times(CN1,pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Times(Power(b,CN2),Int(Times(Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(b,pb),Times(CN1,a,pc),Times(b,pc,Tan(Plus(pe,Times(f,x))))),x)),x)),And(FreeQ(List(a,b,pe,f,pa,pb,pc,m),x),ZeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Times(Power(b,CN2),Int(Times(Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(b,pb),Times(CN1,a,pc),Times(b,pc,Cot(Plus(pe,Times(f,x))))),x)),x)),And(FreeQ(List(a,b,pe,f,pa,pb,pc,m),x),ZeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Times(CN1,pc,Power(b,CN2),Int(Times(Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Plus(a,Times(CN1,b,Tan(Plus(pe,Times(f,x)))))),x)),And(FreeQ(List(a,b,pe,f,pa,pc,m),x),ZeroQ(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Times(CN1,pc,Power(b,CN2),Int(Times(Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Plus(a,Times(CN1,b,Cot(Plus(pe,Times(f,x)))))),x)),And(FreeQ(List(a,b,pe,f,pa,pc,m),x),ZeroQ(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(CN1,Plus(Times(a,pa),Times(b,pb),Times(CN1,a,pc)),Tan(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),m),Power(Times(C2,a,f,m),CN1)),Times(Power(Times(C2,Sqr(a),m),CN1),Int(Times(Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(b,pb),Times(CN1,a,pc),Times(a,pa,Plus(Times(C2,m),C1)),Times(CN1,Plus(Times(b,pc,Plus(m,Times(CN1,C1))),Times(Plus(Times(pa,b),Times(CN1,a,pb)),Plus(m,C1))),Tan(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pe,f,pa,pb,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))),RationalQ(m)),LessEqual(m,CN1)),ZeroQ(Plus(Sqr(a),Sqr(b)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Plus(Times(a,pa),Times(b,pb),Times(CN1,a,pc)),Cot(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),m),Power(Times(C2,a,f,m),CN1)),Times(Power(Times(C2,Sqr(a),m),CN1),Int(Times(Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(b,pb),Times(CN1,a,pc),Times(a,pa,Plus(Times(C2,m),C1)),Times(CN1,Plus(Times(b,pc,Plus(m,Times(CN1,C1))),Times(Plus(Times(pa,b),Times(CN1,a,pb)),Plus(m,C1))),Cot(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pe,f,pa,pb,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))),RationalQ(m)),LessEqual(m,CN1)),ZeroQ(Plus(Sqr(a),Sqr(b)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(CN1,Plus(Times(a,pa),Times(CN1,a,pc)),Tan(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),m),Power(Times(C2,a,f,m),CN1)),Times(Power(Times(C2,Sqr(a),m),CN1),Int(Times(Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(CN1,a,pc),Times(a,pa,Plus(Times(C2,m),C1)),Times(CN1,Plus(Times(b,pc,Plus(m,Times(CN1,C1))),Times(pa,b,Plus(m,C1))),Tan(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pe,f,pa,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)))),RationalQ(m)),LessEqual(m,CN1)),ZeroQ(Plus(Sqr(a),Sqr(b)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Plus(Times(a,pa),Times(CN1,a,pc)),Cot(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),m),Power(Times(C2,a,f,m),CN1)),Times(Power(Times(C2,Sqr(a),m),CN1),Int(Times(Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(CN1,a,pc),Times(a,pa,Plus(Times(C2,m),C1)),Times(CN1,Plus(Times(b,pc,Plus(m,Times(CN1,C1))),Times(pa,b,Plus(m,C1))),Cot(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pe,f,pa,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)))),RationalQ(m)),LessEqual(m,CN1)),ZeroQ(Plus(Sqr(a),Sqr(b)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),CN1)),x_Symbol),
    Condition(Plus(Times(Plus(Times(a,pa),Times(b,pb),Times(CN1,a,pc)),x,Power(Plus(Sqr(a),Sqr(b)),CN1)),Times(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Plus(C1,Sqr(Tan(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),CN1)),x))),And(And(FreeQ(List(a,b,pe,f,pa,pb,pc),x),NonzeroQ(Plus(Sqr(a),Sqr(b)))),ZeroQ(Plus(Times(pa,b),Times(CN1,a,pb),Times(CN1,b,pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),CN1)),x_Symbol),
    Condition(Plus(Times(Plus(Times(a,pa),Times(b,pb),Times(CN1,a,pc)),x,Power(Plus(Sqr(a),Sqr(b)),CN1)),Times(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Plus(C1,Sqr(Cot(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),CN1)),x))),And(And(FreeQ(List(a,b,pe,f,pa,pb,pc),x),NonzeroQ(Plus(Sqr(a),Sqr(b)))),ZeroQ(Plus(Times(pa,b),Times(CN1,a,pb),Times(CN1,b,pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),CN1)),x_Symbol),
    Condition(Plus(Times(pb,x),Times(pa,Int(Power(Tan(Plus(pe,Times(f,x))),CN1),x)),Times(pc,Int(Tan(Plus(pe,Times(f,x))),x))),And(FreeQ(List(pe,f,pa,pb,pc),x),NonzeroQ(Plus(pa,Times(CN1,pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),CN1)),x_Symbol),
    Condition(Plus(Times(pb,x),Times(pa,Int(Power(Cot(Plus(pe,Times(f,x))),CN1),x)),Times(pc,Int(Cot(Plus(pe,Times(f,x))),x))),And(FreeQ(List(pe,f,pa,pb,pc),x),NonzeroQ(Plus(pa,Times(CN1,pc)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),CN1)),x_Symbol),
    Condition(Plus(Times(pa,Int(Power(Tan(Plus(pe,Times(f,x))),CN1),x)),Times(pc,Int(Tan(Plus(pe,Times(f,x))),x))),And(FreeQ(List(pe,f,pa,pc),x),NonzeroQ(Plus(pa,Times(CN1,pc)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),CN1)),x_Symbol),
    Condition(Plus(Times(pa,Int(Power(Cot(Plus(pe,Times(f,x))),CN1),x)),Times(pc,Int(Cot(Plus(pe,Times(f,x))),x))),And(FreeQ(List(pe,f,pa,pc),x),NonzeroQ(Plus(pa,Times(CN1,pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),CN1)),x_Symbol),
    Condition(Plus(Times(Plus(Times(a,pa),Times(b,pb),Times(CN1,a,pc)),x,Power(Plus(Sqr(a),Sqr(b)),CN1)),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb),Times(CN1,b,pc)),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Tan(Plus(pe,Times(f,x))),x)),Times(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Plus(C1,Sqr(Tan(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,pe,f,pa,pb,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))),NonzeroQ(Plus(Sqr(a),Sqr(b)))),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb),Times(CN1,b,pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),CN1)),x_Symbol),
    Condition(Plus(Times(Plus(Times(a,pa),Times(b,pb),Times(CN1,a,pc)),x,Power(Plus(Sqr(a),Sqr(b)),CN1)),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb),Times(CN1,b,pc)),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Cot(Plus(pe,Times(f,x))),x)),Times(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Plus(C1,Sqr(Cot(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,pe,f,pa,pb,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))),NonzeroQ(Plus(Sqr(a),Sqr(b)))),NonzeroQ(Plus(Times(pa,b),Times(CN1,a,pb),Times(CN1,b,pc)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_),CN1)),x_Symbol),
    Condition(Plus(Times(a,Plus(pa,Times(CN1,pc)),x,Power(Plus(Sqr(a),Sqr(b)),CN1)),Times(CN1,b,Plus(pa,Times(CN1,pc)),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Tan(Plus(pe,Times(f,x))),x)),Times(Plus(Times(Sqr(a),pc),Times(pa,Sqr(b))),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Plus(C1,Sqr(Tan(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,pe,f,pa,pc),x),NonzeroQ(Plus(Times(Sqr(a),pc),Times(pa,Sqr(b))))),NonzeroQ(Plus(Sqr(a),Sqr(b)))),NonzeroQ(Plus(pa,Times(CN1,pc)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_),CN1)),x_Symbol),
    Condition(Plus(Times(a,Plus(pa,Times(CN1,pc)),x,Power(Plus(Sqr(a),Sqr(b)),CN1)),Times(CN1,b,Plus(pa,Times(CN1,pc)),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Cot(Plus(pe,Times(f,x))),x)),Times(Plus(Times(Sqr(a),pc),Times(pa,Sqr(b))),Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Plus(C1,Sqr(Cot(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,pe,f,pa,pc),x),NonzeroQ(Plus(Times(Sqr(a),pc),Times(pa,Sqr(b))))),NonzeroQ(Plus(Sqr(a),Sqr(b)))),NonzeroQ(Plus(pa,Times(CN1,pc)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_)),x_Symbol),
    Condition(Plus(Times(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)),Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1),Plus(Sqr(a),Sqr(b))),CN1)),Times(Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(b,pb),Times(a,Plus(pa,Times(CN1,pc))),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb),Times(CN1,b,pc)),Tan(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pe,f,pa,pb,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))),RationalQ(m)),Less(m,CN1)),NonzeroQ(Plus(Sqr(a),Sqr(b)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_)),x_Symbol),
    Condition(Plus(Times(CN1,Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)),Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1),Plus(Sqr(a),Sqr(b))),CN1)),Times(Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(b,pb),Times(a,Plus(pa,Times(CN1,pc))),Times(CN1,Plus(Times(pa,b),Times(CN1,a,pb),Times(CN1,b,pc)),Cot(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pe,f,pa,pb,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))),RationalQ(m)),Less(m,CN1)),NonzeroQ(Plus(Sqr(a),Sqr(b)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_)),x_Symbol),
    Condition(Plus(Times(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)),Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1),Plus(Sqr(a),Sqr(b))),CN1)),Times(Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(a,Plus(pa,Times(CN1,pc))),Times(CN1,Plus(Times(pa,b),Times(CN1,b,pc)),Tan(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pe,f,pa,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)))),RationalQ(m)),Less(m,CN1)),NonzeroQ(Plus(Sqr(a),Sqr(b)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_)),x_Symbol),
    Condition(Plus(Times(CN1,Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)),Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1),Plus(Sqr(a),Sqr(b))),CN1)),Times(Power(Plus(Sqr(a),Sqr(b)),CN1),Int(Times(Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(a,Plus(pa,Times(CN1,pc))),Times(CN1,Plus(Times(pa,b),Times(CN1,b,pc)),Cot(Plus(pe,Times(f,x))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pe,f,pa,pc),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)))),RationalQ(m)),Less(m,CN1)),NonzeroQ(Plus(Sqr(a),Sqr(b)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(pc,Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1)),CN1)),Int(Times(Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),m),Simp(Plus(pa,Times(CN1,pc),Times(pb,Tan(Plus(pe,Times(f,x))))),x)),x)),And(And(FreeQ(List(a,b,pe,f,pa,pb,pc,m),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))),Not(And(RationalQ(m),LessEqual(m,CN1)))))),
ISetDelayed(Int(Times(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),pb_DEFAULT),Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(CN1,pc,Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1)),CN1)),Int(Times(Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),m),Simp(Plus(pa,Times(CN1,pc),Times(pb,Cot(Plus(pe,Times(f,x))))),x)),x)),And(And(FreeQ(List(a,b,pe,f,pa,pb,pc,m),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(CN1,a,b,pb),Times(Sqr(a),pc)))),Not(And(RationalQ(m),LessEqual(m,CN1)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§tan"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(pc,Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1)),CN1)),Times(Plus(pa,Times(CN1,pc)),Int(Power(Plus(a,Times(b,Tan(Plus(pe,Times(f,x))))),m),x))),And(And(FreeQ(List(a,b,pe,f,pa,pc,m),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)))),Not(And(RationalQ(m),LessEqual(m,CN1)))))),
ISetDelayed(Int(Times(Plus(Times(Sqr($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT))),pc_DEFAULT),pa_DEFAULT),Power(Plus(Times($($s("§cot"),Plus(Times(f_DEFAULT,x_),pe_DEFAULT)),b_DEFAULT),a_DEFAULT),m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(CN1,pc,Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1)),CN1)),Times(Plus(pa,Times(CN1,pc)),Int(Power(Plus(a,Times(b,Cot(Plus(pe,Times(f,x))))),m),x))),And(And(FreeQ(List(a,b,pe,f,pa,pc,m),x),NonzeroQ(Plus(Times(pa,Sqr(b)),Times(Sqr(a),pc)))),Not(And(RationalQ(m),LessEqual(m,CN1))))))
  );
}
