package org.matheclipse.core.integrate.rubi45;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.ISymbol;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules71 { 
  public static IAST RULES = List( 
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(3L,2L))),x_Symbol),
    Condition(Times(pd,Sqrt(Times(pd,Cos(Plus(pe,Times(f,x))))),Sqrt(Times(pd,Sec(Plus(pe,Times(f,x))))),Int(Power(Times(Sqrt(Times(pd,Cos(Plus(pe,Times(f,x))))),Plus(b,Times(a,Cos(Plus(pe,Times(f,x)))))),CN1),x)),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(3L,2L))),x_Symbol),
    Condition(Times(pd,Sqrt(Times(pd,Sin(Plus(pe,Times(f,x))))),Sqrt(Times(pd,Csc(Plus(pe,Times(f,x))))),Int(Power(Times(Sqrt(Times(pd,Sin(Plus(pe,Times(f,x))))),Plus(b,Times(a,Sin(Plus(pe,Times(f,x)))))),CN1),x)),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(5L,2L))),x_Symbol),
    Condition(Plus(Times(pd,Power(b,CN1),Int(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),QQ(3L,2L)),x)),Times(CN1,a,pd,Power(b,CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1)),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(5L,2L))),x_Symbol),
    Condition(Plus(Times(pd,Power(b,CN1),Int(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),QQ(3L,2L)),x)),Times(CN1,a,pd,Power(b,CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1)),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Power(Times(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),CN1),x_Symbol),
    Condition(Plus(Times(Sqr(b),Power(Times(Sqr(a),Sqr(pd)),CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1)),x)),Times(Power(a,CN2),Int(Times(Plus(a,Times(CN1,b,Sec(Plus(pe,Times(f,x))))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),CN1D2)),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Power(Times(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),CN1),x_Symbol),
    Condition(Plus(Times(Sqr(b),Power(Times(Sqr(a),Sqr(pd)),CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1)),x)),Times(Power(a,CN2),Int(Times(Plus(a,Times(CN1,b,Csc(Plus(pe,Times(f,x))))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),CN1D2)),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN1,Tan(Plus(pe,Times(f,x))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),pn),Power(Times(a,f,pn),CN1)),Times(CN1,Power(Times(a,pd,pn),CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,C1)),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1),Simp(Plus(Times(b,pn),Times(CN1,a,Plus(pn,C1),Sec(Plus(pe,Times(f,x)))),Times(CN1,b,Plus(pn,C1),Sqr(Sec(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),LessEqual(pn,CN1)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(Cot(Plus(pe,Times(f,x))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),pn),Power(Times(a,f,pn),CN1)),Times(CN1,Power(Times(a,pd,pn),CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,C1)),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1),Simp(Plus(Times(b,pn),Times(CN1,a,Plus(pn,C1),Csc(Plus(pe,Times(f,x)))),Times(CN1,b,Plus(pn,C1),Sqr(Csc(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),LessEqual(pn,CN1)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Sqrt(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),x_Symbol),
    Condition(Plus(Times(a,Int(Times(Sqrt(Times(pd,Sec(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2)),x)),Times(b,Power(pd,CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2)),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Sqrt(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),x_Symbol),
    Condition(Plus(Times(a,Int(Times(Sqrt(Times(pd,Csc(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2)),x)),Times(b,Power(pd,CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),QQ(3L,2L)),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2)),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(C2,pd,Sin(Plus(pe,Times(f,x))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C1))),Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(f,Plus(Times(C2,pn),Times(CN1,C1))),CN1)),Times(Sqr(pd),Power(Plus(Times(C2,pn),Times(CN1,C1)),CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C2))),Simp(Plus(Times(C2,a,Plus(pn,Times(CN1,C2))),Times(b,Plus(Times(C2,pn),Times(CN1,C3)),Sec(Plus(pe,Times(f,x)))),Times(a,Sqr(Sec(Plus(pe,Times(f,x)))))),x),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),Greater(pn,C1)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN2,pd,Cos(Plus(pe,Times(f,x))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C1))),Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(f,Plus(Times(C2,pn),Times(CN1,C1))),CN1)),Times(Sqr(pd),Power(Plus(Times(C2,pn),Times(CN1,C1)),CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C2))),Simp(Plus(Times(C2,a,Plus(pn,Times(CN1,C2))),Times(b,Plus(Times(C2,pn),Times(CN1,C3)),Csc(Plus(pe,Times(f,x)))),Times(a,Sqr(Csc(Plus(pe,Times(f,x)))))),x),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),Greater(pn,C1)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),CN1D2)),x_Symbol),
    Condition(Times(Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(Sqrt(Times(pd,Sec(Plus(pe,Times(f,x))))),Sqrt(Plus(b,Times(a,Cos(Plus(pe,Times(f,x))))))),CN1),Int(Sqrt(Plus(b,Times(a,Cos(Plus(pe,Times(f,x)))))),x)),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),CN1D2)),x_Symbol),
    Condition(Times(Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(Sqrt(Times(pd,Csc(Plus(pe,Times(f,x))))),Sqrt(Plus(b,Times(a,Sin(Plus(pe,Times(f,x))))))),CN1),Int(Sqrt(Plus(b,Times(a,Sin(Plus(pe,Times(f,x)))))),x)),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN1,Tan(Plus(pe,Times(f,x))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),pn),Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(f,pn),CN1)),Times(CN1,Power(Times(C2,pd,pn),CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,C1)),Simp(Plus(b,Times(CN1,C2,a,Plus(pn,C1),Sec(Plus(pe,Times(f,x)))),Times(CN1,b,Plus(Times(C2,pn),C3),Sqr(Sec(Plus(pe,Times(f,x)))))),x),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),LessEqual(pn,CN1)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(Cot(Plus(pe,Times(f,x))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),pn),Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(f,pn),CN1)),Times(CN1,Power(Times(C2,pd,pn),CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,C1)),Simp(Plus(b,Times(CN1,C2,a,Plus(pn,C1),Csc(Plus(pe,Times(f,x)))),Times(CN1,b,Plus(Times(C2,pn),C3),Sqr(Csc(Plus(pe,Times(f,x)))))),x),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),LessEqual(pn,CN1)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Sqrt(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),x_Symbol),
    Condition(Times(Sqrt(Times(pd,Sec(Plus(pe,Times(f,x))))),Sqrt(Plus(b,Times(a,Cos(Plus(pe,Times(f,x)))))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2),Int(Power(Plus(b,Times(a,Cos(Plus(pe,Times(f,x))))),CN1D2),x)),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Sqrt(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),x_Symbol),
    Condition(Times(Sqrt(Times(pd,Csc(Plus(pe,Times(f,x))))),Sqrt(Plus(b,Times(a,Sin(Plus(pe,Times(f,x)))))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2),Int(Power(Plus(b,Times(a,Sin(Plus(pe,Times(f,x))))),CN1D2),x)),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(3L,2L))),x_Symbol),
    Condition(Times(pd,Sqrt(Times(pd,Sec(Plus(pe,Times(f,x))))),Sqrt(Plus(b,Times(a,Cos(Plus(pe,Times(f,x)))))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2),Int(Times(Sec(Plus(pe,Times(f,x))),Power(Plus(b,Times(a,Cos(Plus(pe,Times(f,x))))),CN1D2)),x)),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),QQ(3L,2L))),x_Symbol),
    Condition(Times(pd,Sqrt(Times(pd,Csc(Plus(pe,Times(f,x))))),Sqrt(Plus(b,Times(a,Sin(Plus(pe,Times(f,x)))))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2),Int(Times(Csc(Plus(pe,Times(f,x))),Power(Plus(b,Times(a,Sin(Plus(pe,Times(f,x))))),CN1D2)),x)),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(C2,Sqr(pd),Sin(Plus(pe,Times(f,x))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C2))),Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(b,f,Plus(Times(C2,pn),Times(CN1,C3))),CN1)),Times(Power(pd,C3),Power(Times(b,Plus(Times(C2,pn),Times(CN1,C3))),CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C3))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2),Simp(Plus(Times(C2,a,Plus(pn,Times(CN1,C3))),Times(b,Plus(Times(C2,pn),Times(CN1,C5)),Sec(Plus(pe,Times(f,x)))),Times(CN1,C2,a,Plus(pn,Times(CN1,C2)),Sqr(Sec(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),Greater(pn,C2)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN2,Sqr(pd),Cos(Plus(pe,Times(f,x))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C2))),Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(b,f,Plus(Times(C2,pn),Times(CN1,C3))),CN1)),Times(Power(pd,C3),Power(Times(b,Plus(Times(C2,pn),Times(CN1,C3))),CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C3))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2),Simp(Plus(Times(C2,a,Plus(pn,Times(CN1,C3))),Times(b,Plus(Times(C2,pn),Times(CN1,C5)),Csc(Plus(pe,Times(f,x)))),Times(CN1,C2,a,Plus(pn,Times(CN1,C2)),Sqr(Csc(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),Greater(pn,C2)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Power(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),CN1),x_Symbol),
    Condition(Plus(Times(Sin(Plus(pe,Times(f,x))),Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(a,f),CN1)),Times(CN1,b,Power(Times(C2,a),CN1),Int(Times(Plus(C1,Sqr(Sec(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2)),x))),And(FreeQ(List(a,b,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Power(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),CN1),x_Symbol),
    Condition(Plus(Times(CN1,Cos(Plus(pe,Times(f,x))),Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(a,f),CN1)),Times(CN1,b,Power(Times(C2,a),CN1),Int(Times(Plus(C1,Sqr(Csc(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2)),x))),And(FreeQ(List(a,b,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Power(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Sqrt(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),CN1),x_Symbol),
    Condition(Plus(Times(Power(a,CN1),Int(Times(Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),CN1D2)),x)),Times(CN1,b,Power(Times(a,pd),CN1),Int(Times(Sqrt(Times(pd,Sec(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2)),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Power(Times(Sqrt(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),Sqrt(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))))),CN1),x_Symbol),
    Condition(Plus(Times(Power(a,CN1),Int(Times(Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),CN1D2)),x)),Times(CN1,b,Power(Times(a,pd),CN1),Int(Times(Sqrt(Times(pd,Csc(Plus(pe,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2)),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN1,Sin(Plus(pe,Times(f,x))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,C1)),Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(a,pd,f,pn),CN1)),Times(Power(Times(C2,a,pd,pn),CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,C1)),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2),Simp(Plus(Times(CN1,b,Plus(Times(C2,pn),C1)),Times(C2,a,Plus(pn,C1),Sec(Plus(pe,Times(f,x)))),Times(b,Plus(Times(C2,pn),C3),Sqr(Sec(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),Less(pn,CN1)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(Cos(Plus(pe,Times(f,x))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,C1)),Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(a,pd,f,pn),CN1)),Times(Power(Times(C2,a,pd,pn),CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,C1)),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2),Simp(Plus(Times(CN1,b,Plus(Times(C2,pn),C1)),Times(C2,a,Plus(pn,C1),Csc(Plus(pe,Times(f,x)))),Times(b,Plus(Times(C2,pn),C3),Sqr(Csc(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),Less(pn,CN1)),IntegerQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),QQ(3L,2L)),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN1,a,Tan(Plus(pe,Times(f,x))),Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),pn),Power(Times(f,pn),CN1)),Times(Power(Times(C2,pd,pn),CN1),Int(Times(Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,C1)),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),CN1D2),Simp(Plus(Times(a,b,Plus(Times(C2,pn),Times(CN1,C1))),Times(C2,Plus(Times(Sqr(b),pn),Times(Sqr(a),Plus(pn,C1))),Sec(Plus(pe,Times(f,x)))),Times(a,b,Plus(Times(C2,pn),C3),Sqr(Sec(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),LessEqual(pn,CN1)),IntegersQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),QQ(3L,2L)),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(a,Cot(Plus(pe,Times(f,x))),Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),pn),Power(Times(f,pn),CN1)),Times(Power(Times(C2,pd,pn),CN1),Int(Times(Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,C1)),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),CN1D2),Simp(Plus(Times(a,b,Plus(Times(C2,pn),Times(CN1,C1))),Times(C2,Plus(Times(Sqr(b),pn),Times(Sqr(a),Plus(pn,C1))),Csc(Plus(pe,Times(f,x)))),Times(a,b,Plus(Times(C2,pn),C3),Sqr(Csc(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),LessEqual(pn,CN1)),IntegersQ(Times(C2,pn))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(Power(pd,C3),Tan(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C3))),Power(Times(b,f,Plus(m,pn,Times(CN1,C1))),CN1)),Times(Power(pd,C3),Power(Times(b,Plus(m,pn,Times(CN1,C1))),CN1),Int(Times(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),m),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C3))),Simp(Plus(Times(a,Plus(pn,Times(CN1,C3))),Times(b,Plus(m,pn,Times(CN1,C2)),Sec(Plus(pe,Times(f,x)))),Times(CN1,a,Plus(pn,Times(CN1,C2)),Sqr(Sec(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(And(FreeQ(List(a,b,pd,pe,f,m),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),Greater(pn,C3)),Or(IntegerQ(pn),IntegersQ(Times(C2,m),Times(C2,pn)))),Not(And(IntegerQ(m),Greater(m,C2)))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN1,Power(pd,C3),Cot(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,C1)),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C3))),Power(Times(b,f,Plus(m,pn,Times(CN1,C1))),CN1)),Times(Power(pd,C3),Power(Times(b,Plus(m,pn,Times(CN1,C1))),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),m),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C3))),Simp(Plus(Times(a,Plus(pn,Times(CN1,C3))),Times(b,Plus(m,pn,Times(CN1,C2)),Csc(Plus(pe,Times(f,x)))),Times(CN1,a,Plus(pn,Times(CN1,C2)),Sqr(Csc(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(And(FreeQ(List(a,b,pd,pe,f,m),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(pn)),Greater(pn,C3)),Or(IntegerQ(pn),IntegersQ(Times(C2,m),Times(C2,pn)))),Not(And(IntegerQ(m),Greater(m,C2)))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(b,pd,Tan(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C1))),Power(Times(f,Plus(m,pn,Times(CN1,C1))),CN1)),Times(pd,Power(Plus(m,pn,Times(CN1,C1)),CN1),Int(Times(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C2))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C1))),Simp(Plus(Times(a,b,Plus(pn,Times(CN1,C1))),Times(Plus(Times(Sqr(b),Plus(m,pn,Times(CN1,C2))),Times(Sqr(a),Plus(m,pn,Times(CN1,C1)))),Sec(Plus(pe,Times(f,x)))),Times(a,b,Plus(Times(C2,m),pn,Times(CN1,C2)),Sqr(Sec(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m,pn)),Less(Less(C0,m),C2)),Less(Less(C0,pn),C3)),NonzeroQ(Plus(m,pn,Times(CN1,C1)))),Or(IntegerQ(m),IntegersQ(Times(C2,m),Times(C2,pn)))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN1,b,pd,Cot(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C1))),Power(Times(f,Plus(m,pn,Times(CN1,C1))),CN1)),Times(pd,Power(Plus(m,pn,Times(CN1,C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C2))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C1))),Simp(Plus(Times(a,b,Plus(pn,Times(CN1,C1))),Times(Plus(Times(Sqr(b),Plus(m,pn,Times(CN1,C2))),Times(Sqr(a),Plus(m,pn,Times(CN1,C1)))),Csc(Plus(pe,Times(f,x)))),Times(a,b,Plus(Times(C2,m),pn,Times(CN1,C2)),Sqr(Csc(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m,pn)),Less(Less(C0,m),C2)),Less(Less(C0,pn),C3)),NonzeroQ(Plus(m,pn,Times(CN1,C1)))),Or(IntegerQ(m),IntegersQ(Times(C2,m),Times(C2,pn)))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(Sqr(pd),Tan(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),m),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C2))),Power(Times(f,Plus(m,pn,Times(CN1,C1))),CN1)),Times(Sqr(pd),Power(Times(b,Plus(m,pn,Times(CN1,C1))),CN1),Int(Times(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C2))),Simp(Plus(Times(a,b,Plus(pn,Times(CN1,C2))),Times(Sqr(b),Plus(m,pn,Times(CN1,C2)),Sec(Plus(pe,Times(f,x)))),Times(a,b,m,Sqr(Sec(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m,pn)),Less(Less(C1,pn),C3)),Less(Less(CN1,m),C2)),NonzeroQ(Plus(m,pn,Times(CN1,C1)))),Or(IntegerQ(pn),IntegersQ(Times(C2,m),Times(C2,pn)))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(CN1,Sqr(pd),Cot(Plus(pe,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),m),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C2))),Power(Times(f,Plus(m,pn,Times(CN1,C1))),CN1)),Times(Sqr(pd),Power(Times(b,Plus(m,pn,Times(CN1,C1))),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,Times(CN1,C2))),Simp(Plus(Times(a,b,Plus(pn,Times(CN1,C2))),Times(Sqr(b),Plus(m,pn,Times(CN1,C2)),Csc(Plus(pe,Times(f,x)))),Times(a,b,m,Sqr(Csc(Plus(pe,Times(f,x)))))),x)),x))),And(And(And(And(And(And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))),RationalQ(m,pn)),Less(Less(C1,pn),C3)),Less(Less(CN1,m),C2)),NonzeroQ(Plus(m,pn,Times(CN1,C1)))),Or(IntegerQ(pn),IntegersQ(Times(C2,m),Times(C2,pn)))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),QQ(3L,2L)),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),CN1D2)),x_Symbol),
    Condition(Plus(Times(a,Int(Times(Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x)))))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),CN1D2)),x)),Times(b,Power(pd,CN1),Int(Times(Sqrt(Times(pd,Sec(Plus(pe,Times(f,x))))),Sqrt(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))))),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),QQ(3L,2L)),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),CN1D2)),x_Symbol),
    Condition(Plus(Times(a,Int(Times(Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x)))))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),CN1D2)),x)),Times(b,Power(pd,CN1),Int(Times(Sqrt(Times(pd,Csc(Plus(pe,Times(f,x))))),Sqrt(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))))),x))),And(FreeQ(List(a,b,pd,pe,f),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(b,Power(pd,CN1),Int(Times(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),Plus(pn,C1))),x)),Times(a,Int(Times(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),pn)),x))),And(FreeQ(List(a,b,pd,pe,f,pn),x),PositiveIntegerQ(m)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition(Plus(Times(b,Power(pd,CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),Plus(pn,C1))),x)),Times(a,Int(Times(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),Plus(m,Times(CN1,C1))),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),pn)),x))),And(FreeQ(List(a,b,pd,pe,f,pn),x),PositiveIntegerQ(m)))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§sec"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition($(Defer($s("Int")),Times(Power(Plus(a,Times(b,Sec(Plus(pe,Times(f,x))))),m),Power(Times(pd,Sec(Plus(pe,Times(f,x)))),pn)),x),And(FreeQ(List(a,b,pd,pe,f,m,pn),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b))))))),
ISetDelayed(Int(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_))))),m_),Power(Times(pd_DEFAULT,$($s("§csc"),Plus(pe_DEFAULT,Times(f_DEFAULT,x_)))),pn_)),x_Symbol),
    Condition($(Defer($s("Int")),Times(Power(Plus(a,Times(b,Csc(Plus(pe,Times(f,x))))),m),Power(Times(pd,Csc(Plus(pe,Times(f,x)))),pn)),x),And(FreeQ(List(a,b,pd,pe,f,m,pn),x),NonzeroQ(Plus(Sqr(a),Times(CN1,Sqr(b)))))))
  );
}
