package org.matheclipse.core.integrate.rubi45;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi45.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.ISymbol;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules103 { 
  public static IAST RULES = List( 
ISetDelayed(Int(Power(Sinh(Times(Power(Plus(Times(x_,pd_DEFAULT),c_DEFAULT),CN1),a_DEFAULT)),pn_DEFAULT),x_Symbol),
    Condition(Times(CN1,Power(pd,CN1),Subst(Int(Times(Power(Sinh(Times(a,x)),pn),Power(x,CN2)),x),x,Power(Plus(c,Times(pd,x)),CN1))),And(FreeQ(List(a,c,pd),x),PositiveIntegerQ(pn)))),
ISetDelayed(Int(Power(Cosh(Times(Power(Plus(Times(x_,pd_DEFAULT),c_DEFAULT),CN1),a_DEFAULT)),pn_DEFAULT),x_Symbol),
    Condition(Times(CN1,Power(pd,CN1),Subst(Int(Times(Power(Cosh(Times(a,x)),pn),Power(x,CN2)),x),x,Power(Plus(c,Times(pd,x)),CN1))),And(FreeQ(List(a,c,pd),x),PositiveIntegerQ(pn)))),
ISetDelayed(Int(Power(Sinh(Times(Plus(Times(b_DEFAULT,x_),a_DEFAULT),Power(Plus(Times(x_,pd_DEFAULT),c_DEFAULT),CN1),pe_DEFAULT)),pn_DEFAULT),x_Symbol),
    Condition(Times(CN1,Power(pd,CN1),Subst(Int(Times(Power(Sinh(Plus(Times(b,pe,Power(pd,CN1)),Times(CN1,pe,Plus(Times(b,c),Times(CN1,a,pd)),x,Power(pd,CN1)))),pn),Power(x,CN2)),x),x,Power(Plus(c,Times(pd,x)),CN1))),And(And(FreeQ(List(a,b,c,pd),x),PositiveIntegerQ(pn)),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))))),
ISetDelayed(Int(Power(Cosh(Times(Plus(Times(b_DEFAULT,x_),a_DEFAULT),Power(Plus(Times(x_,pd_DEFAULT),c_DEFAULT),CN1),pe_DEFAULT)),pn_DEFAULT),x_Symbol),
    Condition(Times(CN1,Power(pd,CN1),Subst(Int(Times(Power(Cosh(Plus(Times(b,pe,Power(pd,CN1)),Times(CN1,pe,Plus(Times(b,c),Times(CN1,a,pd)),x,Power(pd,CN1)))),pn),Power(x,CN2)),x),x,Power(Plus(c,Times(pd,x)),CN1))),And(And(FreeQ(List(a,b,c,pd),x),PositiveIntegerQ(pn)),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))))),
ISetDelayed(Int(Power(Sinh(u_),pn_DEFAULT),x_Symbol),
    Condition(Module(List(Set($s("lst"),QuotientOfLinearsParts(u,x))),Int(Power(Sinh(Times(Plus(Part($s("lst"),C1),Times(Part($s("lst"),C2),x)),Power(Plus(Part($s("lst"),C3),Times(Part($s("lst"),C4),x)),CN1))),pn),x)),And(PositiveIntegerQ(pn),QuotientOfLinearsQ(u,x)))),
ISetDelayed(Int(Power(Cosh(u_),pn_DEFAULT),x_Symbol),
    Condition(Module(List(Set($s("lst"),QuotientOfLinearsParts(u,x))),Int(Power(Cosh(Times(Plus(Part($s("lst"),C1),Times(Part($s("lst"),C2),x)),Power(Plus(Part($s("lst"),C3),Times(Part($s("lst"),C4),x)),CN1))),pn),x)),And(PositiveIntegerQ(pn),QuotientOfLinearsQ(u,x)))),
ISetDelayed(Int(Times(Power(Sinh(v_),p_DEFAULT),Power(Sinh(w_),q_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Int(Times(u,Power(Sinh(v),Plus(p,q))),x),ZeroQ(Plus(v,Times(CN1,w))))),
ISetDelayed(Int(Times(Power(Cosh(v_),p_DEFAULT),Power(Cosh(w_),q_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Int(Times(u,Power(Cosh(v),Plus(p,q))),x),ZeroQ(Plus(v,Times(CN1,w))))),
ISetDelayed(Int(Times(Power(Sinh(v_),p_DEFAULT),Power(Sinh(w_),q_DEFAULT)),x_Symbol),
    Condition(Int(ExpandTrigReduce(Times(Power(Sinh(v),p),Power(Sinh(w),q)),x),x),And(PositiveIntegerQ(p,q),Or(And(PolynomialQ(v,x),PolynomialQ(w,x)),And(BinomialQ(List(v,w),x),IndependentQ(Cancel(Times(v,Power(w,CN1))),x)))))),
ISetDelayed(Int(Times(Power(Cosh(v_),p_DEFAULT),Power(Cosh(w_),q_DEFAULT)),x_Symbol),
    Condition(Int(ExpandTrigReduce(Times(Power(Cosh(v),p),Power(Cosh(w),q)),x),x),And(PositiveIntegerQ(p,q),Or(And(PolynomialQ(v,x),PolynomialQ(w,x)),And(BinomialQ(List(v,w),x),IndependentQ(Cancel(Times(v,Power(w,CN1))),x)))))),
ISetDelayed(Int(Times(Power(Sinh(v_),p_DEFAULT),Power(Sinh(w_),q_DEFAULT),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Int(ExpandTrigReduce(Power(x,m),Times(Power(Sinh(v),p),Power(Sinh(w),q)),x),x),And(PositiveIntegerQ(m,p,q),Or(And(PolynomialQ(v,x),PolynomialQ(w,x)),And(BinomialQ(List(v,w),x),IndependentQ(Cancel(Times(v,Power(w,CN1))),x)))))),
ISetDelayed(Int(Times(Power(Cosh(v_),p_DEFAULT),Power(Cosh(w_),q_DEFAULT),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Int(ExpandTrigReduce(Power(x,m),Times(Power(Cosh(v),p),Power(Cosh(w),q)),x),x),And(PositiveIntegerQ(m,p,q),Or(And(PolynomialQ(v,x),PolynomialQ(w,x)),And(BinomialQ(List(v,w),x),IndependentQ(Cancel(Times(v,Power(w,CN1))),x)))))),
ISetDelayed(Int(Times(Power(Cosh(w_),p_DEFAULT),Power(Sinh(v_),p_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Times(Power(Power(C2,p),CN1),Int(Times(u,Power(Sinh(Times(C2,v)),p)),x)),And(ZeroQ(Plus(v,Times(CN1,w))),IntegerQ(p)))),
ISetDelayed(Int(Times(Power(Cosh(w_),q_DEFAULT),Power(Sinh(v_),p_DEFAULT)),x_Symbol),
    Condition(Int(ExpandTrigReduce(Times(Power(Sinh(v),p),Power(Cosh(w),q)),x),x),And(PositiveIntegerQ(p,q),Or(And(PolynomialQ(v,x),PolynomialQ(w,x)),And(BinomialQ(List(v,w),x),IndependentQ(Cancel(Times(v,Power(w,CN1))),x)))))),
ISetDelayed(Int(Times(Power(Cosh(w_),q_DEFAULT),Power(Sinh(v_),p_DEFAULT),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Int(ExpandTrigReduce(Power(x,m),Times(Power(Sinh(v),p),Power(Cosh(w),q)),x),x),And(PositiveIntegerQ(m,p,q),Or(And(PolynomialQ(v,x),PolynomialQ(w,x)),And(BinomialQ(List(v,w),x),IndependentQ(Cancel(Times(v,Power(w,CN1))),x)))))),
ISetDelayed(Int(Times(Power(Tanh(w_),pn_DEFAULT),Sinh(v_)),x_Symbol),
    Condition(Plus(Int(Times(Cosh(v),Power(Tanh(w),Plus(pn,Times(CN1,C1)))),x),Times(CN1,Cosh(Plus(v,Times(CN1,w))),Int(Times(Sech(w),Power(Tanh(w),Plus(pn,Times(CN1,C1)))),x))),And(And(And(RationalQ(pn),Greater(pn,C0)),FreeQ(Plus(v,Times(CN1,w)),x)),NonzeroQ(Plus(v,Times(CN1,w)))))),
ISetDelayed(Int(Times(Cosh(v_),Power(Coth(w_),pn_DEFAULT)),x_Symbol),
    Condition(Plus(Int(Times(Sinh(v),Power(Coth(w),Plus(pn,Times(CN1,C1)))),x),Times(Cosh(Plus(v,Times(CN1,w))),Int(Times(Csch(w),Power(Coth(w),Plus(pn,Times(CN1,C1)))),x))),And(And(And(RationalQ(pn),Greater(pn,C0)),FreeQ(Plus(v,Times(CN1,w)),x)),NonzeroQ(Plus(v,Times(CN1,w)))))),
ISetDelayed(Int(Times(Power(Coth(w_),pn_DEFAULT),Sinh(v_)),x_Symbol),
    Condition(Plus(Int(Times(Cosh(v),Power(Coth(w),Plus(pn,Times(CN1,C1)))),x),Times(Sinh(Plus(v,Times(CN1,w))),Int(Times(Csch(w),Power(Coth(w),Plus(pn,Times(CN1,C1)))),x))),And(And(And(RationalQ(pn),Greater(pn,C0)),FreeQ(Plus(v,Times(CN1,w)),x)),NonzeroQ(Plus(v,Times(CN1,w)))))),
ISetDelayed(Int(Times(Cosh(v_),Power(Tanh(w_),pn_DEFAULT)),x_Symbol),
    Condition(Plus(Int(Times(Sinh(v),Power(Tanh(w),Plus(pn,Times(CN1,C1)))),x),Times(CN1,Sinh(Plus(v,Times(CN1,w))),Int(Times(Sech(w),Power(Tanh(w),Plus(pn,Times(CN1,C1)))),x))),And(And(And(RationalQ(pn),Greater(pn,C0)),FreeQ(Plus(v,Times(CN1,w)),x)),NonzeroQ(Plus(v,Times(CN1,w)))))),
ISetDelayed(Int(Times(Power(Sech(w_),pn_DEFAULT),Sinh(v_)),x_Symbol),
    Condition(Plus(Times(Cosh(Plus(v,Times(CN1,w))),Int(Times(Tanh(w),Power(Sech(w),Plus(pn,Times(CN1,C1)))),x)),Times(Sinh(Plus(v,Times(CN1,w))),Int(Power(Sech(w),Plus(pn,Times(CN1,C1))),x))),And(And(And(RationalQ(pn),Greater(pn,C0)),FreeQ(Plus(v,Times(CN1,w)),x)),NonzeroQ(Plus(v,Times(CN1,w)))))),
ISetDelayed(Int(Times(Cosh(v_),Power(Csch(w_),pn_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Cosh(Plus(v,Times(CN1,w))),Int(Times(Coth(w),Power(Csch(w),Plus(pn,Times(CN1,C1)))),x)),Times(Sinh(Plus(v,Times(CN1,w))),Int(Power(Csch(w),Plus(pn,Times(CN1,C1))),x))),And(And(And(RationalQ(pn),Greater(pn,C0)),FreeQ(Plus(v,Times(CN1,w)),x)),NonzeroQ(Plus(v,Times(CN1,w)))))),
ISetDelayed(Int(Times(Power(Csch(w_),pn_DEFAULT),Sinh(v_)),x_Symbol),
    Condition(Plus(Times(Sinh(Plus(v,Times(CN1,w))),Int(Times(Coth(w),Power(Csch(w),Plus(pn,Times(CN1,C1)))),x)),Times(Cosh(Plus(v,Times(CN1,w))),Int(Power(Csch(w),Plus(pn,Times(CN1,C1))),x))),And(And(And(RationalQ(pn),Greater(pn,C0)),FreeQ(Plus(v,Times(CN1,w)),x)),NonzeroQ(Plus(v,Times(CN1,w)))))),
ISetDelayed(Int(Times(Cosh(v_),Power(Sech(w_),pn_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Sinh(Plus(v,Times(CN1,w))),Int(Times(Tanh(w),Power(Sech(w),Plus(pn,Times(CN1,C1)))),x)),Times(Cosh(Plus(v,Times(CN1,w))),Int(Power(Sech(w),Plus(pn,Times(CN1,C1))),x))),And(And(And(RationalQ(pn),Greater(pn,C0)),FreeQ(Plus(v,Times(CN1,w)),x)),NonzeroQ(Plus(v,Times(CN1,w)))))),
ISetDelayed(Int(Times(Power(Sinh(Plus(Times(Power(Plus(Times(x_,pd_DEFAULT),c_),pn_),b_DEFAULT),a_DEFAULT)),p_DEFAULT),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Times(Power(pd,CN1),Subst(Int(Times(Power(Plus(Times(CN1,c,Power(pd,CN1)),Times(x,Power(pd,CN1))),m),Power(Sinh(Plus(a,Times(b,Power(x,pn)))),p)),x),x,Plus(c,Times(pd,x)))),And(And(FreeQ(List(a,b,c,pd,pn),x),PositiveIntegerQ(m)),RationalQ(p)))),
ISetDelayed(Int(Times(Power(Cosh(Plus(Times(Power(Plus(Times(x_,pd_DEFAULT),c_),pn_),b_DEFAULT),a_DEFAULT)),p_DEFAULT),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Times(Power(pd,CN1),Subst(Int(Times(Power(Plus(Times(CN1,c,Power(pd,CN1)),Times(x,Power(pd,CN1))),m),Power(Cosh(Plus(a,Times(b,Power(x,pn)))),p)),x),x,Plus(c,Times(pd,x)))),And(And(FreeQ(List(a,b,c,pd,pn),x),PositiveIntegerQ(m)),RationalQ(p)))),
ISetDelayed(Int(Times(Power(Plus(Times(Sqr(Cosh(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),b_DEFAULT),Times(Sqr(Sinh(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),c_DEFAULT),a_DEFAULT),CN1),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Times(C2,Int(Times(Power(x,m),Power(Plus(Times(C2,a),b,Times(CN1,c),Times(Plus(b,c),Cosh(Plus(Times(C2,pd),Times(C2,pe,x))))),CN1)),x)),And(And(And(FreeQ(List(a,b,c,pd,pe),x),PositiveIntegerQ(m)),NonzeroQ(Plus(a,b))),NonzeroQ(Plus(a,c))))),
ISetDelayed(Int(Times(Power(Plus(Times(Sqr(Tanh(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),c_DEFAULT),b_),CN1),Sqr(Sech(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Times(C2,Int(Times(Power(x,m),Power(Plus(b,Times(CN1,c),Times(Plus(b,c),Cosh(Plus(Times(C2,pd),Times(C2,pe,x))))),CN1)),x)),And(FreeQ(List(b,c,pd,pe),x),PositiveIntegerQ(m)))),
ISetDelayed(Int(Times(Power(Plus(Times(Sqr(Sech(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),a_DEFAULT),Times(Sqr(Tanh(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),c_DEFAULT),b_DEFAULT),CN1),Sqr(Sech(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Times(C2,Int(Times(Power(x,m),Power(Plus(Times(C2,a),b,Times(CN1,c),Times(Plus(b,c),Cosh(Plus(Times(C2,pd),Times(C2,pe,x))))),CN1)),x)),And(And(And(FreeQ(List(a,b,c,pd,pe),x),PositiveIntegerQ(m)),NonzeroQ(Plus(a,b))),NonzeroQ(Plus(a,c))))),
ISetDelayed(Int(Times(Sqr(Csch(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),Power(Plus(Times(Sqr(Coth(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),b_DEFAULT),c_),CN1),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Times(C2,Int(Times(Power(x,m),Power(Plus(b,Times(CN1,c),Times(Plus(b,c),Cosh(Plus(Times(C2,pd),Times(C2,pe,x))))),CN1)),x)),And(FreeQ(List(b,c,pd,pe),x),PositiveIntegerQ(m)))),
ISetDelayed(Int(Times(Sqr(Csch(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),Power(Plus(Times(Sqr(Csch(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),a_DEFAULT),Times(Sqr(Coth(Plus(Times(x_,pe_DEFAULT),pd_DEFAULT))),b_DEFAULT),c_DEFAULT),CN1),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Times(C2,Int(Times(Power(x,m),Power(Plus(Times(C2,a),b,Times(CN1,c),Times(Plus(b,c),Cosh(Plus(Times(C2,pd),Times(C2,pe,x))))),CN1)),x)),And(And(And(FreeQ(List(a,b,c,pd,pe),x),PositiveIntegerQ(m)),NonzeroQ(Plus(a,b))),NonzeroQ(Plus(a,c))))),
ISetDelayed(Int(Times(Cosh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),Power(Plus(Times(Sinh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),b_DEFAULT),a_),CN1),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(CN1,Power(x,Plus(m,C1)),Power(Times(b,Plus(m,C1)),CN1)),Int(Times(Power(x,m),Power(E,Plus(c,Times(pd,x))),Power(Plus(a,Sqrt(Plus(Sqr(a),Sqr(b))),Times(b,Power(E,Plus(c,Times(pd,x))))),CN1)),x),Int(Times(Power(x,m),Power(E,Plus(c,Times(pd,x))),Power(Plus(a,Times(CN1,Sqrt(Plus(Sqr(a),Sqr(b)))),Times(b,Power(E,Plus(c,Times(pd,x))))),CN1)),x)),And(FreeQ(List(a,b,c,pd),x),PositiveIntegerQ(m)))),
ISetDelayed(Int(Times(Power(Plus(Times(Cosh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),b_DEFAULT),a_),CN1),Power(x_,m_DEFAULT),Sinh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT))),x_Symbol),
    Condition(Plus(Times(CN1,Power(x,Plus(m,C1)),Power(Times(b,Plus(m,C1)),CN1)),Int(Times(Power(x,m),Power(E,Plus(c,Times(pd,x))),Power(Plus(a,Sqrt(Plus(Sqr(a),Times(CN1,Sqr(b)))),Times(b,Power(E,Plus(c,Times(pd,x))))),CN1)),x),Int(Times(Power(x,m),Power(E,Plus(c,Times(pd,x))),Power(Plus(a,Times(CN1,Sqrt(Plus(Sqr(a),Times(CN1,Sqr(b))))),Times(b,Power(E,Plus(c,Times(pd,x))))),CN1)),x)),And(FreeQ(List(a,b,c,pd),x),PositiveIntegerQ(m)))),
ISetDelayed(Int(Times(Power(Cosh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),pn_),Power(Plus(Times(Sinh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),b_DEFAULT),a_),CN1),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(CN1,a,Power(b,CN2),Int(Times(Power(x,m),Power(Cosh(Plus(c,Times(pd,x))),Plus(pn,Times(CN1,C2)))),x)),Times(Power(b,CN1),Int(Times(Power(x,m),Power(Cosh(Plus(c,Times(pd,x))),Plus(pn,Times(CN1,C2))),Sinh(Plus(c,Times(pd,x)))),x)),Times(Plus(Sqr(a),Sqr(b)),Power(b,CN2),Int(Times(Power(x,m),Power(Cosh(Plus(c,Times(pd,x))),Plus(pn,Times(CN1,C2))),Power(Plus(a,Times(b,Sinh(Plus(c,Times(pd,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),PositiveIntegerQ(m)),IntegerQ(pn)),Greater(pn,C1)))),
ISetDelayed(Int(Times(Power(Plus(Times(Cosh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),b_DEFAULT),a_),CN1),Power(Sinh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),pn_),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(CN1,a,Power(b,CN2),Int(Times(Power(x,m),Power(Sinh(Plus(c,Times(pd,x))),Plus(pn,Times(CN1,C2)))),x)),Times(Power(b,CN1),Int(Times(Power(x,m),Power(Sinh(Plus(c,Times(pd,x))),Plus(pn,Times(CN1,C2))),Cosh(Plus(c,Times(pd,x)))),x)),Times(Plus(Sqr(a),Times(CN1,Sqr(b))),Power(b,CN2),Int(Times(Power(x,m),Power(Sinh(Plus(c,Times(pd,x))),Plus(pn,Times(CN1,C2))),Power(Plus(a,Times(b,Cosh(Plus(c,Times(pd,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),PositiveIntegerQ(m)),IntegerQ(pn)),Greater(pn,C1)))),
ISetDelayed(Int(Times(Plus(Times(Sinh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),pb_DEFAULT),pa_),Power(Plus(Times(Sinh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),b_DEFAULT),a_),CN2),x_),x_Symbol),
    Condition(Plus(Times(pb,x,Cosh(Plus(c,Times(pd,x))),Power(Times(a,pd,Plus(a,Times(b,Sinh(Plus(c,Times(pd,x)))))),CN1)),Times(CN1,pb,Power(Times(a,pd),CN1),Int(Times(Cosh(Plus(c,Times(pd,x))),Power(Plus(a,Times(b,Sinh(Plus(c,Times(pd,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd,pa,pb),x),ZeroQ(Plus(Times(a,pa),Times(b,pb)))))),
ISetDelayed(Int(Times(Plus(Times(Cosh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),pb_DEFAULT),pa_),Power(Plus(Times(Cosh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),b_DEFAULT),a_),CN2),x_),x_Symbol),
    Condition(Plus(Times(pb,x,Sinh(Plus(c,Times(pd,x))),Power(Times(a,pd,Plus(a,Times(b,Cosh(Plus(c,Times(pd,x)))))),CN1)),Times(CN1,pb,Power(Times(a,pd),CN1),Int(Times(Sinh(Plus(c,Times(pd,x))),Power(Plus(a,Times(b,Cosh(Plus(c,Times(pd,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd,pa,pb),x),ZeroQ(Plus(Times(a,pa),Times(CN1,b,pb)))))),
ISetDelayed(Int(Times(Power(Plus(Times(Tanh(v_),b_DEFAULT),a_),pn_DEFAULT),Power(Sech(v_),m_DEFAULT)),x_Symbol),
    Condition(Int(Power(Plus(Times(a,Cosh(v)),Times(b,Sinh(v))),pn),x),And(And(And(FreeQ(List(a,b),x),IntegersQ(m,pn)),Equal(Plus(m,pn),C0)),OddQ(m)))),
ISetDelayed(Int(Times(Power(Csch(v_),m_DEFAULT),Power(Plus(Times(Coth(v_),b_DEFAULT),a_),pn_DEFAULT)),x_Symbol),
    Condition(Int(Power(Plus(Times(b,Cosh(v)),Times(a,Sinh(v))),pn),x),And(And(And(FreeQ(List(a,b),x),IntegersQ(m,pn)),Equal(Plus(m,pn),C0)),OddQ(m)))),
ISetDelayed(Int(Times(Power(Sinh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),m_DEFAULT),Power(Sinh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),pn_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Int(ExpandTrigReduce(u,Times(Power(Sinh(Plus(a,Times(b,x))),m),Power(Sinh(Plus(c,Times(pd,x))),pn)),x),x),And(FreeQ(List(a,b,c,pd),x),PositiveIntegerQ(m,pn)))),
ISetDelayed(Int(Times(Power(Cosh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),m_DEFAULT),Power(Cosh(Plus(Times(x_,pd_DEFAULT),c_DEFAULT)),pn_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Int(ExpandTrigReduce(u,Times(Power(Cosh(Plus(a,Times(b,x))),m),Power(Cosh(Plus(c,Times(pd,x))),pn)),x),x),And(FreeQ(List(a,b,c,pd),x),PositiveIntegerQ(m,pn)))),
ISetDelayed(Int(Times(Sech(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),Sech(Plus(Times(x_,pd_DEFAULT),c_))),x_Symbol),
    Condition(Plus(Times(CN1,Csch(Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(pd,CN1))),Int(Tanh(Plus(a,Times(b,x))),x)),Times(Csch(Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(b,CN1))),Int(Tanh(Plus(c,Times(pd,x))),x))),And(And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(b),Times(CN1,Sqr(pd))))),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))))),
ISetDelayed(Int(Times(Csch(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),Csch(Plus(Times(x_,pd_DEFAULT),c_))),x_Symbol),
    Condition(Plus(Times(Csch(Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(b,CN1))),Int(Coth(Plus(a,Times(b,x))),x)),Times(CN1,Csch(Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(pd,CN1))),Int(Coth(Plus(c,Times(pd,x))),x))),And(And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(b),Times(CN1,Sqr(pd))))),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))))),
ISetDelayed(Int(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),Tanh(Plus(Times(x_,pd_DEFAULT),c_))),x_Symbol),
    Condition(Plus(Times(b,x,Power(pd,CN1)),Times(CN1,b,Power(pd,CN1),Cosh(Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(pd,CN1))),Int(Times(Sech(Plus(a,Times(b,x))),Sech(Plus(c,Times(pd,x)))),x))),And(And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(b),Times(CN1,Sqr(pd))))),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))))),
ISetDelayed(Int(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),Coth(Plus(Times(x_,pd_DEFAULT),c_))),x_Symbol),
    Condition(Plus(Times(b,x,Power(pd,CN1)),Times(Cosh(Times(Plus(Times(b,c),Times(CN1,a,pd)),Power(pd,CN1))),Int(Times(Csch(Plus(a,Times(b,x))),Csch(Plus(c,Times(pd,x)))),x))),And(And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(b),Times(CN1,Sqr(pd))))),NonzeroQ(Plus(Times(b,c),Times(CN1,a,pd)))))),
ISetDelayed(Int(ArcTan(Plus(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Plus(Times(x,ArcTan(Plus(c,Times(pd,Tanh(Plus(a,Times(b,x))))))),Times(CN1,b,Int(Times(x,Power(Plus(c,Times(CN1,pd),Times(c,Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))))),
ISetDelayed(Int(ArcCot(Plus(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Plus(Times(x,ArcCot(Plus(c,Times(pd,Tanh(Plus(a,Times(b,x))))))),Times(b,Int(Times(x,Power(Plus(c,Times(CN1,pd),Times(c,Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))))),
ISetDelayed(Int(ArcTan(Plus(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Plus(Times(x,ArcTan(Plus(c,Times(pd,Tanh(Plus(a,Times(b,x))))))),Times(CN1,CI,b,Plus(Times(CN1,CI),c,Times(CN1,pd)),Int(Times(x,Power(Plus(Times(CN1,CI),c,Times(CN1,pd),Times(Plus(Times(CN1,CI),c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x)),Times(CI,b,Plus(CI,c,Times(CN1,pd)),Int(Times(x,Power(Plus(CI,c,Times(CN1,pd),Times(Plus(CI,c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd),x),NonzeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))))),
ISetDelayed(Int(ArcCot(Plus(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Plus(Times(x,ArcCot(Plus(c,Times(pd,Tanh(Plus(a,Times(b,x))))))),Times(CI,b,Plus(Times(CN1,CI),c,Times(CN1,pd)),Int(Times(x,Power(Plus(Times(CN1,CI),c,Times(CN1,pd),Times(Plus(Times(CN1,CI),c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x)),Times(CN1,CI,b,Plus(CI,c,Times(CN1,pd)),Int(Times(x,Power(Plus(CI,c,Times(CN1,pd),Times(Plus(CI,c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd),x),NonzeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))))),
ISetDelayed(Int(Times(ArcTan(Plus(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),ArcTan(Plus(c,Times(pd,Tanh(Plus(a,Times(b,x)))))),Power(Plus(m,C1),CN1)),Times(CN1,b,Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(c,Times(CN1,pd),Times(c,Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))),RationalQ(m)),Greater(m,C0)))),
ISetDelayed(Int(Times(ArcCot(Plus(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),ArcCot(Plus(c,Times(pd,Tanh(Plus(a,Times(b,x)))))),Power(Plus(m,C1),CN1)),Times(b,Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(c,Times(CN1,pd),Times(c,Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))),RationalQ(m)),Greater(m,C0)))),
ISetDelayed(Int(Times(ArcTan(Plus(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),ArcTan(Plus(c,Times(pd,Tanh(Plus(a,Times(b,x)))))),Power(Plus(m,C1),CN1)),Times(CN1,CI,b,Plus(Times(CN1,CI),c,Times(CN1,pd)),Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(Times(CN1,CI),c,Times(CN1,pd),Times(Plus(Times(CN1,CI),c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x)),Times(CI,b,Plus(CI,c,Times(CN1,pd)),Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(CI,c,Times(CN1,pd),Times(Plus(CI,c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),NonzeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))),RationalQ(m)),Greater(m,C0)))),
ISetDelayed(Int(Times(ArcCot(Plus(Times(Tanh(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),ArcCot(Plus(c,Times(pd,Tanh(Plus(a,Times(b,x)))))),Power(Plus(m,C1),CN1)),Times(CI,b,Plus(Times(CN1,CI),c,Times(CN1,pd)),Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(Times(CN1,CI),c,Times(CN1,pd),Times(Plus(Times(CN1,CI),c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x)),Times(CN1,CI,b,Plus(CI,c,Times(CN1,pd)),Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(CI,c,Times(CN1,pd),Times(Plus(CI,c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),NonzeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))),RationalQ(m)),Greater(m,C0)))),
ISetDelayed(Int(ArcTan(Plus(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Plus(Times(x,ArcTan(Plus(c,Times(pd,Coth(Plus(a,Times(b,x))))))),Times(CN1,b,Int(Times(x,Power(Plus(c,Times(CN1,pd),Times(CN1,c,Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))))),
ISetDelayed(Int(ArcCot(Plus(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Plus(Times(x,ArcCot(Plus(c,Times(pd,Coth(Plus(a,Times(b,x))))))),Times(b,Int(Times(x,Power(Plus(c,Times(CN1,pd),Times(CN1,c,Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))))),
ISetDelayed(Int(ArcTan(Plus(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Plus(Times(x,ArcTan(Plus(c,Times(pd,Coth(Plus(a,Times(b,x))))))),Times(CN1,CI,b,Plus(Times(CN1,CI),c,Times(CN1,pd)),Int(Times(x,Power(Plus(Times(CN1,CI),c,Times(CN1,pd),Times(CN1,Plus(Times(CN1,CI),c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x)),Times(CI,b,Plus(CI,c,Times(CN1,pd)),Int(Times(x,Power(Plus(CI,c,Times(CN1,pd),Times(CN1,Plus(CI,c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd),x),NonzeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))))),
ISetDelayed(Int(ArcCot(Plus(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Plus(Times(x,ArcCot(Plus(c,Times(pd,Coth(Plus(a,Times(b,x))))))),Times(CI,b,Plus(Times(CN1,CI),c,Times(CN1,pd)),Int(Times(x,Power(Plus(Times(CN1,CI),c,Times(CN1,pd),Times(CN1,Plus(Times(CN1,CI),c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x)),Times(CN1,CI,b,Plus(CI,c,Times(CN1,pd)),Int(Times(x,Power(Plus(CI,c,Times(CN1,pd),Times(CN1,Plus(CI,c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(FreeQ(List(a,b,c,pd),x),NonzeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))))),
ISetDelayed(Int(Times(ArcTan(Plus(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),ArcTan(Plus(c,Times(pd,Coth(Plus(a,Times(b,x)))))),Power(Plus(m,C1),CN1)),Times(CN1,b,Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(c,Times(CN1,pd),Times(CN1,c,Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))),RationalQ(m)),Greater(m,C0)))),
ISetDelayed(Int(Times(ArcCot(Plus(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),ArcCot(Plus(c,Times(pd,Coth(Plus(a,Times(b,x)))))),Power(Plus(m,C1),CN1)),Times(b,Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(c,Times(CN1,pd),Times(CN1,c,Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),ZeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))),RationalQ(m)),Greater(m,C0)))),
ISetDelayed(Int(Times(ArcTan(Plus(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),ArcTan(Plus(c,Times(pd,Coth(Plus(a,Times(b,x)))))),Power(Plus(m,C1),CN1)),Times(CN1,CI,b,Plus(Times(CN1,CI),c,Times(CN1,pd)),Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(Times(CN1,CI),c,Times(CN1,pd),Times(CN1,Plus(Times(CN1,CI),c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x)),Times(CI,b,Plus(CI,c,Times(CN1,pd)),Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(CI,c,Times(CN1,pd),Times(CN1,Plus(CI,c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),NonzeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))),RationalQ(m)),Greater(m,C0)))),
ISetDelayed(Int(Times(ArcCot(Plus(Times(Coth(Plus(Times(b_DEFAULT,x_),a_DEFAULT)),pd_DEFAULT),c_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Plus(Times(Power(x,Plus(m,C1)),ArcCot(Plus(c,Times(pd,Coth(Plus(a,Times(b,x)))))),Power(Plus(m,C1),CN1)),Times(CI,b,Plus(Times(CN1,CI),c,Times(CN1,pd)),Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(Times(CN1,CI),c,Times(CN1,pd),Times(CN1,Plus(Times(CN1,CI),c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x)),Times(CN1,CI,b,Plus(CI,c,Times(CN1,pd)),Power(Plus(m,C1),CN1),Int(Times(Power(x,Plus(m,C1)),Power(Plus(CI,c,Times(CN1,pd),Times(CN1,Plus(CI,c,pd),Power(E,Plus(Times(C2,a),Times(C2,b,x))))),CN1)),x))),And(And(And(FreeQ(List(a,b,c,pd),x),NonzeroQ(Plus(Sqr(Plus(c,Times(CN1,pd))),C1))),RationalQ(m)),Greater(m,C0))))
  );
}
