package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules50 { 

	public static void initialize() {
		Initializer.init();
	}

	private static class Initializer  {

		private static void init() {
IIntegrate(2501,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),u_DEFAULT),Power(Plus(s_DEFAULT,Times(Log(Times(i_DEFAULT,Power(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),n_DEFAULT))),t_DEFAULT)),m_DEFAULT),Power(Plus(j_DEFAULT,Times(k_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Unintegrable(Times(Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),u),Power(Plus(s,Times(t,Log(Times(i,Power(Plus(g,Times(h,x)),n))))),m),Power(Plus(j,Times(k,x)),CN1)),x),And(FreeQ(List(a,b,c,d,e,f,g,h,i,j,k,s,t,m,n,p,q,r,u),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0))));
IIntegrate(2502,Int(Times(Log(Times(e_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),CN1),Plus(c_DEFAULT,Times(d_DEFAULT,x_)))),u_),x_Symbol),
    Condition(With(List(Set(g,Coeff(Simplify(Power(Times(u,Plus(a,Times(b,x))),CN1)),x,C0)),Set(h,Coeff(Simplify(Power(Times(u,Plus(a,Times(b,x))),CN1)),x,C1))),Condition(Negate(Dist(Times(Subtract(b,Times(d,e)),Power(Times(h,Subtract(Times(b,c),Times(a,d))),CN1)),Subst(Int(Times(Log(Times(e,x)),Power(Subtract(C1,Times(e,x)),CN1)),x),x,Times(Plus(c,Times(d,x)),Power(Plus(a,Times(b,x)),CN1))),x)),EqQ(Subtract(Times(g,Subtract(b,Times(d,e))),Times(h,Subtract(a,Times(c,e)))),C0))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LinearQ(Simplify(Power(Times(u,Plus(a,Times(b,x))),CN1)),x))));
IIntegrate(2503,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),s_DEFAULT),u_),x_Symbol),
    Condition(With(List(Set(g,Coeff(Simplify(Power(Times(u,Plus(a,Times(b,x))),CN1)),x,C0)),Set(h,Coeff(Simplify(Power(Times(u,Plus(a,Times(b,x))),CN1)),x,C1))),Condition(Plus(Negate(Simp(Times(Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),s),Log(Times(CN1,Subtract(Times(b,c),Times(a,d)),Plus(g,Times(h,x)),Power(Times(Subtract(Times(d,g),Times(c,h)),Plus(a,Times(b,x))),CN1))),Power(Subtract(Times(b,g),Times(a,h)),CN1)),x)),Dist(Times(p,r,s,Subtract(Times(b,c),Times(a,d)),Power(Subtract(Times(b,g),Times(a,h)),CN1)),Int(Times(Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),Subtract(s,C1)),Log(Times(CN1,Subtract(Times(b,c),Times(a,d)),Plus(g,Times(h,x)),Power(Times(Subtract(Times(d,g),Times(c,h)),Plus(a,Times(b,x))),CN1))),Power(Times(Plus(a,Times(b,x)),Plus(c,Times(d,x))),CN1)),x),x)),And(NeQ(Subtract(Times(b,g),Times(a,h)),C0),NeQ(Subtract(Times(d,g),Times(c,h)),C0)))),And(FreeQ(List(a,b,c,d,e,f,p,q,r,s),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),IGtQ(s,C0),EqQ(Plus(p,q),C0),LinearQ(Simplify(Power(Times(u,Plus(a,Times(b,x))),CN1)),x))));
IIntegrate(2504,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),CN1),u_),x_Symbol),
    Condition(With(List(Set(h,Simplify(Times(u,Plus(a,Times(b,x)),Plus(c,Times(d,x)))))),Condition(Simp(Times(h,Log(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r)))),Power(Times(p,r,Subtract(Times(b,c),Times(a,d))),CN1)),x),FreeQ(h,x))),And(FreeQ(List(a,b,c,d,e,f,p,q,r),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(p,q),C0))));
IIntegrate(2505,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),s_DEFAULT),u_),x_Symbol),
    Condition(With(List(Set(h,Simplify(Times(u,Plus(a,Times(b,x)),Plus(c,Times(d,x)))))),Condition(Simp(Times(h,Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),Plus(s,C1)),Power(Times(p,r,Plus(s,C1),Subtract(Times(b,c),Times(a,d))),CN1)),x),FreeQ(h,x))),And(FreeQ(List(a,b,c,d,e,f,p,q,r,s),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(p,q),C0),NeQ(s,CN1))));
IIntegrate(2506,Int(Times(Log(v_),Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),s_DEFAULT),u_),x_Symbol),
    Condition(With(List(Set(g,Simplify(Times(Subtract(v,C1),Plus(c,Times(d,x)),Power(Plus(a,Times(b,x)),CN1)))),Set(h,Simplify(Times(u,Plus(a,Times(b,x)),Plus(c,Times(d,x)))))),Condition(Plus(Negate(Simp(Times(h,PolyLog(C2,Subtract(C1,v)),Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),s),Power(Subtract(Times(b,c),Times(a,d)),CN1)),x)),Dist(Times(h,p,r,s),Int(Times(PolyLog(C2,Subtract(C1,v)),Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),Subtract(s,C1)),Power(Times(Plus(a,Times(b,x)),Plus(c,Times(d,x))),CN1)),x),x)),FreeQ(List(g,h),x))),And(FreeQ(List(a,b,c,d,e,f,p,q,r,s),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),IGtQ(s,C0),EqQ(Plus(p,q),C0))));
IIntegrate(2507,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),s_DEFAULT),Log(Times(i_DEFAULT,Power(Times(j_DEFAULT,Power(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),t_DEFAULT)),u_DEFAULT))),v_),x_Symbol),
    Condition(With(List(Set(k,Simplify(Times(v,Plus(a,Times(b,x)),Plus(c,Times(d,x)))))),Condition(Subtract(Simp(Times(k,Log(Times(i,Power(Times(j,Power(Plus(g,Times(h,x)),t)),u))),Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),Plus(s,C1)),Power(Times(p,r,Plus(s,C1),Subtract(Times(b,c),Times(a,d))),CN1)),x),Dist(Times(k,h,t,u,Power(Times(p,r,Plus(s,C1),Subtract(Times(b,c),Times(a,d))),CN1)),Int(Times(Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),Plus(s,C1)),Power(Plus(g,Times(h,x)),CN1)),x),x)),FreeQ(k,x))),And(FreeQ(List(a,b,c,d,e,f,g,h,i,j,p,q,r,s,t,u),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(p,q),C0),NeQ(s,CN1))));
IIntegrate(2508,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),s_DEFAULT),u_,PolyLog(n_,v_)),x_Symbol),
    Condition(With(List(Set(g,Simplify(Times(v,Plus(c,Times(d,x)),Power(Plus(a,Times(b,x)),CN1)))),Set(h,Simplify(Times(u,Plus(a,Times(b,x)),Plus(c,Times(d,x)))))),Condition(Subtract(Simp(Times(h,PolyLog(Plus(n,C1),v),Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),s),Power(Subtract(Times(b,c),Times(a,d)),CN1)),x),Dist(Times(h,p,r,s),Int(Times(PolyLog(Plus(n,C1),v),Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),Subtract(s,C1)),Power(Times(Plus(a,Times(b,x)),Plus(c,Times(d,x))),CN1)),x),x)),FreeQ(List(g,h),x))),And(FreeQ(List(a,b,c,d,e,f,n,p,q,r,s),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),IGtQ(s,C0),EqQ(Plus(p,q),C0))));
IIntegrate(2509,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),s_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),s),Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d))),CN1)),x),Dist(Times(p,r,s,Subtract(Times(b,c),Times(a,d)),Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d))),CN1)),Int(Times(Power(Plus(a,Times(b,x)),m),Power(Plus(c,Times(d,x)),n),Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),Subtract(s,C1))),x),x)),And(FreeQ(List(a,b,c,d,e,f,m,n,p,q,r,s),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(p,q),C0),EqQ(Plus(m,n,C2),C0),NeQ(m,CN1),IGtQ(s,C0))));
IIntegrate(2510,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_DEFAULT)),x_Symbol),
    Condition(Simp(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),ExpIntegralEi(Times(Plus(m,C1),Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),Power(Times(p,r),CN1))),Power(Times(p,r,Subtract(Times(b,c),Times(a,d)),Power(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r)),Times(Plus(m,C1),Power(Times(p,r),CN1)))),CN1)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p,q,r),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(p,q),C0),EqQ(Plus(m,n,C2),C0),NeQ(m,CN1))));
IIntegrate(2511,Int(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Sqrt(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),CN1D2))),b_DEFAULT)),n_DEFAULT),Power(Plus(A_DEFAULT,Times(B_DEFAULT,x_),Times(C_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Dist(Times(C2,e,g,Power(Times(CSymbol,Subtract(Times(e,f),Times(d,g))),CN1)),Subst(Int(Times(Power(Plus(a,Times(b,Log(Times(c,x)))),n),Power(x,CN1)),x),x,Times(Sqrt(Plus(d,Times(e,x))),Power(Plus(f,Times(g,x)),CN1D2))),x),And(FreeQ(List(a,b,c,d,e,f,g,ASymbol,BSymbol,CSymbol,n),x),EqQ(Subtract(Times(CSymbol,d,f),Times(ASymbol,e,g)),C0),EqQ(Subtract(Times(BSymbol,e,g),Times(CSymbol,Plus(Times(e,f),Times(d,g)))),C0))));
IIntegrate(2512,Int(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Sqrt(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),CN1D2))),b_DEFAULT)),n_DEFAULT),Power(Plus(A_DEFAULT,Times(C_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Dist(Times(g,Power(Times(CSymbol,f),CN1)),Subst(Int(Times(Power(Plus(a,Times(b,Log(Times(c,x)))),n),Power(x,CN1)),x),x,Times(Sqrt(Plus(d,Times(e,x))),Power(Plus(f,Times(g,x)),CN1D2))),x),And(FreeQ(List(a,b,c,d,e,f,g,ASymbol,CSymbol,n),x),EqQ(Subtract(Times(CSymbol,d,f),Times(ASymbol,e,g)),C0),EqQ(Plus(Times(e,f),Times(d,g)),C0))));
IIntegrate(2513,Int(Times(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),$p("§rfx",true)),x_Symbol),
    Condition(Plus(Dist(Times(p,r),Int(Times($s("§rfx"),Log(Plus(a,Times(b,x)))),x),x),Dist(Times(q,r),Int(Times($s("§rfx"),Log(Plus(c,Times(d,x)))),x),x),Negate(Dist(Subtract(Plus(Times(p,r,Log(Plus(a,Times(b,x)))),Times(q,r,Log(Plus(c,Times(d,x))))),Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r)))),Int($s("§rfx"),x),x))),And(FreeQ(List(a,b,c,d,e,f,p,q,r),x),RationalFunctionQ($s("§rfx"),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),Not(MatchQ($s("§rfx"),Condition(Times(u_DEFAULT,Power(Plus(a,Times(b,x)),m_DEFAULT),Power(Plus(c,Times(d,x)),n_DEFAULT)),IntegersQ(m,n)))))));
IIntegrate(2514,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),s_DEFAULT),$p("§rfx")),x_Symbol),
    Condition(With(List(Set(u,ExpandIntegrand(Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),s),$s("§rfx"),x))),Condition(Int(u,x),SumQ(u))),And(FreeQ(List(a,b,c,d,e,f,p,q,r,s),x),RationalFunctionQ($s("§rfx"),x),IGtQ(s,C0))));
IIntegrate(2515,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),q_DEFAULT)),r_DEFAULT))),s_DEFAULT),$p("§rfx")),x_Symbol),
    Condition(Unintegrable(Times($s("§rfx"),Power(Log(Times(e,Power(Times(f,Power(Plus(a,Times(b,x)),p),Power(Plus(c,Times(d,x)),q)),r))),s)),x),And(FreeQ(List(a,b,c,d,e,f,p,q,r,s),x),RationalFunctionQ($s("§rfx"),x))));
IIntegrate(2516,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Power(v_,p_DEFAULT),Power(w_,q_DEFAULT)),r_DEFAULT))),s_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Int(Times(u,Power(Log(Times(e,Power(Times(f,Power(ExpandToSum(v,x),p),Power(ExpandToSum(w,x),q)),r))),s)),x),And(FreeQ(List(e,f,p,q,r,s),x),LinearQ(List(v,w),x),Not(LinearMatchQ(List(v,w),x)),AlgebraicFunctionQ(u,x))));
IIntegrate(2517,Int(Times(Power(Log(Times(e_DEFAULT,Power(Times(f_DEFAULT,Plus(g_,Times(v_DEFAULT,Power(w_,CN1)))),r_DEFAULT))),s_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Int(Times(u,Power(Log(Times(e,Power(Times(f,ExpandToSum(Plus(v,Times(g,w)),x),Power(ExpandToSum(w,x),CN1)),r))),s)),x),And(FreeQ(List(e,f,g,r,s),x),LinearQ(w,x),Or(FreeQ(v,x),LinearQ(v,x)),AlgebraicFunctionQ(u,x))));
IIntegrate(2518,Int(Times(Log(v_),u_),x_Symbol),
    With(List(Set(w,DerivativeDivides(v,Times(u,Subtract(C1,v)),x))),Condition(Simp(Times(w,PolyLog(C2,Subtract(C1,v))),x),Not(FalseQ(w)))));
IIntegrate(2519,Int(Times(Log(v_),Plus(a_DEFAULT,Times(Log(u_),b_DEFAULT)),w_),x_Symbol),
    Condition(With(List(Set(z,DerivativeDivides(v,Times(w,Subtract(C1,v)),x))),Condition(Subtract(Simp(Times(z,Plus(a,Times(b,Log(u))),PolyLog(C2,Subtract(C1,v))),x),Dist(b,Int(SimplifyIntegrand(Times(z,PolyLog(C2,Subtract(C1,v)),D(u,x),Power(u,CN1)),x),x),x)),Not(FalseQ(z)))),And(FreeQ(List(a,b),x),InverseFunctionFreeQ(u,x))));
IIntegrate(2520,Int(Log(Times(Power(Log(Times(d_DEFAULT,Power(x_,n_DEFAULT))),p_DEFAULT),c_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(x,Log(Times(c,Power(Log(Times(d,Power(x,n))),p)))),x),Dist(Times(n,p),Int(Power(Log(Times(d,Power(x,n))),CN1),x),x)),FreeQ(List(c,d,n,p),x)));
IIntegrate(2521,Int(Times(Plus(a_DEFAULT,Times(Log(Times(Power(Log(Times(d_DEFAULT,Power(x_,n_DEFAULT))),p_DEFAULT),c_DEFAULT)),b_DEFAULT)),Power(x_,CN1)),x_Symbol),
    Condition(Subtract(Simp(Times(Log(Times(d,Power(x,n))),Plus(a,Times(b,Log(Times(c,Power(Log(Times(d,Power(x,n))),p))))),Power(n,CN1)),x),Simp(Times(b,p,Log(x)),x)),FreeQ(List(a,b,c,d,n,p),x)));
IIntegrate(2522,Int(Times(Plus(a_DEFAULT,Times(Log(Times(Power(Log(Times(d_DEFAULT,Power(x_,n_DEFAULT))),p_DEFAULT),c_DEFAULT)),b_DEFAULT)),Power(Times(e_DEFAULT,x_),m_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Times(e,x),Plus(m,C1)),Plus(a,Times(b,Log(Times(c,Power(Log(Times(d,Power(x,n))),p))))),Power(Times(e,Plus(m,C1)),CN1)),x),Dist(Times(b,n,p,Power(Plus(m,C1),CN1)),Int(Times(Power(Times(e,x),m),Power(Log(Times(d,Power(x,n))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,m,n,p),x),NeQ(m,CN1))));
IIntegrate(2523,Int(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power($p("§rfx"),p_DEFAULT))),b_DEFAULT)),n_DEFAULT),x_Symbol),
    Condition(Subtract(Simp(Times(x,Power(Plus(a,Times(b,Log(Times(c,Power($s("§rfx"),p))))),n)),x),Dist(Times(b,n,p),Int(SimplifyIntegrand(Times(x,Power(Plus(a,Times(b,Log(Times(c,Power($s("§rfx"),p))))),Subtract(n,C1)),D($s("§rfx"),x),Power($s("§rfx"),CN1)),x),x),x)),And(FreeQ(List(a,b,c,p),x),RationalFunctionQ($s("§rfx"),x),IGtQ(n,C0))));
IIntegrate(2524,Int(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power($p("§rfx"),p_DEFAULT))),b_DEFAULT)),n_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Subtract(Simp(Times(Log(Plus(d,Times(e,x))),Power(Plus(a,Times(b,Log(Times(c,Power($s("§rfx"),p))))),n),Power(e,CN1)),x),Dist(Times(b,n,p,Power(e,CN1)),Int(Times(Log(Plus(d,Times(e,x))),Power(Plus(a,Times(b,Log(Times(c,Power($s("§rfx"),p))))),Subtract(n,C1)),D($s("§rfx"),x),Power($s("§rfx"),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,p),x),RationalFunctionQ($s("§rfx"),x),IGtQ(n,C0))));
IIntegrate(2525,Int(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power($p("§rfx"),p_DEFAULT))),b_DEFAULT)),n_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(d,Times(e,x)),Plus(m,C1)),Power(Plus(a,Times(b,Log(Times(c,Power($s("§rfx"),p))))),n),Power(Times(e,Plus(m,C1)),CN1)),x),Dist(Times(b,n,p,Power(Times(e,Plus(m,C1)),CN1)),Int(SimplifyIntegrand(Times(Power(Plus(d,Times(e,x)),Plus(m,C1)),Power(Plus(a,Times(b,Log(Times(c,Power($s("§rfx"),p))))),Subtract(n,C1)),D($s("§rfx"),x),Power($s("§rfx"),CN1)),x),x),x)),And(FreeQ(List(a,b,c,d,e,m,p),x),RationalFunctionQ($s("§rfx"),x),IGtQ(n,C0),Or(EqQ(n,C1),IntegerQ(m)),NeQ(m,CN1))));
IIntegrate(2526,Int(Times(Log(Times(c_DEFAULT,Power($p("§rfx"),n_DEFAULT))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(List(Set(u,IntHide(Power(Plus(d,Times(e,Sqr(x))),CN1),x))),Subtract(Simp(Times(u,Log(Times(c,Power($s("§rfx"),n)))),x),Dist(n,Int(SimplifyIntegrand(Times(u,D($s("§rfx"),x),Power($s("§rfx"),CN1)),x),x),x))),And(FreeQ(List(c,d,e,n),x),RationalFunctionQ($s("§rfx"),x),Not(PolynomialQ($s("§rfx"),x)))));
IIntegrate(2527,Int(Times(Log(Times(c_DEFAULT,Power($p("§px"),n_DEFAULT))),Power($p("§qx"),CN1)),x_Symbol),
    Condition(With(List(Set(u,IntHide(Power($s("§qx"),CN1),x))),Subtract(Simp(Times(u,Log(Times(c,Power($s("§px"),n)))),x),Dist(n,Int(SimplifyIntegrand(Times(u,D($s("§px"),x),Power($s("§px"),CN1)),x),x),x))),And(FreeQ(List(c,n),x),QuadraticQ(List($s("§qx"),$s("§px")),x),EqQ(D(Times($s("§px"),Power($s("§qx"),CN1)),x),C0))));
IIntegrate(2528,Int(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power($p("§rfx"),p_DEFAULT))),b_DEFAULT)),n_DEFAULT),$p("§rgx")),x_Symbol),
    Condition(With(List(Set(u,ExpandIntegrand(Power(Plus(a,Times(b,Log(Times(c,Power($s("§rfx"),p))))),n),$s("§rgx"),x))),Condition(Int(u,x),SumQ(u))),And(FreeQ(List(a,b,c,p),x),RationalFunctionQ($s("§rfx"),x),RationalFunctionQ($s("§rgx"),x),IGtQ(n,C0))));
IIntegrate(2529,Int(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power($p("§rfx"),p_DEFAULT))),b_DEFAULT)),n_DEFAULT),$p("§rgx")),x_Symbol),
    Condition(With(List(Set(u,ExpandIntegrand(Times($s("§rgx"),Power(Plus(a,Times(b,Log(Times(c,Power($s("§rfx"),p))))),n)),x))),Condition(Int(u,x),SumQ(u))),And(FreeQ(List(a,b,c,p),x),RationalFunctionQ($s("§rfx"),x),RationalFunctionQ($s("§rgx"),x),IGtQ(n,C0))));
IIntegrate(2530,Int(Times(Plus(a_DEFAULT,Times(Log(u_),b_DEFAULT)),$p("§rfx")),x_Symbol),
    Condition(With(List(Set($s("lst"),SubstForFractionalPowerOfLinear(Times($s("§rfx"),Plus(a,Times(b,Log(u)))),x))),Condition(Dist(Times(Part($s("lst"),C2),Part($s("lst"),C4)),Subst(Int(Part($s("lst"),C1),x),x,Power(Part($s("lst"),C3),Power(Part($s("lst"),C2),CN1))),x),Not(FalseQ($s("lst"))))),And(FreeQ(List(a,b),x),RationalFunctionQ($s("§rfx"),x))));
IIntegrate(2531,Int(Times(Log(Plus(C1,Times(e_DEFAULT,Power(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),n_DEFAULT)))),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(Power(Plus(f,Times(g,x)),m),PolyLog(C2,Times(CN1,e,Power(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),n))),Power(Times(b,c,n,Log(FSymbol)),CN1)),x)),Dist(Times(g,m,Power(Times(b,c,n,Log(FSymbol)),CN1)),Int(Times(Power(Plus(f,Times(g,x)),Subtract(m,C1)),PolyLog(C2,Times(CN1,e,Power(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),n)))),x),x)),And(FreeQ(List(FSymbol,a,b,c,e,f,g,n),x),GtQ(m,C0))));
IIntegrate(2532,Int(Times(Log(Plus(d_,Times(e_DEFAULT,Power(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),n_DEFAULT)))),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Plus(Simp(Times(Power(Plus(f,Times(g,x)),Plus(m,C1)),Log(Plus(d,Times(e,Power(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),n)))),Power(Times(g,Plus(m,C1)),CN1)),x),Int(Times(Power(Plus(f,Times(g,x)),m),Log(Plus(C1,Times(e,Power(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),n),Power(d,CN1))))),x),Negate(Simp(Times(Power(Plus(f,Times(g,x)),Plus(m,C1)),Log(Plus(C1,Times(e,Power(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),n),Power(d,CN1)))),Power(Times(g,Plus(m,C1)),CN1)),x))),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,n),x),GtQ(m,C0),NeQ(d,C1))));
IIntegrate(2533,Int(Log(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqrt(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))))))),x_Symbol),
    Condition(Plus(Simp(Times(x,Log(Plus(d,Times(e,x),Times(f,Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))))))),x),Dist(Times(C1D2,Sqr(f),Subtract(Sqr(b),Times(C4,a,c))),Int(Times(x,Power(Subtract(Times(Subtract(Times(C2,d,e),Times(b,Sqr(f))),Plus(a,Times(b,x),Times(c,Sqr(x)))),Times(f,Plus(Times(b,d),Times(CN1,C2,a,e),Times(Subtract(Times(C2,c,d),Times(b,e)),x)),Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ(Subtract(Sqr(e),Times(c,Sqr(f))),C0))));
IIntegrate(2534,Int(Log(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqrt(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(x_))))))),x_Symbol),
    Condition(Subtract(Simp(Times(x,Log(Plus(d,Times(e,x),Times(f,Sqrt(Plus(a,Times(c,Sqr(x)))))))),x),Dist(Times(a,c,Sqr(f)),Int(Times(x,Power(Plus(Times(d,e,Plus(a,Times(c,Sqr(x)))),Times(f,Subtract(Times(a,e),Times(c,d,x)),Sqrt(Plus(a,Times(c,Sqr(x)))))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,f),x),EqQ(Subtract(Sqr(e),Times(c,Sqr(f))),C0))));
IIntegrate(2535,Int(Times(Log(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqrt(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))))))),Power(Times(g_DEFAULT,x_),m_DEFAULT)),x_Symbol),
    Condition(Plus(Simp(Times(Power(Times(g,x),Plus(m,C1)),Log(Plus(d,Times(e,x),Times(f,Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x))))))),Power(Times(g,Plus(m,C1)),CN1)),x),Dist(Times(Sqr(f),Subtract(Sqr(b),Times(C4,a,c)),Power(Times(C2,g,Plus(m,C1)),CN1)),Int(Times(Power(Times(g,x),Plus(m,C1)),Power(Subtract(Times(Subtract(Times(C2,d,e),Times(b,Sqr(f))),Plus(a,Times(b,x),Times(c,Sqr(x)))),Times(f,Plus(Times(b,d),Times(CN1,C2,a,e),Times(Subtract(Times(C2,c,d),Times(b,e)),x)),Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,f,g,m),x),EqQ(Subtract(Sqr(e),Times(c,Sqr(f))),C0),NeQ(m,CN1),IntegerQ(Times(C2,m)))));
IIntegrate(2536,Int(Times(Log(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqrt(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(x_))))))),Power(Times(g_DEFAULT,x_),m_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Times(g,x),Plus(m,C1)),Log(Plus(d,Times(e,x),Times(f,Sqrt(Plus(a,Times(c,Sqr(x))))))),Power(Times(g,Plus(m,C1)),CN1)),x),Dist(Times(a,c,Sqr(f),Power(Times(g,Plus(m,C1)),CN1)),Int(Times(Power(Times(g,x),Plus(m,C1)),Power(Plus(Times(d,e,Plus(a,Times(c,Sqr(x)))),Times(f,Subtract(Times(a,e),Times(c,d,x)),Sqrt(Plus(a,Times(c,Sqr(x)))))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,f,g,m),x),EqQ(Subtract(Sqr(e),Times(c,Sqr(f))),C0),NeQ(m,CN1),IntegerQ(Times(C2,m)))));
IIntegrate(2537,Int(Times(Log(Plus(d_DEFAULT,Times(f_DEFAULT,Sqrt(u_)),Times(e_DEFAULT,x_))),v_DEFAULT),x_Symbol),
    Condition(Int(Times(v,Log(Plus(d,Times(e,x),Times(f,Sqrt(ExpandToSum(u,x)))))),x),And(FreeQ(List(d,e,f),x),QuadraticQ(u,x),Not(QuadraticMatchQ(u,x)),Or(EqQ(v,C1),MatchQ(v,Condition(Power(Times(g_DEFAULT,x),m_DEFAULT),FreeQ(List(g,m),x)))))));
IIntegrate(2538,Int(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),r_DEFAULT),Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Times(Log(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q)))),Power(Times(b,n,q),CN1)),x),Dist(Times(a,m,Power(Times(b,n,q),CN1)),Int(Times(Power(x,Subtract(m,C1)),Power(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q))),CN1)),x),x)),And(FreeQ(List(a,b,c,m,n,q,r),x),EqQ(r,Subtract(q,C1)))));
IIntegrate(2539,Int(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),r_DEFAULT),Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),p_DEFAULT)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Log(Times(c,Power(x,n))),r),Power(x,CN1)),Power(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q))),p),x),x),And(FreeQ(List(a,b,c,m,n,p,q,r),x),EqQ(r,Subtract(q,C1)),IGtQ(p,C0))));
IIntegrate(2540,Int(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),r_DEFAULT),Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),p_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q))),Plus(p,C1)),Power(Times(b,n,q,Plus(p,C1)),CN1)),x),Dist(Times(a,m,Power(Times(b,n,q),CN1)),Int(Times(Power(x,Subtract(m,C1)),Power(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q))),p)),x),x)),And(FreeQ(List(a,b,c,m,n,p,q,r),x),EqQ(r,Subtract(q,C1)),NeQ(p,CN1))));
IIntegrate(2541,Int(Times(Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),CN1),Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),r_DEFAULT),e_DEFAULT),Times(d_DEFAULT,Power(x_,m_DEFAULT)))),x_Symbol),
    Condition(Simp(Times(e,Log(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q)))),Power(Times(b,n,q),CN1)),x),And(FreeQ(List(a,b,c,d,e,m,n,q,r),x),EqQ(r,Subtract(q,C1)),EqQ(Subtract(Times(a,e,m),Times(b,d,n,q)),C0))));
IIntegrate(2542,Int(Times(Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),CN1),Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),r_DEFAULT),e_DEFAULT),u_,Times(d_DEFAULT,Power(x_,m_DEFAULT)))),x_Symbol),
    Condition(Plus(Simp(Times(e,Log(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q)))),Power(Times(b,n,q),CN1)),x),Int(Times(u,Power(Times(x,Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q)))),CN1)),x)),And(FreeQ(List(a,b,c,d,e,m,n,q,r),x),EqQ(r,Subtract(q,C1)),EqQ(Subtract(Times(a,e,m),Times(b,d,n,q)),C0))));
IIntegrate(2543,Int(Times(Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),CN1),Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),r_DEFAULT),e_DEFAULT),Times(d_DEFAULT,Power(x_,m_DEFAULT)))),x_Symbol),
    Condition(Subtract(Simp(Times(e,Log(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q)))),Power(Times(b,n,q),CN1)),x),Dist(Times(Subtract(Times(a,e,m),Times(b,d,n,q)),Power(Times(b,n,q),CN1)),Int(Times(Power(x,Subtract(m,C1)),Power(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,m,n,q,r),x),EqQ(r,Subtract(q,C1)),NeQ(Subtract(Times(a,e,m),Times(b,d,n,q)),C0))));
IIntegrate(2544,Int(Times(Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),p_DEFAULT),Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),r_DEFAULT),e_DEFAULT),Times(d_DEFAULT,Power(x_,m_DEFAULT)))),x_Symbol),
    Condition(Simp(Times(e,Power(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q))),Plus(p,C1)),Power(Times(b,n,q,Plus(p,C1)),CN1)),x),And(FreeQ(List(a,b,c,d,e,m,n,p,q,r),x),EqQ(r,Subtract(q,C1)),NeQ(p,CN1),EqQ(Subtract(Times(a,e,m),Times(b,d,n,q)),C0))));
IIntegrate(2545,Int(Times(Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),p_DEFAULT),Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),r_DEFAULT),e_DEFAULT),Times(d_DEFAULT,Power(x_,m_DEFAULT)))),x_Symbol),
    Condition(Subtract(Simp(Times(e,Power(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q))),Plus(p,C1)),Power(Times(b,n,q,Plus(p,C1)),CN1)),x),Dist(Times(Subtract(Times(a,e,m),Times(b,d,n,q)),Power(Times(b,n,q),CN1)),Int(Times(Power(x,Subtract(m,C1)),Power(Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q))),p)),x),x)),And(FreeQ(List(a,b,c,d,e,m,n,p,q,r),x),EqQ(r,Subtract(q,C1)),NeQ(p,CN1),NeQ(Subtract(Times(a,e,m),Times(b,d,n,q)),C0))));
IIntegrate(2546,Int(Times(Power(x_,CN1),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,Power(x_,m_DEFAULT))),CN2),Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_DEFAULT),f_DEFAULT),Times(d_DEFAULT,Power(x_,m_DEFAULT)),Times(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),e_DEFAULT,Power(x_,m_DEFAULT)))),x_Symbol),
    Condition(Simp(Times(d,Log(Times(c,Power(x,n))),Power(Times(a,n,Plus(Times(a,Power(x,m)),Times(b,Power(Log(Times(c,Power(x,n))),q)))),CN1)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,q),x),EqQ(Plus(Times(e,n),Times(d,m)),C0),EqQ(Plus(Times(a,f),Times(b,d,Subtract(q,C1))),C0))));
IIntegrate(2547,Int(Times(Plus(Times(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),e_DEFAULT),d_),Power(Plus(Times(Power(Log(Times(c_DEFAULT,Power(x_,n_DEFAULT))),q_),b_DEFAULT),Times(a_DEFAULT,x_)),CN2)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(e,Log(Times(c,Power(x,n))),Power(Times(a,Plus(Times(a,x),Times(b,Power(Log(Times(c,Power(x,n))),q)))),CN1)),x)),Dist(Times(Plus(d,Times(e,n)),Power(a,CN1)),Int(Power(Times(x,Plus(Times(a,x),Times(b,Power(Log(Times(c,Power(x,n))),q)))),CN1),x),x)),And(FreeQ(List(a,b,c,d,e,n,q),x),EqQ(Plus(d,Times(e,n,q)),C0))));
IIntegrate(2548,Int(Log(u_),x_Symbol),
    Condition(Subtract(Simp(Times(x,Log(u)),x),Int(SimplifyIntegrand(Times(x,D(u,x),Power(u,CN1)),x),x)),InverseFunctionFreeQ(u,x)));
IIntegrate(2549,Int(Log(u_),x_Symbol),
    Condition(Subtract(Simp(Times(x,Log(u)),x),Int(SimplifyIntegrand(Times(x,Simplify(Times(D(u,x),Power(u,CN1)))),x),x)),ProductQ(u)));
IIntegrate(2550,Int(Times(Log(u_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Subtract(Simp(Times(Log(Plus(a,Times(b,x))),Log(u),Power(b,CN1)),x),Dist(Power(b,CN1),Int(SimplifyIntegrand(Times(Log(Plus(a,Times(b,x))),D(u,x),Power(u,CN1)),x),x),x)),And(FreeQ(List(a,b),x),RationalFunctionQ(Times(D(u,x),Power(u,CN1)),x),Or(NeQ(a,C0),Not(And(BinomialQ(u,x),EqQ(Sqr(BinomialDegree(u,x)),C1)))))));
  }
}
}
