package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules46 { 
  public static IAST RULES = List( 
IIntegrate(921,Integrate(Times(Sqrt(Plus(a_,Times(b_DEFAULT,Power(x_,C4)))),Power(Plus(c_,Times(d_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,a,b),C4))),Plus(Simp(Times(a,Power(Times(C2,c,q),CN1),ArcTan(Times(q,x,Plus(a,Times(Sqr(q),Sqr(x))),Power(Times(a,Sqrt(Plus(a,Times(b,Power(x,C4))))),CN1)))),x),Simp(Times(a,Power(Times(C2,c,q),CN1),ArcTanh(Times(q,x,Subtract(a,Times(Sqr(q),Sqr(x))),Power(Times(a,Sqrt(Plus(a,Times(b,Power(x,C4))))),CN1)))),x))),And(FreeQ(List(a,b,c,d),x),EqQ(Plus(Times(b,c),Times(a,d)),C0),NegQ(Times(a,b))))),
IIntegrate(922,Integrate(Times(Sqrt(Plus(a_,Times(b_DEFAULT,Power(x_,C4)))),Power(Plus(c_,Times(d_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(b,Power(d,CN1)),Integrate(Power(Plus(a,Times(b,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(Subtract(Times(b,c),Times(a,d)),Power(d,CN1)),Integrate(Power(Times(Sqrt(Plus(a,Times(b,Power(x,C4)))),Plus(c,Times(d,Power(x,C4)))),CN1),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(923,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,C4))),C1D4),Power(Plus(c_,Times(d_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Simp(Star(Times(Sqrt(Plus(a,Times(b,Power(x,C4)))),Sqrt(Times(a,Power(Plus(a,Times(b,Power(x,C4))),CN1)))),Subst(Integrate(Power(Times(Sqrt(Subtract(C1,Times(b,Power(x,C4)))),Subtract(c,Times(Subtract(Times(b,c),Times(a,d)),Power(x,C4)))),CN1),x),x,Times(x,Power(Plus(a,Times(b,Power(x,C4))),CN1D4)))),x),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(924,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,C4))),QQ(5L,4L)),Power(Plus(c_,Times(d_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(b,Power(d,CN1)),Integrate(Power(Plus(a,Times(b,Power(x,C4))),C1D4),x)),x),Simp(Star(Times(Subtract(Times(b,c),Times(a,d)),Power(d,CN1)),Integrate(Times(Power(Plus(a,Times(b,Power(x,C4))),C1D4),Power(Plus(c,Times(d,Power(x,C4))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(925,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,C4))),CN1D2),Power(Plus(c_,Times(d_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Power(Times(C2,c),CN1),Integrate(Power(Times(Sqrt(Plus(a,Times(b,Power(x,C4)))),Subtract(C1,Times(Rt(Times(CN1,d,Power(c,CN1)),C2),Sqr(x)))),CN1),x)),x),Simp(Star(Power(Times(C2,c),CN1),Integrate(Power(Times(Sqrt(Plus(a,Times(b,Power(x,C4)))),Plus(C1,Times(Rt(Times(CN1,d,Power(c,CN1)),C2),Sqr(x)))),CN1),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(926,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,C4))),QQ(-3L,4L)),Power(Plus(c_,Times(d_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Power(Plus(a,Times(b,Power(x,C4))),QQ(-3L,4L)),x)),x),Simp(Star(Times(d,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Times(Power(Plus(a,Times(b,Power(x,C4))),C1D4),Power(Plus(c,Times(d,Power(x,C4))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(927,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,C3))),C1D3),Power(Plus(c_,Times(d_DEFAULT,Power(x_,C3))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(b,Power(a,CN1)),C3))),Simp(Star(Times(C9,a,Power(Times(c,q),CN1)),Subst(Integrate(Times(x,Power(Times(Subtract(C4,Times(a,Power(x,C3))),Plus(C1,Times(C2,a,Power(x,C3)))),CN1)),x),x,Times(Plus(C1,Times(q,x)),Power(Plus(a,Times(b,Power(x,C3))),CN1D3)))),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(Times(b,c),Times(a,d)),C0)))),
IIntegrate(928,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,C3))),QQ(-2L,3L)),Power(Plus(c_,Times(d_DEFAULT,Power(x_,C3))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Power(Plus(a,Times(b,Power(x,C3))),QQ(-2L,3L)),x)),x),Simp(Star(Times(d,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Times(Power(Plus(a,Times(b,Power(x,C3))),C1D3),Power(Plus(c,Times(d,Power(x,C3))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(Times(b,c),Times(a,d)),C0)))),
IIntegrate(929,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,x,Power(Plus(a,Times(b,Power(x,n))),Plus(p,C1)),Power(Plus(c,Times(d,Power(x,n))),q),Power(Times(a,n,Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(a,n,Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Power(x,n))),Plus(p,C1)),Power(Plus(c,Times(d,Power(x,n))),Subtract(q,C1)),Simp(Plus(Times(c,Plus(Times(n,Plus(p,C1)),C1)),Times(d,Plus(Times(n,Plus(p,q,C1)),C1),Power(x,n))),x)),x)),x)),And(FreeQ(List(a,b,c,d,n),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(p,CN1),LtQ(C0,q,C1),IntBinomialQ(a,b,c,d,n,p,q,x)))),
IIntegrate(930,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Subtract(Times(a,d),Times(c,b)),x,Power(Plus(a,Times(b,Power(x,n))),Plus(p,C1)),Power(Plus(c,Times(d,Power(x,n))),Subtract(q,C1)),Power(Times(a,b,n,Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(a,b,n,Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Power(x,n))),Plus(p,C1)),Power(Plus(c,Times(d,Power(x,n))),Subtract(q,C2)),Simp(Plus(Times(c,Subtract(Times(a,d),Times(c,b,Plus(Times(n,Plus(p,C1)),C1)))),Times(d,Subtract(Times(a,d,Plus(Times(n,Subtract(q,C1)),C1)),Times(b,c,Plus(Times(n,Plus(p,q)),C1))),Power(x,n))),x)),x)),x)),And(FreeQ(List(a,b,c,d,n),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(p,CN1),GtQ(q,C1),IntBinomialQ(a,b,c,d,n,p,q,x)))),
IIntegrate(931,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,x,Power(Plus(a,Times(b,Power(x,n))),Plus(p,C1)),Power(Plus(c,Times(d,Power(x,n))),Plus(q,C1)),Power(Times(a,n,Plus(p,C1),Subtract(Times(b,c),Times(a,d))),CN1)),x),Simp(Star(Power(Times(a,n,Plus(p,C1),Subtract(Times(b,c),Times(a,d))),CN1),Integrate(Times(Power(Plus(a,Times(b,Power(x,n))),Plus(p,C1)),Power(Plus(c,Times(d,Power(x,n))),q),Simp(Plus(Times(b,c),Times(n,Plus(p,C1),Subtract(Times(b,c),Times(a,d))),Times(d,b,Plus(Times(n,Plus(p,q,C2)),C1),Power(x,n))),x)),x)),x)),And(FreeQ(List(a,b,c,d,n,q),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(p,CN1),Not(And(Not(IntegerQ(p)),IntegerQ(q),LtQ(q,CN1))),IntBinomialQ(a,b,c,d,n,p,q,x)))),
IIntegrate(932,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(a,Times(b,Power(x,n))),p),Power(Plus(c,Times(d,Power(x,n))),q)),x),x),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),IGtQ(n,C0),IntegersQ(p,q),GtQ(Plus(p,q),C0)))),
IIntegrate(933,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(d,x,Power(Plus(a,Times(b,Power(x,n))),Plus(p,C1)),Power(Plus(c,Times(d,Power(x,n))),Subtract(q,C1)),Power(Times(b,Plus(Times(n,Plus(p,q)),C1)),CN1)),x),Simp(Star(Power(Times(b,Plus(Times(n,Plus(p,q)),C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Power(x,n))),p),Power(Plus(c,Times(d,Power(x,n))),Subtract(q,C2)),Simp(Plus(Times(c,Subtract(Times(b,c,Plus(Times(n,Plus(p,q)),C1)),Times(a,d))),Times(d,Subtract(Times(b,c,Plus(Times(n,Subtract(Plus(p,Times(C2,q)),C1)),C1)),Times(a,d,Plus(Times(n,Subtract(q,C1)),C1))),Power(x,n))),x)),x)),x)),And(FreeQ(List(a,b,c,d,n,p),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),GtQ(q,C1),NeQ(Plus(Times(n,Plus(p,q)),C1),C0),Not(IGtQ(p,C1)),IntBinomialQ(a,b,c,d,n,p,q,x)))),
IIntegrate(934,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(x,Power(Plus(a,Times(b,Power(x,n))),p),Power(Plus(c,Times(d,Power(x,n))),q),Power(Plus(Times(n,Plus(p,q)),C1),CN1)),x),Simp(Star(Times(n,Power(Plus(Times(n,Plus(p,q)),C1),CN1)),Integrate(Times(Power(Plus(a,Times(b,Power(x,n))),Subtract(p,C1)),Power(Plus(c,Times(d,Power(x,n))),Subtract(q,C1)),Simp(Plus(Times(a,c,Plus(p,q)),Times(Plus(Times(q,Subtract(Times(b,c),Times(a,d))),Times(a,d,Plus(p,q))),Power(x,n))),x)),x)),x)),And(FreeQ(List(a,b,c,d,n),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),GtQ(q,C0),GtQ(p,C0),IntBinomialQ(a,b,c,d,n,p,q,x)))),
IIntegrate(935,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_DEFAULT),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(a,Times(b,Power(x,n))),p),Power(Plus(c,Times(d,Power(x,n))),q)),x),x),And(FreeQ(List(a,b,c,d,n,q),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),IGtQ(p,C0)))),
IIntegrate(936,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Simp(Times(Power(a,p),Power(c,q),x,AppellF1(Power(n,CN1),Negate(p),Negate(q),Plus(C1,Power(n,CN1)),Times(CN1,b,Power(x,n),Power(a,CN1)),Times(CN1,d,Power(x,n),Power(c,CN1)))),x),And(FreeQ(List(a,b,c,d,n,p,q),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(n,CN1),Or(IntegerQ(p),GtQ(a,C0)),Or(IntegerQ(q),GtQ(c,C0))))),
IIntegrate(937,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Simp(Star(Times(Power(a,IntPart(p)),Power(Plus(a,Times(b,Power(x,n))),FracPart(p)),Power(Power(Plus(C1,Times(b,Power(x,n),Power(a,CN1))),FracPart(p)),CN1)),Integrate(Times(Power(Plus(C1,Times(b,Power(x,n),Power(a,CN1))),p),Power(Plus(c,Times(d,Power(x,n))),q)),x)),x),And(FreeQ(List(a,b,c,d,n,p,q),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(n,CN1),Not(Or(IntegerQ(p),GtQ(a,C0)))))),
IIntegrate(938,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power(u_,n_))),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,Power(u_,n_))),q_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(Coefficient(u,x,C1),CN1),Subst(Integrate(Times(Power(Plus(a,Times(b,Power(x,n))),p),Power(Plus(c,Times(d,Power(x,n))),q)),x),x,u)),x),And(FreeQ(List(a,b,c,d,n,p,q),x),LinearQ(u,x),NeQ(u,x)))),
IIntegrate(939,Integrate(Times(Power(u_,p_DEFAULT),Power(v_,q_DEFAULT)),x_Symbol),
    Condition(Integrate(Times(Power(NormalizePseudoBinomial(u,x),p),Power(NormalizePseudoBinomial(v,x),q)),x),And(FreeQ(list(p,q),x),PseudoBinomialPairQ(u,v,x)))),
IIntegrate(940,Integrate(Times(Power(u_,p_DEFAULT),Power(v_,q_DEFAULT),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Integrate(Times(Power(NormalizePseudoBinomial(Times(Power(x,Times(m,Power(p,CN1))),u),x),p),Power(NormalizePseudoBinomial(v,x),q)),x),And(FreeQ(list(p,q),x),IntegersQ(p,Times(m,Power(p,CN1))),PseudoBinomialPairQ(Times(Power(x,Times(m,Power(p,CN1))),u),v,x))))
  );
}
