package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules232 { 
  public static IAST RULES = List( 
IIntegrate(4641,Integrate(Power(Plus(a_DEFAULT,Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),b_DEFAULT),Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)),c_DEFAULT)),p_DEFAULT),x_Symbol),
    Condition(Simp(Star(Power(Times(Power(C4,p),Power(c,p)),CN1),Integrate(Power(Plus(b,Times(C2,c,Power(Csc(Plus(d,Times(e,x))),n))),Times(C2,p)),x)),x),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IntegerQ(p)))),
IIntegrate(4642,Integrate(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),p_),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(a,Times(b,Power(Sec(Plus(d,Times(e,x))),n)),Times(c,Power(Sec(Plus(d,Times(e,x))),Times(C2,n)))),p),Power(Power(Plus(b,Times(C2,c,Power(Sec(Plus(d,Times(e,x))),n))),Times(C2,p)),CN1)),Integrate(Times(u,Power(Plus(b,Times(C2,c,Power(Sec(Plus(d,Times(e,x))),n))),Times(C2,p))),x)),x),And(FreeQ(List(a,b,c,d,e,n,p),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(p))))),
IIntegrate(4643,Integrate(Power(Plus(a_DEFAULT,Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),b_DEFAULT),Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)),c_DEFAULT)),p_),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(a,Times(b,Power(Csc(Plus(d,Times(e,x))),n)),Times(c,Power(Csc(Plus(d,Times(e,x))),Times(C2,n)))),p),Power(Power(Plus(b,Times(C2,c,Power(Csc(Plus(d,Times(e,x))),n))),Times(C2,p)),CN1)),Integrate(Times(u,Power(Plus(b,Times(C2,c,Power(Csc(Plus(d,Times(e,x))),n))),Times(C2,p))),x)),x),And(FreeQ(List(a,b,c,d,e,n,p),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(p))))),
IIntegrate(4644,Integrate(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),CN1),x_Symbol),
    Condition(Module(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Simp(Star(Times(C2,c,Power(q,CN1)),Integrate(Power(Plus(b,Negate(q),Times(C2,c,Power(Sec(Plus(d,Times(e,x))),n))),CN1),x)),x),Simp(Star(Times(C2,c,Power(q,CN1)),Integrate(Power(Plus(b,q,Times(C2,c,Power(Sec(Plus(d,Times(e,x))),n))),CN1),x)),x))),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(4645,Integrate(Power(Plus(a_DEFAULT,Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),b_DEFAULT),Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)),c_DEFAULT)),CN1),x_Symbol),
    Condition(Module(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Simp(Star(Times(C2,c,Power(q,CN1)),Integrate(Power(Plus(b,Negate(q),Times(C2,c,Power(Csc(Plus(d,Times(e,x))),n))),CN1),x)),x),Simp(Star(Times(C2,c,Power(q,CN1)),Integrate(Power(Plus(b,q,Times(C2,c,Power(Csc(Plus(d,Times(e,x))),n))),CN1),x)),x))),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(4646,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2")))),p_DEFAULT),Power($($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(Module(list(Set(f,FreeFactors(Cos(Plus(d,Times(e,x))),x))),Simp(Star(Times(CN1,f,Power(e,CN1)),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr(f),Sqr(x))),Times(C1D2,Subtract(m,C1))),Power(Plus(b,Times(a,Power(Times(f,x),n))),p),Power(Power(Times(f,x),Times(n,p)),CN1)),x),x,Times(Cos(Plus(d,Times(e,x))),Power(f,CN1)))),x)),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),IntegerQ(Times(C1D2,Subtract(m,C1))),IntegersQ(n,p)))),
IIntegrate(4647,Integrate(Times(Power($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_DEFAULT,Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),b_DEFAULT),Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2")),c_DEFAULT)),p_DEFAULT)),x_Symbol),
    Condition(Module(list(Set(f,FreeFactors(Sin(Plus(d,Times(e,x))),x))),Simp(Star(Times(f,Power(e,CN1)),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr(f),Sqr(x))),Times(C1D2,Subtract(m,C1))),Power(Plus(b,Times(a,Power(Times(f,x),n))),p),Power(Power(Times(f,x),Times(n,p)),CN1)),x),x,Times(Sin(Plus(d,Times(e,x))),Power(f,CN1)))),x)),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),IntegerQ(Times(C1D2,Subtract(m,C1))),IntegersQ(n,p)))),
IIntegrate(4648,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2")))),p_DEFAULT),Power($($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_)),x_Symbol),
    Condition(Module(list(Set(f,FreeFactors(Tan(Plus(d,Times(e,x))),x))),Simp(Star(Times(Power(f,Plus(m,C1)),Power(e,CN1)),Subst(Integrate(Times(Power(x,m),Power(ExpandToSum(Plus(a,Times(b,Power(Plus(C1,Times(Sqr(f),Sqr(x))),Times(C1D2,n))),Times(c,Power(Plus(C1,Times(Sqr(f),Sqr(x))),n))),x),p),Power(Power(Plus(C1,Times(Sqr(f),Sqr(x))),Plus(Times(C1D2,m),C1)),CN1)),x),x,Times(Tan(Plus(d,Times(e,x))),Power(f,CN1)))),x)),And(FreeQ(List(a,b,c,d,e,p),x),EqQ($s("n2"),Times(C2,n)),IntegerQ(Times(C1D2,m)),IntegerQ(Times(C1D2,n))))),
IIntegrate(4649,Integrate(Times(Power($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_),Power(Plus(a_DEFAULT,Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_),b_DEFAULT),Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2")),c_DEFAULT)),p_DEFAULT)),x_Symbol),
    Condition(Module(list(Set(f,FreeFactors(Cot(Plus(d,Times(e,x))),x))),Simp(Star(Times(CN1,Power(f,Plus(m,C1)),Power(e,CN1)),Subst(Integrate(Times(Power(x,m),Power(ExpandToSum(Plus(a,Times(b,Power(Plus(C1,Times(Sqr(f),Sqr(x))),Times(C1D2,n))),Times(c,Power(Plus(C1,Times(Sqr(f),Sqr(x))),n))),x),p),Power(Power(Plus(C1,Times(Sqr(f),Sqr(x))),Plus(Times(C1D2,m),C1)),CN1)),x),x,Times(Cot(Plus(d,Times(e,x))),Power(f,CN1)))),x)),And(FreeQ(List(a,b,c,d,e,p),x),EqQ($s("n2"),Times(C2,n)),IntegerQ(Times(C1D2,m)),IntegerQ(Times(C1D2,n))))),
IIntegrate(4650,Integrate(Times(Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),p_)),x_Symbol),
    Condition(Simp(Star(Power(Times(Power(C4,p),Power(c,p)),CN1),Integrate(Times(Power(Sec(Plus(d,Times(e,x))),m),Power(Plus(b,Times(C2,c,Power(Sec(Plus(d,Times(e,x))),n))),Times(C2,p))),x)),x),And(FreeQ(List(a,b,c,d,e,m,n),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IntegerQ(p)))),
IIntegrate(4651,Integrate(Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_DEFAULT,Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),b_DEFAULT),Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)),c_DEFAULT)),p_)),x_Symbol),
    Condition(Simp(Star(Power(Times(Power(C4,p),Power(c,p)),CN1),Integrate(Times(Power(Csc(Plus(d,Times(e,x))),m),Power(Plus(b,Times(C2,c,Power(Csc(Plus(d,Times(e,x))),n))),Times(C2,p))),x)),x),And(FreeQ(List(a,b,c,d,e,m,n),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IntegerQ(p)))),
IIntegrate(4652,Integrate(Times(Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(a,Times(b,Power(Sec(Plus(d,Times(e,x))),n)),Times(c,Power(Sec(Plus(d,Times(e,x))),Times(C2,n)))),p),Power(Power(Plus(b,Times(C2,c,Power(Sec(Plus(d,Times(e,x))),n))),Times(C2,p)),CN1)),Integrate(Times(Power(Sec(Plus(d,Times(e,x))),m),Power(Plus(b,Times(C2,c,Power(Sec(Plus(d,Times(e,x))),n))),Times(C2,p))),x)),x),And(FreeQ(List(a,b,c,d,e,m,n,p),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(p))))),
IIntegrate(4653,Integrate(Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_DEFAULT,Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),b_DEFAULT),Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)),c_DEFAULT)),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(a,Times(b,Power(Csc(Plus(d,Times(e,x))),n)),Times(c,Power(Csc(Plus(d,Times(e,x))),Times(C2,n)))),p),Power(Power(Plus(b,Times(C2,c,Power(Csc(Plus(d,Times(e,x))),n))),Times(C2,p)),CN1)),Integrate(Times(Power(Csc(Plus(d,Times(e,x))),m),Power(Plus(b,Times(C2,c,Power(Csc(Plus(d,Times(e,x))),n))),Times(C2,p))),x)),x),And(FreeQ(List(a,b,c,d,e,m,n,p),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(p))))),
IIntegrate(4654,Integrate(Times(Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),p_)),x_Symbol),
    Condition(Integrate(ExpandTrig(Times(Power($($s("§sec"),Plus(d,Times(e,x))),m),Power(Plus(a,Times(b,Power($($s("§sec"),Plus(d,Times(e,x))),n)),Times(c,Power($($s("§sec"),Plus(d,Times(e,x))),Times(C2,n)))),p)),x),x),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),IntegersQ(m,n,p)))),
IIntegrate(4655,Integrate(Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_DEFAULT,Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),b_DEFAULT),Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)),c_DEFAULT)),p_)),x_Symbol),
    Condition(Integrate(ExpandTrig(Times(Power($($s("§csc"),Plus(d,Times(e,x))),m),Power(Plus(a,Times(b,Power($($s("§csc"),Plus(d,Times(e,x))),n)),Times(c,Power($($s("§csc"),Plus(d,Times(e,x))),Times(C2,n)))),p)),x),x),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),IntegersQ(m,n,p)))),
IIntegrate(4656,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),p_DEFAULT),Power($($s("§tan"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(Module(list(Set(f,FreeFactors(Cos(Plus(d,Times(e,x))),x))),Simp(Star(Negate(Power(Times(e,Power(f,Subtract(Plus(m,Times(n,p)),C1))),CN1)),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr(f),Sqr(x))),Times(C1D2,Subtract(m,C1))),Power(Plus(c,Times(b,Power(Times(f,x),n)),Times(c,Power(Times(f,x),Times(C2,n)))),p),Power(Power(x,Plus(m,Times(C2,n,p))),CN1)),x),x,Times(Cos(Plus(d,Times(e,x))),Power(f,CN1)))),x)),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),IntegerQ(Times(C1D2,Subtract(m,C1))),IntegerQ(n),IntegerQ(p)))),
IIntegrate(4657,Integrate(Times(Power($($s("§cot"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),b_DEFAULT),a_,Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),p_DEFAULT)),x_Symbol),
    Condition(Module(list(Set(f,FreeFactors(Sin(Plus(d,Times(e,x))),x))),Simp(Star(Power(Times(e,Power(f,Subtract(Plus(m,Times(n,p)),C1))),CN1),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr(f),Sqr(x))),Times(C1D2,Subtract(m,C1))),Power(Plus(c,Times(b,Power(Times(f,x),n)),Times(c,Power(Times(f,x),Times(C2,n)))),p),Power(Power(x,Plus(m,Times(C2,n,p))),CN1)),x),x,Times(Sin(Plus(d,Times(e,x))),Power(f,CN1)))),x)),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),IntegerQ(Times(C1D2,Subtract(m,C1))),IntegerQ(n),IntegerQ(p)))),
IIntegrate(4658,Integrate(Times(Power(Plus(a_,Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true))),Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_))),p_DEFAULT),Power($($s("§tan"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(Module(list(Set(f,FreeFactors(Tan(Plus(d,Times(e,x))),x))),Simp(Star(Times(Power(f,Plus(m,C1)),Power(e,CN1)),Subst(Integrate(Times(Power(x,m),Power(ExpandToSum(Plus(a,Times(b,Power(Plus(C1,Times(Sqr(f),Sqr(x))),Times(C1D2,n))),Times(c,Power(Plus(C1,Times(Sqr(f),Sqr(x))),n))),x),p),Power(Plus(C1,Times(Sqr(f),Sqr(x))),CN1)),x),x,Times(Tan(Plus(d,Times(e,x))),Power(f,CN1)))),x)),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),IntegerQ(Times(C1D2,m)),IntegerQ(Times(C1D2,n))))),
IIntegrate(4659,Integrate(Times(Power($($s("§cot"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),m_DEFAULT),Power(Plus(Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_),b_DEFAULT),a_,Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),p_DEFAULT)),x_Symbol),
    Condition(Module(list(Set(f,FreeFactors(Cot(Plus(d,Times(e,x))),x))),Simp(Star(Times(CN1,Power(f,Plus(m,C1)),Power(e,CN1)),Subst(Integrate(Times(Power(x,m),Power(ExpandToSum(Plus(a,Times(b,Power(Plus(C1,Times(Sqr(f),Sqr(x))),Times(C1D2,n))),Times(c,Power(Plus(C1,Times(Sqr(f),Sqr(x))),n))),x),p),Power(Plus(C1,Times(Sqr(f),Sqr(x))),CN1)),x),x,Times(Cot(Plus(d,Times(e,x))),Power(f,CN1)))),x)),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),IntegerQ(Times(C1D2,m)),IntegerQ(Times(C1D2,n))))),
IIntegrate(4660,Integrate(Times(Plus(A_,Times(B_DEFAULT,$($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),Power(Plus(a_,Times(b_DEFAULT,$($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))),Times(c_DEFAULT,Sqr($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))))),n_)),x_Symbol),
    Condition(Simp(Star(Power(Times(Power(C4,n),Power(c,n)),CN1),Integrate(Times(Plus(ASymbol,Times(BSymbol,Sec(Plus(d,Times(e,x))))),Power(Plus(b,Times(C2,c,Sec(Plus(d,Times(e,x))))),Times(C2,n))),x)),x),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IntegerQ(n))))
  );
}
