package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules67 { 
  public static IAST RULES = List( 
IIntegrate(1341,Integrate(Times(Plus(g_,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1D3),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CSqrt3,h,ArcTan(Subtract(C1DSqrt3,Times(Power(C2,QQ(2L,3L)),Power(Subtract(C1,Times(C3,h,x,Power(g,CN1))),QQ(2L,3L)),Power(Times(CSqrt3,Power(Plus(C1,Times(C3,h,x,Power(g,CN1))),C1D3)),CN1)))),Power(Times(Power(C2,QQ(2L,3L)),Power(a,C1D3),f),CN1)),x),Negate(Simp(Times(C3,h,Log(Plus(Power(Subtract(C1,Times(C3,h,x,Power(g,CN1))),QQ(2L,3L)),Times(Power(C2,C1D3),Power(Plus(C1,Times(C3,h,x,Power(g,CN1))),C1D3)))),Power(Times(Power(C2,QQ(5L,3L)),Power(a,C1D3),f),CN1)),x)),Simp(Times(h,Log(Plus(d,Times(f,Sqr(x)))),Power(Times(Power(C2,QQ(5L,3L)),Power(a,C1D3),f),CN1)),x)),And(FreeQ(List(a,c,d,f,g,h),x),EqQ(Plus(Times(c,d),Times(C3,a,f)),C0),EqQ(Plus(Times(c,Sqr(g)),Times(C9,a,Sqr(h))),C0),GtQ(a,C0)))),
IIntegrate(1342,Integrate(Times(Plus(g_,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1D3),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(C1,Times(c,Sqr(x),Power(a,CN1))),C1D3),Power(Plus(a,Times(c,Sqr(x))),CN1D3)),Integrate(Times(Plus(g,Times(h,x)),Power(Times(Power(Plus(C1,Times(c,Sqr(x),Power(a,CN1))),C1D3),Plus(d,Times(f,Sqr(x)))),CN1)),x)),x),And(FreeQ(List(a,c,d,f,g,h),x),EqQ(Plus(Times(c,d),Times(C3,a,f)),C0),EqQ(Plus(Times(c,Sqr(g)),Times(C9,a,Sqr(h))),C0),Not(GtQ(a,C0))))),
IIntegrate(1343,Integrate(Times(Plus(g_,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Star(g,Integrate(Times(Power(Plus(a,Times(c,Sqr(x))),p),Power(Plus(d,Times(f,Sqr(x))),q)),x)),x),Simp(Star(h,Integrate(Times(x,Power(Plus(a,Times(c,Sqr(x))),p),Power(Plus(d,Times(f,Sqr(x))),q)),x)),x)),FreeQ(List(a,c,d,f,g,h,p,q),x))),
IIntegrate(1344,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Plus(g,Times(h,x))),x),x),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),IGtQ(p,C0),IntegerQ(q)))),
IIntegrate(1345,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(a,Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Plus(g,Times(h,x))),x),x),And(FreeQ(List(a,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),IntegersQ(p,q),Or(GtQ(p,C0),GtQ(q,C0))))),
IIntegrate(1346,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Subtract(Subtract(Times(g,b),Times(C2,a,h)),Times(Subtract(Times(b,h),Times(C2,g,c)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Subtract(q,C1)),Simp(Subtract(Plus(Times(e,q,Subtract(Times(g,b),Times(C2,a,h))),Times(CN1,d,Subtract(Times(b,h),Times(C2,g,c)),Plus(Times(C2,p),C3)),Times(Subtract(Times(C2,f,q,Subtract(Times(g,b),Times(C2,a,h))),Times(e,Subtract(Times(b,h),Times(C2,g,c)),Plus(Times(C2,p),q,C3))),x)),Times(f,Subtract(Times(b,h),Times(C2,g,c)),Plus(Times(C2,p),Times(C2,q),C3),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),LtQ(p,CN1),GtQ(q,C0)))),
IIntegrate(1347,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(Subtract(Times(a,h),Times(g,c,x)),Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Power(Times(C2,a,c,Plus(p,C1)),CN1)),x),Simp(Star(Times(C2,Power(Times(C4,a,c,Plus(p,C1)),CN1)),Integrate(Times(Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Subtract(q,C1)),Simp(Plus(Times(g,c,d,Plus(Times(C2,p),C3)),Times(CN1,a,h,e,q),Times(Subtract(Times(g,c,e,Plus(Times(C2,p),q,C3)),Times(a,C2,h,f,q)),x),Times(g,c,f,Plus(Times(C2,p),Times(C2,q),C3),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),LtQ(p,CN1),GtQ(q,C0)))),
IIntegrate(1348,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Subtract(Subtract(Times(g,b),Times(C2,a,h)),Times(Subtract(Times(b,h),Times(C2,g,c)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(f,Sqr(x))),q),Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(f,Sqr(x))),Subtract(q,C1)),Simp(Subtract(Plus(Times(CN1,d,Subtract(Times(b,h),Times(C2,g,c)),Plus(Times(C2,p),C3)),Times(C2,f,q,Subtract(Times(g,b),Times(C2,a,h)),x)),Times(f,Subtract(Times(b,h),Times(C2,g,c)),Plus(Times(C2,p),Times(C2,q),C3),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1),GtQ(q,C0)))),
IIntegrate(1349,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(q,C1)),Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),Plus(p,C1)),CN1),Plus(Times(g,c,Subtract(Times(C2,a,c,e),Times(b,Plus(Times(c,d),Times(a,f))))),Times(Subtract(Times(g,b),Times(a,h)),Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,Plus(Times(b,e),Times(C2,a,f))))),Times(c,Subtract(Times(g,Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,Plus(Times(b,e),Times(C2,a,f))))),Times(h,Plus(Times(b,c,d),Times(CN1,C2,a,c,e),Times(a,b,f)))),x))),x),Simp(Star(Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Simp(Subtract(Subtract(Subtract(Plus(Times(Subtract(Times(b,h),Times(C2,g,c)),Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),Plus(p,C1)),Times(Plus(Times(Sqr(b),g,f),Times(CN1,b,Plus(Times(h,c,d),Times(g,c,e),Times(a,h,f))),Times(C2,Subtract(Times(g,c,Subtract(Times(c,d),Times(a,f))),Times(a,CN1,h,c,e)))),Subtract(Times(a,f,Plus(p,C1)),Times(c,d,Plus(p,C2))))),Times(e,Plus(Times(g,c,Subtract(Times(C2,a,c,e),Times(b,Plus(Times(c,d),Times(a,f))))),Times(Subtract(Times(g,b),Times(a,h)),Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,Plus(Times(b,e),Times(C2,a,f)))))),Plus(p,q,C2))),Times(Subtract(Times(C2,f,Plus(Times(g,c,Subtract(Times(C2,a,c,e),Times(b,Plus(Times(c,d),Times(a,f))))),Times(Subtract(Times(g,b),Times(a,h)),Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,Plus(Times(b,e),Times(C2,a,f)))))),Plus(p,q,C2)),Times(Plus(Times(Sqr(b),g,f),Times(CN1,b,Plus(Times(h,c,d),Times(g,c,e),Times(a,h,f))),Times(C2,Subtract(Times(g,c,Subtract(Times(c,d),Times(a,f))),Times(a,CN1,h,c,e)))),Subtract(Times(b,f,Plus(p,C1)),Times(c,e,Plus(Times(C2,p),q,C4))))),x)),Times(c,f,Plus(Times(Sqr(b),g,f),Times(CN1,b,Plus(Times(h,c,d),Times(g,c,e),Times(a,h,f))),Times(C2,Plus(Times(g,c,Subtract(Times(c,d),Times(a,f))),Times(a,h,c,e)))),Plus(Times(C2,p),Times(C2,q),C5),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),LtQ(p,CN1),NeQ(Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),C0),Not(And(Not(IntegerQ(p)),ILtQ(q,CN1)))))),
IIntegrate(1350,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(q,C1)),Power(Times(CN4,a,c,Plus(Times(a,c,Sqr(e)),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),CN1),Plus(Times(g,c,C2,a,c,e),Times(CN1,a,h,Subtract(Times(C2,Sqr(c),d),Times(c,C2,a,f))),Times(c,Subtract(Times(g,Subtract(Times(C2,Sqr(c),d),Times(c,C2,a,f))),Times(h,CN2,a,c,e)),x))),x),Simp(Star(Power(Times(CN4,a,c,Plus(Times(a,c,Sqr(e)),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Simp(Subtract(Subtract(Subtract(Plus(Times(CN2,g,c,Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(CN1,a,e,c,e)),Plus(p,C1)),Times(C2,Subtract(Times(g,c,Subtract(Times(c,d),Times(a,f))),Times(a,CN1,h,c,e)),Subtract(Times(a,f,Plus(p,C1)),Times(c,d,Plus(p,C2))))),Times(e,Plus(Times(g,c,C2,a,c,e),Times(CN1,a,h,Subtract(Times(C2,Sqr(c),d),Times(c,Plus(C2),a,f)))),Plus(p,q,C2))),Times(Subtract(Times(C2,f,Plus(Times(g,c,C2,a,c,e),Times(CN1,a,h,Plus(Times(C2,Sqr(c),d),Times(CN1,c,Plus(C2),a,f)))),Plus(p,q,C2)),Times(C2,Subtract(Times(g,c,Subtract(Times(c,d),Times(a,f))),Times(a,CN1,h,c,e)),CN1,c,e,Plus(Times(C2,p),q,C4))),x)),Times(c,f,C2,Subtract(Times(g,c,Subtract(Times(c,d),Times(a,f))),Times(a,CN1,h,c,e)),Plus(Times(C2,p),Times(C2,q),C5),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,c,d,e,f,g,h,q),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),LtQ(p,CN1),NeQ(Plus(Times(a,c,Sqr(e)),Sqr(Subtract(Times(c,d),Times(a,f)))),C0),Not(And(Not(IntegerQ(p)),ILtQ(q,CN1)))))),
IIntegrate(1351,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(f,Sqr(x))),Plus(q,C1)),Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(Times(Sqr(b),d,f),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),CN1),Plus(Times(g,c,CN1,b,Plus(Times(c,d),Times(a,f))),Times(Subtract(Times(g,b),Times(a,h)),Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,C2,a,f))),Times(c,Subtract(Times(g,Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,C2,a,f))),Times(h,Plus(Times(b,c,d),Times(a,b,f)))),x))),x),Simp(Star(Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(Times(Sqr(b),d,f),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(f,Sqr(x))),q),Simp(Subtract(Subtract(Plus(Times(Subtract(Times(b,h),Times(C2,g,c)),Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(b,d,CN1,b,f)),Plus(p,C1)),Times(Plus(Times(Sqr(b),g,f),Times(CN1,b,Plus(Times(h,c,d),Times(a,h,f))),Times(C2,g,c,Subtract(Times(c,d),Times(a,f)))),Subtract(Times(a,f,Plus(p,C1)),Times(c,d,Plus(p,C2))))),Times(Subtract(Times(C2,f,Plus(Times(g,c,CN1,b,Plus(Times(c,d),Times(a,f))),Times(Subtract(Times(g,b),Times(a,h)),Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,C2,a,f)))),Plus(p,q,C2)),Times(Plus(Times(Sqr(b),g,f),Times(CN1,b,Plus(Times(h,c,d),Times(a,h,f))),Times(C2,g,c,Subtract(Times(c,d),Times(a,f)))),b,f,Plus(p,C1))),x)),Times(c,f,Plus(Times(Sqr(b),g,f),Times(CN1,b,Plus(Times(h,c,d),Times(a,h,f))),Times(C2,g,c,Subtract(Times(c,d),Times(a,f)))),Plus(Times(C2,p),Times(C2,q),C5),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d,f,g,h,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1),NeQ(Plus(Times(Sqr(b),d,f),Sqr(Subtract(Times(c,d),Times(a,f)))),C0),Not(And(Not(IntegerQ(p)),ILtQ(q,CN1)))))),
IIntegrate(1352,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(h,Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(q,C1)),Power(Times(C2,f,Plus(p,q,C1)),CN1)),x),Simp(Star(Power(Times(C2,f,Plus(p,q,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Simp(Plus(Times(h,p,Subtract(Times(b,d),Times(a,e))),Times(a,Subtract(Times(h,e),Times(C2,g,f)),Plus(p,q,C1)),Times(Plus(Times(C2,h,p,Subtract(Times(c,d),Times(a,f))),Times(b,Subtract(Times(h,e),Times(C2,g,f)),Plus(p,q,C1))),x),Times(Plus(Times(h,p,Subtract(Times(c,e),Times(b,f))),Times(c,Subtract(Times(h,e),Times(C2,g,f)),Plus(p,q,C1))),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),GtQ(p,C0),NeQ(Plus(p,q,C1),C0)))),
IIntegrate(1353,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(h,Power(Plus(a,Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(q,C1)),Power(Times(C2,f,Plus(p,q,C1)),CN1)),x),Simp(Star(Power(Times(C2,f,Plus(p,q,C1)),CN1),Integrate(Times(Power(Plus(a,Times(c,Sqr(x))),Subtract(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Simp(Subtract(Subtract(Subtract(Times(a,h,e,p),Times(a,Subtract(Times(h,e),Times(C2,g,f)),Plus(p,q,C1))),Times(C2,h,p,Subtract(Times(c,d),Times(a,f)),x)),Times(Plus(Times(h,c,e,p),Times(c,Subtract(Times(h,e),Times(C2,g,f)),Plus(p,q,C1))),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,c,d,e,f,g,h,q),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),GtQ(p,C0),NeQ(Plus(p,q,C1),C0)))),
IIntegrate(1354,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(h,Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Power(Plus(d,Times(f,Sqr(x))),Plus(q,C1)),Power(Times(C2,f,Plus(p,q,C1)),CN1)),x),Simp(Star(Power(Times(C2,f,Plus(p,q,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C1)),Power(Plus(d,Times(f,Sqr(x))),q),Simp(Plus(Times(h,p,b,d),Times(a,CN2,g,f,Plus(p,q,C1)),Times(Plus(Times(C2,h,p,Subtract(Times(c,d),Times(a,f))),Times(b,CN2,g,f,Plus(p,q,C1))),x),Times(Plus(Times(h,p,CN1,b,f),Times(c,CN2,g,f,Plus(p,q,C1))),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d,f,g,h,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),GtQ(p,C0),NeQ(Plus(p,q,C1),C0)))),
IIntegrate(1355,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Simplify(Plus(Times(Sqr(c),Sqr(d)),Times(CN1,b,c,d,e),Times(a,c,Sqr(e)),Times(Sqr(b),d,f),Times(CN1,C2,a,c,d,f),Times(CN1,a,b,e,f),Times(Sqr(a),Sqr(f)))))),Condition(Plus(Simp(Star(Power(q,CN1),Integrate(Times(Simp(Plus(Times(g,Sqr(c),d),Times(CN1,g,b,c,e),Times(a,h,c,e),Times(g,Sqr(b),f),Times(CN1,a,b,h,f),Times(CN1,a,g,c,f),Times(c,Subtract(Plus(Times(h,c,d),Times(CN1,g,c,e),Times(g,b,f)),Times(a,h,f)),x)),x),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x)),x),Simp(Star(Power(q,CN1),Integrate(Times(Simp(Subtract(Plus(Times(CN1,h,c,d,e),Times(g,c,Sqr(e)),Times(b,h,d,f),Times(CN1,g,c,d,f),Times(CN1,g,b,e,f),Times(a,g,Sqr(f))),Times(f,Subtract(Plus(Times(h,c,d),Times(CN1,g,c,e),Times(g,b,f)),Times(a,h,f)),x)),x),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),CN1)),x)),x)),NeQ(q,C0))),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0)))),
IIntegrate(1356,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Simplify(Plus(Times(Sqr(c),Sqr(d)),Times(Sqr(b),d,f),Times(CN1,C2,a,c,d,f),Times(Sqr(a),Sqr(f)))))),Condition(Plus(Simp(Star(Power(q,CN1),Integrate(Times(Simp(Plus(Times(g,Sqr(c),d),Times(g,Sqr(b),f),Times(CN1,a,b,h,f),Times(CN1,a,g,c,f),Times(c,Subtract(Plus(Times(h,c,d),Times(g,b,f)),Times(a,h,f)),x)),x),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x)),x),Simp(Star(Power(q,CN1),Integrate(Times(Simp(Subtract(Plus(Times(b,h,d,f),Times(CN1,g,c,d,f),Times(a,g,Sqr(f))),Times(f,Subtract(Plus(Times(h,c,d),Times(g,b,f)),Times(a,h,f)),x)),x),Power(Plus(d,Times(f,Sqr(x))),CN1)),x)),x)),NeQ(q,C0))),And(FreeQ(List(a,b,c,d,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1357,Integrate(Times(Plus(g_,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Simp(Star(Times(CN2,g),Subst(Integrate(Power(Subtract(Subtract(Times(b,d),Times(a,e)),Times(b,Sqr(x))),CN1),x),x,Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x)))))),x),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),EqQ(Subtract(Times(c,e),Times(b,f)),C0),EqQ(Subtract(Times(h,e),Times(C2,g,f)),C0)))),
IIntegrate(1358,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Subtract(Times(h,e),Times(C2,g,f)),Power(Times(C2,f),CN1)),Integrate(Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x)),x),Simp(Star(Times(h,Power(Times(C2,f),CN1)),Integrate(Times(Plus(e,Times(C2,f,x)),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),EqQ(Subtract(Times(c,e),Times(b,f)),C0),NeQ(Subtract(Times(h,e),Times(C2,g,f)),C0)))),
IIntegrate(1359,Integrate(Times(x_,Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Simp(Star(Times(CN2,e),Subst(Integrate(Times(Subtract(C1,Times(d,Sqr(x))),Power(Plus(Times(c,e),Times(CN1,b,f),Times(CN1,e,Plus(Times(C2,c,d),Times(CN1,b,e),Times(C2,a,f)),Sqr(x)),Times(Sqr(d),Subtract(Times(c,e),Times(b,f)),Power(x,C4))),CN1)),x),x,Times(Plus(C1,Times(Plus(e,Sqrt(Subtract(Sqr(e),Times(C4,d,f)))),x,Power(Times(C2,d),CN1))),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),CN1D2)))),x),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),EqQ(Subtract(Times(b,d),Times(a,e)),C0)))),
IIntegrate(1360,Integrate(Times(Plus(g_,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Simp(Star(g,Subst(Integrate(Power(Plus(a,Times(Subtract(Times(c,d),Times(a,f)),Sqr(x))),CN1),x),x,Times(x,Power(Plus(d,Times(e,x),Times(f,Sqr(x))),CN1D2)))),x),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),EqQ(Subtract(Times(b,d),Times(a,e)),C0),EqQ(Subtract(Times(C2,h,d),Times(g,e)),C0))))
  );
}
