package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules247 { 
  public static IAST RULES = List( 
IIntegrate(4941,Integrate(Times(Power(Cos(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Simp(Star(Times(Exp(Times(CI,n,Plus(d,Times(e,x)))),Power(Cos(Plus(d,Times(e,x))),n),Power(Power(Plus(C1,Exp(Times(C2,CI,Plus(d,Times(e,x))))),n),CN1)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Plus(C1,Exp(Times(C2,CI,Plus(d,Times(e,x))))),n),Power(Exp(Times(CI,n,Plus(d,Times(e,x)))),CN1)),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e,n),x),Not(IntegerQ(n))))),
IIntegrate(4942,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Tan(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(CI,n),Integrate(ExpandIntegrand(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Subtract(C1,Exp(Times(C2,CI,Plus(d,Times(e,x))))),n),Power(Power(Plus(C1,Exp(Times(C2,CI,Plus(d,Times(e,x))))),n),CN1)),x),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e),x),IntegerQ(n)))),
IIntegrate(4943,Integrate(Times(Power(Cot(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Simp(Star(Power(CNI,n),Integrate(ExpandIntegrand(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Plus(C1,Exp(Times(C2,CI,Plus(d,Times(e,x))))),n),Power(Power(Subtract(C1,Exp(Times(C2,CI,Plus(d,Times(e,x))))),n),CN1)),x),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e),x),IntegerQ(n)))),
IIntegrate(4944,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Sec(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_)),x_Symbol),
    Condition(Plus(Simp(Times(b,c,Log(FSymbol),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sec(Plus(d,Times(e,x))),n),Power(Plus(Times(Sqr(e),Sqr(n)),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),CN1)),x),Negate(Simp(Times(e,n,Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sec(Plus(d,Times(e,x))),Plus(n,C1)),Sin(Plus(d,Times(e,x))),Power(Plus(Times(Sqr(e),Sqr(n)),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),CN1)),x)),Simp(Star(Times(Sqr(e),n,Plus(n,C1),Power(Plus(Times(Sqr(e),Sqr(n)),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),CN1)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sec(Plus(d,Times(e,x))),Plus(n,C2))),x)),x)),And(FreeQ(List(FSymbol,a,b,c,d,e),x),NeQ(Plus(Times(Sqr(e),Sqr(n)),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),C0),LtQ(n,CN1)))),
IIntegrate(4945,Integrate(Times(Power(Csc(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Plus(Simp(Times(b,c,Log(FSymbol),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Csc(Plus(d,Times(e,x))),n),Power(Plus(Times(Sqr(e),Sqr(n)),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),CN1)),x),Simp(Times(e,n,Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Csc(Plus(d,Times(e,x))),Plus(n,C1)),Cos(Plus(d,Times(e,x))),Power(Plus(Times(Sqr(e),Sqr(n)),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),CN1)),x),Simp(Star(Times(Sqr(e),n,Plus(n,C1),Power(Plus(Times(Sqr(e),Sqr(n)),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),CN1)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Csc(Plus(d,Times(e,x))),Plus(n,C2))),x)),x)),And(FreeQ(List(FSymbol,a,b,c,d,e),x),NeQ(Plus(Times(Sqr(e),Sqr(n)),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),C0),LtQ(n,CN1)))),
IIntegrate(4946,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Sec(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,c,Log(FSymbol),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sec(Plus(d,Times(e,x))),Subtract(n,C2)),Power(Times(Sqr(e),Subtract(n,C1),Subtract(n,C2)),CN1)),x),Simp(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sec(Plus(d,Times(e,x))),Subtract(n,C1)),Sin(Plus(d,Times(e,x))),Power(Times(e,Subtract(n,C1)),CN1)),x)),And(FreeQ(List(FSymbol,a,b,c,d,e,n),x),EqQ(Plus(Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol))),Times(Sqr(e),Sqr(Subtract(n,C2)))),C0),NeQ(n,C1),NeQ(n,C2)))),
IIntegrate(4947,Integrate(Times(Power(Csc(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,c,Log(FSymbol),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Csc(Plus(d,Times(e,x))),Subtract(n,C2)),Power(Times(Sqr(e),Subtract(n,C1),Subtract(n,C2)),CN1)),x),Simp(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Csc(Plus(d,Times(e,x))),Subtract(n,C1)),Cos(Plus(d,Times(e,x))),Power(Times(e,Subtract(n,C1)),CN1)),x)),And(FreeQ(List(FSymbol,a,b,c,d,e,n),x),EqQ(Plus(Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol))),Times(Sqr(e),Sqr(Subtract(n,C2)))),C0),NeQ(n,C1),NeQ(n,C2)))),
IIntegrate(4948,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Sec(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,c,Log(FSymbol),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sec(Plus(d,Times(e,x))),Subtract(n,C2)),Power(Times(Sqr(e),Subtract(n,C1),Subtract(n,C2)),CN1)),x),Simp(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sec(Plus(d,Times(e,x))),Subtract(n,C1)),Sin(Plus(d,Times(e,x))),Power(Times(e,Subtract(n,C1)),CN1)),x),Simp(Star(Times(Plus(Times(Sqr(e),Sqr(Subtract(n,C2))),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),Power(Times(Sqr(e),Subtract(n,C1),Subtract(n,C2)),CN1)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sec(Plus(d,Times(e,x))),Subtract(n,C2))),x)),x)),And(FreeQ(List(FSymbol,a,b,c,d,e),x),NeQ(Plus(Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol))),Times(Sqr(e),Sqr(Subtract(n,C2)))),C0),GtQ(n,C1),NeQ(n,C2)))),
IIntegrate(4949,Integrate(Times(Power(Csc(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,c,Log(FSymbol),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Csc(Plus(d,Times(e,x))),Subtract(n,C2)),Power(Times(Sqr(e),Subtract(n,C1),Subtract(n,C2)),CN1)),x),Negate(Simp(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Csc(Plus(d,Times(e,x))),Subtract(n,C1)),Cos(Plus(d,Times(e,x))),Power(Times(e,Subtract(n,C1)),CN1)),x)),Simp(Star(Times(Plus(Times(Sqr(e),Sqr(Subtract(n,C2))),Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol)))),Power(Times(Sqr(e),Subtract(n,C1),Subtract(n,C2)),CN1)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Csc(Plus(d,Times(e,x))),Subtract(n,C2))),x)),x)),And(FreeQ(List(FSymbol,a,b,c,d,e),x),NeQ(Plus(Times(Sqr(b),Sqr(c),Sqr(Log(FSymbol))),Times(Sqr(e),Sqr(Subtract(n,C2)))),C0),GtQ(n,C1),NeQ(n,C2)))),
IIntegrate(4950,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Sec(Plus(d_DEFAULT,Times(Pi,k_DEFAULT),Times(e_DEFAULT,x_))),n_DEFAULT)),x_Symbol),
    Condition(Simp(Times(Power(C2,n),Exp(Times(CI,k,n,Pi)),Exp(Times(CI,n,Plus(d,Times(e,x)))),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Plus(Times(CI,e,n),Times(b,c,Log(FSymbol))),CN1),Hypergeometric2F1(n,Subtract(Times(C1D2,n),Times(CI,b,c,Log(FSymbol),Power(Times(C2,e),CN1))),Subtract(Plus(C1,Times(C1D2,n)),Times(CI,b,c,Log(FSymbol),Power(Times(C2,e),CN1))),Times(CN1,Exp(Times(C2,CI,k,Pi)),Exp(Times(C2,CI,Plus(d,Times(e,x))))))),x),And(FreeQ(List(FSymbol,a,b,c,d,e),x),IntegerQ(Times(C4,k)),IntegerQ(n)))),
IIntegrate(4951,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Sec(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),x_Symbol),
    Condition(Simp(Times(Power(C2,n),Exp(Times(CI,n,Plus(d,Times(e,x)))),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Plus(Times(CI,e,n),Times(b,c,Log(FSymbol))),CN1),Hypergeometric2F1(n,Subtract(Times(C1D2,n),Times(CI,b,c,Log(FSymbol),Power(Times(C2,e),CN1))),Subtract(Plus(C1,Times(C1D2,n)),Times(CI,b,c,Log(FSymbol),Power(Times(C2,e),CN1))),Negate(Exp(Times(C2,CI,Plus(d,Times(e,x))))))),x),And(FreeQ(List(FSymbol,a,b,c,d,e),x),IntegerQ(n)))),
IIntegrate(4952,Integrate(Times(Power(Csc(Plus(d_DEFAULT,Times(Pi,k_DEFAULT),Times(e_DEFAULT,x_))),n_DEFAULT),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Simp(Times(Power(Times(CN2,CI),n),Exp(Times(CI,k,n,Pi)),Exp(Times(CI,n,Plus(d,Times(e,x)))),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Plus(Times(CI,e,n),Times(b,c,Log(FSymbol))),CN1),Hypergeometric2F1(n,Subtract(Times(C1D2,n),Times(CI,b,c,Log(FSymbol),Power(Times(C2,e),CN1))),Subtract(Plus(C1,Times(C1D2,n)),Times(CI,b,c,Log(FSymbol),Power(Times(C2,e),CN1))),Times(Exp(Times(C2,CI,k,Pi)),Exp(Times(C2,CI,Plus(d,Times(e,x))))))),x),And(FreeQ(List(FSymbol,a,b,c,d,e),x),IntegerQ(Times(C4,k)),IntegerQ(n)))),
IIntegrate(4953,Integrate(Times(Power(Csc(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Simp(Times(Power(Times(CN2,CI),n),Exp(Times(CI,n,Plus(d,Times(e,x)))),Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Plus(Times(CI,e,n),Times(b,c,Log(FSymbol))),CN1),Hypergeometric2F1(n,Subtract(Times(C1D2,n),Times(CI,b,c,Log(FSymbol),Power(Times(C2,e),CN1))),Subtract(Plus(C1,Times(C1D2,n)),Times(CI,b,c,Log(FSymbol),Power(Times(C2,e),CN1))),Exp(Times(C2,CI,Plus(d,Times(e,x)))))),x),And(FreeQ(List(FSymbol,a,b,c,d,e),x),IntegerQ(n)))),
IIntegrate(4954,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Sec(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(C1,Exp(Times(C2,CI,Plus(d,Times(e,x))))),n),Power(Sec(Plus(d,Times(e,x))),n),Power(Exp(Times(CI,n,Plus(d,Times(e,x)))),CN1)),Integrate(SimplifyIntegrand(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Exp(Times(CI,n,Plus(d,Times(e,x)))),Power(Power(Plus(C1,Exp(Times(C2,CI,Plus(d,Times(e,x))))),n),CN1)),x),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e),x),Not(IntegerQ(n))))),
IIntegrate(4955,Integrate(Times(Power(Csc(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Simp(Star(Times(Power(Subtract(C1,Exp(Times(CN2,CI,Plus(d,Times(e,x))))),n),Power(Csc(Plus(d,Times(e,x))),n),Power(Exp(Times(CN1,CI,n,Plus(d,Times(e,x)))),CN1)),Integrate(SimplifyIntegrand(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Times(Exp(Times(CI,n,Plus(d,Times(e,x)))),Power(Subtract(C1,Exp(Times(CN2,CI,Plus(d,Times(e,x))))),n)),CN1)),x),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e),x),Not(IntegerQ(n))))),
IIntegrate(4956,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Plus(f_,Times(g_DEFAULT,Sin(Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),n_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Times(Power(C2,n),Power(f,n)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Cos(Plus(Times(C1D2,d),Times(CN1,f,Pi,Power(Times(C4,g),CN1)),Times(e,C1D2,x))),Times(C2,n))),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g),x),EqQ(Subtract(Sqr(f),Sqr(g)),C0),ILtQ(n,C0)))),
IIntegrate(4957,Integrate(Times(Power(Plus(Times(Cos(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),g_DEFAULT),f_),n_DEFAULT),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Simp(Star(Times(Power(C2,n),Power(f,n)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Cos(Plus(Times(C1D2,d),Times(e,C1D2,x))),Times(C2,n))),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g),x),EqQ(Subtract(f,g),C0),ILtQ(n,C0)))),
IIntegrate(4958,Integrate(Times(Power(Plus(Times(Cos(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),g_DEFAULT),f_),n_DEFAULT),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Simp(Star(Times(Power(C2,n),Power(f,n)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Sin(Plus(Times(C1D2,d),Times(e,C1D2,x))),Times(C2,n))),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g),x),EqQ(Plus(f,g),C0),ILtQ(n,C0)))),
IIntegrate(4959,Integrate(Times(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),Power(Plus(f_,Times(g_DEFAULT,Sin(Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),n_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(f,Times(g,Sin(Plus(d,Times(e,x))))),n),Power(Power(Cos(Plus(Times(C1D2,d),Times(CN1,f,Pi,Power(Times(C4,g),CN1)),Times(e,C1D2,x))),Times(C2,n)),CN1)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Cos(Plus(Times(C1D2,d),Times(CN1,f,Pi,Power(Times(C4,g),CN1)),Times(e,C1D2,x))),Times(C2,n))),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,n),x),EqQ(Subtract(Sqr(f),Sqr(g)),C0),Not(IntegerQ(n))))),
IIntegrate(4960,Integrate(Times(Power(Plus(Times(Cos(Plus(d_DEFAULT,Times(e_DEFAULT,x_))),g_DEFAULT),f_),n_DEFAULT),Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_))))),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(f,Times(g,Cos(Plus(d,Times(e,x))))),n),Power(Power(Cos(Plus(Times(C1D2,d),Times(e,C1D2,x))),Times(C2,n)),CN1)),Integrate(Times(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),Power(Cos(Plus(Times(C1D2,d),Times(e,C1D2,x))),Times(C2,n))),x)),x),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,n),x),EqQ(Subtract(f,g),C0),Not(IntegerQ(n)))))
  );
}
