package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules81 { 
  public static IAST RULES = List( 
IIntegrate(1621,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(Sqr(d),Power(f,C4),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,C4)),Power(Plus(d,Times(e,Sqr(x))),q)),x)),x),Simp(Star(Times(a,Power(f,C4),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,C4)),Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Subtract(d,Times(e,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f),x),Not(IntegerQ(q)),LtQ(q,CN1),GtQ(m,C3)))),
IIntegrate(1622,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,d,e,Sqr(f),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,C2)),Power(Plus(d,Times(e,Sqr(x))),q)),x)),x),Simp(Star(Times(Sqr(f),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,C2)),Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Simp(Plus(Times(a,e),Times(c,d,Sqr(x))),x),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(q)),LtQ(q,CN1),GtQ(m,C1),LeQ(m,C3)))),
IIntegrate(1623,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,d,e,Sqr(f),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,C2)),Power(Plus(d,Times(e,Sqr(x))),q)),x)),x),Simp(Star(Times(Sqr(f),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,C2)),Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Simp(Plus(Times(a,e),Times(c,d,Sqr(x))),x),Power(Plus(a,Times(c,Power(x,C4))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f),x),Not(IntegerQ(q)),LtQ(q,CN1),GtQ(m,C1),LeQ(m,C3)))),
IIntegrate(1624,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Sqr(e),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q)),x)),x),Simp(Star(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Simp(Subtract(Subtract(Times(c,d),Times(b,e)),Times(c,e,Sqr(x))),x),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,m),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(q)),LtQ(q,CN1)))),
IIntegrate(1625,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Sqr(e),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q)),x)),x),Simp(Star(Times(c,Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Subtract(d,Times(e,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f,m),x),Not(IntegerQ(q)),LtQ(q,CN1)))),
IIntegrate(1626,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Power(Plus(d,Times(e,Sqr(x))),q),Times(Power(Times(f,x),m),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1)),x),x),And(FreeQ(List(a,b,c,d,e,f,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(q)),IntegerQ(m)))),
IIntegrate(1627,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Power(Plus(d,Times(e,Sqr(x))),q),Times(Power(Times(f,x),m),Power(Plus(a,Times(c,Power(x,C4))),CN1)),x),x),And(FreeQ(List(a,c,d,e,f,q),x),Not(IntegerQ(q)),IntegerQ(m)))),
IIntegrate(1628,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(With(list(Set(r,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Simp(Star(Times(C2,c,Power(r,CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(b,Negate(r),Times(C2,c,Sqr(x))),CN1)),x)),x),Simp(Star(Times(C2,c,Power(r,CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(b,r,Times(C2,c,Sqr(x))),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,e,f,m,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1629,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(With(list(Set(r,Rt(Times(CN1,a,c),C2))),Subtract(Simp(Star(Times(CN1,c,Power(Times(C2,r),CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Subtract(r,Times(c,Sqr(x))),CN1)),x)),x),Simp(Star(Times(c,Power(Times(C2,r),CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(r,Times(c,Sqr(x))),CN1)),x)),x))),FreeQ(List(a,c,d,e,f,m,q),x))),
IIntegrate(1630,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1)),Integrate(Times(Plus(Times(a,d,Rt(Times(c,Power(a,CN1)),C2)),Times(a,e),Times(Plus(Times(c,d),Times(a,e,Rt(Times(c,Power(a,CN1)),C2))),Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x)),x),Simp(Star(Power(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),ExpandToSum(Times(Plus(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(x,m),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1D2))),Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Plus(Times(a,d,Rt(Times(c,Power(a,CN1)),C2)),Times(a,e),Times(Plus(Times(c,d),Times(a,e,Rt(Times(c,Power(a,CN1)),C2))),Sqr(x))))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(Plus(p,C1D2),C0),IGtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1631,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1)),Integrate(Times(Plus(Times(a,d,Rt(Times(c,Power(a,CN1)),C2)),Times(a,e),Times(Plus(Times(c,d),Times(a,e,Rt(Times(c,Power(a,CN1)),C2))),Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x)),x),Simp(Star(Power(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1),Integrate(Times(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),ExpandToSum(Times(Plus(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(x,m),Power(Plus(a,Times(c,Power(x,C4))),Plus(p,C1D2))),Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Plus(Times(a,d,Rt(Times(c,Power(a,CN1)),C2)),Times(a,e),Times(Plus(Times(c,d),Times(a,e,Rt(Times(c,Power(a,CN1)),C2))),Sqr(x))))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,c,d,e),x),IGtQ(Plus(p,C1D2),C0),IGtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1632,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(e,Plus(Times(C2,p),C1)),CN1)),Integrate(Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1),x)),x),Simp(Star(Power(Power(e,Plus(Times(C2,p),C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),ExpandToSum(Times(Subtract(Times(Power(e,Plus(Times(C2,p),C1)),Power(x,m),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1D2))),Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(Plus(p,C1D2),C0),IGtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NegQ(Times(c,Power(a,CN1)))))),
IIntegrate(1633,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(e,Plus(Times(C2,p),C1)),CN1)),Integrate(Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1),x)),x),Simp(Star(Power(Power(e,Plus(Times(C2,p),C1)),CN1),Integrate(Times(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),ExpandToSum(Times(Subtract(Times(Power(e,Plus(Times(C2,p),C1)),Power(x,m),Power(Plus(a,Times(c,Power(x,C4))),Plus(p,C1D2))),Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,c,d,e),x),IGtQ(Plus(p,C1D2),C0),IGtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NegQ(Times(c,Power(a,CN1)))))),
IIntegrate(1634,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1)),Integrate(Times(Plus(Times(a,d,Rt(Times(c,Power(a,CN1)),C2)),Times(a,e),Times(Plus(Times(c,d),Times(a,e,Rt(Times(c,Power(a,CN1)),C2))),Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x)),x),Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1)),Integrate(Times(Power(x,m),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),ExpandToSum(Times(Plus(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1D2)),Power(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),CN1)),Times(Plus(Times(a,d,Rt(Times(c,Power(a,CN1)),C2)),Times(a,e),Times(Plus(Times(c,d),Times(a,e,Rt(Times(c,Power(a,CN1)),C2))),Sqr(x))),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(x,m),CN1))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(Plus(p,C1D2),C0),ILtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1635,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1)),Integrate(Times(Plus(Times(a,d,Rt(Times(c,Power(a,CN1)),C2)),Times(a,e),Times(Plus(Times(c,d),Times(a,e,Rt(Times(c,Power(a,CN1)),C2))),Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x)),x),Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1)),Integrate(Times(Power(x,m),Power(Plus(a,Times(c,Power(x,C4))),CN1D2),ExpandToSum(Times(Plus(Times(Power(e,Times(C2,p)),Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(Plus(a,Times(c,Power(x,C4))),Plus(p,C1D2)),Power(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),CN1)),Times(Plus(Times(a,d,Rt(Times(c,Power(a,CN1)),C2)),Times(a,e),Times(Plus(Times(c,d),Times(a,e,Rt(Times(c,Power(a,CN1)),C2))),Sqr(x))),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(x,m),CN1))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,c,d,e),x),IGtQ(Plus(p,C1D2),C0),ILtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1636,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(e,Plus(Times(C2,p),C1)),CN1)),Integrate(Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1),x)),x),Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Power(e,Plus(Times(C2,p),C1)),CN1)),Integrate(Times(Power(x,m),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),ExpandToSum(Times(Subtract(Times(Power(e,Plus(Times(C2,p),C1)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1D2)),Power(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),CN1)),Times(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(x,m),CN1))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(Plus(p,C1D2),C0),ILtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NegQ(Times(c,Power(a,CN1)))))),
IIntegrate(1637,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(e,Plus(Times(C2,p),C1)),CN1)),Integrate(Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1),x)),x),Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Power(e,Plus(Times(C2,p),C1)),CN1)),Integrate(Times(Power(x,m),Power(Plus(a,Times(c,Power(x,C4))),CN1D2),ExpandToSum(Times(Subtract(Times(Power(e,Plus(Times(C2,p),C1)),Power(Plus(a,Times(c,Power(x,C4))),Plus(p,C1D2)),Power(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),CN1)),Times(Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(x,m),CN1))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,c,d,e),x),IGtQ(Plus(p,C1D2),C0),ILtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NegQ(Times(c,Power(a,CN1)))))),
IIntegrate(1638,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Times(Power(e,Times(C2,p)),Subtract(Times(Rt(Times(c,Power(a,CN1)),C2),d),e)),CN1)),Integrate(Times(Plus(C1,Times(Rt(Times(c,Power(a,CN1)),C2),Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x)),x),Simp(Star(Times(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Subtract(Times(Rt(Times(c,Power(a,CN1)),C2),d),e),CN1)),Integrate(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p),ExpandToSum(Times(Plus(Times(Subtract(Times(Rt(Times(c,Power(a,CN1)),C2),d),e),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Subtract(Negate(p),C1D2)),Power(x,m)),Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Plus(C1,Times(Rt(Times(c,Power(a,CN1)),C2),Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Subtract(Negate(p),C1D2)),Power(Power(e,Times(C2,p)),CN1))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),ILtQ(Plus(p,C1D2),C0),IGtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1639,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Times(Power(e,Times(C2,p)),Subtract(Times(Rt(Times(c,Power(a,CN1)),C2),d),e)),CN1)),Integrate(Times(Plus(C1,Times(Rt(Times(c,Power(a,CN1)),C2),Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x)),x),Simp(Star(Times(Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Subtract(Times(Rt(Times(c,Power(a,CN1)),C2),d),e),CN1)),Integrate(Times(Power(Plus(a,Times(c,Power(x,C4))),p),ExpandToSum(Times(Plus(Times(Subtract(Times(Rt(Times(c,Power(a,CN1)),C2),d),e),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Subtract(Negate(p),C1D2)),Power(x,m)),Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Plus(C1,Times(Rt(Times(c,Power(a,CN1)),C2),Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),Subtract(Negate(p),C1D2)),Power(Power(e,Times(C2,p)),CN1))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,c,d,e),x),ILtQ(Plus(p,C1D2),C0),IGtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1640,Integrate(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Power(Power(e,Plus(Times(C2,p),C1)),CN1)),Integrate(Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1),x)),x),Simp(Star(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Plus(p,C1D2)),Integrate(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p),ExpandToSum(Times(Subtract(Times(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Subtract(Negate(p),C1D2)),Power(x,m)),Times(Power(e,Subtract(Times(CN2,p),C1)),Power(Times(CN1,d,Power(e,CN1)),Times(C1D2,m)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Subtract(Negate(p),C1D2)))),Power(Plus(d,Times(e,Sqr(x))),CN1)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),ILtQ(Plus(p,C1D2),C0),IGtQ(Times(C1D2,m),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NegQ(Times(c,Power(a,CN1))))))
  );
}
