package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules68 { 
  public static IAST RULES = List( 
IIntegrate(1361,Integrate(Times(Plus(g_,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Subtract(Times(C2,h,d),Times(g,e)),Power(e,CN1)),Integrate(Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x)),x),Simp(Star(Times(h,Power(e,CN1)),Integrate(Times(Plus(Times(C2,d),Times(e,x)),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),EqQ(Subtract(Times(b,d),Times(a,e)),C0),NeQ(Subtract(Times(C2,h,d),Times(g,e)),C0)))),
IIntegrate(1362,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Simp(Star(Times(CN2,g,Subtract(Times(g,b),Times(C2,a,h))),Subst(Integrate(Power(Simp(Subtract(Times(g,Subtract(Times(g,b),Times(C2,a,h)),Subtract(Sqr(b),Times(C4,a,c))),Times(Subtract(Times(b,d),Times(a,e)),Sqr(x))),x),CN1),x),x,Times(Simp(Subtract(Subtract(Times(g,b),Times(C2,a,h)),Times(Subtract(Times(b,h),Times(C2,g,c)),x)),x),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),CN1D2)))),x),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),NeQ(Subtract(Times(b,d),Times(a,e)),C0),EqQ(Plus(Times(Sqr(h),Subtract(Times(b,d),Times(a,e))),Times(CN1,C2,g,h,Subtract(Times(c,d),Times(a,f))),Times(Sqr(g),Subtract(Times(c,e),Times(b,f)))),C0)))),
IIntegrate(1363,Integrate(Times(Plus(g_,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Simp(Star(Times(CN2,a,g,h),Subst(Integrate(Power(Simp(Plus(Times(C2,Sqr(a),g,h,c),Times(a,e,Sqr(x))),x),CN1),x),x,Times(Simp(Subtract(Times(a,h),Times(g,c,x)),x),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),CN1D2)))),x),And(FreeQ(List(a,c,d,e,f,g,h),x),EqQ(Subtract(Plus(Times(a,Sqr(h),e),Times(C2,g,h,Subtract(Times(c,d),Times(a,f)))),Times(Sqr(g),c,e)),C0)))),
IIntegrate(1364,Integrate(Times(Plus(g_,Times(h_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Simp(Star(Times(CN2,g,Subtract(Times(g,b),Times(C2,a,h))),Subst(Integrate(Power(Simp(Subtract(Times(g,Subtract(Times(g,b),Times(C2,a,h)),Subtract(Sqr(b),Times(C4,a,c))),Times(b,d,Sqr(x))),x),CN1),x),x,Times(Simp(Subtract(Subtract(Times(g,b),Times(C2,a,h)),Times(Subtract(Times(b,h),Times(C2,g,c)),x)),x),Power(Plus(d,Times(f,Sqr(x))),CN1D2)))),x),And(FreeQ(List(a,b,c,d,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Subtract(Subtract(Times(b,Sqr(h),d),Times(C2,g,h,Subtract(Times(c,d),Times(a,f)))),Times(Sqr(g),b,f)),C0)))),
IIntegrate(1365,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Simp(Star(Times(Subtract(Times(C2,c,g),Times(h,Subtract(b,q))),Power(q,CN1)),Integrate(Power(Times(Plus(b,Negate(q),Times(C2,c,x)),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x)),x),Simp(Star(Times(Subtract(Times(C2,c,g),Times(h,Plus(b,q))),Power(q,CN1)),Integrate(Power(Times(Plus(b,q,Times(C2,c,x)),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x)),x))),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),PosQ(Subtract(Sqr(b),Times(C4,a,c)))))),
IIntegrate(1366,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,a,c),C2))),Plus(Simp(Star(Plus(Times(C1D2,h),Times(c,g,Power(Times(C2,q),CN1))),Integrate(Power(Times(Plus(Negate(q),Times(c,x)),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x)),x),Simp(Star(Subtract(Times(C1D2,h),Times(c,g,Power(Times(C2,q),CN1))),Integrate(Power(Times(Plus(q,Times(c,x)),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x)),x))),And(FreeQ(List(a,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),PosQ(Times(CN1,a,c))))),
IIntegrate(1367,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Simp(Star(Times(Subtract(Times(C2,c,g),Times(h,Subtract(b,q))),Power(q,CN1)),Integrate(Power(Times(Plus(b,Negate(q),Times(C2,c,x)),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1),x)),x),Simp(Star(Times(Subtract(Times(C2,c,g),Times(h,Plus(b,q))),Power(q,CN1)),Integrate(Power(Times(Plus(b,q,Times(C2,c,x)),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1),x)),x))),And(FreeQ(List(a,b,c,d,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),PosQ(Subtract(Sqr(b),Times(C4,a,c)))))),
IIntegrate(1368,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),C2))),Subtract(Simp(Star(Power(Times(C2,q),CN1),Integrate(Times(Simp(Subtract(Subtract(Times(h,Subtract(Times(b,d),Times(a,e))),Times(g,Subtract(Subtract(Times(c,d),Times(a,f)),q))),Times(Subtract(Times(g,Subtract(Times(c,e),Times(b,f))),Times(h,Plus(Times(c,d),Times(CN1,a,f),q))),x)),x),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x)),x),Simp(Star(Power(Times(C2,q),CN1),Integrate(Times(Simp(Subtract(Subtract(Times(h,Subtract(Times(b,d),Times(a,e))),Times(g,Plus(Times(c,d),Times(CN1,a,f),q))),Times(Subtract(Times(g,Subtract(Times(c,e),Times(b,f))),Times(h,Subtract(Subtract(Times(c,d),Times(a,f)),q))),x)),x),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),NeQ(Subtract(Times(b,d),Times(a,e)),C0),NegQ(Subtract(Sqr(b),Times(C4,a,c)))))),
IIntegrate(1369,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Plus(Sqr(Subtract(Times(c,d),Times(a,f))),Times(a,c,Sqr(e))),C2))),Subtract(Simp(Star(Power(Times(C2,q),CN1),Integrate(Times(Simp(Plus(Times(CN1,a,h,e),Times(CN1,g,Subtract(Subtract(Times(c,d),Times(a,f)),q)),Times(Subtract(Times(h,Plus(Times(c,d),Times(CN1,a,f),q)),Times(g,c,e)),x)),x),Power(Times(Plus(a,Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x)),x),Simp(Star(Power(Times(C2,q),CN1),Integrate(Times(Simp(Plus(Times(CN1,a,h,e),Times(CN1,g,Plus(Times(c,d),Times(CN1,a,f),q)),Times(Subtract(Times(h,Subtract(Subtract(Times(c,d),Times(a,f)),q)),Times(g,c,e)),x)),x),Power(Times(Plus(a,Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x)),x))),And(FreeQ(List(a,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),NegQ(Times(CN1,a,c))))),
IIntegrate(1370,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Plus(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Sqr(b),d,f)),C2))),Subtract(Simp(Star(Power(Times(C2,q),CN1),Integrate(Times(Simp(Plus(Times(h,b,d),Times(CN1,g,Subtract(Subtract(Times(c,d),Times(a,f)),q)),Times(Plus(Times(h,Plus(Times(c,d),Times(CN1,a,f),q)),Times(g,b,f)),x)),x),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1)),x)),x),Simp(Star(Power(Times(C2,q),CN1),Integrate(Times(Simp(Plus(Times(h,b,d),Times(CN1,g,Plus(Times(c,d),Times(CN1,a,f),q)),Times(Plus(Times(h,Subtract(Subtract(Times(c,d),Times(a,f)),q)),Times(g,b,f)),x)),x),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NegQ(Subtract(Sqr(b),Times(C4,a,c)))))),
IIntegrate(1371,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1D2),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(list(Set(s,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2)),Set(t,Rt(Subtract(Sqr(e),Times(C4,d,f)),C2))),Simp(Star(Times(Sqrt(Plus(b,s,Times(C2,c,x))),Sqrt(Plus(Times(C2,a),Times(Plus(b,s),x))),Sqrt(Plus(e,t,Times(C2,f,x))),Sqrt(Plus(Times(C2,d),Times(Plus(e,t),x))),Power(Times(Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),Integrate(Times(Plus(g,Times(h,x)),Power(Times(Sqrt(Plus(b,s,Times(C2,c,x))),Sqrt(Plus(Times(C2,a),Times(Plus(b,s),x))),Sqrt(Plus(e,t,Times(C2,f,x))),Sqrt(Plus(Times(C2,d),Times(Plus(e,t),x)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0)))),
IIntegrate(1372,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1D2),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(list(Set(s,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2)),Set(t,Rt(Times(CN4,d,f),C2))),Simp(Star(Times(Sqrt(Plus(b,s,Times(C2,c,x))),Sqrt(Plus(Times(C2,a),Times(Plus(b,s),x))),Sqrt(Plus(t,Times(C2,f,x))),Sqrt(Plus(Times(C2,d),Times(t,x))),Power(Times(Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1)),Integrate(Times(Plus(g,Times(h,x)),Power(Times(Sqrt(Plus(b,s,Times(C2,c,x))),Sqrt(Plus(Times(C2,a),Times(Plus(b,s),x))),Sqrt(Plus(t,Times(C2,f,x))),Sqrt(Plus(Times(C2,d),Times(t,x)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,f,g,h),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1373,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1D3),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Power(Times(CN9,c,Sqr(h),Power(Subtract(Times(C2,c,g),Times(b,h)),CN2)),C1D3))),Plus(Simp(Times(CSqrt3,h,q,ArcTan(Subtract(C1DSqrt3,Times(Power(C2,QQ(2L,3L)),Power(Subtract(C1,Times(C3,h,Plus(b,Times(C2,c,x)),Power(Subtract(Times(C2,c,g),Times(b,h)),CN1))),QQ(2L,3L)),Power(Times(CSqrt3,Power(Plus(C1,Times(C3,h,Plus(b,Times(C2,c,x)),Power(Subtract(Times(C2,c,g),Times(b,h)),CN1))),C1D3)),CN1)))),Power(f,CN1)),x),Negate(Simp(Times(C3,h,q,Log(Plus(Power(Subtract(C1,Times(C3,h,Plus(b,Times(C2,c,x)),Power(Subtract(Times(C2,c,g),Times(b,h)),CN1))),QQ(2L,3L)),Times(Power(C2,C1D3),Power(Plus(C1,Times(C3,h,Plus(b,Times(C2,c,x)),Power(Subtract(Times(C2,c,g),Times(b,h)),CN1))),C1D3)))),Power(Times(C2,f),CN1)),x)),Simp(Times(h,q,Log(Plus(d,Times(e,x),Times(f,Sqr(x)))),Power(Times(C2,f),CN1)),x))),And(FreeQ(List(a,b,c,d,e,f,g,h),x),EqQ(Subtract(Times(c,e),Times(b,f)),C0),EqQ(Subtract(Times(Sqr(c),d),Times(f,Subtract(Sqr(b),Times(C3,a,c)))),C0),EqQ(Plus(Times(Sqr(c),Sqr(g)),Times(CN1,b,c,g,h),Times(CN1,C2,Sqr(b),Sqr(h)),Times(C9,a,c,Sqr(h))),C0),GtQ(Times(CN9,c,Sqr(h),Power(Subtract(Times(C2,c,g),Times(b,h)),CN2)),C0)))),
IIntegrate(1374,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1D3),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Times(CN1,c,Power(Subtract(Sqr(b),Times(C4,a,c)),CN1)))),Simp(Star(Times(Power(Times(q,Plus(a,Times(b,x),Times(c,Sqr(x)))),C1D3),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1D3)),Integrate(Times(Plus(g,Times(h,x)),Power(Times(Power(Plus(Times(q,a),Times(b,q,x),Times(c,q,Sqr(x))),C1D3),Plus(d,Times(e,x),Times(f,Sqr(x)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h),x),EqQ(Subtract(Times(c,e),Times(b,f)),C0),EqQ(Subtract(Times(Sqr(c),d),Times(f,Subtract(Sqr(b),Times(C3,a,c)))),C0),EqQ(Plus(Times(Sqr(c),Sqr(g)),Times(CN1,b,c,g,h),Times(CN1,C2,Sqr(b),Sqr(h)),Times(C9,a,c,Sqr(h))),C0),Not(GtQ(Subtract(Times(C4,a),Times(Sqr(b),Power(c,CN1))),C0))))),
IIntegrate(1375,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Unintegrable(Times(Plus(g,Times(h,x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),FreeQ(List(a,b,c,d,e,f,g,h,p,q),x))),
IIntegrate(1376,Integrate(Times(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Unintegrable(Times(Plus(g,Times(h,x)),Power(Plus(a,Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),FreeQ(List(a,c,d,e,f,g,h,p,q),x))),
IIntegrate(1377,Integrate(Times(Power(Plus(g_DEFAULT,Times(h_DEFAULT,u_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,u_),Times(c_DEFAULT,Sqr(u_))),p_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,u_),Times(f_DEFAULT,Sqr(u_))),q_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(Coefficient(u,x,C1),CN1),Subst(Integrate(Times(Power(Plus(g,Times(h,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),x,u)),x),And(FreeQ(List(a,b,c,d,e,f,g,h,m,p,q),x),LinearQ(u,x),NeQ(u,x)))),
IIntegrate(1378,Integrate(Times(Power(Plus(g_DEFAULT,Times(h_DEFAULT,u_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(u_))),p_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,u_),Times(f_DEFAULT,Sqr(u_))),q_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(Coefficient(u,x,C1),CN1),Subst(Integrate(Times(Power(Plus(g,Times(h,x)),m),Power(Plus(a,Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),x,u)),x),And(FreeQ(List(a,c,d,e,f,g,h,m,p,q),x),LinearQ(u,x),NeQ(u,x)))),
IIntegrate(1379,Integrate(Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_),x_Symbol),
    Condition(Simp(Star(Power(Power(c,p),CN1),Integrate(Power(Plus(Times(C1D2,b),Times(c,Power(x,n))),Times(C2,p)),x)),x),And(FreeQ(List(a,b,c,n,p),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IntegerQ(p),NeQ(p,C1)))),
IIntegrate(1380,Integrate(Times(u_,Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(Power(c,p),CN1),Integrate(Times(u,Power(Plus(Times(C1D2,b),Times(c,Power(x,n))),Times(C2,p))),x)),x),And(FreeQ(List(a,b,c,n,p),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IntegerQ(p))))
  );
}
