package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules108 { 
  public static IAST RULES = List( 
IIntegrate(2161,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),FracPart(p)),Power(Times(Power(Times(C4,c),IntPart(p)),Power(Plus(b,Times(C2,c,x)),Times(C2,FracPart(p)))),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),m),$s("§pq"),Power(Plus(b,Times(C2,c,x)),Times(C2,p))),x)),x),And(FreeQ(List(a,b,c,d,e,m,p),x),PolyQ($s("§pq"),x),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(2162,Integrate(Times($p("§pq"),Power(Times(e_DEFAULT,x_),m_DEFAULT),Power(Plus(Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Simp(Star(e,Integrate(Times(Power(Times(e,x),Subtract(m,C1)),PolynomialQuotient($s("§pq"),Plus(b,Times(c,x)),x),Power(Plus(Times(b,x),Times(c,Sqr(x))),Plus(p,C1))),x)),x),And(FreeQ(List(b,c,e,m,p),x),PolyQ($s("§pq"),x),EqQ(PolynomialRemainder($s("§pq"),Plus(b,Times(c,x)),x),C0)))),
IIntegrate(2163,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Times(d,e),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),PolynomialQuotient($s("§pq"),Plus(Times(a,e),Times(c,d,x)),x),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1))),x)),x),And(FreeQ(List(a,b,c,d,e,m,p),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),EqQ(PolynomialRemainder($s("§pq"),Plus(Times(a,e),Times(c,d,x)),x),C0)))),
IIntegrate(2164,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Times(d,e),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),PolynomialQuotient($s("§pq"),Plus(Times(a,e),Times(b,d,x)),x),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1))),x)),x),And(FreeQ(List(a,b,d,e,m,p),x),PolyQ($s("§pq"),x),EqQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),EqQ(PolynomialRemainder($s("§pq"),Plus(Times(a,e),Times(b,d,x)),x),C0)))),
IIntegrate(2165,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set($s("§qx"),PolynomialQuotient($s("§pq"),Plus(Times(a,e),Times(c,d,x)),x)),Set($s("R"),PolynomialRemainder($s("§pq"),Plus(Times(a,e),Times(c,d,x)),x))),Plus(Simp(Times($s("R"),Subtract(Times(C2,c,d),Times(b,e)),Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(e,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x),Simp(Star(Power(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),ExpandToSum(Subtract(Times(d,e,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),$s("§qx")),Times($s("R"),Subtract(Times(C2,c,d),Times(b,e)),Plus(m,Times(C2,p),C2))),x)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),ILtQ(Plus(p,C1D2),C0),GtQ(m,C0)))),
IIntegrate(2166,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set($s("§qx"),PolynomialQuotient($s("§pq"),Plus(Times(a,e),Times(b,d,x)),x)),Set($s("R"),PolynomialRemainder($s("§pq"),Plus(Times(a,e),Times(b,d,x)),x))),Plus(Simp(Times(CN1,d,$s("R"),Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(C2,a,e,Plus(p,C1)),CN1)),x),Simp(Star(Times(d,Power(Times(C2,a,Plus(p,C1)),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),ExpandToSum(Plus(Times(C2,a,e,Plus(p,C1),$s("§qx")),Times($s("R"),Plus(m,Times(C2,p),C2))),x)),x)),x))),And(FreeQ(List(a,b,d,e),x),PolyQ($s("§pq"),x),EqQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),ILtQ(Plus(p,C1D2),C0),GtQ(m,C0)))),
IIntegrate(2167,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Times(Power(Plus(d,Times(e,x)),m),$s("§pq")),x),x),And(FreeQ(List(a,b,c,d,e),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),EqQ(Plus(m,Expon($s("§pq"),x),Times(C2,p),C1),C0),ILtQ(m,C0)))),
IIntegrate(2168,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Power(Plus(a,Times(b,Sqr(x))),p),Times(Power(Plus(d,Times(e,x)),m),$s("§pq")),x),x),And(FreeQ(List(a,b,d,e),x),PolyQ($s("§pq"),x),EqQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),EqQ(Plus(m,Expon($s("§pq"),x),Times(C2,p),C1),C0),ILtQ(m,C0)))),
IIntegrate(2169,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set(q,Expon($s("§pq"),x)),Set(f,Coeff($s("§pq"),x,Expon($s("§pq"),x)))),Condition(Plus(Simp(Times(f,Power(Plus(d,Times(e,x)),Subtract(Plus(m,q),C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(c,Power(e,Subtract(q,C1)),Plus(m,q,Times(C2,p),C1)),CN1)),x),Simp(Star(Power(Times(c,Power(e,q),Plus(m,q,Times(C2,p),C1)),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),ExpandToSum(Plus(Times(c,Power(e,q),Plus(m,q,Times(C2,p),C1),$s("§pq")),Times(CN1,c,f,Plus(m,q,Times(C2,p),C1),Power(Plus(d,Times(e,x)),q)),Times(e,f,Plus(m,p,q),Power(Plus(d,Times(e,x)),Subtract(q,C2)),Plus(Times(b,d),Times(CN1,C2,a,e),Times(Subtract(Times(C2,c,d),Times(b,e)),x)))),x)),x)),x)),NeQ(Plus(m,q,Times(C2,p),C1),C0))),And(FreeQ(List(a,b,c,d,e,m,p),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0)))),
IIntegrate(2170,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set(q,Expon($s("§pq"),x)),Set(f,Coeff($s("§pq"),x,Expon($s("§pq"),x)))),Condition(Plus(Simp(Times(f,Power(Plus(d,Times(e,x)),Subtract(Plus(m,q),C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(b,Power(e,Subtract(q,C1)),Plus(m,q,Times(C2,p),C1)),CN1)),x),Simp(Star(Power(Times(b,Power(e,q),Plus(m,q,Times(C2,p),C1)),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,Sqr(x))),p),ExpandToSum(Subtract(Subtract(Times(b,Power(e,q),Plus(m,q,Times(C2,p),C1),$s("§pq")),Times(b,f,Plus(m,q,Times(C2,p),C1),Power(Plus(d,Times(e,x)),q))),Times(C2,e,f,Plus(m,p,q),Power(Plus(d,Times(e,x)),Subtract(q,C2)),Subtract(Times(a,e),Times(b,d,x)))),x)),x)),x)),NeQ(Plus(m,q,Times(C2,p),C1),C0))),And(FreeQ(List(a,b,d,e,m,p),x),PolyQ($s("§pq"),x),EqQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),Not(IGtQ(m,C0))))),
IIntegrate(2171,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Integrate(Times(Power(Plus(d,Times(e,x)),Plus(m,p)),Power(Plus(Times(a,Power(d,CN1)),Times(c,Power(e,CN1),x)),p),$s("§pq")),x),And(FreeQ(List(a,b,c,d,e,m),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IntegerQ(p)))),
IIntegrate(2172,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Integrate(Times(Power(Plus(d,Times(e,x)),Plus(m,p)),Power(Plus(Times(a,Power(d,CN1)),Times(b,Power(e,CN1),x)),p),$s("§pq")),x),And(FreeQ(List(a,b,d,e,m),x),PolyQ($s("§pq"),x),EqQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),IntegerQ(p)))),
IIntegrate(2173,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),FracPart(p)),Power(Times(Power(Plus(d,Times(e,x)),FracPart(p)),Power(Plus(Times(a,Power(d,CN1)),Times(c,x,Power(e,CN1))),FracPart(p))),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Plus(m,p)),Power(Plus(Times(a,Power(d,CN1)),Times(c,Power(e,CN1),x)),p),$s("§pq")),x)),x),And(FreeQ(List(a,b,c,d,e,m,p),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),Not(IntegerQ(p)),Not(IGtQ(m,C0))))),
IIntegrate(2174,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(a,Times(b,Sqr(x))),FracPart(p)),Power(Times(Power(Plus(d,Times(e,x)),FracPart(p)),Power(Plus(Times(a,Power(d,CN1)),Times(b,x,Power(e,CN1))),FracPart(p))),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Plus(m,p)),Power(Plus(Times(a,Power(d,CN1)),Times(b,Power(e,CN1),x)),p),$s("§pq")),x)),x),And(FreeQ(List(a,b,d,e,m,p),x),PolyQ($s("§pq"),x),EqQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),Not(IntegerQ(p)),Not(IGtQ(m,C0))))),
IIntegrate(2175,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set($s("§qx"),PolynomialQuotient($s("§pq"),Plus(a,Times(b,x),Times(c,Sqr(x))),x)),Set($s("R"),Coeff(PolynomialRemainder($s("§pq"),Plus(a,Times(b,x),Times(c,Sqr(x))),x),x,C0)),Set($s("S"),Coeff(PolynomialRemainder($s("§pq"),Plus(a,Times(b,x),Times(c,Sqr(x))),x),x,C1))),Plus(Simp(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Plus(Times($s("R"),b),Times(CN1,C2,a,$s("S")),Times(Subtract(Times(C2,c,$s("R")),Times(b,$s("S"))),x)),Power(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x),Simp(Star(Power(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),ExpandToSum(Subtract(Subtract(Plus(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),Plus(d,Times(e,x)),$s("§qx")),Times($s("S"),Plus(Times(C2,a,e,m),Times(b,d,Plus(Times(C2,p),C3))))),Times($s("R"),Plus(Times(b,e,m),Times(C2,c,d,Plus(Times(C2,p),C3))))),Times(e,Subtract(Times(C2,c,$s("R")),Times(b,$s("S"))),Plus(m,Times(C2,p),C3),x)),x)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),LtQ(p,CN1),GtQ(m,C0),Or(IntegerQ(p),Not(IntegerQ(m)),Not(RationalQ(a,b,c,d,e))),Not(And(IGtQ(m,C0),RationalQ(a,b,c,d,e),Or(IntegerQ(p),ILtQ(Plus(p,C1D2),C0))))))),
IIntegrate(2176,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set($s("§qx"),PolynomialQuotient($s("§pq"),Plus(a,Times(b,Sqr(x))),x)),Set($s("R"),Coeff(PolynomialRemainder($s("§pq"),Plus(a,Times(b,Sqr(x))),x),x,C0)),Set($s("S"),Coeff(PolynomialRemainder($s("§pq"),Plus(a,Times(b,Sqr(x))),x),x,C1))),Plus(Simp(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Subtract(Times(a,$s("S")),Times(b,$s("R"),x)),Power(Times(C2,a,b,Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(C2,a,b,Plus(p,C1)),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),ExpandToSum(Plus(Times(C2,a,b,Plus(p,C1),Plus(d,Times(e,x)),$s("§qx")),Times(CN1,a,e,$s("S"),m),Times(b,d,$s("R"),Plus(Times(C2,p),C3)),Times(b,e,$s("R"),Plus(m,Times(C2,p),C3),x)),x)),x)),x))),And(FreeQ(List(a,b,d,e),x),PolyQ($s("§pq"),x),NeQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),LtQ(p,CN1),GtQ(m,C0),Not(And(IGtQ(m,C0),RationalQ(a,b,d,e),Or(IntegerQ(p),ILtQ(Plus(p,C1D2),C0))))))),
IIntegrate(2177,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set($s("§qx"),PolynomialQuotient(Times(Power(Plus(d,Times(e,x)),m),$s("§pq")),Plus(a,Times(b,x),Times(c,Sqr(x))),x)),Set($s("R"),Coeff(PolynomialRemainder(Times(Power(Plus(d,Times(e,x)),m),$s("§pq")),Plus(a,Times(b,x),Times(c,Sqr(x))),x),x,C0)),Set($s("S"),Coeff(PolynomialRemainder(Times(Power(Plus(d,Times(e,x)),m),$s("§pq")),Plus(a,Times(b,x),Times(c,Sqr(x))),x),x,C1))),Plus(Simp(Times(Plus(Times(b,$s("R")),Times(CN1,C2,a,$s("S")),Times(Subtract(Times(C2,c,$s("R")),Times(b,$s("S"))),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x),Simp(Star(Power(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),ExpandToSum(Subtract(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),$s("§qx"),Power(Power(Plus(d,Times(e,x)),m),CN1)),Times(Plus(Times(C2,p),C3),Subtract(Times(C2,c,$s("R")),Times(b,$s("S"))),Power(Power(Plus(d,Times(e,x)),m),CN1))),x)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),LtQ(p,CN1),ILtQ(m,C0)))),
IIntegrate(2178,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set($s("§qx"),PolynomialQuotient(Times(Power(Plus(d,Times(e,x)),m),$s("§pq")),Plus(a,Times(b,Sqr(x))),x)),Set($s("R"),Coeff(PolynomialRemainder(Times(Power(Plus(d,Times(e,x)),m),$s("§pq")),Plus(a,Times(b,Sqr(x))),x),x,C0)),Set($s("S"),Coeff(PolynomialRemainder(Times(Power(Plus(d,Times(e,x)),m),$s("§pq")),Plus(a,Times(b,Sqr(x))),x),x,C1))),Plus(Simp(Times(Subtract(Times(a,$s("S")),Times(b,$s("R"),x)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(C2,a,b,Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(C2,a,b,Plus(p,C1)),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),ExpandToSum(Plus(Times(C2,a,b,Plus(p,C1),$s("§qx"),Power(Power(Plus(d,Times(e,x)),m),CN1)),Times(b,$s("R"),Plus(Times(C2,p),C3),Power(Power(Plus(d,Times(e,x)),m),CN1))),x)),x)),x))),And(FreeQ(List(a,b,d,e),x),PolyQ($s("§pq"),x),NeQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),LtQ(p,CN1),ILtQ(m,C0)))),
IIntegrate(2179,Integrate(Times($p("§pq"),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set($s("§qx"),PolynomialQuotient($s("§pq"),Plus(a,Times(b,x),Times(c,Sqr(x))),x)),Set($s("R"),Coeff(PolynomialRemainder($s("§pq"),Plus(a,Times(b,x),Times(c,Sqr(x))),x),x,C0)),Set($s("S"),Coeff(PolynomialRemainder($s("§pq"),Plus(a,Times(b,x),Times(c,Sqr(x))),x),x,C1))),Plus(Simp(Times(Power(Plus(d,Times(e,x)),Plus(m,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Plus(Times($s("R"),Plus(Times(b,c,d),Times(CN1,Sqr(b),e),Times(C2,a,c,e))),Times(CN1,a,$s("S"),Subtract(Times(C2,c,d),Times(b,e))),Times(c,Subtract(Times($s("R"),Subtract(Times(C2,c,d),Times(b,e))),Times($s("S"),Subtract(Times(b,d),Times(C2,a,e)))),x)),Power(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e)))),CN1)),x),Simp(Star(Power(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e)))),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),ExpandToSum(Plus(Times(Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),$s("§qx")),Times($s("R"),Subtract(Subtract(Plus(Times(b,c,d,e,Plus(Times(C2,p),Negate(m),C2)),Times(Sqr(b),Sqr(e),Plus(p,m,C2))),Times(C2,Sqr(c),Sqr(d),Plus(Times(C2,p),C3))),Times(C2,a,c,Sqr(e),Plus(m,Times(C2,p),C3)))),Times(CN1,$s("S"),Subtract(Times(a,e,Plus(Times(b,e),Times(CN1,C2,c,d,m),Times(b,e,m))),Times(b,d,Subtract(Plus(Times(C3,c,d),Times(CN1,b,e),Times(C2,c,d,p)),Times(b,e,p))))),Times(c,e,Subtract(Times($s("S"),Subtract(Times(b,d),Times(C2,a,e))),Times($s("R"),Subtract(Times(C2,c,d),Times(b,e)))),Plus(m,Times(C2,p),C4),x)),x)),x)),x))),And(FreeQ(List(a,b,c,d,e,m),x),PolyQ($s("§pq"),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),LtQ(p,CN1),Not(And(IGtQ(m,C0),RationalQ(a,b,c,d,e),Or(IntegerQ(p),ILtQ(Plus(p,C1D2),C0))))))),
IIntegrate(2180,Integrate(Times($p("§pq"),Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set($s("§qx"),PolynomialQuotient($s("§pq"),Plus(a,Times(b,Sqr(x))),x)),Set($s("R"),Coeff(PolynomialRemainder($s("§pq"),Plus(a,Times(b,Sqr(x))),x),x,C0)),Set($s("S"),Coeff(PolynomialRemainder($s("§pq"),Plus(a,Times(b,Sqr(x))),x),x,C1))),Plus(Simp(Times(CN1,Power(Plus(d,Times(e,x)),Plus(m,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Plus(Times(a,Subtract(Times(e,$s("R")),Times(d,$s("S")))),Times(Plus(Times(b,d,$s("R")),Times(a,e,$s("S"))),x)),Power(Times(C2,a,Plus(p,C1),Plus(Times(b,Sqr(d)),Times(a,Sqr(e)))),CN1)),x),Simp(Star(Power(Times(C2,a,Plus(p,C1),Plus(Times(b,Sqr(d)),Times(a,Sqr(e)))),CN1),Integrate(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),ExpandToSum(Plus(Times(C2,a,Plus(p,C1),Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),$s("§qx")),Times(b,Sqr(d),$s("R"),Plus(Times(C2,p),C3)),Times(CN1,a,e,Subtract(Times(d,$s("S"),m),Times(e,$s("R"),Plus(m,Times(C2,p),C3)))),Times(e,Plus(Times(b,d,$s("R")),Times(a,e,$s("S"))),Plus(m,Times(C2,p),C4),x)),x)),x)),x))),And(FreeQ(List(a,b,d,e,m),x),PolyQ($s("§pq"),x),NeQ(Plus(Times(b,Sqr(d)),Times(a,Sqr(e))),C0),LtQ(p,CN1),Not(And(IGtQ(m,C0),RationalQ(a,b,d,e),Or(IntegerQ(p),ILtQ(Plus(p,C1D2),C0)))))))
  );
}
