package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules60 { 
  public static IAST RULES = List( 
IIntegrate(1201,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(g,Power(c,CN2)),Integrate(Times(Simp(Plus(Times(C2,c,e,f),Times(c,d,g),Times(CN1,b,e,g),Times(c,e,g,x)),x),Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(f,Times(g,x)),Subtract(n,C2))),x)),x),Simp(Star(Power(c,CN2),Integrate(Times(Simp(Plus(Times(Sqr(c),d,Sqr(f)),Times(CN1,C2,a,c,e,f,g),Times(CN1,a,c,d,Sqr(g)),Times(a,b,e,Sqr(g)),Times(Subtract(Plus(Times(Sqr(c),e,Sqr(f)),Times(C2,Sqr(c),d,f,g),Times(CN1,C2,b,c,e,f,g),Times(CN1,b,c,d,Sqr(g)),Times(Sqr(b),e,Sqr(g))),Times(a,c,e,Sqr(g))),x)),x),Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(f,Times(g,x)),Subtract(n,C2)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g),x),Not(IntegerQ(m)),Not(IntegerQ(n)),GtQ(m,C0),GtQ(n,C1)))),
IIntegrate(1202,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(e,g,Power(c,CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(f,Times(g,x)),Subtract(n,C1))),x)),x),Simp(Star(Power(c,CN1),Integrate(Times(Simp(Plus(Times(c,d,f),Times(CN1,a,e,g),Times(Subtract(Plus(Times(c,e,f),Times(c,d,g)),Times(b,e,g)),x)),x),Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(f,Times(g,x)),Subtract(n,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g),x),Not(IntegerQ(m)),Not(IntegerQ(n)),GtQ(m,C0),GtQ(n,C0)))),
IIntegrate(1203,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,g,Subtract(Times(e,f),Times(d,g)),Power(Plus(Times(c,Sqr(f)),Times(CN1,b,f,g),Times(a,Sqr(g))),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(f,Times(g,x)),n)),x)),x),Simp(Star(Power(Plus(Times(c,Sqr(f)),Times(CN1,b,f,g),Times(a,Sqr(g))),CN1),Integrate(Times(Simp(Plus(Times(c,d,f),Times(CN1,b,d,g),Times(a,e,g),Times(c,Subtract(Times(e,f),Times(d,g)),x)),x),Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(f,Times(g,x)),Plus(n,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g),x),Not(IntegerQ(m)),Not(IntegerQ(n)),GtQ(m,C0),LtQ(n,CN1)))),
IIntegrate(1204,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),CN1D2),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Power(Times(Sqrt(Plus(d,Times(e,x))),Sqrt(Plus(f,Times(g,x)))),CN1),Times(Power(Plus(d,Times(e,x)),Plus(m,C1D2)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x),x),And(FreeQ(List(a,b,c,d,e,f,g),x),IGtQ(Plus(m,C1D2),C0)))),
IIntegrate(1205,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1),x),x),And(FreeQ(List(a,b,c,d,e,f,g,m,n),x),Not(IntegerQ(m)),Not(IntegerQ(n))))),
IIntegrate(1206,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(f_,Times(g_DEFAULT,x_)),n_DEFAULT),Power(Plus(Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(x,p),Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),Power(Plus(b,Times(c,x)),p)),x),x),And(FreeQ(List(b,c,d,e,f,g),x),ILtQ(p,CN1),IntegersQ(m,n)))),
IIntegrate(1207,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Condition(Simp(Star(Power(Power(c,p),CN1),Integrate(ExpandIntegrand(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),Power(Plus(Times(C1D2,b),Times(CN1,C1D2,q),Times(c,x)),p),Power(Plus(Times(C1D2,b),Times(C1D2,q),Times(c,x)),p)),x),x)),x),Not($($s("§fractionalpowerfactorq"),q)))),And(FreeQ(List(a,b,c,d,e,f,g),x),ILtQ(p,CN1),IntegersQ(m,n),NiceSqrtQ(Subtract(Sqr(b),Times(C4,a,c)))))),
IIntegrate(1208,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Sqr(Plus(f_DEFAULT,Times(g_DEFAULT,x_))),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Simp(Times(Sqr(g),Power(Plus(d,Times(e,x)),Plus(m,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(c,e,Plus(m,Times(C2,p),C3)),CN1)),x),And(FreeQ(List(a,b,c,d,e,f,g,m,p),x),EqQ(Plus(Times(b,e,g,Plus(m,p,C2)),Times(C2,c,Subtract(Times(d,g,Plus(p,C1)),Times(e,f,Plus(m,Times(C2,p),C3))))),C0),EqQ(Plus(Times(e,Plus(Times(c,Sqr(f)),Times(CN1,b,f,g),Times(a,Sqr(g))),Plus(m,C1)),Times(Subtract(Times(C2,c,f),Times(b,g)),Subtract(Times(e,f),Times(d,g)),Plus(p,C1))),C0),NeQ(Plus(m,Times(C2,p),C3),C0)))),
IIntegrate(1209,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Integrate(Times(Power(Plus(f,Times(g,x)),n),Power(Plus(Times(a,d),Times(c,e,Power(x,C3))),p)),x),And(FreeQ(List(a,b,c,d,e,f,g,m,p),x),EqQ(Plus(Times(b,d),Times(a,e)),C0),EqQ(Plus(Times(c,d),Times(b,e)),C0),EqQ(m,p),ILtQ(p,CN1)))),
IIntegrate(1210,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Plus(d,Times(e,x)),FracPart(p)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),FracPart(p)),Power(Power(Plus(Times(a,d),Times(c,e,Power(x,C3))),FracPart(p)),CN1)),Integrate(Times(Power(Plus(f,Times(g,x)),n),Power(Plus(Times(a,d),Times(c,e,Power(x,C3))),p)),x)),x),And(FreeQ(List(a,b,c,d,e,f,g,m,p),x),EqQ(Plus(Times(b,d),Times(a,e)),C0),EqQ(Plus(Times(c,d),Times(b,e)),C0),EqQ(m,p)))),
IIntegrate(1211,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),QQ(-3L,2L))),x_Symbol),
    Condition(Plus(Simp(Times(CN2,Power(Subtract(Times(C2,c,d),Times(b,e)),Subtract(m,C2)),Power(Subtract(Times(c,Plus(Times(e,f),Times(d,g))),Times(b,e,g)),n),Plus(d,Times(e,x)),Power(Times(Power(c,Subtract(Plus(m,n),C1)),Power(e,Subtract(n,C1)),Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x))))),CN1)),x),Simp(Star(Power(Times(Power(c,Subtract(Plus(m,n),C1)),Power(e,Subtract(n,C2))),CN1),Integrate(Times(ExpandToSum(Times(Subtract(Times(Power(Subtract(Times(C2,c,d),Times(b,e)),Subtract(m,C1)),Power(Subtract(Times(c,Plus(Times(e,f),Times(d,g))),Times(b,e,g)),n)),Times(Power(c,Subtract(Plus(m,n),C1)),Power(e,n),Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(f,Times(g,x)),n))),Power(Subtract(Subtract(Times(c,d),Times(b,e)),Times(c,e,x)),CN1)),x),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1D2)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IGtQ(m,C0),IGtQ(n,C0)))),
IIntegrate(1212,Integrate(Times(Power(x_,n_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),QQ(-3L,2L))),x_Symbol),
    Condition(Subtract(Simp(Times(CN2,Power(Subtract(Times(C2,c,d),Times(b,e)),Subtract(m,C2)),Power(Subtract(Times(c,d),Times(b,e)),n),Plus(d,Times(e,x)),Power(Times(Power(c,Subtract(Plus(m,n),C1)),Power(e,Subtract(n,C1)),Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x))))),CN1)),x),Simp(Star(Times(Sqr(e),Power(Power(c,Subtract(Plus(m,n),C1)),CN1)),Integrate(Times(ExpandToSum(Times(Subtract(Times(Power(c,Subtract(Plus(m,n),C1)),Power(Plus(d,Times(e,x)),Subtract(m,C1))),Times(Power(Subtract(Times(c,d),Times(b,e)),n),Power(Subtract(Times(C2,c,d),Times(b,e)),Subtract(m,C1)),Power(Times(Power(e,n),Power(x,n)),CN1))),Power(Subtract(Subtract(Times(c,d),Times(b,e)),Times(c,e,x)),CN1)),x),Power(Times(Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))),Power(Power(x,n),CN1)),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IGtQ(m,C0),ILtQ(n,C0)))),
IIntegrate(1213,Integrate(Times(Power(x_,n_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Simp(Times(CN2,Power(Negate(d),n),Power(e,Plus(Times(C2,m),Negate(n),C3)),Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))),Power(Times(Power(Plus(Times(CN2,c,d),Times(b,e)),Plus(m,C2)),Plus(d,Times(e,x))),CN1)),x),Simp(Star(Power(e,Plus(Times(C2,m),Negate(n),C2)),Integrate(Times(ExpandToSum(Times(Subtract(Times(Power(Negate(d),n),Power(Plus(Times(CN2,c,d),Times(b,e)),Subtract(Negate(m),C1))),Times(Power(e,n),Power(x,n),Power(Plus(Times(CN1,c,d),Times(b,e),Times(c,e,x)),Subtract(Negate(m),C1)))),Power(Plus(d,Times(e,x)),CN1)),x),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1D2)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),ILtQ(m,C0),IGtQ(n,C0),EqQ(Plus(m,p),QQ(-3L,2L))))),
IIntegrate(1214,Integrate(Times(Power(x_,n_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Simp(Times(CN2,Power(Negate(d),n),Power(e,Plus(Times(C2,m),Negate(n),C3)),Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))),Power(Times(Power(Plus(Times(CN2,c,d),Times(b,e)),Plus(m,C2)),Plus(d,Times(e,x))),CN1)),x),Simp(Star(Power(e,Plus(Times(C2,m),C2)),Integrate(Times(ExpandToSum(Times(Subtract(Times(Power(Negate(d),n),Power(Plus(Times(CN2,c,d),Times(b,e)),Subtract(Negate(m),C1)),Power(Times(Power(e,n),Power(x,n)),CN1)),Power(Plus(Times(CN1,c,d),Times(b,e),Times(c,e,x)),Subtract(Negate(m),C1))),Power(Plus(d,Times(e,x)),CN1)),x),Power(Times(Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))),Power(Power(x,n),CN1)),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),ILtQ(m,C0),ILtQ(n,C0),EqQ(Plus(m,p),QQ(-3L,2L))))),
IIntegrate(1215,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,x_)),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Integrate(Times(Plus(Times(a,Power(d,CN1)),Times(c,x,Power(e,CN1))),Power(Plus(f,Times(g,x)),n),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C1))),x),And(FreeQ(List(a,b,c,d,e,f,g,n,p),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),GtQ(p,C0)))),
IIntegrate(1216,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_DEFAULT),Sqrt(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))))),x_Symbol),
    Condition(Integrate(Times(Power(Plus(f,Times(g,x)),n),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(m,C1D2)),Power(Power(Plus(Times(a,Power(d,CN1)),Times(c,x,Power(e,CN1))),m),CN1)),x),And(FreeQ(List(a,b,c,d,e,f,g,n),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),ILtQ(m,C0),IntegerQ(n)))),
IIntegrate(1217,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Plus(f_DEFAULT,Times(g_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Simp(Times(g,Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(c,Plus(m,Times(C2,p),C2)),CN1)),x),And(FreeQ(List(a,b,c,d,e,f,g,m,p),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),EqQ(Plus(Times(c,e,f,Plus(m,Times(C2,p),C2)),Times(g,Subtract(Times(c,d,m),Times(b,e,Plus(m,p,C1))))),C0)))),
IIntegrate(1218,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_DEFAULT),Plus(f_DEFAULT,Times(g_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(Times(g,Subtract(Times(c,d),Times(b,e))),Times(c,e,f)),Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(c,Plus(p,C1),Subtract(Times(C2,c,d),Times(b,e))),CN1)),x),Simp(Star(Times(e,Plus(Times(m,Plus(Times(g,Subtract(Times(c,d),Times(b,e))),Times(c,e,f))),Times(e,Plus(p,C1),Subtract(Times(C2,c,f),Times(b,g)))),Power(Times(c,Plus(p,C1),Subtract(Times(C2,c,d),Times(b,e))),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Subtract(m,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1))),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),LtQ(p,CN1),GtQ(m,C0)))),
IIntegrate(1219,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Plus(f_DEFAULT,Times(g_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(Times(g,Subtract(Times(c,d),Times(b,e))),Times(c,e,f)),Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(c,Plus(p,C1),Subtract(Times(C2,c,d),Times(b,e))),CN1)),x),Simp(Star(Times(e,Plus(Times(m,Plus(Times(g,Subtract(Times(c,d),Times(b,e))),Times(c,e,f))),Times(e,Plus(p,C1),Subtract(Times(C2,c,f),Times(b,g)))),Power(Times(c,Plus(p,C1),Subtract(Times(C2,c,d),Times(b,e))),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Simplify(Subtract(m,C1))),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Simplify(Plus(p,C1)))),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,m,p),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),SumSimplerQ(p,C1),SumSimplerQ(m,CN1),NeQ(p,CN1)))),
IIntegrate(1220,Integrate(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Plus(f_DEFAULT,Times(g_DEFAULT,x_)),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(Subtract(Times(d,g),Times(e,f)),Power(Plus(d,Times(e,x)),m),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Times(Subtract(Times(C2,c,d),Times(b,e)),Plus(m,p,C1)),CN1)),x),Simp(Star(Times(Plus(Times(m,Plus(Times(g,Subtract(Times(c,d),Times(b,e))),Times(c,e,f))),Times(e,Plus(p,C1),Subtract(Times(C2,c,f),Times(b,g)))),Power(Times(e,Subtract(Times(C2,c,d),Times(b,e)),Plus(m,p,C1)),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Plus(m,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,m,p),x),EqQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),Or(And(LtQ(m,CN1),Not(IGtQ(Plus(m,p,C1),C0))),And(LtQ(m,C0),LtQ(p,CN1)),EqQ(Plus(m,Times(C2,p),C2),C0)),NeQ(Plus(m,p,C1),C0))))
  );
}
