package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules231 { 
  public static IAST RULES = List( 
IIntegrate(4621,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_))),p_DEFAULT),Power($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Cos(Plus(e,Times(f,x))),x))),Simp(Star(Times(CN1,$s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Subtract(m,C1))),Power(Plus(b,Times(a,Power(Times($s("ff"),x),n))),p),Power(Power(Times($s("ff"),x),Times(n,p)),CN1)),x),x,Times(Cos(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),And(FreeQ(List(a,b,e,f),x),IntegerQ(Times(C1D2,Subtract(m,C1))),IntegerQ(n),IntegerQ(p)))),
IIntegrate(4622,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_))),p_DEFAULT),Power($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Cos(Plus(e,Times(f,x))),x))),Simp(Star(Power(Times(f,Power($s("ff"),m)),CN1),Subst(Integrate(Times(Power(Plus(CN1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Subtract(m,C1))),Power(Plus(a,Times(b,Power(Times(c,$s("ff"),x),n))),p),Power(Power(x,Plus(m,C1)),CN1)),x),x,Times(Sec(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),And(FreeQ(List(a,b,c,e,f,n,p),x),IntegerQ(Times(C1D2,Subtract(m,C1))),Or(GtQ(m,C0),EqQ(n,C2),EqQ(n,C4))))),
IIntegrate(4623,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_))),p_DEFAULT),Power(Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(a,Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n))),p),Power(Times(d,Sin(Plus(e,Times(f,x)))),m)),x),FreeQ(List(a,b,c,d,e,f,m,n,p),x))),
IIntegrate(4624,Integrate(Times(Power(Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),m_),Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_DEFAULT))),p_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(d,Times(n,p)),Integrate(Times(Power(Times(d,Cos(Plus(e,Times(f,x)))),Subtract(m,Times(n,p))),Power(Plus(b,Times(a,Power(Cos(Plus(e,Times(f,x))),n))),p)),x)),x),And(FreeQ(List(a,b,d,e,f,m,n,p),x),Not(IntegerQ(m)),IntegersQ(n,p)))),
IIntegrate(4625,Integrate(Times(Power(Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),m_),Power(Plus(a_,Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_))),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Times(d,Cos(Plus(e,Times(f,x)))),FracPart(m)),Power(Times(Sec(Plus(e,Times(f,x))),Power(d,CN1)),FracPart(m))),Integrate(Times(Power(Plus(a,Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n))),p),Power(Power(Times(Sec(Plus(e,Times(f,x))),Power(d,CN1)),m),CN1)),x)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),Not(IntegerQ(m))))),
IIntegrate(4626,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_))),p_DEFAULT),Power($($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(Module(list(Set($s("ff"),FreeFactors(Cos(Plus(e,Times(f,x))),x))),Simp(Star(Negate(Power(Times(f,Power($s("ff"),Subtract(Plus(m,Times(n,p)),C1))),CN1)),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Subtract(m,C1))),Power(Plus(b,Times(a,Power(Times($s("ff"),x),n))),p),Power(Power(x,Plus(m,Times(n,p))),CN1)),x),x,Times(Cos(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),And(FreeQ(List(a,b,e,f,n),x),IntegerQ(Times(C1D2,Subtract(m,C1))),IntegerQ(n),IntegerQ(p)))),
IIntegrate(4627,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_))),p_DEFAULT),Power($($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sec(Plus(e,Times(f,x))),x))),Simp(Star(Power(f,CN1),Subst(Integrate(Times(Power(Plus(CN1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Subtract(m,C1))),Power(Plus(a,Times(b,Power(Times(c,$s("ff"),x),n))),p),Power(x,CN1)),x),x,Times(Sec(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),And(FreeQ(List(a,b,c,e,f,n,p),x),IntegerQ(Times(C1D2,Subtract(m,C1))),Or(GtQ(m,C0),EqQ(n,C2),EqQ(n,C4),IGtQ(p,C0),IntegersQ(Times(C2,n),p))))),
IIntegrate(4628,Integrate(Times(Power(Times(b_DEFAULT,Sqr($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),p_DEFAULT),Power(Times(d_DEFAULT,$($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Tan(Plus(e,Times(f,x))),x))),Simp(Star(Times(b,$s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Times(d,$s("ff"),x),m),Power(Plus(b,Times(b,Sqr($s("ff")),Sqr(x))),Subtract(p,C1))),x),x,Times(Tan(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),FreeQ(List(b,d,e,f,m,p),x))),
IIntegrate(4629,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_))),p_DEFAULT),Power(Times(d_DEFAULT,$($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Tan(Plus(e,Times(f,x))),x))),Simp(Star(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Times(d,$s("ff"),x),m),Power(Plus(a,Times(b,Power(Plus(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,n)))),p),Power(Plus(C1,Times(Sqr($s("ff")),Sqr(x))),CN1)),x),x,Times(Tan(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),And(FreeQ(List(a,b,d,e,f,m,p),x),IntegerQ(Times(C1D2,n)),Or(IntegerQ(Times(C1D2,m)),EqQ(n,C2))))),
IIntegrate(4630,Integrate(Times(Power(Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_)),p_DEFAULT),Power(Times(d_DEFAULT,$($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(d,Power(Times(d,Tan(Plus(e,Times(f,x)))),Subtract(m,C1)),Power(Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n)),p),Power(Times(f,Subtract(Plus(Times(p,n),m),C1)),CN1)),x),Simp(Star(Times(Sqr(d),Subtract(m,C1),Power(Subtract(Plus(Times(p,n),m),C1),CN1)),Integrate(Times(Power(Times(d,Tan(Plus(e,Times(f,x)))),Subtract(m,C2)),Power(Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n)),p)),x)),x)),And(FreeQ(List(b,c,d,e,f,p,n),x),GtQ(m,C1),NeQ(Subtract(Plus(Times(p,n),m),C1),C0),IntegersQ(Times(C2,p,n),Times(C2,m))))),
IIntegrate(4631,Integrate(Times(Power(Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_)),p_DEFAULT),Power(Times(d_DEFAULT,$($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Times(d,Tan(Plus(e,Times(f,x)))),Plus(m,C1)),Power(Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n)),p),Power(Times(d,f,Plus(m,C1)),CN1)),x),Simp(Star(Times(Plus(Times(p,n),m,C1),Power(Times(Sqr(d),Plus(m,C1)),CN1)),Integrate(Times(Power(Times(d,Tan(Plus(e,Times(f,x)))),Plus(m,C2)),Power(Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n)),p)),x)),x)),And(FreeQ(List(b,c,d,e,f,p,n),x),LtQ(m,CN1),NeQ(Plus(Times(p,n),m,C1),C0),IntegersQ(Times(C2,p,n),Times(C2,m))))),
IIntegrate(4632,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_))),p_DEFAULT),Power(Times(d_DEFAULT,$($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(a,Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n))),p),Power(Times(d,Tan(Plus(e,Times(f,x)))),m)),x),FreeQ(List(a,b,c,d,e,f,m,n,p),x))),
IIntegrate(4633,Integrate(Times(Power(Times($($s("§cot"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),m_),Power(Plus(a_,Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_))),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Times(d,Cot(Plus(e,Times(f,x)))),FracPart(m)),Power(Times(Tan(Plus(e,Times(f,x))),Power(d,CN1)),FracPart(m))),Integrate(Times(Power(Plus(a,Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n))),p),Power(Power(Times(Tan(Plus(e,Times(f,x))),Power(d,CN1)),m),CN1)),x)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),Not(IntegerQ(m))))),
IIntegrate(4634,Integrate(Times(Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_),Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_))),p_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Tan(Plus(e,Times(f,x))),x))),Simp(Star(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Plus(C1,Times(Sqr($s("ff")),Sqr(x))),Subtract(Times(C1D2,m),C1)),Power(ExpandToSum(Plus(a,Times(b,Power(Plus(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,n)))),x),p)),x),x,Times(Tan(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),And(FreeQ(List(a,b,e,f,p),x),IntegerQ(Times(C1D2,m)),IntegerQ(Times(C1D2,n))))),
IIntegrate(4635,Integrate(Times(Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_))),p_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Star(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(ExpandToSum(Plus(b,Times(a,Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,n)))),x),p),Power(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,Times(n,p),C1))),CN1)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),And(FreeQ(List(a,b,e,f),x),IntegerQ(Times(C1D2,Subtract(m,C1))),IntegerQ(Times(C1D2,n)),IntegerQ(p)))),
IIntegrate(4636,Integrate(Times(Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_))),p_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Star(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Plus(a,Times(b,Power(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,n)),CN1))),p),Power(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,C1))),CN1)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1)))),x)),And(FreeQ(List(a,b,e,f,p),x),IntegerQ(Times(C1D2,Subtract(m,C1))),IntegerQ(Times(C1D2,n)),Not(IntegerQ(p))))),
IIntegrate(4637,Integrate(Times(Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_))),p_)),x_Symbol),
    Condition(Integrate(ExpandTrig(Times(Power($($s("§sec"),Plus(e,Times(f,x))),m),Power(Plus(a,Times(b,Power($($s("§sec"),Plus(e,Times(f,x))),n))),p)),x),x),And(FreeQ(List(a,b,e,f),x),IntegersQ(m,n,p)))),
IIntegrate(4638,Integrate(Times(Power(Times(d_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_))),p_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Times(d,Sec(Plus(e,Times(f,x)))),m),Power(Plus(a,Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n))),p)),x),FreeQ(List(a,b,c,d,e,f,m,n,p),x))),
IIntegrate(4639,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),m_),Power(Plus(a_,Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_))),p_)),x_Symbol),
    Condition(Simp(Star(Times(Power(Times(d,Csc(Plus(e,Times(f,x)))),FracPart(m)),Power(Times(Sin(Plus(e,Times(f,x))),Power(d,CN1)),FracPart(m))),Integrate(Times(Power(Plus(a,Times(b,Power(Times(c,Sec(Plus(e,Times(f,x)))),n))),p),Power(Power(Times(Sin(Plus(e,Times(f,x))),Power(d,CN1)),m),CN1)),x)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),Not(IntegerQ(m))))),
IIntegrate(4640,Integrate(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),Times(c_DEFAULT,Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),$p("n2",true)))),p_DEFAULT),x_Symbol),
    Condition(Simp(Star(Power(Times(Power(C4,p),Power(c,p)),CN1),Integrate(Power(Plus(b,Times(C2,c,Power(Sec(Plus(d,Times(e,x))),n))),Times(C2,p)),x)),x),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IntegerQ(p))))
  );
}
