package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules87 { 
  public static IAST RULES = List( 
IIntegrate(1741,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2"))))),x_Symbol),
    Condition(Plus(Simp(Times(c,Power(x,Plus(n,C1)),Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Power(Times(e,Plus(Times(n,Plus(q,C2)),C1)),CN1)),x),Simp(Star(Power(Times(e,Plus(Times(n,Plus(q,C2)),C1)),CN1),Integrate(Times(Power(Plus(d,Times(e,Power(x,n))),q),Subtract(Times(a,e,Plus(Times(n,Plus(q,C2)),C1)),Times(Subtract(Times(c,d,Plus(n,C1)),Times(b,e,Plus(Times(n,Plus(q,C2)),C1))),Power(x,n)))),x)),x)),And(FreeQ(List(a,b,c,d,e,n,q),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0)))),
IIntegrate(1742,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2"))))),x_Symbol),
    Condition(Plus(Simp(Times(c,Power(x,Plus(n,C1)),Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Power(Times(e,Plus(Times(n,Plus(q,C2)),C1)),CN1)),x),Simp(Star(Power(Times(e,Plus(Times(n,Plus(q,C2)),C1)),CN1),Integrate(Times(Power(Plus(d,Times(e,Power(x,n))),q),Subtract(Times(a,e,Plus(Times(n,Plus(q,C2)),C1)),Times(c,d,Plus(n,C1),Power(x,n)))),x)),x)),And(FreeQ(List(a,c,d,e,n,q),x),EqQ($s("n2"),Times(C2,n)),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0)))),
IIntegrate(1743,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(C2,d,e),C2))),Plus(Simp(Star(Times(Sqr(e),Power(Times(C2,c),CN1)),Integrate(Power(Plus(d,Times(q,Power(x,Times(C1D2,n))),Times(e,Power(x,n))),CN1),x)),x),Simp(Star(Times(Sqr(e),Power(Times(C2,c),CN1)),Integrate(Power(Plus(d,Times(CN1,q,Power(x,Times(C1D2,n))),Times(e,Power(x,n))),CN1),x)),x))),And(FreeQ(List(a,c,d,e),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IGtQ(Times(C1D2,n),C0),PosQ(Times(d,e))))),
IIntegrate(1744,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN2,d,e),C2))),Plus(Simp(Star(Times(d,Power(Times(C2,a),CN1)),Integrate(Times(Subtract(d,Times(q,Power(x,Times(C1D2,n)))),Power(Subtract(Subtract(d,Times(q,Power(x,Times(C1D2,n)))),Times(e,Power(x,n))),CN1)),x)),x),Simp(Star(Times(d,Power(Times(C2,a),CN1)),Integrate(Times(Plus(d,Times(q,Power(x,Times(C1D2,n)))),Power(Subtract(Plus(d,Times(q,Power(x,Times(C1D2,n)))),Times(e,Power(x,n))),CN1)),x)),x))),And(FreeQ(List(a,c,d,e),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IGtQ(Times(C1D2,n),C0),NegQ(Times(d,e))))),
IIntegrate(1745,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(a,Power(c,CN1)),C4))),Plus(Simp(Star(Power(Times(C2,CSqrt2,c,Power(q,C3)),CN1),Integrate(Times(Subtract(Times(CSqrt2,d,q),Times(Subtract(d,Times(e,Sqr(q))),Power(x,Times(C1D2,n)))),Power(Plus(Sqr(q),Times(CN1,CSqrt2,q,Power(x,Times(C1D2,n))),Power(x,n)),CN1)),x)),x),Simp(Star(Power(Times(C2,CSqrt2,c,Power(q,C3)),CN1),Integrate(Times(Plus(Times(CSqrt2,d,q),Times(Subtract(d,Times(e,Sqr(q))),Power(x,Times(C1D2,n)))),Power(Plus(Sqr(q),Times(CSqrt2,q,Power(x,Times(C1D2,n))),Power(x,n)),CN1)),x)),x))),And(FreeQ(List(a,c,d,e),x),EqQ($s("n2"),Times(C2,n)),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IGtQ(Times(C1D2,n),C0),PosQ(Times(a,c))))),
IIntegrate(1746,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,C3))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C6))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(c,Power(a,CN1)),C6))),Plus(Simp(Star(Power(Times(C3,a,Sqr(q)),CN1),Integrate(Times(Subtract(Times(Sqr(q),d),Times(e,x)),Power(Plus(C1,Times(Sqr(q),Sqr(x))),CN1)),x)),x),Simp(Star(Power(Times(C6,a,Sqr(q)),CN1),Integrate(Times(Subtract(Times(C2,Sqr(q),d),Times(Subtract(Times(CSqrt3,Power(q,C3),d),e),x)),Power(Plus(C1,Times(CN1,CSqrt3,q,x),Times(Sqr(q),Sqr(x))),CN1)),x)),x),Simp(Star(Power(Times(C6,a,Sqr(q)),CN1),Integrate(Times(Plus(Times(C2,Sqr(q),d),Times(Plus(Times(CSqrt3,Power(q,C3),d),e),x)),Power(Plus(C1,Times(CSqrt3,q,x),Times(Sqr(q),Sqr(x))),CN1)),x)),x))),And(FreeQ(List(a,c,d,e),x),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1747,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,a,Power(c,CN1)),C2))),Plus(Simp(Star(Times(C1D2,Plus(d,Times(e,q))),Integrate(Power(Plus(a,Times(c,q,Power(x,n))),CN1),x)),x),Simp(Star(Times(C1D2,Subtract(d,Times(e,q))),Integrate(Power(Subtract(a,Times(c,q,Power(x,n))),CN1),x)),x))),And(FreeQ(List(a,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NegQ(Times(a,c)),IntegerQ(n)))),
IIntegrate(1748,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(d,Integrate(Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1),x)),x),Simp(Star(e,Integrate(Times(Power(x,n),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),Or(PosQ(Times(a,c)),Not(IntegerQ(n)))))),
IIntegrate(1749,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Times(C2,d,Power(e,CN1)),Times(b,Power(c,CN1))),C2))),Plus(Simp(Star(Times(e,Power(Times(C2,c),CN1)),Integrate(Power(Simp(Plus(Times(d,Power(e,CN1)),Times(q,Power(x,Times(C1D2,n))),Power(x,n)),x),CN1),x)),x),Simp(Star(Times(e,Power(Times(C2,c),CN1)),Integrate(Power(Simp(Plus(Times(d,Power(e,CN1)),Times(CN1,q,Power(x,Times(C1D2,n))),Power(x,n)),x),CN1),x)),x))),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IGtQ(Times(C1D2,n),C0),Or(GtQ(Subtract(Times(C2,d,Power(e,CN1)),Times(b,Power(c,CN1))),C0),And(Not(LtQ(Subtract(Times(C2,d,Power(e,CN1)),Times(b,Power(c,CN1))),C0)),EqQ(d,Times(e,Rt(Times(a,Power(c,CN1)),C2)))))))),
IIntegrate(1750,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Plus(Simp(Star(Plus(Times(C1D2,e),Times(Subtract(Times(C2,c,d),Times(b,e)),Power(Times(C2,q),CN1))),Integrate(Power(Plus(Times(C1D2,b),Times(CN1,C1D2,q),Times(c,Power(x,n))),CN1),x)),x),Simp(Star(Subtract(Times(C1D2,e),Times(Subtract(Times(C2,c,d),Times(b,e)),Power(Times(C2,q),CN1))),Integrate(Power(Plus(Times(C1D2,b),Times(C1D2,q),Times(c,Power(x,n))),CN1),x)),x))),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IGtQ(Times(C1D2,n),C0),GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1751,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Times(CN2,d,Power(e,CN1)),Times(b,Power(c,CN1))),C2))),Plus(Simp(Star(Times(e,Power(Times(C2,c,q),CN1)),Integrate(Times(Subtract(q,Times(C2,Power(x,Times(C1D2,n)))),Power(Simp(Subtract(Plus(Times(d,Power(e,CN1)),Times(q,Power(x,Times(C1D2,n)))),Power(x,n)),x),CN1)),x)),x),Simp(Star(Times(e,Power(Times(C2,c,q),CN1)),Integrate(Times(Plus(q,Times(C2,Power(x,Times(C1D2,n)))),Power(Simp(Subtract(Subtract(Times(d,Power(e,CN1)),Times(q,Power(x,Times(C1D2,n)))),Power(x,n)),x),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IGtQ(Times(C1D2,n),C0),Not(GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0))))),
IIntegrate(1752,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Plus(Simp(Star(Plus(Times(C1D2,e),Times(Subtract(Times(C2,c,d),Times(b,e)),Power(Times(C2,q),CN1))),Integrate(Power(Plus(Times(C1D2,b),Times(CN1,C1D2,q),Times(c,Power(x,n))),CN1),x)),x),Simp(Star(Subtract(Times(C1D2,e),Times(Subtract(Times(C2,c,d),Times(b,e)),Power(Times(C2,q),CN1))),Integrate(Power(Plus(Times(C1D2,b),Times(C1D2,q),Times(c,Power(x,n))),CN1),x)),x))),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),Or(PosQ(Subtract(Sqr(b),Times(C4,a,c))),Not(IGtQ(Times(C1D2,n),C0)))))),
IIntegrate(1753,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(a,Power(c,CN1)),C2))),With(list(Set(r,Rt(Subtract(Times(C2,q),Times(b,Power(c,CN1))),C2))),Plus(Simp(Star(Power(Times(C2,c,q,r),CN1),Integrate(Times(Subtract(Times(d,r),Times(Subtract(d,Times(e,q)),Power(x,Times(C1D2,n)))),Power(Plus(q,Times(CN1,r,Power(x,Times(C1D2,n))),Power(x,n)),CN1)),x)),x),Simp(Star(Power(Times(C2,c,q,r),CN1),Integrate(Times(Plus(Times(d,r),Times(Subtract(d,Times(e,q)),Power(x,Times(C1D2,n)))),Power(Plus(q,Times(r,Power(x,Times(C1D2,n))),Power(x,n)),CN1)),x)),x)))),And(FreeQ(List(a,b,c,d,e),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IGtQ(Times(C1D2,n),C0),NegQ(Subtract(Sqr(b),Times(C4,a,c)))))),
IIntegrate(1754,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(d,Times(e,Power(x,n))),q),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1)),x),x),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IntegerQ(q)))),
IIntegrate(1755,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(d,Times(e,Power(x,n))),q),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x),x),And(FreeQ(List(a,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IntegerQ(q)))),
IIntegrate(1756,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Sqr(e),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Power(Plus(d,Times(e,Power(x,n))),q),x)),x),Simp(Star(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1),Integrate(Times(Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Subtract(Subtract(Times(c,d),Times(b,e)),Times(c,e,Power(x,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),Not(IntegerQ(q)),LtQ(q,CN1)))),
IIntegrate(1757,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Sqr(e),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Power(Plus(d,Times(e,Power(x,n))),q),x)),x),Simp(Star(Times(c,Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Subtract(d,Times(e,Power(x,n))),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),Not(IntegerQ(q)),LtQ(q,CN1)))),
IIntegrate(1758,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(r,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Simp(Star(Times(C2,c,Power(r,CN1)),Integrate(Times(Power(Plus(d,Times(e,Power(x,n))),q),Power(Plus(b,Negate(r),Times(C2,c,Power(x,n))),CN1)),x)),x),Simp(Star(Times(C2,c,Power(r,CN1)),Integrate(Times(Power(Plus(d,Times(e,Power(x,n))),q),Power(Plus(b,r,Times(C2,c,Power(x,n))),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,e,n,q),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),Not(IntegerQ(q))))),
IIntegrate(1759,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(With(list(Set(r,Rt(Times(CN1,a,c),C2))),Subtract(Simp(Star(Times(CN1,c,Power(Times(C2,r),CN1)),Integrate(Times(Power(Plus(d,Times(e,Power(x,n))),q),Power(Subtract(r,Times(c,Power(x,n))),CN1)),x)),x),Simp(Star(Times(c,Power(Times(C2,r),CN1)),Integrate(Times(Power(Plus(d,Times(e,Power(x,n))),q),Power(Plus(r,Times(c,Power(x,n))),CN1)),x)),x))),And(FreeQ(List(a,c,d,e,n,q),x),EqQ($s("n2"),Times(C2,n)),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),Not(IntegerQ(q))))),
IIntegrate(1760,Integrate(Times(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,x,Plus(Times(d,Sqr(b)),Times(CN1,a,b,e),Times(CN1,C2,a,c,d),Times(Subtract(Times(b,d),Times(C2,a,e)),c,Power(x,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Plus(p,C1)),Power(Times(a,n,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x),Simp(Star(Power(Times(a,n,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Integrate(Times(Simp(Plus(Times(Plus(Times(n,p),n,C1),d,Sqr(b)),Times(CN1,a,b,e),Times(CN1,C2,a,c,d,Plus(Times(C2,n,p),Times(C2,n),C1)),Times(Plus(Times(C2,n,p),Times(C3,n),C1),Subtract(Times(d,b),Times(C2,a,e)),c,Power(x,n))),x),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Plus(p,C1))),x)),x)),And(FreeQ(List(a,b,c,d,e,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),ILtQ(p,CN1))))
  );
}
