package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules75 { 
  public static IAST RULES = List( 
IIntegrate(1501,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Condition(Plus(Simp(Star(Times(Subtract(Times(C2,c,d),Times(e,Subtract(b,q))),Power(Times(C2,c),CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(e,Power(Times(C2,c),CN1)),Integrate(Times(Plus(b,Negate(q),Times(C2,c,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x)),x)),NeQ(Subtract(Times(C2,c,d),Times(e,Subtract(b,q))),C0))),And(FreeQ(List(a,b,c,d,e),x),GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(a,C0),GtQ(c,C0)))),
IIntegrate(1502,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,a,c),C2))),Condition(Subtract(Simp(Star(Times(Plus(Times(c,d),Times(e,q)),Power(c,CN1)),Integrate(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(e,Power(c,CN1)),Integrate(Times(Subtract(q,Times(c,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1D2)),x)),x)),NeQ(Plus(Times(c,d),Times(e,q)),C0))),And(FreeQ(List(a,c,d,e),x),LtQ(a,C0),GtQ(c,C0)))),
IIntegrate(1503,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Condition(Plus(Simp(Star(d,Integrate(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(e,Integrate(Times(Sqr(x),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x)),x)),Or(PosQ(Times(Plus(b,q),Power(a,CN1))),PosQ(Times(Subtract(b,q),Power(a,CN1)))))),And(FreeQ(List(a,b,c,d,e),x),GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1504,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Plus(Simp(Star(d,Integrate(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(e,Integrate(Times(Sqr(x),Power(Plus(a,Times(c,Power(x,C4))),CN1D2)),x)),x)),And(FreeQ(List(a,c,d,e),x),GtQ(Times(CN1,a,c),C0)))),
IIntegrate(1505,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Condition(Simp(Times(CN1,a,e,Rt(Times(CN1,Plus(b,q),Power(Times(C2,a),CN1)),C2),Sqrt(Plus(C1,Times(Plus(b,q),Sqr(x),Power(Times(C2,a),CN1)))),Sqrt(Plus(C1,Times(Subtract(b,q),Sqr(x),Power(Times(C2,a),CN1)))),Power(Times(c,Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1),EllipticE(ArcSin(Times(Rt(Times(CN1,Plus(b,q),Power(Times(C2,a),CN1)),C2),x)),Times(Subtract(b,q),Power(Plus(b,q),CN1)))),x),And(NegQ(Times(Plus(b,q),Power(a,CN1))),EqQ(Subtract(Times(C2,c,d),Times(e,Plus(b,q))),C0),Not(SimplerSqrtQ(Times(CN1,Subtract(b,q),Power(Times(C2,a),CN1)),Times(CN1,Plus(b,q),Power(Times(C2,a),CN1))))))),And(FreeQ(List(a,b,c,d,e),x),GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1506,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Condition(Plus(Simp(Star(Times(Subtract(Times(C2,c,d),Times(e,Plus(b,q))),Power(Times(C2,c),CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(e,Power(Times(C2,c),CN1)),Integrate(Times(Plus(b,q,Times(C2,c,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x)),x)),And(NegQ(Times(Plus(b,q),Power(a,CN1))),NeQ(Subtract(Times(C2,c,d),Times(e,Plus(b,q))),C0),Not(SimplerSqrtQ(Times(CN1,Subtract(b,q),Power(Times(C2,a),CN1)),Times(CN1,Plus(b,q),Power(Times(C2,a),CN1))))))),And(FreeQ(List(a,b,c,d,e),x),GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1507,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Condition(Simp(Times(CN1,a,e,Rt(Times(CN1,Subtract(b,q),Power(Times(C2,a),CN1)),C2),Sqrt(Plus(C1,Times(Subtract(b,q),Sqr(x),Power(Times(C2,a),CN1)))),Sqrt(Plus(C1,Times(Plus(b,q),Sqr(x),Power(Times(C2,a),CN1)))),Power(Times(c,Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1),EllipticE(ArcSin(Times(Rt(Times(CN1,Subtract(b,q),Power(Times(C2,a),CN1)),C2),x)),Times(Plus(b,q),Power(Subtract(b,q),CN1)))),x),And(NegQ(Times(Subtract(b,q),Power(a,CN1))),EqQ(Subtract(Times(C2,c,d),Times(e,Subtract(b,q))),C0)))),And(FreeQ(List(a,b,c,d,e),x),GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1508,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Condition(Plus(Simp(Star(Times(Subtract(Times(C2,c,d),Times(e,Subtract(b,q))),Power(Times(C2,c),CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(e,Power(Times(C2,c),CN1)),Integrate(Times(Plus(b,Negate(q),Times(C2,c,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x)),x)),And(NegQ(Times(Subtract(b,q),Power(a,CN1))),NeQ(Subtract(Times(C2,c,d),Times(e,Subtract(b,q))),C0)))),And(FreeQ(List(a,b,c,d,e),x),GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0)))),
IIntegrate(1509,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(c,Power(a,CN1)),C4))),Condition(Plus(Simp(Times(CN1,d,x,Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4)))),Power(Times(a,Plus(C1,Times(Sqr(q),Sqr(x)))),CN1)),x),Simp(Times(d,Plus(C1,Times(Sqr(q),Sqr(x))),Sqrt(Times(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Power(Times(a,Sqr(Plus(C1,Times(Sqr(q),Sqr(x))))),CN1))),Power(Times(q,Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1),EllipticE(Times(C2,ArcTan(Times(q,x))),Subtract(C1D2,Times(b,Sqr(q),Power(Times(C4,c),CN1))))),x)),EqQ(Plus(e,Times(d,Sqr(q))),C0))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1510,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(c,Power(a,CN1)),C4))),Condition(Plus(Simp(Times(CN1,d,x,Sqrt(Plus(a,Times(c,Power(x,C4)))),Power(Times(a,Plus(C1,Times(Sqr(q),Sqr(x)))),CN1)),x),Simp(Times(d,Plus(C1,Times(Sqr(q),Sqr(x))),Sqrt(Times(Plus(a,Times(c,Power(x,C4))),Power(Times(a,Sqr(Plus(C1,Times(Sqr(q),Sqr(x))))),CN1))),Power(Times(q,Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1),EllipticE(Times(C2,ArcTan(Times(q,x))),C1D2)),x)),EqQ(Plus(e,Times(d,Sqr(q))),C0))),And(FreeQ(List(a,c,d,e),x),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1511,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(c,Power(a,CN1)),C2))),Condition(Subtract(Simp(Star(Times(Plus(e,Times(d,q)),Power(q,CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(e,Power(q,CN1)),Integrate(Times(Subtract(C1,Times(q,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x)),x)),NeQ(Plus(e,Times(d,q)),C0))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1512,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(c,Power(a,CN1)),C2))),Condition(Subtract(Simp(Star(Times(Plus(e,Times(d,q)),Power(q,CN1)),Integrate(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(e,Power(q,CN1)),Integrate(Times(Subtract(C1,Times(q,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1D2)),x)),x)),NeQ(Plus(e,Times(d,q)),C0))),And(FreeQ(List(a,c,d,e),x),PosQ(Times(c,Power(a,CN1)))))),
IIntegrate(1513,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,c,Power(a,CN1)),C2))),Plus(Simp(Star(Times(Subtract(Times(d,q),e),Power(q,CN1)),Integrate(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(e,Power(q,CN1)),Integrate(Times(Plus(C1,Times(q,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1D2)),x)),x))),And(FreeQ(List(a,c,d,e),x),NegQ(Times(c,Power(a,CN1))),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0)))),
IIntegrate(1514,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Simp(Star(Times(Sqrt(Plus(C1,Times(C2,c,Sqr(x),Power(Subtract(b,q),CN1)))),Sqrt(Plus(C1,Times(C2,c,Sqr(x),Power(Plus(b,q),CN1)))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),Integrate(Times(Plus(d,Times(e,Sqr(x))),Power(Times(Sqrt(Plus(C1,Times(C2,c,Sqr(x),Power(Subtract(b,q),CN1)))),Sqrt(Plus(C1,Times(C2,c,Sqr(x),Power(Plus(b,q),CN1))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NegQ(Times(c,Power(a,CN1)))))),
IIntegrate(1515,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Plus(d,Times(e,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p)),x),x),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0)))),
IIntegrate(1516,Integrate(Times(Plus(d_,Times(e_DEFAULT,Sqr(x_))),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Plus(d,Times(e,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),p)),x),x),And(FreeQ(List(a,c,d,e),x),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0)))),
IIntegrate(1517,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(With(list(Set(f,Coeff(PolynomialRemainder(Power(Plus(d,Times(e,Sqr(x))),q),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),x,C0)),Set(g,Coeff(PolynomialRemainder(Power(Plus(d,Times(e,Sqr(x))),q),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),x,C2))),Plus(Simp(Times(x,Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Subtract(Subtract(Times(a,b,g),Times(f,Subtract(Sqr(b),Times(C2,a,c)))),Times(c,Subtract(Times(b,f),Times(C2,a,g)),Sqr(x))),Power(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x),Simp(Star(Power(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),ExpandToSum(Plus(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),PolynomialQuotient(Power(Plus(d,Times(e,Sqr(x))),q),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x)),Times(Sqr(b),f,Plus(Times(C2,p),C3)),Times(CN1,C2,a,c,f,Plus(Times(C4,p),C5)),Times(CN1,a,b,g),Times(c,Plus(Times(C4,p),C7),Subtract(Times(b,f),Times(C2,a,g)),Sqr(x))),x)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IGtQ(q,C1),LtQ(p,CN1)))),
IIntegrate(1518,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(Power(e,q),Power(x,Subtract(Times(C2,q),C3)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Power(Times(c,Plus(Times(C4,p),Times(C2,q),C1)),CN1)),x),Simp(Star(Power(Times(c,Plus(Times(C4,p),Times(C2,q),C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p),ExpandToSum(Subtract(Subtract(Subtract(Times(c,Plus(Times(C4,p),Times(C2,q),C1),Power(Plus(d,Times(e,Sqr(x))),q)),Times(a,Subtract(Times(C2,q),C3),Power(e,q),Power(x,Subtract(Times(C2,q),C4)))),Times(b,Subtract(Plus(Times(C2,p),Times(C2,q)),C1),Power(e,q),Power(x,Subtract(Times(C2,q),C2)))),Times(c,Plus(Times(C4,p),Times(C2,q),C1),Power(e,q),Power(x,Times(C2,q)))),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,p),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IGtQ(q,C1)))),
IIntegrate(1519,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(Power(e,q),Power(x,Subtract(Times(C2,q),C3)),Power(Plus(a,Times(c,Power(x,C4))),Plus(p,C1)),Power(Times(c,Plus(Times(C4,p),Times(C2,q),C1)),CN1)),x),Simp(Star(Power(Times(c,Plus(Times(C4,p),Times(C2,q),C1)),CN1),Integrate(Times(Power(Plus(a,Times(c,Power(x,C4))),p),ExpandToSum(Subtract(Subtract(Times(c,Plus(Times(C4,p),Times(C2,q),C1),Power(Plus(d,Times(e,Sqr(x))),q)),Times(a,Subtract(Times(C2,q),C3),Power(e,q),Power(x,Subtract(Times(C2,q),C4)))),Times(c,Plus(Times(C4,p),Times(C2,q),C1),Power(e,q),Power(x,Times(C2,q)))),x)),x)),x)),And(FreeQ(List(a,c,d,e,p),x),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IGtQ(q,C1)))),
IIntegrate(1520,Integrate(Times(Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Sqrt(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))))),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,c,Power(e,CN2)),Integrate(Times(Subtract(d,Times(e,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x)),x),Integrate(Times(Plus(Times(C2,a),Times(b,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))))
  );
}
