package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules24 { 
  public static IAST RULES = List( 
IIntegrate(481,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(d,Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Times(b,Subtract(n,C1)),CN1)),x),Simp(Star(Power(b,CN1),Integrate(Times(Power(Plus(c,Times(d,x)),Subtract(n,C2)),Simp(Plus(Times(b,Sqr(c)),Times(CN1,a,Sqr(d)),Times(C2,b,c,d,x)),x),Power(Plus(a,Times(b,Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d),x),GtQ(n,C1)))),
IIntegrate(482,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(d,Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Times(Plus(n,C1),Plus(Times(b,Sqr(c)),Times(a,Sqr(d)))),CN1)),x),Simp(Star(Times(b,Power(Plus(Times(b,Sqr(c)),Times(a,Sqr(d))),CN1)),Integrate(Times(Power(Plus(c,Times(d,x)),Plus(n,C1)),Subtract(c,Times(d,x)),Power(Plus(a,Times(b,Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,n),x),LtQ(n,CN1)))),
IIntegrate(483,Integrate(Times(Sqrt(Plus(c_,Times(d_DEFAULT,x_))),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Simp(Star(Times(C2,d),Subst(Integrate(Times(Sqr(x),Power(Plus(Times(b,Sqr(c)),Times(a,Sqr(d)),Times(CN1,C2,b,c,Sqr(x)),Times(b,Power(x,C4))),CN1)),x),x,Sqrt(Plus(c,Times(d,x))))),x),FreeQ(List(a,b,c,d),x))),
IIntegrate(484,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),CN1D2),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Simp(Star(Times(C2,d),Subst(Integrate(Power(Plus(Times(b,Sqr(c)),Times(a,Sqr(d)),Times(CN1,C2,b,c,Sqr(x)),Times(b,Power(x,C4))),CN1),x),x,Sqrt(Plus(c,Times(d,x))))),x),FreeQ(List(a,b,c,d),x))),
IIntegrate(485,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Power(Plus(c,Times(d,x)),n),Power(Plus(a,Times(b,Sqr(x))),CN1),x),x),And(FreeQ(List(a,b,c,d,n),x),Not(IntegerQ(Times(C2,n)))))),
IIntegrate(486,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(c,Times(d,x)),Plus(n,C1)),Subtract(Times(a,d),Times(b,c,x)),Power(Plus(a,Times(b,Sqr(x))),p),Power(Times(Plus(n,C1),Plus(Times(b,Sqr(c)),Times(a,Sqr(d)))),CN1)),x),Simp(Star(Times(C2,a,b,p,Power(Times(Plus(n,C1),Plus(Times(b,Sqr(c)),Times(a,Sqr(d)))),CN1)),Integrate(Times(Power(Plus(c,Times(d,x)),Plus(n,C2)),Power(Plus(a,Times(b,Sqr(x))),Subtract(p,C1))),x)),x)),And(FreeQ(List(a,b,c,d),x),EqQ(Plus(n,Times(C2,p),C2),C0),GtQ(p,C0)))),
IIntegrate(487,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(Power(Plus(c,Times(d,x)),Subtract(n,C1)),Subtract(Times(a,d),Times(b,c,x)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(C2,a,b,Plus(p,C1)),CN1)),x),Simp(Star(Times(Plus(Times(C2,p),C3),Plus(Times(b,Sqr(c)),Times(a,Sqr(d))),Power(Times(C2,a,b,Plus(p,C1)),CN1)),Integrate(Times(Power(Plus(c,Times(d,x)),Subtract(n,C2)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1))),x)),x)),And(FreeQ(List(a,b,c,d),x),EqQ(Plus(n,Times(C2,p),C2),C0),LtQ(p,CN1)))),
IIntegrate(488,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Negate(Subst(Integrate(Power(Subtract(Plus(Times(b,Sqr(c)),Times(a,Sqr(d))),Sqr(x)),CN1),x),x,Times(Subtract(Times(a,d),Times(b,c,x)),Power(Plus(a,Times(b,Sqr(x))),CN1D2)))),FreeQ(List(a,b,c,d),x))),
IIntegrate(489,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,a,b),C2))),Simp(Times(Subtract(q,Times(b,x)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),p),Power(Times(Plus(n,C1),Plus(Times(b,c),Times(d,q)),Power(Times(Plus(Times(b,c),Times(d,q)),Plus(q,Times(b,x)),Power(Times(Subtract(Times(b,c),Times(d,q)),Plus(Negate(q),Times(b,x))),CN1)),p)),CN1),Hypergeometric2F1(Plus(n,C1),Negate(p),Plus(n,C2),Times(C2,b,q,Plus(c,Times(d,x)),Power(Times(Subtract(Times(b,c),Times(d,q)),Subtract(q,Times(b,x))),CN1)))),x)),And(FreeQ(List(a,b,c,d,n,p),x),EqQ(Plus(n,Times(C2,p),C2),C0)))),
IIntegrate(490,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Simp(Times(CN1,x,Power(Plus(c,Times(d,x)),n),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(C2,a,Plus(p,C1)),CN1)),x),Simp(Star(Times(c,n,Power(Times(C2,a,Plus(p,C1)),CN1)),Integrate(Times(Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1))),x)),x)),And(FreeQ(List(a,b,c,d,n,p),x),EqQ(Plus(n,Times(C2,p),C3),C0),LtQ(p,CN1)))),
IIntegrate(491,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(d,Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(Plus(n,C1),Plus(Times(b,Sqr(c)),Times(a,Sqr(d)))),CN1)),x),Simp(Star(Times(b,c,Power(Plus(Times(b,Sqr(c)),Times(a,Sqr(d))),CN1)),Integrate(Times(Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),p)),x)),x)),And(FreeQ(List(a,b,c,d,n,p),x),EqQ(Plus(n,Times(C2,p),C3),C0)))),
IIntegrate(492,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),p),Power(Times(d,Plus(n,C1)),CN1)),x),Simp(Star(Times(C2,b,p,Power(Times(d,Plus(n,C1)),CN1)),Integrate(Times(x,Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),Subtract(p,C1))),x)),x)),And(FreeQ(List(a,b,c,d,n),x),GtQ(p,C0),Or(IntegerQ(p),LtQ(n,CN1)),NeQ(n,CN1),Not(ILtQ(Plus(n,Times(C2,p),C1),C0)),IntQuadraticQ(a,C0,b,c,d,n,p,x)))),
IIntegrate(493,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),p),Power(Times(d,Plus(n,Times(C2,p),C1)),CN1)),x),Simp(Star(Times(C2,p,Power(Times(d,Plus(n,Times(C2,p),C1)),CN1)),Integrate(Times(Power(Plus(c,Times(d,x)),n),Power(Plus(a,Times(b,Sqr(x))),Subtract(p,C1)),Subtract(Times(a,d),Times(b,c,x))),x)),x)),And(FreeQ(List(a,b,c,d,n),x),GtQ(p,C0),NeQ(Plus(n,Times(C2,p),C1),C0),Or(Not(RationalQ(n)),LtQ(n,C1)),Not(ILtQ(Plus(n,Times(C2,p)),C0)),IntQuadraticQ(a,C0,b,c,d,n,p,x)))),
IIntegrate(494,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,x,Power(Plus(c,Times(d,x)),n),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(C2,a,Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(C2,a,Plus(p,C1)),CN1),Integrate(Times(Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Plus(Times(c,Plus(Times(C2,p),C3)),Times(d,Plus(n,Times(C2,p),C3),x))),x)),x)),And(FreeQ(List(a,b,c,d),x),LtQ(p,CN1),GtQ(n,C0),Or(LtQ(n,C1),And(ILtQ(Plus(n,Times(C2,p),C3),C0),NeQ(n,C2))),IntQuadraticQ(a,C0,b,c,d,n,p,x)))),
IIntegrate(495,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Simp(Times(Subtract(Times(a,d),Times(b,c,x)),Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(C2,a,b,Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(C2,a,b,Plus(p,C1)),CN1),Integrate(Times(Power(Plus(c,Times(d,x)),Subtract(n,C2)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Simp(Subtract(Subtract(Times(a,Sqr(d),Subtract(n,C1)),Times(b,Sqr(c),Plus(Times(C2,p),C3))),Times(b,c,d,Plus(n,Times(C2,p),C2),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d),x),LtQ(p,CN1),GtQ(n,C1),IntQuadraticQ(a,C0,b,c,d,n,p,x)))),
IIntegrate(496,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Plus(Times(a,d),Times(b,c,x)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(C2,a,Plus(p,C1),Plus(Times(b,Sqr(c)),Times(a,Sqr(d)))),CN1)),x),Simp(Star(Power(Times(C2,a,Plus(p,C1),Plus(Times(b,Sqr(c)),Times(a,Sqr(d)))),CN1),Integrate(Times(Power(Plus(c,Times(d,x)),n),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Simp(Plus(Times(b,Sqr(c),Plus(Times(C2,p),C3)),Times(a,Sqr(d),Plus(n,Times(C2,p),C3)),Times(b,c,d,Plus(n,Times(C2,p),C4),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,n),x),LtQ(p,CN1),IntQuadraticQ(a,C0,b,c,d,n,p,x)))),
IIntegrate(497,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(d,Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(b,Plus(n,Times(C2,p),C1)),CN1)),x),Simp(Star(Power(Times(b,Plus(n,Times(C2,p),C1)),CN1),Integrate(Times(Power(Plus(c,Times(d,x)),Subtract(n,C2)),Power(Plus(a,Times(b,Sqr(x))),p),Simp(Plus(Times(b,Sqr(c),Plus(n,Times(C2,p),C1)),Times(CN1,a,Sqr(d),Subtract(n,C1)),Times(C2,b,c,d,Plus(n,p),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,n,p),x),If(RationalQ(n),GtQ(n,C1),SumSimplerQ(n,CN2)),NeQ(Plus(n,Times(C2,p),C1),C0),IntQuadraticQ(a,C0,b,c,d,n,p,x)))),
IIntegrate(498,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Simp(Times(d,Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Times(Plus(n,C1),Plus(Times(b,Sqr(c)),Times(a,Sqr(d)))),CN1)),x),Simp(Star(Times(b,Power(Times(Plus(n,C1),Plus(Times(b,Sqr(c)),Times(a,Sqr(d)))),CN1)),Integrate(Times(Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(a,Times(b,Sqr(x))),p),Subtract(Times(c,Plus(n,C1)),Times(d,Plus(n,Times(C2,p),C3),x))),x)),x)),And(FreeQ(List(a,b,c,d,n,p),x),NeQ(n,CN1),Or(And(LtQ(n,CN1),IntQuadraticQ(a,C0,b,c,d,n,p,x)),And(SumSimplerQ(n,C1),IntegerQ(p)),ILtQ(Simplify(Plus(n,Times(C2,p),C3)),C0))))),
IIntegrate(499,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D4)),x_Symbol),
    Condition(With(list(Set(q,Rt(Negate(a),C4))),Subtract(Simp(Times(Power(Times(C2,d,q),CN1),ArcTan(Times(c,q,Power(Plus(a,Times(b,Sqr(x))),C1D4),Power(Subtract(Times(Sqr(q),Plus(c,Times(d,x))),Times(c,Sqrt(Plus(a,Times(b,Sqr(x)))))),CN1)))),x),Simp(Times(Power(Times(C2,d,q),CN1),ArcTanh(Times(c,q,Power(Plus(a,Times(b,Sqr(x))),C1D4),Power(Plus(Times(Sqr(q),Plus(c,Times(d,x))),Times(c,Sqrt(Plus(a,Times(b,Sqr(x)))))),CN1)))),x))),And(FreeQ(List(a,b,c,d),x),EqQ(Plus(Times(b,Sqr(c)),Times(C2,a,Sqr(d))),C0),NegQ(a)))),
IIntegrate(500,Integrate(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D4)),x_Symbol),
    Condition(Simp(Star(Times(Power(Subtract(Negate(a),Times(b,Sqr(x))),C1D4),Power(Plus(a,Times(b,Sqr(x))),CN1D4)),Integrate(Power(Times(Plus(c,Times(d,x)),Power(Subtract(Negate(a),Times(b,Sqr(x))),C1D4)),CN1),x)),x),And(FreeQ(List(a,b,c,d),x),EqQ(Plus(Times(b,Sqr(c)),Times(C2,a,Sqr(d))),C0),PosQ(a))))
  );
}
