package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules226 { 
  public static IAST RULES = List( 
IIntegrate(4521,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),A_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,BSymbol,Sqr(d),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),Subtract(n,C2)),Power(Times(b,f,Plus(m,n)),CN1)),x),Simp(Star(Times(Sqr(d),Power(Times(b,Plus(m,n)),CN1)),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),Subtract(n,C2)),Simp(Plus(Times(a,BSymbol,Subtract(n,C2)),Times(BSymbol,b,Subtract(Plus(m,n),C1),Csc(Plus(e,Times(f,x)))),Times(Subtract(Times(ASymbol,b,Plus(m,n)),Times(a,BSymbol,Subtract(n,C1))),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x)),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,m),x),NeQ(Subtract(Times(ASymbol,b),Times(a,BSymbol)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),GtQ(n,C1),NeQ(Plus(m,n),C0),Not(IGtQ(m,C1))))),
IIntegrate(4522,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),A_)),x_Symbol),
    Condition(Plus(Simp(Times(ASymbol,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(a,f,n),CN1)),x),Simp(Star(Power(Times(a,d,n),CN1),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),Plus(n,C1)),Simp(Plus(Times(a,BSymbol,n),Times(CN1,ASymbol,b,Plus(m,n,C1)),Times(ASymbol,a,Plus(n,C1),Csc(Plus(e,Times(f,x)))),Times(ASymbol,b,Plus(m,n,C2),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x)),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,m),x),NeQ(Subtract(Times(ASymbol,b),Times(a,BSymbol)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),LeQ(n,CN1)))),
IIntegrate(4523,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),CN1D2),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1D2),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),A_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(ASymbol,Power(a,CN1)),Integrate(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Power(Times(d,Csc(Plus(e,Times(f,x)))),CN1D2)),x)),x),Simp(Star(Times(Subtract(Times(ASymbol,b),Times(a,BSymbol)),Power(Times(a,d),CN1)),Integrate(Times(Sqrt(Times(d,Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(ASymbol,b),Times(a,BSymbol)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4524,Integrate(Times(Sqrt(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1D2),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),A_)),x_Symbol),
    Condition(Plus(Simp(Star(ASymbol,Integrate(Times(Sqrt(Times(d,Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x),Simp(Star(Times(BSymbol,Power(d,CN1)),Integrate(Times(Power(Times(d,Csc(Plus(e,Times(f,x)))),QQ(3L,2L)),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(ASymbol,b),Times(a,BSymbol)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4525,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),CN1D2),Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),A_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(BSymbol,Power(d,CN1)),Integrate(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Sqrt(Times(d,Csc(Plus(e,Times(f,x)))))),x)),x),Simp(Star(ASymbol,Integrate(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Power(Times(d,Csc(Plus(e,Times(f,x)))),CN1D2)),x)),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(ASymbol,b),Times(a,BSymbol)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4526,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),A_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(ASymbol,Power(a,CN1)),Integrate(Power(Times(d,Csc(Plus(e,Times(f,x)))),n),x)),x),Simp(Star(Times(Subtract(Times(ASymbol,b),Times(a,BSymbol)),Power(Times(a,d),CN1)),Integrate(Times(Power(Times(d,Csc(Plus(e,Times(f,x)))),Plus(n,C1)),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1)),x)),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,n),x),NeQ(Subtract(Times(ASymbol,b),Times(a,BSymbol)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4527,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_DEFAULT),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),A_)),x_Symbol),
    Condition(Unintegrable(Times(Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Plus(ASymbol,Times(BSymbol,Csc(Plus(e,Times(f,x)))))),x),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,m,n),x),NeQ(Subtract(Times(ASymbol,b),Times(a,BSymbol)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4528,Integrate(Times(Power(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT)),p_DEFAULT),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_DEFAULT),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_),n_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(Times(CN1,a,c),m),Integrate(Times(Power(Cos(Plus(e,Times(f,x))),Times(C2,m)),Power(Plus(d,Times(c,Sin(Plus(e,Times(f,x))))),Subtract(n,m)),Power(Plus(BSymbol,Times(ASymbol,Sin(Plus(e,Times(f,x))))),p),Power(Power(Sin(Plus(e,Times(f,x))),Plus(m,n,p)),CN1)),x)),x),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol,n,p),x),EqQ(Plus(Times(b,c),Times(a,d)),C0),EqQ(Subtract(Sqr(a),Sqr(b)),C0),IntegersQ(m,n,p)))),
IIntegrate(4529,Integrate(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(b,CN2),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(b,BSymbol),Times(CN1,a,CSymbol),Times(b,CSymbol,Csc(Plus(e,Times(f,x))))),x)),x)),x),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,CSymbol,m),x),EqQ(Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),CSymbol)),C0)))),
IIntegrate(4530,Integrate(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Times(CSymbol,Power(b,CN2)),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Plus(Negate(a),Times(b,Csc(Plus(e,Times(f,x))))),x)),x)),x),And(FreeQ(List(a,b,e,f,ASymbol,CSymbol,m),x),EqQ(Plus(Times(ASymbol,Sqr(b)),Times(Sqr(a),CSymbol)),C0)))),
IIntegrate(4531,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),m_DEFAULT),Plus(Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT),A_)),x_Symbol),
    Condition(Simp(Times(ASymbol,Cot(Plus(e,Times(f,x))),Power(Times(b,Csc(Plus(e,Times(f,x)))),m),Power(Times(f,m),CN1)),x),And(FreeQ(List(b,e,f,ASymbol,CSymbol,m),x),EqQ(Plus(Times(CSymbol,m),Times(ASymbol,Plus(m,C1))),C0)))),
IIntegrate(4532,Integrate(Times(Power($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT),Plus(Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT),A_)),x_Symbol),
    Condition(Integrate(Times(Plus(CSymbol,Times(ASymbol,Sqr(Sin(Plus(e,Times(f,x)))))),Power(Power(Sin(Plus(e,Times(f,x))),Plus(m,C2)),CN1)),x),And(FreeQ(List(e,f,ASymbol,CSymbol),x),NeQ(Plus(Times(CSymbol,m),Times(ASymbol,Plus(m,C1))),C0),ILtQ(Times(C1D2,Plus(m,C1)),C0)))),
IIntegrate(4533,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),m_DEFAULT),Plus(Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT),A_)),x_Symbol),
    Condition(Plus(Simp(Times(ASymbol,Cot(Plus(e,Times(f,x))),Power(Times(b,Csc(Plus(e,Times(f,x)))),m),Power(Times(f,m),CN1)),x),Simp(Star(Times(Plus(Times(CSymbol,m),Times(ASymbol,Plus(m,C1))),Power(Times(Sqr(b),m),CN1)),Integrate(Power(Times(b,Csc(Plus(e,Times(f,x)))),Plus(m,C2)),x)),x)),And(FreeQ(List(b,e,f,ASymbol,CSymbol),x),NeQ(Plus(Times(CSymbol,m),Times(ASymbol,Plus(m,C1))),C0),LeQ(m,CN1)))),
IIntegrate(4534,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),m_DEFAULT),Plus(Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT),A_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,CSymbol,Cot(Plus(e,Times(f,x))),Power(Times(b,Csc(Plus(e,Times(f,x)))),m),Power(Times(f,Plus(m,C1)),CN1)),x),Simp(Star(Times(Plus(Times(CSymbol,m),Times(ASymbol,Plus(m,C1))),Power(Plus(m,C1),CN1)),Integrate(Power(Times(b,Csc(Plus(e,Times(f,x)))),m),x)),x)),And(FreeQ(List(b,e,f,ASymbol,CSymbol,m),x),NeQ(Plus(Times(CSymbol,m),Times(ASymbol,Plus(m,C1))),C0),Not(LeQ(m,CN1))))),
IIntegrate(4535,Integrate(Times(Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),m_DEFAULT),Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT))),x_Symbol),
    Condition(Plus(Simp(Star(Times(BSymbol,Power(b,CN1)),Integrate(Power(Times(b,Csc(Plus(e,Times(f,x)))),Plus(m,C1)),x)),x),Integrate(Times(Power(Times(b,Csc(Plus(e,Times(f,x)))),m),Plus(ASymbol,Times(CSymbol,Sqr(Csc(Plus(e,Times(f,x))))))),x)),FreeQ(List(b,e,f,ASymbol,BSymbol,CSymbol,m),x))),
IIntegrate(4536,Integrate(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,CSymbol,Csc(Plus(e,Times(f,x))),Cot(Plus(e,Times(f,x))),Power(Times(C2,f),CN1)),x),Simp(Star(C1D2,Integrate(Simp(Plus(Times(C2,ASymbol,a),Times(Plus(Times(C2,BSymbol,a),Times(b,Plus(Times(C2,ASymbol),CSymbol))),Csc(Plus(e,Times(f,x)))),Times(C2,Plus(Times(a,CSymbol),Times(BSymbol,b)),Sqr(Csc(Plus(e,Times(f,x)))))),x),x)),x)),FreeQ(List(a,b,e,f,ASymbol,BSymbol,CSymbol),x))),
IIntegrate(4537,Integrate(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,CSymbol,Csc(Plus(e,Times(f,x))),Cot(Plus(e,Times(f,x))),Power(Times(C2,f),CN1)),x),Simp(Star(C1D2,Integrate(Simp(Plus(Times(C2,ASymbol,a),Times(b,Plus(Times(C2,ASymbol),CSymbol),Csc(Plus(e,Times(f,x)))),Times(C2,a,CSymbol,Sqr(Csc(Plus(e,Times(f,x)))))),x),x)),x)),FreeQ(List(a,b,e,f,ASymbol,CSymbol),x))),
IIntegrate(4538,Integrate(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CSymbol,Power(b,CN1)),Integrate(Csc(Plus(e,Times(f,x))),x)),x),Simp(Star(Power(b,CN1),Integrate(Times(Plus(Times(ASymbol,b),Times(Subtract(Times(b,BSymbol),Times(a,CSymbol)),Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1)),x)),x)),FreeQ(List(a,b,e,f,ASymbol,BSymbol,CSymbol),x))),
IIntegrate(4539,Integrate(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CSymbol,Power(b,CN1)),Integrate(Csc(Plus(e,Times(f,x))),x)),x),Simp(Star(Power(b,CN1),Integrate(Times(Subtract(Times(ASymbol,b),Times(a,CSymbol,Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1)),x)),x)),FreeQ(List(a,b,e,f,ASymbol,CSymbol),x))),
IIntegrate(4540,Integrate(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Plus(Times(a,ASymbol),Times(CN1,b,BSymbol),Times(a,CSymbol)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(a,f,Plus(Times(C2,m),C1)),CN1)),x),Simp(Star(Power(Times(a,b,Plus(Times(C2,m),C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(ASymbol,b,Plus(Times(C2,m),C1)),Times(Subtract(Times(b,BSymbol,Plus(m,C1)),Times(a,Subtract(Times(ASymbol,Plus(m,C1)),Times(CSymbol,m)))),Csc(Plus(e,Times(f,x))))),x)),x)),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,CSymbol),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,Negate(C1D2)))))
  );
}
