package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules81 { 

	public static void initialize() {
		Initializer.init();
	}

	private static class Initializer  {

		private static void init() {
IIntegrate(4051,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1)),x_Symbol),
    Condition(Plus(Dist(Times(C,Power(b,CN1)),Int(Csc(Plus(e,Times(f,x))),x),x),Dist(Power(b,CN1),Int(Times(Subtract(Times(ASymbol,b),Times(a,C,Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1)),x),x)),FreeQ(List(a,b,e,f,ASymbol,C),x)));
IIntegrate(4052,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(Plus(Times(a,ASymbol),Times(CN1,b,BSymbol),Times(a,C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(a,f,Plus(Times(C2,m),C1)),CN1)),x)),Dist(Power(Times(a,b,Plus(Times(C2,m),C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(ASymbol,b,Plus(Times(C2,m),C1)),Times(Subtract(Times(b,BSymbol,Plus(m,C1)),Times(a,Subtract(Times(ASymbol,Plus(m,C1)),Times(C,m)))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,Negate(C1D2)))));
IIntegrate(4053,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(a,Plus(ASymbol,C),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(a,f,Plus(Times(C2,m),C1)),CN1)),x)),Dist(Power(Times(a,b,Plus(Times(C2,m),C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Subtract(Times(ASymbol,b,Plus(Times(C2,m),C1)),Times(a,Subtract(Times(ASymbol,Plus(m,C1)),Times(C,m)),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,Negate(C1D2)))));
IIntegrate(4054,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_DEFAULT)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(f,Plus(m,C1)),CN1)),x)),Dist(Power(Times(b,Plus(m,C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Simp(Plus(Times(ASymbol,b,Plus(m,C1)),Times(Plus(Times(a,C,m),Times(b,BSymbol,Plus(m,C1))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C,m),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),Not(LtQ(m,Negate(C1D2))))));
IIntegrate(4055,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_DEFAULT)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(f,Plus(m,C1)),CN1)),x)),Dist(Power(Times(b,Plus(m,C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Simp(Plus(Times(ASymbol,b,Plus(m,C1)),Times(a,C,m,Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C,m),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),Not(LtQ(m,Negate(C1D2))))));
IIntegrate(4056,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_DEFAULT)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(f,Plus(m,C1)),CN1)),x)),Dist(Power(Plus(m,C1),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Simp(Plus(Times(a,ASymbol,Plus(m,C1)),Times(Plus(Times(Plus(Times(ASymbol,b),Times(a,BSymbol)),Plus(m,C1)),Times(b,C,m)),Csc(Plus(e,Times(f,x)))),Times(Plus(Times(b,BSymbol,Plus(m,C1)),Times(a,C,m)),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),IGtQ(Times(C2,m),C0))));
IIntegrate(4057,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_DEFAULT)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(f,Plus(m,C1)),CN1)),x)),Dist(Power(Plus(m,C1),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Simp(Plus(Times(a,ASymbol,Plus(m,C1)),Times(Plus(Times(ASymbol,b,Plus(m,C1)),Times(b,C,m)),Csc(Plus(e,Times(f,x)))),Times(a,C,m,Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),IGtQ(Times(C2,m),C0))));
IIntegrate(4058,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1D2)),x_Symbol),
    Condition(Plus(Int(Times(Plus(ASymbol,Times(Subtract(BSymbol,C),Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x),Dist(C,Int(Times(Csc(Plus(e,Times(f,x))),Plus(C1,Csc(Plus(e,Times(f,x)))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0))));
IIntegrate(4059,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1D2)),x_Symbol),
    Condition(Plus(Int(Times(Subtract(ASymbol,Times(C,Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x),Dist(C,Int(Times(Csc(Plus(e,Times(f,x))),Plus(C1,Csc(Plus(e,Times(f,x)))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0))));
IIntegrate(4060,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Simp(Times(Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(a,f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x),Dist(Power(Times(a,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(ASymbol,Subtract(Sqr(a),Sqr(b)),Plus(m,C1)),Times(CN1,a,Plus(Times(ASymbol,b),Times(CN1,a,BSymbol),Times(b,C)),Plus(m,C1),Csc(Plus(e,Times(f,x)))),Times(Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),Plus(m,C2),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,CN1))));
IIntegrate(4061,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Simp(Times(Plus(Times(ASymbol,Sqr(b)),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(a,f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x),Dist(Power(Times(a,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(ASymbol,Subtract(Sqr(a),Sqr(b)),Plus(m,C1)),Times(CN1,a,b,Plus(ASymbol,C),Plus(m,C1),Csc(Plus(e,Times(f,x)))),Times(Plus(Times(ASymbol,Sqr(b)),Times(Sqr(a),C)),Plus(m,C2),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),IntegerQ(Times(C2,m)),LtQ(m,CN1))));
IIntegrate(4062,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Dist(Power(b,CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Plus(Times(ASymbol,b),Times(Subtract(Times(b,BSymbol),Times(a,C)),Csc(Plus(e,Times(f,x)))))),x),x),Dist(Times(C,Power(b,CN1)),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1))),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C,m),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),Not(IntegerQ(Times(C2,m))))));
IIntegrate(4063,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Dist(Power(b,CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Subtract(Times(ASymbol,b),Times(a,C,Csc(Plus(e,Times(f,x)))))),x),x),Dist(Times(C,Power(b,CN1)),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1))),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C,m),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),Not(IntegerQ(Times(C2,m))))));
IIntegrate(4064,Int(Times(Power(Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),m_),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Times(C_DEFAULT,Sqr($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Dist(Sqr(b),Int(Times(Power(Times(b,Cos(Plus(e,Times(f,x)))),Subtract(m,C2)),Plus(C,Times(BSymbol,Cos(Plus(e,Times(f,x)))),Times(ASymbol,Sqr(Cos(Plus(e,Times(f,x))))))),x),x),And(FreeQ(List(b,e,f,ASymbol,BSymbol,C,m),x),Not(IntegerQ(m)))));
IIntegrate(4065,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_)),x_Symbol),
    Condition(Dist(Sqr(b),Int(Times(Power(Times(b,Sin(Plus(e,Times(f,x)))),Subtract(m,C2)),Plus(C,Times(BSymbol,Sin(Plus(e,Times(f,x)))),Times(ASymbol,Sqr(Sin(Plus(e,Times(f,x))))))),x),x),And(FreeQ(List(b,e,f,ASymbol,BSymbol,C,m),x),Not(IntegerQ(m)))));
IIntegrate(4066,Int(Times(Power(Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),m_),Plus(A_DEFAULT,Times(C_DEFAULT,Sqr($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Dist(Sqr(b),Int(Times(Power(Times(b,Cos(Plus(e,Times(f,x)))),Subtract(m,C2)),Plus(C,Times(ASymbol,Sqr(Cos(Plus(e,Times(f,x))))))),x),x),And(FreeQ(List(b,e,f,ASymbol,C,m),x),Not(IntegerQ(m)))));
IIntegrate(4067,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_)),x_Symbol),
    Condition(Dist(Sqr(b),Int(Times(Power(Times(b,Sin(Plus(e,Times(f,x)))),Subtract(m,C2)),Plus(C,Times(ASymbol,Sqr(Sin(Plus(e,Times(f,x))))))),x),x),And(FreeQ(List(b,e,f,ASymbol,C,m),x),Not(IntegerQ(m)))));
IIntegrate(4068,Int(Times(Power(Times(a_DEFAULT,Power(Times(b_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),p_)),m_),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Times(C_DEFAULT,Sqr($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Dist(Times(Power(a,IntPart(m)),Power(Times(a,Power(Times(b,Sec(Plus(e,Times(f,x)))),p)),FracPart(m)),Power(Power(Times(b,Sec(Plus(e,Times(f,x)))),Times(p,FracPart(m))),CN1)),Int(Times(Power(Times(b,Sec(Plus(e,Times(f,x)))),Times(m,p)),Plus(ASymbol,Times(BSymbol,Sec(Plus(e,Times(f,x)))),Times(C,Sqr(Sec(Plus(e,Times(f,x))))))),x),x),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C,m,p),x),Not(IntegerQ(m)))));
IIntegrate(4069,Int(Times(Power(Times(a_DEFAULT,Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),p_)),m_),Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT))),x_Symbol),
    Condition(Dist(Times(Power(a,IntPart(m)),Power(Times(a,Power(Times(b,Csc(Plus(e,Times(f,x)))),p)),FracPart(m)),Power(Power(Times(b,Csc(Plus(e,Times(f,x)))),Times(p,FracPart(m))),CN1)),Int(Times(Power(Times(b,Csc(Plus(e,Times(f,x)))),Times(m,p)),Plus(ASymbol,Times(BSymbol,Csc(Plus(e,Times(f,x)))),Times(C,Sqr(Csc(Plus(e,Times(f,x))))))),x),x),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C,m,p),x),Not(IntegerQ(m)))));
IIntegrate(4070,Int(Times(Power(Times(a_DEFAULT,Power(Times(b_DEFAULT,$($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),p_)),m_),Plus(A_DEFAULT,Times(C_DEFAULT,Sqr($($s("§sec"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Dist(Times(Power(a,IntPart(m)),Power(Times(a,Power(Times(b,Sec(Plus(e,Times(f,x)))),p)),FracPart(m)),Power(Power(Times(b,Sec(Plus(e,Times(f,x)))),Times(p,FracPart(m))),CN1)),Int(Times(Power(Times(b,Sec(Plus(e,Times(f,x)))),Times(m,p)),Plus(ASymbol,Times(C,Sqr(Sec(Plus(e,Times(f,x))))))),x),x),And(FreeQ(List(a,b,e,f,ASymbol,C,m,p),x),Not(IntegerQ(m)))));
IIntegrate(4071,Int(Times(Power(Times(a_DEFAULT,Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),p_)),m_),Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT))),x_Symbol),
    Condition(Dist(Times(Power(a,IntPart(m)),Power(Times(a,Power(Times(b,Csc(Plus(e,Times(f,x)))),p)),FracPart(m)),Power(Power(Times(b,Csc(Plus(e,Times(f,x)))),Times(p,FracPart(m))),CN1)),Int(Times(Power(Times(b,Csc(Plus(e,Times(f,x)))),Times(m,p)),Plus(ASymbol,Times(C,Sqr(Csc(Plus(e,Times(f,x))))))),x),x),And(FreeQ(List(a,b,e,f,ASymbol,C,m,p),x),Not(IntegerQ(m)))));
IIntegrate(4072,Int(Times(Power(Plus(a_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT)),m_DEFAULT),Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(c_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT)),n_DEFAULT)),x_Symbol),
    Condition(Dist(Power(b,CN2),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Plus(c,Times(d,Csc(Plus(e,Times(f,x))))),n),Plus(Times(b,BSymbol),Times(CN1,a,C),Times(b,C,Csc(Plus(e,Times(f,x)))))),x),x),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol,C,m,n),x),EqQ(Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),C0))));
IIntegrate(4073,Int(Times(Power(Plus(a_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT)),m_DEFAULT),Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(c_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT)),n_DEFAULT)),x_Symbol),
    Condition(Negate(Dist(Times(C,Power(b,CN2)),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Plus(c,Times(d,Csc(Plus(e,Times(f,x))))),n),Subtract(a,Times(b,Csc(Plus(e,Times(f,x)))))),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,C,m,n),x),EqQ(Plus(Times(ASymbol,Sqr(b)),Times(Sqr(a),C)),C0))));
IIntegrate(4074,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),x_Symbol),
    Condition(Plus(Simp(Times(ASymbol,a,Cot(Plus(e,Times(f,x))),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,n),CN1)),x),Dist(Power(Times(d,n),CN1),Int(Times(Power(Times(d,Csc(Plus(e,Times(f,x)))),Plus(n,C1)),Simp(Plus(Times(n,Plus(Times(BSymbol,a),Times(ASymbol,b))),Times(Plus(Times(n,Plus(Times(a,C),Times(BSymbol,b))),Times(ASymbol,a,Plus(n,C1))),Csc(Plus(e,Times(f,x)))),Times(b,C,n,Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C),x),LtQ(n,CN1))));
IIntegrate(4075,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),x_Symbol),
    Condition(Plus(Simp(Times(ASymbol,a,Cot(Plus(e,Times(f,x))),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,n),CN1)),x),Dist(Power(Times(d,n),CN1),Int(Times(Power(Times(d,Csc(Plus(e,Times(f,x)))),Plus(n,C1)),Simp(Plus(Times(ASymbol,b,n),Times(a,Plus(Times(C,n),Times(ASymbol,Plus(n,C1))),Csc(Plus(e,Times(f,x)))),Times(b,C,n,Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,C),x),LtQ(n,CN1))));
IIntegrate(4076,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_DEFAULT),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(b,C,Csc(Plus(e,Times(f,x))),Cot(Plus(e,Times(f,x))),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,Plus(n,C2)),CN1)),x)),Dist(Power(Plus(n,C2),CN1),Int(Times(Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Plus(Times(ASymbol,a,Plus(n,C2)),Times(Plus(Times(BSymbol,a,Plus(n,C2)),Times(b,Plus(Times(C,Plus(n,C1)),Times(ASymbol,Plus(n,C2))))),Csc(Plus(e,Times(f,x)))),Times(Plus(Times(a,C),Times(BSymbol,b)),Plus(n,C2),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C,n),x),Not(LtQ(n,CN1)))));
IIntegrate(4077,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_DEFAULT),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(b,C,Csc(Plus(e,Times(f,x))),Cot(Plus(e,Times(f,x))),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,Plus(n,C2)),CN1)),x)),Dist(Power(Plus(n,C2),CN1),Int(Times(Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Plus(Times(ASymbol,a,Plus(n,C2)),Times(b,Plus(Times(C,Plus(n,C1)),Times(ASymbol,Plus(n,C2))),Csc(Plus(e,Times(f,x)))),Times(a,C,Plus(n,C2),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,C,n),x),Not(LtQ(n,CN1)))));
IIntegrate(4078,Int(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Negate(Simp(Times(Plus(Times(a,ASymbol),Times(CN1,b,BSymbol),Times(a,C)),Cot(Plus(e,Times(f,x))),Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(a,f,Plus(Times(C2,m),C1)),CN1)),x)),Dist(Power(Times(a,b,Plus(Times(C2,m),C1)),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Subtract(Subtract(Subtract(Times(a,BSymbol),Times(b,C)),Times(C2,ASymbol,b,Plus(m,C1))),Times(Subtract(Times(b,BSymbol,Plus(m,C2)),Times(a,Subtract(Times(ASymbol,Plus(m,C2)),Times(C,Subtract(m,C1))))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C),x),LtQ(m,CN1),EqQ(Subtract(Sqr(a),Sqr(b)),C0))));
IIntegrate(4079,Int(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Negate(Simp(Times(Plus(ASymbol,C),Cot(Plus(e,Times(f,x))),Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(f,Plus(Times(C2,m),C1)),CN1)),x)),Dist(Power(Times(a,b,Plus(Times(C2,m),C1)),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(CN1,b,C),Times(CN1,C2,ASymbol,b,Plus(m,C1)),Times(a,Subtract(Times(ASymbol,Plus(m,C2)),Times(C,Subtract(m,C1))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C),x),LtQ(m,CN1),EqQ(Subtract(Sqr(a),Sqr(b)),C0))));
IIntegrate(4080,Int(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x)),Dist(Power(Times(b,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Subtract(Times(b,Plus(Times(a,ASymbol),Times(CN1,b,BSymbol),Times(a,C)),Plus(m,C1)),Times(Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C),Times(b,Plus(Times(ASymbol,b),Times(CN1,a,BSymbol),Times(b,C)),Plus(m,C1))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C),x),LtQ(m,CN1),NeQ(Subtract(Sqr(a),Sqr(b)),C0))));
IIntegrate(4081,Int(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(Plus(Times(ASymbol,Sqr(b)),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x)),Dist(Power(Times(b,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Subtract(Times(a,b,Plus(ASymbol,C),Plus(m,C1)),Times(Plus(Times(ASymbol,Sqr(b)),Times(Sqr(a),C),Times(b,Plus(Times(ASymbol,b),Times(b,C)),Plus(m,C1))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C),x),LtQ(m,CN1),NeQ(Subtract(Sqr(a),Sqr(b)),C0))));
IIntegrate(4082,Int(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C2)),CN1)),x)),Dist(Power(Times(b,Plus(m,C2)),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Simp(Plus(Times(b,ASymbol,Plus(m,C2)),Times(b,C,Plus(m,C1)),Times(Subtract(Times(b,BSymbol,Plus(m,C2)),Times(a,C)),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C,m),x),Not(LtQ(m,CN1)))));
IIntegrate(4083,Int(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C2)),CN1)),x)),Dist(Power(Times(b,Plus(m,C2)),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Simp(Subtract(Plus(Times(b,ASymbol,Plus(m,C2)),Times(b,C,Plus(m,C1))),Times(a,C,Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C,m),x),Not(LtQ(m,CN1)))));
IIntegrate(4084,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Negate(Simp(Times(Plus(Times(a,ASymbol),Times(CN1,b,BSymbol),Times(a,C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(a,f,Plus(Times(C2,m),C1)),CN1)),x)),Dist(Power(Times(a,b,Plus(Times(C2,m),C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Subtract(Subtract(Subtract(Times(a,BSymbol,n),Times(b,C,n)),Times(ASymbol,b,Plus(Times(C2,m),n,C1))),Times(Subtract(Times(b,BSymbol,Plus(m,n,C1)),Times(a,Subtract(Times(ASymbol,Plus(m,n,C1)),Times(C,Subtract(m,n))))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C,n),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,Negate(C1D2)))));
IIntegrate(4085,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(a,Plus(ASymbol,C),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(a,f,Plus(Times(C2,m),C1)),CN1)),x)),Dist(Power(Times(a,b,Plus(Times(C2,m),C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Subtract(Plus(Times(b,C,n),Times(ASymbol,b,Plus(Times(C2,m),n,C1))),Times(a,Subtract(Times(ASymbol,Plus(m,n,C1)),Times(C,Subtract(m,n))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,C,n),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,Negate(C1D2)))));
IIntegrate(4086,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(ASymbol,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,n),CN1)),x),Dist(Power(Times(b,d,n),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),Plus(n,C1)),Simp(Subtract(Subtract(Times(a,ASymbol,m),Times(b,BSymbol,n)),Times(b,Plus(Times(ASymbol,Plus(m,n,C1)),Times(C,n)),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C,m),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),Not(LtQ(m,Negate(C1D2))),Or(LtQ(n,Negate(C1D2)),EqQ(Plus(m,n,C1),C0)))));
IIntegrate(4087,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(ASymbol,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,n),CN1)),x),Dist(Power(Times(b,d,n),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),Plus(n,C1)),Simp(Subtract(Times(a,ASymbol,m),Times(b,Plus(Times(ASymbol,Plus(m,n,C1)),Times(C,n)),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,C,m),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),Not(LtQ(m,Negate(C1D2))),Or(LtQ(n,Negate(C1D2)),EqQ(Plus(m,n,C1),C0)))));
IIntegrate(4088,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,Plus(m,n,C1)),CN1)),x)),Dist(Power(Times(b,Plus(m,n,C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Plus(Times(ASymbol,b,Plus(m,n,C1)),Times(b,C,n),Times(Plus(Times(a,C,m),Times(b,BSymbol,Plus(m,n,C1))),Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C,m,n),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),Not(LtQ(m,Negate(C1D2))),Not(LtQ(n,Negate(C1D2))),NeQ(Plus(m,n,C1),C0))));
IIntegrate(4089,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,Plus(m,n,C1)),CN1)),x)),Dist(Power(Times(b,Plus(m,n,C1)),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Plus(Times(ASymbol,b,Plus(m,n,C1)),Times(b,C,n),Times(a,C,m,Csc(Plus(e,Times(f,x))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,C,m,n),x),EqQ(Subtract(Sqr(a),Sqr(b)),C0),Not(LtQ(m,Negate(C1D2))),Not(LtQ(n,Negate(C1D2))),NeQ(Plus(m,n,C1),C0))));
IIntegrate(4090,Int(Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(a,Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(Sqr(b),f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x),Dist(Power(Times(Sqr(b),Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Subtract(Plus(Times(b,Plus(m,C1),Plus(Times(CN1,a,Subtract(Times(b,BSymbol),Times(a,C))),Times(ASymbol,Sqr(b)))),Times(Subtract(Times(b,BSymbol,Plus(Sqr(a),Times(Sqr(b),Plus(m,C1)))),Times(a,Plus(Times(ASymbol,Sqr(b),Plus(m,C2)),Times(C,Plus(Sqr(a),Times(Sqr(b),Plus(m,C1))))))),Csc(Plus(e,Times(f,x))))),Times(b,C,Plus(m,C1),Subtract(Sqr(a),Sqr(b)),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,CN1))));
IIntegrate(4091,Int(Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(a,Plus(Times(ASymbol,Sqr(b)),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(Sqr(b),f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x),Dist(Power(Times(Sqr(b),Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Subtract(Subtract(Times(b,Plus(m,C1),Plus(Times(Sqr(a),C),Times(ASymbol,Sqr(b)))),Times(a,Plus(Times(ASymbol,Sqr(b),Plus(m,C2)),Times(C,Plus(Sqr(a),Times(Sqr(b),Plus(m,C1))))),Csc(Plus(e,Times(f,x))))),Times(b,C,Plus(m,C1),Subtract(Sqr(a),Sqr(b)),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,CN1))));
IIntegrate(4092,Int(Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Csc(Plus(e,Times(f,x))),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C3)),CN1)),x)),Dist(Power(Times(b,Plus(m,C3)),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Simp(Subtract(Plus(Times(a,C),Times(b,Plus(Times(C,Plus(m,C2)),Times(ASymbol,Plus(m,C3))),Csc(Plus(e,Times(f,x))))),Times(Subtract(Times(C2,a,C),Times(b,BSymbol,Plus(m,C3))),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol,C,m),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),Not(LtQ(m,CN1)))));
IIntegrate(4093,Int(Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Csc(Plus(e,Times(f,x))),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(b,f,Plus(m,C3)),CN1)),x)),Dist(Power(Times(b,Plus(m,C3)),CN1),Int(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Simp(Subtract(Plus(Times(a,C),Times(b,Plus(Times(C,Plus(m,C2)),Times(ASymbol,Plus(m,C3))),Csc(Plus(e,Times(f,x))))),Times(C2,a,C,Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,e,f,ASymbol,C,m),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),Not(LtQ(m,CN1)))));
IIntegrate(4094,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(ASymbol,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,n),CN1)),x),Dist(Power(Times(d,n),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),Plus(n,C1)),Simp(Subtract(Subtract(Subtract(Times(ASymbol,b,m),Times(a,BSymbol,n)),Times(Plus(Times(b,BSymbol,n),Times(a,Plus(Times(C,n),Times(ASymbol,Plus(n,C1))))),Csc(Plus(e,Times(f,x))))),Times(b,Plus(Times(C,n),Times(ASymbol,Plus(m,n,C1))),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),GtQ(m,C0),LeQ(n,CN1))));
IIntegrate(4095,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(ASymbol,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,n),CN1)),x),Dist(Power(Times(d,n),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),Plus(n,C1)),Simp(Subtract(Subtract(Times(ASymbol,b,m),Times(a,Plus(Times(C,n),Times(ASymbol,Plus(n,C1))),Csc(Plus(e,Times(f,x))))),Times(b,Plus(Times(C,n),Times(ASymbol,Plus(m,n,C1))),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),GtQ(m,C0),LeQ(n,CN1))));
IIntegrate(4096,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,Plus(m,n,C1)),CN1)),x)),Dist(Power(Plus(m,n,C1),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Plus(Times(a,ASymbol,Plus(m,n,C1)),Times(a,C,n),Times(Plus(Times(Plus(Times(ASymbol,b),Times(a,BSymbol)),Plus(m,n,C1)),Times(b,C,Plus(m,n))),Csc(Plus(e,Times(f,x)))),Times(Plus(Times(b,BSymbol,Plus(m,n,C1)),Times(a,C,m)),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C,n),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),GtQ(m,C0),Not(LeQ(n,CN1)))));
IIntegrate(4097,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(C,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(f,Plus(m,n,C1)),CN1)),x)),Dist(Power(Plus(m,n,C1),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Plus(Times(a,ASymbol,Plus(m,n,C1)),Times(a,C,n),Times(b,Plus(Times(ASymbol,Plus(m,n,C1)),Times(C,Plus(m,n))),Csc(Plus(e,Times(f,x)))),Times(a,C,m,Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,C,n),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),GtQ(m,C0),Not(LeQ(n,CN1)))));
IIntegrate(4098,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(d,Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),Subtract(n,C1)),Power(Times(b,f,Subtract(Sqr(a),Sqr(b)),Plus(m,C1)),CN1)),x)),Dist(Times(d,Power(Times(b,Subtract(Sqr(a),Sqr(b)),Plus(m,C1)),CN1)),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),Subtract(n,C1)),Simp(Subtract(Plus(Times(ASymbol,Sqr(b),Subtract(n,C1)),Times(CN1,a,Subtract(Times(b,BSymbol),Times(a,C)),Subtract(n,C1)),Times(b,Plus(Times(a,ASymbol),Times(CN1,b,BSymbol),Times(a,C)),Plus(m,C1),Csc(Plus(e,Times(f,x))))),Times(Plus(Times(b,Subtract(Times(ASymbol,b),Times(a,BSymbol)),Plus(m,n,C1)),Times(C,Plus(Times(Sqr(a),n),Times(Sqr(b),Plus(m,C1))))),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,CN1),GtQ(n,C0))));
IIntegrate(4099,Int(Times(Plus(A_DEFAULT,Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Negate(Simp(Times(d,Plus(Times(ASymbol,Sqr(b)),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),Subtract(n,C1)),Power(Times(b,f,Subtract(Sqr(a),Sqr(b)),Plus(m,C1)),CN1)),x)),Dist(Times(d,Power(Times(b,Subtract(Sqr(a),Sqr(b)),Plus(m,C1)),CN1)),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),Subtract(n,C1)),Simp(Subtract(Plus(Times(ASymbol,Sqr(b),Subtract(n,C1)),Times(Sqr(a),C,Subtract(n,C1)),Times(a,b,Plus(ASymbol,C),Plus(m,C1),Csc(Plus(e,Times(f,x))))),Times(Plus(Times(ASymbol,Sqr(b),Plus(m,n,C1)),Times(C,Plus(Times(Sqr(a),n),Times(Sqr(b),Plus(m,C1))))),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,C),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,CN1),GtQ(n,C0))));
IIntegrate(4100,Int(Times(Plus(A_DEFAULT,Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT),Times(Sqr($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),C_DEFAULT)),Power(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),n_),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_)),x_Symbol),
    Condition(Plus(Simp(Times(Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Power(Times(a,f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x),Dist(Power(Times(a,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Int(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(d,Csc(Plus(e,Times(f,x)))),n),Simp(Plus(Times(a,Plus(Times(a,ASymbol),Times(CN1,b,BSymbol),Times(a,C)),Plus(m,C1)),Times(CN1,Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),Plus(m,n,C1)),Times(CN1,a,Plus(Times(ASymbol,b),Times(CN1,a,BSymbol),Times(b,C)),Plus(m,C1),Csc(Plus(e,Times(f,x)))),Times(Plus(Times(ASymbol,Sqr(b)),Times(CN1,a,b,BSymbol),Times(Sqr(a),C)),Plus(m,n,C2),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol,C,n),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0),LtQ(m,CN1),Not(And(ILtQ(Plus(m,C1D2),C0),ILtQ(n,C0))))));
  }
}
}
