package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules7 { 
  public static IAST RULES = List( 
IIntegrate(141,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Times(Power(Subtract(Times(b,c),Times(a,d)),n),Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Times(Plus(m,C1),Power(Subtract(Times(b,e),Times(a,f)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(m,C1))),CN1),Hypergeometric2F1(Plus(m,C1),Negate(n),Plus(m,C2),Times(CN1,Subtract(Times(d,e),Times(c,f)),Plus(a,Times(b,x)),Power(Times(Subtract(Times(b,c),Times(a,d)),Plus(e,Times(f,x))),CN1)))),x),And(FreeQ(List(a,b,c,d,e,f,m,p),x),EqQ(Plus(m,n,p,C2),C0),ILtQ(n,C0),Or(SumSimplerQ(m,C1),Not(SumSimplerQ(p,C1))),Not(ILtQ(m,C0))))),
IIntegrate(142,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(Subtract(Times(b,e),Times(a,f)),Plus(m,C1)),CN1),Hypergeometric2F1(Plus(m,C1),Negate(n),Plus(m,C2),Times(CN1,Subtract(Times(d,e),Times(c,f)),Plus(a,Times(b,x)),Power(Times(Subtract(Times(b,c),Times(a,d)),Plus(e,Times(f,x))),CN1))),Power(Power(Times(Subtract(Times(b,e),Times(a,f)),Plus(c,Times(d,x)),Power(Times(Subtract(Times(b,c),Times(a,d)),Plus(e,Times(f,x))),CN1)),n),CN1)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),EqQ(Plus(m,n,p,C2),C0),Not(IntegerQ(n))))),
IIntegrate(143,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),CN1)),x_),
    Condition(Plus(Simp(Star(Times(Power(Subtract(Times(c,f),Times(d,e)),Plus(m,n,C1)),Power(Power(f,Plus(m,n,C1)),CN1)),Integrate(Times(Power(Plus(a,Times(b,x)),m),Power(Times(Power(Plus(c,Times(d,x)),Plus(m,C1)),Plus(e,Times(f,x))),CN1)),x)),x),Simp(Star(Power(Power(f,Plus(m,n,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),m),Power(Power(Plus(c,Times(d,x)),Plus(m,C1)),CN1),ExpandToSum(Times(Subtract(Times(Power(f,Plus(m,n,C1)),Power(Plus(c,Times(d,x)),Plus(m,n,C1))),Power(Subtract(Times(c,f),Times(d,e)),Plus(m,n,C1))),Power(Plus(e,Times(f,x)),CN1)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,m,n),x),IGtQ(Plus(m,n,C1),C0),Or(LtQ(m,C0),SumSimplerQ(m,C1),Not(Or(LtQ(n,C0),SumSimplerQ(n,C1))))))),
IIntegrate(144,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(With(list(Set($s("mnp"),Simplify(Plus(m,n,p)))),Condition(Plus(Simp(Times(b,Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1)),x),Simp(Star(Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p),Simp(Subtract(Subtract(Times(a,d,f,Plus(m,C1)),Times(b,Plus(Times(d,e,Plus(m,n,C2)),Times(c,f,Plus(m,p,C2))))),Times(b,d,f,Plus($s("mnp"),C3),x)),x)),x)),x)),And(ILtQ(Plus($s("mnp"),C2),C0),Or(SumSimplerQ(m,C1),And(Not(SumSimplerQ(n,C1)),Not(SumSimplerQ(p,C1))))))),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),NeQ(m,CN1)))),
IIntegrate(145,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Star(Power(b,CN1),Subst(Integrate(Times(Power(x,m),Power(Plus(Times(c,e),Times(CN1,Sqr(Plus(Times(d,e),Times(c,f))),Power(Times(C4,d,f),CN1)),Times(d,f,Sqr(x),Power(b,CN2))),n)),x),x,Plus(a,Times(b,x)))),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),EqQ(p,n),EqQ(Subtract(Plus(Times(b,d,e),Times(b,c,f)),Times(C2,a,d,f)),C0),EqQ(Plus(Times(d,e),Times(c,f)),C0),GtQ(c,C0),GtQ(e,C0)))),
IIntegrate(146,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Star(Times(Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p),Power(Times(b,Power(Plus(Times(c,e),Times(Plus(Times(d,e),Times(c,f)),x),Times(d,f,Sqr(x))),n)),CN1)),Subst(Integrate(Times(Power(x,m),Power(Plus(Times(c,e),Times(CN1,Sqr(Plus(Times(d,e),Times(c,f))),Power(Times(C4,d,f),CN1)),Times(d,f,Sqr(x),Power(b,CN2))),n)),x),x,Plus(a,Times(b,x)))),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),EqQ(p,n),EqQ(Subtract(Plus(Times(b,d,e),Times(b,c,f)),Times(C2,a,d,f)),C0)))),
IIntegrate(147,Integrate(Times(Power(Times(f_DEFAULT,x_),p_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_)),x_),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(a,Times(b,x)),n),Power(Plus(c,Times(d,x)),n),Power(Times(f,x),p)),Power(Plus(a,Times(b,x)),Subtract(m,n)),x),x),And(FreeQ(List(a,b,c,d,f,m,n,p),x),EqQ(Plus(Times(b,c),Times(a,d)),C0),IGtQ(Subtract(m,n),C0),NeQ(Plus(m,n,p,C2),C0)))),
IIntegrate(148,Integrate(Times(Power(Times(b_DEFAULT,x_),m_),Power(Plus(c_,Times(d_DEFAULT,x_)),n_DEFAULT),Power(Plus(e_,Times(f_DEFAULT,x_)),p_DEFAULT)),x_),
    Condition(With(list(Set(k,Denominator(m))),Simp(Star(Times(k,Power(b,CN1)),Subst(Integrate(Times(Power(x,Subtract(Times(k,Plus(m,C1)),C1)),Power(Plus(c,Times(d,Power(x,k),Power(b,CN1))),n),Power(Plus(e,Times(f,Power(x,k),Power(b,CN1))),p)),x),x,Power(Times(b,x),Power(k,CN1)))),x)),And(FreeQ(List(b,c,d,e,f,n,p),x),FractionQ(m),IntegerQ(p)))),
IIntegrate(149,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_DEFAULT),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_DEFAULT)),x_),
    Condition(With(list(Set(k,Denominator(m))),Simp(Star(Times(k,Power(b,CN1)),Subst(Integrate(Times(Power(x,Subtract(Times(k,Plus(m,C1)),C1)),Power(Plus(c,Times(CN1,a,d,Power(b,CN1)),Times(d,Power(x,k),Power(b,CN1))),n),Power(Plus(e,Times(CN1,a,f,Power(b,CN1)),Times(f,Power(x,k),Power(b,CN1))),p)),x),x,Power(Plus(a,Times(b,x)),Power(k,CN1)))),x)),And(FreeQ(List(a,b,c,d,e,f,n,p),x),FractionQ(m),IntegerQ(Times(C2,n)),IntegerQ(p)))),
IIntegrate(150,Integrate(Times(Power(Times(b_DEFAULT,x_),m_),Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(e_,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Times(Power(c,n),Power(e,p),Power(Times(b,x),Plus(m,C1)),Power(Times(b,Plus(m,C1)),CN1),AppellF1(Plus(m,C1),Negate(n),Negate(p),Plus(m,C2),Times(CN1,d,x,Power(c,CN1)),Times(CN1,f,x,Power(e,CN1)))),x),And(FreeQ(List(b,c,d,e,f,m,n,p),x),Not(IntegerQ(m)),Not(IntegerQ(n)),GtQ(c,C0),Or(IntegerQ(p),GtQ(e,C0))))),
IIntegrate(151,Integrate(Times(Power(Times(b_DEFAULT,x_),m_),Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(e_,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Times(Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Times(d,Plus(n,C1),Power(Times(CN1,d,Power(Times(b,c),CN1)),m),Power(Times(d,Power(Subtract(Times(d,e),Times(c,f)),CN1)),p)),CN1),AppellF1(Plus(n,C1),Negate(m),Negate(p),Plus(n,C2),Plus(C1,Times(d,x,Power(c,CN1))),Times(CN1,f,Plus(c,Times(d,x)),Power(Subtract(Times(d,e),Times(c,f)),CN1)))),x),And(FreeQ(List(b,c,d,e,f,m,n,p),x),Not(IntegerQ(m)),Not(IntegerQ(n)),GtQ(Times(CN1,d,Power(Times(b,c),CN1)),C0),Or(IntegerQ(p),GtQ(Times(d,Power(Subtract(Times(d,e),Times(c,f)),CN1)),C0))))),
IIntegrate(152,Integrate(Times(Power(Times(b_DEFAULT,x_),m_),Power(Plus(c_,Times(d_DEFAULT,x_)),n_),Power(Plus(e_,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Star(Times(Power(c,IntPart(n)),Power(Plus(c,Times(d,x)),FracPart(n)),Power(Power(Plus(C1,Times(d,x,Power(c,CN1))),FracPart(n)),CN1)),Integrate(Times(Power(Times(b,x),m),Power(Plus(C1,Times(d,x,Power(c,CN1))),n),Power(Plus(e,Times(f,x)),p)),x)),x),And(FreeQ(List(b,c,d,e,f,m,n,p),x),Not(IntegerQ(m)),Not(IntegerQ(n)),Not(GtQ(c,C0))))),
IIntegrate(153,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Times(Power(Subtract(Times(b,e),Times(a,f)),p),Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Times(Power(b,Plus(p,C1)),Plus(m,C1),Power(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),n)),CN1),AppellF1(Plus(m,C1),Negate(n),Negate(p),Plus(m,C2),Times(CN1,d,Plus(a,Times(b,x)),Power(Subtract(Times(b,c),Times(a,d)),CN1)),Times(CN1,f,Plus(a,Times(b,x)),Power(Subtract(Times(b,e),Times(a,f)),CN1)))),x),And(FreeQ(List(a,b,c,d,e,f,m,n),x),Not(IntegerQ(m)),Not(IntegerQ(n)),IntegerQ(p),GtQ(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),C0),Not(And(GtQ(Simplify(Times(d,Power(Subtract(Times(d,a),Times(c,b)),CN1))),C0),SimplerQ(Plus(c,Times(d,x)),Plus(a,Times(b,x)))))))),
IIntegrate(154,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Star(Times(Power(Plus(c,Times(d,x)),FracPart(n)),Power(Times(Power(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),IntPart(n)),Power(Times(b,Plus(c,Times(d,x)),Power(Subtract(Times(b,c),Times(a,d)),CN1)),FracPart(n))),CN1)),Integrate(Times(Power(Plus(a,Times(b,x)),m),Power(Simp(Plus(Times(b,c,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Times(b,d,x,Power(Subtract(Times(b,c),Times(a,d)),CN1))),x),n),Power(Plus(e,Times(f,x)),p)),x)),x),And(FreeQ(List(a,b,c,d,e,f,m,n),x),Not(IntegerQ(m)),Not(IntegerQ(n)),IntegerQ(p),Not(GtQ(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),C0)),Not(SimplerQ(Plus(c,Times(d,x)),Plus(a,Times(b,x))))))),
IIntegrate(155,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Times(b,Plus(m,C1),Power(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),n),Power(Simplify(Times(b,Power(Subtract(Times(b,e),Times(a,f)),CN1))),p)),CN1),AppellF1(Plus(m,C1),Negate(n),Negate(p),Plus(m,C2),Times(CN1,d,Plus(a,Times(b,x)),Power(Subtract(Times(b,c),Times(a,d)),CN1)),Times(CN1,f,Plus(a,Times(b,x)),Power(Subtract(Times(b,e),Times(a,f)),CN1)))),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),Not(IntegerQ(m)),Not(IntegerQ(n)),Not(IntegerQ(p)),GtQ(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),C0),GtQ(Simplify(Times(b,Power(Subtract(Times(b,e),Times(a,f)),CN1))),C0),Not(And(GtQ(Simplify(Times(d,Power(Subtract(Times(d,a),Times(c,b)),CN1))),C0),GtQ(Simplify(Times(d,Power(Subtract(Times(d,e),Times(c,f)),CN1))),C0),SimplerQ(Plus(c,Times(d,x)),Plus(a,Times(b,x))))),Not(And(GtQ(Simplify(Times(f,Power(Subtract(Times(f,a),Times(e,b)),CN1))),C0),GtQ(Simplify(Times(f,Power(Subtract(Times(f,c),Times(e,d)),CN1))),C0),SimplerQ(Plus(e,Times(f,x)),Plus(a,Times(b,x)))))))),
IIntegrate(156,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Star(Times(Power(Plus(e,Times(f,x)),FracPart(p)),Power(Times(Power(Simplify(Times(b,Power(Subtract(Times(b,e),Times(a,f)),CN1))),IntPart(p)),Power(Times(b,Plus(e,Times(f,x)),Power(Subtract(Times(b,e),Times(a,f)),CN1)),FracPart(p))),CN1)),Integrate(Times(Power(Plus(a,Times(b,x)),m),Power(Plus(c,Times(d,x)),n),Power(Simp(Plus(Times(b,e,Power(Subtract(Times(b,e),Times(a,f)),CN1)),Times(b,f,x,Power(Subtract(Times(b,e),Times(a,f)),CN1))),x),p)),x)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),Not(IntegerQ(m)),Not(IntegerQ(n)),Not(IntegerQ(p)),GtQ(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),C0),Not(GtQ(Simplify(Times(b,Power(Subtract(Times(b,e),Times(a,f)),CN1))),C0))))),
IIntegrate(157,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Star(Times(Power(Plus(c,Times(d,x)),FracPart(n)),Power(Times(Power(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),IntPart(n)),Power(Times(b,Plus(c,Times(d,x)),Power(Subtract(Times(b,c),Times(a,d)),CN1)),FracPart(n))),CN1)),Integrate(Times(Power(Plus(a,Times(b,x)),m),Power(Simp(Plus(Times(b,c,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Times(b,d,x,Power(Subtract(Times(b,c),Times(a,d)),CN1))),x),n),Power(Plus(e,Times(f,x)),p)),x)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),Not(IntegerQ(m)),Not(IntegerQ(n)),Not(IntegerQ(p)),Not(GtQ(Simplify(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1))),C0)),Not(SimplerQ(Plus(c,Times(d,x)),Plus(a,Times(b,x)))),Not(SimplerQ(Plus(e,Times(f,x)),Plus(a,Times(b,x))))))),
IIntegrate(158,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,u_)),m_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,u_)),n_DEFAULT),Power(Plus(e_,Times(f_DEFAULT,u_)),p_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(D(u,x),CN1),Subst(Integrate(Times(Power(Plus(a,Times(b,x)),m),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p)),x),x,u)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),LinearQ(u,x),NeQ(u,x)))),
IIntegrate(159,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_DEFAULT),Plus(e_,Times(f_DEFAULT,x_)),Plus(g_DEFAULT,Times(h_DEFAULT,x_))),x_),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(a,Times(b,x)),m),Power(Plus(c,Times(d,x)),n),Plus(e,Times(f,x)),Plus(g,Times(h,x))),x),x),And(FreeQ(List(a,b,c,d,e,f,g,h),x),Or(IGtQ(m,C0),IntegersQ(m,n))))),
IIntegrate(160,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_DEFAULT),Plus(e_,Times(f_DEFAULT,x_)),Plus(g_DEFAULT,Times(h_DEFAULT,x_))),x_),
    Condition(Plus(Simp(Times(Plus(Times(Sqr(b),d,e,g),Times(CN1,Sqr(a),d,f,h,m),Times(CN1,a,b,Subtract(Times(d,Plus(Times(f,g),Times(e,h))),Times(c,f,h,Plus(m,C1)))),Times(b,f,h,Subtract(Times(b,c),Times(a,d)),Plus(m,C1),x)),Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Times(Sqr(b),d,Subtract(Times(b,c),Times(a,d)),Plus(m,C1)),CN1)),x),Simp(Star(Times(Plus(Times(a,d,f,h,m),Times(b,Subtract(Times(d,Plus(Times(f,g),Times(e,h))),Times(c,f,h,Plus(m,C2))))),Power(Times(Sqr(b),d),CN1)),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h,m,n),x),EqQ(Plus(m,n,C2),C0),NeQ(m,CN1),Or(SumSimplerQ(m,C1),Not(SumSimplerQ(n,C1))))))
  );
}
