package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.IAST;
import com.google.common.base.Supplier;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules182 { 
  public static IAST RULES = List( 
IIntegrate(3641,Integrate(Times(Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),CN2),Plus(A_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),B_DEFAULT),Times(C_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))))),x_Symbol),
    Condition(Simp(Times(Plus(Times(c,BSymbol),Times(CN1,b,CSymbol),Times(CN1,Subtract(Times(a,CSymbol),Times(c,ASymbol)),Cos(Plus(d,Times(e,x)))),Times(Subtract(Times(a,BSymbol),Times(b,ASymbol)),Sin(Plus(d,Times(e,x))))),Power(Times(e,Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x)))))),CN1)),x),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol,CSymbol),x),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),EqQ(Subtract(Subtract(Times(a,ASymbol),Times(b,BSymbol)),Times(c,CSymbol)),C0)))),
IIntegrate(3642,Integrate(Times(Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),CN2),Plus(A_DEFAULT,Times(C_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))))),x_Symbol),
    Condition(Simp(Times(CN1,Plus(Times(b,CSymbol),Times(Subtract(Times(a,CSymbol),Times(c,ASymbol)),Cos(Plus(d,Times(e,x)))),Times(b,ASymbol,Sin(Plus(d,Times(e,x))))),Power(Times(e,Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x)))))),CN1)),x),And(FreeQ(List(a,b,c,d,e,ASymbol,CSymbol),x),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),EqQ(Subtract(Times(a,ASymbol),Times(c,CSymbol)),C0)))),
IIntegrate(3643,Integrate(Times(Plus(A_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),B_DEFAULT)),Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),CN2)),x_Symbol),
    Condition(Simp(Times(Plus(Times(c,BSymbol),Times(c,ASymbol,Cos(Plus(d,Times(e,x)))),Times(Subtract(Times(a,BSymbol),Times(b,ASymbol)),Sin(Plus(d,Times(e,x))))),Power(Times(e,Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x)))))),CN1)),x),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),EqQ(Subtract(Times(a,ASymbol),Times(b,BSymbol)),C0)))),
IIntegrate(3644,Integrate(Times(Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),CN2),Plus(A_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),B_DEFAULT),Times(C_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))))),x_Symbol),
    Condition(Plus(Simp(Times(Plus(Times(c,BSymbol),Times(CN1,b,CSymbol),Times(CN1,Subtract(Times(a,CSymbol),Times(c,ASymbol)),Cos(Plus(d,Times(e,x)))),Times(Subtract(Times(a,BSymbol),Times(b,ASymbol)),Sin(Plus(d,Times(e,x))))),Power(Times(e,Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x)))))),CN1)),x),Simp(Dist(Times(Subtract(Subtract(Times(a,ASymbol),Times(b,BSymbol)),Times(c,CSymbol)),Power(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),CN1)),Integrate(Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),CN1),x),x),x)),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol,CSymbol),x),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),NeQ(Subtract(Subtract(Times(a,ASymbol),Times(b,BSymbol)),Times(c,CSymbol)),C0)))),
IIntegrate(3645,Integrate(Times(Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),CN2),Plus(A_DEFAULT,Times(C_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))))),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Plus(Times(b,CSymbol),Times(Subtract(Times(a,CSymbol),Times(c,ASymbol)),Cos(Plus(d,Times(e,x)))),Times(b,ASymbol,Sin(Plus(d,Times(e,x))))),Power(Times(e,Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x)))))),CN1)),x),Simp(Dist(Times(Subtract(Times(a,ASymbol),Times(c,CSymbol)),Power(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),CN1)),Integrate(Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),CN1),x),x),x)),And(FreeQ(List(a,b,c,d,e,ASymbol,CSymbol),x),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),NeQ(Subtract(Times(a,ASymbol),Times(c,CSymbol)),C0)))),
IIntegrate(3646,Integrate(Times(Plus(A_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),B_DEFAULT)),Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),CN2)),x_Symbol),
    Condition(Plus(Simp(Times(Plus(Times(c,BSymbol),Times(c,ASymbol,Cos(Plus(d,Times(e,x)))),Times(Subtract(Times(a,BSymbol),Times(b,ASymbol)),Sin(Plus(d,Times(e,x))))),Power(Times(e,Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x)))))),CN1)),x),Simp(Dist(Times(Subtract(Times(a,ASymbol),Times(b,BSymbol)),Power(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),CN1)),Integrate(Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),CN1),x),x),x)),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),NeQ(Subtract(Times(a,ASymbol),Times(b,BSymbol)),C0)))),
IIntegrate(3647,Integrate(Times(Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),n_),Plus(A_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),B_DEFAULT),Times(C_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))))),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Plus(Times(c,BSymbol),Times(CN1,b,CSymbol),Times(CN1,Subtract(Times(a,CSymbol),Times(c,ASymbol)),Cos(Plus(d,Times(e,x)))),Times(Subtract(Times(a,BSymbol),Times(b,ASymbol)),Sin(Plus(d,Times(e,x))))),Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),Plus(n,C1)),Power(Times(e,Plus(n,C1),Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c))),CN1)),x),Simp(Dist(Power(Times(Plus(n,C1),Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c))),CN1),Integrate(Times(Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),Plus(n,C1)),Simp(Plus(Times(Plus(n,C1),Subtract(Subtract(Times(a,ASymbol),Times(b,BSymbol)),Times(c,CSymbol))),Times(Plus(n,C2),Subtract(Times(a,BSymbol),Times(b,ASymbol)),Cos(Plus(d,Times(e,x)))),Times(Plus(n,C2),Subtract(Times(a,CSymbol),Times(c,ASymbol)),Sin(Plus(d,Times(e,x))))),x)),x),x),x)),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol,CSymbol),x),LtQ(n,CN1),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),NeQ(n,CN2)))),
IIntegrate(3648,Integrate(Times(Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),n_),Plus(A_DEFAULT,Times(C_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))))),x_Symbol),
    Condition(Plus(Simp(Times(Plus(Times(b,CSymbol),Times(Subtract(Times(a,CSymbol),Times(c,ASymbol)),Cos(Plus(d,Times(e,x)))),Times(b,ASymbol,Sin(Plus(d,Times(e,x))))),Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),Plus(n,C1)),Power(Times(e,Plus(n,C1),Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c))),CN1)),x),Simp(Dist(Power(Times(Plus(n,C1),Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c))),CN1),Integrate(Times(Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),Plus(n,C1)),Simp(Plus(Times(Plus(n,C1),Subtract(Times(a,ASymbol),Times(c,CSymbol))),Times(CN1,Plus(n,C2),b,ASymbol,Cos(Plus(d,Times(e,x)))),Times(Plus(n,C2),Subtract(Times(a,CSymbol),Times(c,ASymbol)),Sin(Plus(d,Times(e,x))))),x)),x),x),x)),And(FreeQ(List(a,b,c,d,e,ASymbol,CSymbol),x),LtQ(n,CN1),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),NeQ(n,CN2)))),
IIntegrate(3649,Integrate(Times(Plus(A_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),B_DEFAULT)),Power(Plus(a_DEFAULT,Times($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times(c_DEFAULT,$($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),n_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Plus(Times(c,BSymbol),Times(c,ASymbol,Cos(Plus(d,Times(e,x)))),Times(Subtract(Times(a,BSymbol),Times(b,ASymbol)),Sin(Plus(d,Times(e,x))))),Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),Plus(n,C1)),Power(Times(e,Plus(n,C1),Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c))),CN1)),x),Simp(Dist(Power(Times(Plus(n,C1),Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c))),CN1),Integrate(Times(Power(Plus(a,Times(b,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),Plus(n,C1)),Simp(Subtract(Plus(Times(Plus(n,C1),Subtract(Times(a,ASymbol),Times(b,BSymbol))),Times(Plus(n,C2),Subtract(Times(a,BSymbol),Times(b,ASymbol)),Cos(Plus(d,Times(e,x))))),Times(Plus(n,C2),c,ASymbol,Sin(Plus(d,Times(e,x))))),x)),x),x),x)),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),LtQ(n,CN1),NeQ(Subtract(Subtract(Sqr(a),Sqr(b)),Sqr(c)),C0),NeQ(n,CN2)))),
IIntegrate(3650,Integrate(Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))),Times(c_DEFAULT,$($s("§tan"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),CN1),x_Symbol),
    Condition(Integrate(Times(Cos(Plus(d,Times(e,x))),Power(Plus(b,Times(a,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),CN1)),x),FreeQ(List(a,b,c,d,e),x))),
IIntegrate(3651,Integrate(Power(Plus(a_DEFAULT,Times($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times($($s("§cot"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),c_DEFAULT)),CN1),x_Symbol),
    Condition(Integrate(Times(Sin(Plus(d,Times(e,x))),Power(Plus(b,Times(a,Sin(Plus(d,Times(e,x)))),Times(c,Cos(Plus(d,Times(e,x))))),CN1)),x),FreeQ(List(a,b,c,d,e),x))),
IIntegrate(3652,Integrate(Times(Power($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))),Times(c_DEFAULT,$($s("§tan"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),n_DEFAULT)),x_Symbol),
    Condition(Integrate(Power(Plus(b,Times(a,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),n),x),And(FreeQ(List(a,b,c,d,e),x),IntegerQ(n)))),
IIntegrate(3653,Integrate(Times(Power(Plus(a_DEFAULT,Times($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times($($s("§cot"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),c_DEFAULT)),n_DEFAULT),Power($($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT)),x_Symbol),
    Condition(Integrate(Power(Plus(b,Times(a,Sin(Plus(d,Times(e,x)))),Times(c,Cos(Plus(d,Times(e,x))))),n),x),And(FreeQ(List(a,b,c,d,e),x),IntegerQ(n)))),
IIntegrate(3654,Integrate(Times(Power($($s("§cos"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))),Times(c_DEFAULT,$($s("§tan"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),n_)),x_Symbol),
    Condition(Simp(Dist(Times(Power(Cos(Plus(d,Times(e,x))),n),Power(Plus(a,Times(b,Sec(Plus(d,Times(e,x)))),Times(c,Tan(Plus(d,Times(e,x))))),n),Power(Power(Plus(b,Times(a,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),n),CN1)),Integrate(Power(Plus(b,Times(a,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),n),x),x),x),And(FreeQ(List(a,b,c,d,e),x),Not(IntegerQ(n))))),
IIntegrate(3655,Integrate(Times(Power(Plus(a_DEFAULT,Times($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times($($s("§cot"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),c_DEFAULT)),n_),Power($($s("§sin"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_)),x_Symbol),
    Condition(Simp(Dist(Times(Power(Sin(Plus(d,Times(e,x))),n),Power(Plus(a,Times(b,Csc(Plus(d,Times(e,x)))),Times(c,Cot(Plus(d,Times(e,x))))),n),Power(Power(Plus(b,Times(a,Sin(Plus(d,Times(e,x)))),Times(c,Cos(Plus(d,Times(e,x))))),n),CN1)),Integrate(Power(Plus(b,Times(a,Sin(Plus(d,Times(e,x)))),Times(c,Cos(Plus(d,Times(e,x))))),n),x),x),x),And(FreeQ(List(a,b,c,d,e),x),Not(IntegerQ(n))))),
IIntegrate(3656,Integrate(Times(Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))),Times(c_DEFAULT,$($s("§tan"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),m_)),x_Symbol),
    Condition(Integrate(Power(Power(Plus(b,Times(a,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),n),CN1),x),And(FreeQ(List(a,b,c,d,e),x),EqQ(Plus(m,n),C0),IntegerQ(n)))),
IIntegrate(3657,Integrate(Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),Power(Plus(a_DEFAULT,Times($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times($($s("§cot"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),c_DEFAULT)),m_)),x_Symbol),
    Condition(Integrate(Power(Power(Plus(b,Times(a,Sin(Plus(d,Times(e,x)))),Times(c,Cos(Plus(d,Times(e,x))))),n),CN1),x),And(FreeQ(List(a,b,c,d,e),x),EqQ(Plus(m,n),C0),IntegerQ(n)))),
IIntegrate(3658,Integrate(Times(Power($($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sec"),Plus(d_DEFAULT,Times(e_DEFAULT,x_)))),Times(c_DEFAULT,$($s("§tan"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))))),m_)),x_Symbol),
    Condition(Simp(Dist(Times(Power(Sec(Plus(d,Times(e,x))),n),Power(Plus(b,Times(a,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),n),Power(Power(Plus(a,Times(b,Sec(Plus(d,Times(e,x)))),Times(c,Tan(Plus(d,Times(e,x))))),n),CN1)),Integrate(Power(Power(Plus(b,Times(a,Cos(Plus(d,Times(e,x)))),Times(c,Sin(Plus(d,Times(e,x))))),n),CN1),x),x),x),And(FreeQ(List(a,b,c,d,e),x),EqQ(Plus(m,n),C0),Not(IntegerQ(n))))),
IIntegrate(3659,Integrate(Times(Power($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),n_DEFAULT),Power(Plus(a_DEFAULT,Times($($s("§csc"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),b_DEFAULT),Times($($s("§cot"),Plus(d_DEFAULT,Times(e_DEFAULT,x_))),c_DEFAULT)),m_)),x_Symbol),
    Condition(Simp(Dist(Times(Power(Csc(Plus(d,Times(e,x))),n),Power(Plus(b,Times(a,Sin(Plus(d,Times(e,x)))),Times(c,Cos(Plus(d,Times(e,x))))),n),Power(Power(Plus(a,Times(b,Csc(Plus(d,Times(e,x)))),Times(c,Cot(Plus(d,Times(e,x))))),n),CN1)),Integrate(Power(Power(Plus(b,Times(a,Sin(Plus(d,Times(e,x)))),Times(c,Cos(Plus(d,Times(e,x))))),n),CN1),x),x),x),And(FreeQ(List(a,b,c,d,e),x),EqQ(Plus(m,n),C0),Not(IntegerQ(n))))),
IIntegrate(3660,Integrate(Times(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),Plus(A_DEFAULT,Times(B_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Plus(Simp(Times(Plus(Times(C4,ASymbol,Plus(Times(C2,a),b)),Times(BSymbol,Plus(Times(C4,a),Times(C3,b)))),QQ(1L,8L),x),x),Negate(Simp(Times(b,BSymbol,Cos(Plus(e,Times(f,x))),Power(Sin(Plus(e,Times(f,x))),C3),Power(Times(C4,f),CN1)),x)),Negate(Simp(Times(Plus(Times(C4,ASymbol,b),Times(BSymbol,Plus(Times(C4,a),Times(C3,b)))),Cos(Plus(e,Times(f,x))),Sin(Plus(e,Times(f,x))),Power(Times(C8,f),CN1)),x))),FreeQ(List(a,b,e,f,ASymbol,BSymbol),x)))
  );
}
