package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.IAST;
import com.google.common.base.Supplier;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules174 { 
  public static IAST RULES = List( 
IIntegrate(3481,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),m_),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,BSymbol,Cos(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),Plus(m,CN1)),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),Plus(n,C1)),Power(Times(d,f,Plus(m,n,C1)),CN1)),x),Simp(Dist(Power(Times(d,Plus(m,n,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),Plus(m,CN2)),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),n),Simp(Plus(Times(Sqr(a),ASymbol,d,Plus(m,n,C1)),Times(b,BSymbol,Plus(Times(b,c,Plus(m,CN1)),Times(a,d,Plus(n,C1)))),Times(Subtract(Times(a,d,Plus(Times(C2,ASymbol,b),Times(a,BSymbol)),Plus(m,n,C1)),Times(b,BSymbol,Subtract(Times(a,c),Times(b,d,Plus(m,n))))),Sin(Plus(e,Times(f,x)))),Times(b,Subtract(Times(ASymbol,b,d,Plus(m,n,C1)),Times(BSymbol,Subtract(Times(b,c,m),Times(a,d,Plus(Times(C2,m),n))))),Sqr(Sin(Plus(e,Times(f,x)))))),x)),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol,n),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0),GtQ(m,C1),Not(And(IGtQ(n,C1),Or(Not(IntegerQ(m)),And(EqQ(a,C0),NeQ(c,C0)))))))),
IIntegrate(3482,Integrate(Times(Power(Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),QQ(-3L,2L)),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Plus(c_,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Plus(Simp(Dist(Times(BSymbol,d,Power(b,CN2)),Integrate(Times(Sqrt(Times(b,Sin(Plus(e,Times(f,x))))),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),CN1D2)),x),x),x),Integrate(Times(Plus(Times(ASymbol,c),Times(Plus(Times(BSymbol,c),Times(ASymbol,d)),Sin(Plus(e,Times(f,x))))),Power(Times(Power(Times(b,Sin(Plus(e,Times(f,x)))),QQ(3L,2L)),Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))))),CN1)),x)),And(FreeQ(List(b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(3483,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),QQ(-3L,2L)),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Sqrt(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))))),x_Symbol),
    Condition(Plus(Simp(Dist(Times(BSymbol,Power(b,CN1)),Integrate(Times(Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x)))))),Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),CN1D2)),x),x),x),Simp(Dist(Times(Subtract(Times(ASymbol,b),Times(a,BSymbol)),Power(b,CN1)),Integrate(Times(Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x)))))),Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),QQ(-3L,2L))),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(3484,Integrate(Times(Power(Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),CN1D2),Power(Plus(a_,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),QQ(-3L,2L)),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),x_Symbol),
    Condition(Plus(Simp(Times(C2,Subtract(Times(ASymbol,b),Times(a,BSymbol)),Cos(Plus(e,Times(f,x))),Power(Times(f,Subtract(Sqr(a),Sqr(b)),Sqrt(Plus(a,Times(b,Sin(Plus(e,Times(f,x)))))),Sqrt(Times(d,Sin(Plus(e,Times(f,x)))))),CN1)),x),Simp(Dist(Times(d,Power(Subtract(Sqr(a),Sqr(b)),CN1)),Integrate(Times(Plus(Times(ASymbol,b),Times(CN1,a,BSymbol),Times(Subtract(Times(a,ASymbol),Times(b,BSymbol)),Sin(Plus(e,Times(f,x))))),Power(Times(Sqrt(Plus(a,Times(b,Sin(Plus(e,Times(f,x)))))),Power(Times(d,Sin(Plus(e,Times(f,x)))),QQ(3L,2L))),CN1)),x),x),x)),And(FreeQ(List(a,b,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(3485,Integrate(Times(Power(Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),QQ(-3L,2L)),Plus(A_,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Simp(Times(CN2,ASymbol,Subtract(c,d),Tan(Plus(e,Times(f,x))),Power(Times(f,b,Sqr(c)),CN1),Rt(Times(Plus(c,d),Power(b,CN1)),C2),Sqrt(Times(c,Plus(C1,Csc(Plus(e,Times(f,x)))),Power(Subtract(c,d),CN1))),Sqrt(Times(c,Subtract(C1,Csc(Plus(e,Times(f,x)))),Power(Plus(c,d),CN1))),EllipticE(ArcSin(Times(Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x)))))),Power(Times(b,Sin(Plus(e,Times(f,x)))),CN1D2),Power(Rt(Times(Plus(c,d),Power(b,CN1)),C2),CN1))),Times(CN1,Plus(c,d),Power(Subtract(c,d),CN1)))),x),And(FreeQ(List(b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Sqr(c),Sqr(d)),C0),EqQ(ASymbol,BSymbol),PosQ(Times(Plus(c,d),Power(b,CN1)))))),
IIntegrate(3486,Integrate(Times(Power(Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),QQ(-3L,2L)),Plus(A_,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Simp(Dist(Times(CN1,Sqrt(Times(CN1,b,Sin(Plus(e,Times(f,x))))),Power(Times(b,Sin(Plus(e,Times(f,x)))),CN1D2)),Integrate(Times(Plus(ASymbol,Times(BSymbol,Sin(Plus(e,Times(f,x))))),Power(Times(Power(Times(CN1,b,Sin(Plus(e,Times(f,x)))),QQ(3L,2L)),Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))))),CN1)),x),x),x),And(FreeQ(List(b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Sqr(c),Sqr(d)),C0),EqQ(ASymbol,BSymbol),NegQ(Times(Plus(c,d),Power(b,CN1)))))),
IIntegrate(3487,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),QQ(-3L,2L)),Plus(A_,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Simp(Times(CN2,ASymbol,Subtract(c,d),Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),Power(Times(f,Sqr(Subtract(Times(b,c),Times(a,d))),Rt(Times(Plus(a,b),Power(Plus(c,d),CN1)),C2),Cos(Plus(e,Times(f,x)))),CN1),Sqrt(Times(Subtract(Times(b,c),Times(a,d)),Plus(C1,Sin(Plus(e,Times(f,x)))),Power(Times(Subtract(c,d),Plus(a,Times(b,Sin(Plus(e,Times(f,x)))))),CN1))),Sqrt(Times(CN1,Subtract(Times(b,c),Times(a,d)),Subtract(C1,Sin(Plus(e,Times(f,x)))),Power(Times(Plus(c,d),Plus(a,Times(b,Sin(Plus(e,Times(f,x)))))),CN1))),EllipticE(ArcSin(Times(Rt(Times(Plus(a,b),Power(Plus(c,d),CN1)),C2),Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x)))))),Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),CN1D2))),Times(Subtract(a,b),Plus(c,d),Power(Times(Plus(a,b),Subtract(c,d)),CN1)))),x),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0),EqQ(ASymbol,BSymbol),PosQ(Times(Plus(a,b),Power(Plus(c,d),CN1)))))),
IIntegrate(3488,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),QQ(-3L,2L)),Plus(A_,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Simp(Dist(Times(Sqrt(Subtract(Negate(c),Times(d,Sin(Plus(e,Times(f,x)))))),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),CN1D2)),Integrate(Times(Plus(ASymbol,Times(BSymbol,Sin(Plus(e,Times(f,x))))),Power(Times(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),QQ(3L,2L)),Sqrt(Subtract(Negate(c),Times(d,Sin(Plus(e,Times(f,x))))))),CN1)),x),x),x),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0),EqQ(ASymbol,BSymbol),NegQ(Times(Plus(a,b),Power(Plus(c,d),CN1)))))),
IIntegrate(3489,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),QQ(-3L,2L)),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Subtract(Simp(Dist(Times(Subtract(ASymbol,BSymbol),Power(Subtract(a,b),CN1)),Integrate(Power(Times(Sqrt(Plus(a,Times(b,Sin(Plus(e,Times(f,x)))))),Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))))),CN1),x),x),x),Simp(Dist(Times(Subtract(Times(ASymbol,b),Times(a,BSymbol)),Power(Subtract(a,b),CN1)),Integrate(Times(Plus(C1,Sin(Plus(e,Times(f,x)))),Power(Times(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),QQ(3L,2L)),Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))))),CN1)),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0),NeQ(ASymbol,BSymbol)))),
IIntegrate(3490,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),m_),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_)),x_Symbol),
    Condition(Plus(Simp(Times(Subtract(Times(BSymbol,a),Times(ASymbol,b)),Cos(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),n),Power(Times(f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x),Simp(Dist(Power(Times(Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Integrate(Times(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),Plus(n,CN1)),Simp(Subtract(Plus(Times(c,Subtract(Times(a,ASymbol),Times(b,BSymbol)),Plus(m,C1)),Times(d,n,Subtract(Times(ASymbol,b),Times(a,BSymbol))),Times(Subtract(Times(d,Subtract(Times(a,ASymbol),Times(b,BSymbol)),Plus(m,C1)),Times(c,Subtract(Times(ASymbol,b),Times(a,BSymbol)),Plus(m,C2))),Sin(Plus(e,Times(f,x))))),Times(d,Subtract(Times(ASymbol,b),Times(a,BSymbol)),Plus(m,n,C2),Sqr(Sin(Plus(e,Times(f,x)))))),x)),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0),LtQ(m,CN1),GtQ(n,C0)))),
IIntegrate(3491,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),m_),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Subtract(Times(ASymbol,Sqr(b)),Times(a,b,BSymbol)),Cos(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),Plus(C1,n)),Power(Times(f,Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Sqr(a),Sqr(b))),CN1)),x),Simp(Dist(Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Sqr(a),Sqr(b))),CN1),Integrate(Times(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),n),Simp(Subtract(Plus(Times(Subtract(Times(a,ASymbol),Times(b,BSymbol)),Subtract(Times(b,c),Times(a,d)),Plus(m,C1)),Times(b,d,Subtract(Times(ASymbol,b),Times(a,BSymbol)),Plus(m,n,C2)),Times(Subtract(Times(ASymbol,b),Times(a,BSymbol)),Subtract(Times(a,d,Plus(m,C1)),Times(b,c,Plus(m,C2))),Sin(Plus(e,Times(f,x))))),Times(b,d,Subtract(Times(ASymbol,b),Times(a,BSymbol)),Plus(m,n,C3),Sqr(Sin(Plus(e,Times(f,x)))))),x)),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol,n),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0),RationalQ(m),Less(m,CN1),Or(And(EqQ(a,C0),IntegerQ(m),Not(IntegerQ(n))),Not(And(IntegerQ(Times(C2,n)),LtQ(n,CN1),Or(And(IntegerQ(n),Not(IntegerQ(m))),EqQ(a,C0)))))))),
IIntegrate(3492,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1)),x_Symbol),
    Condition(Plus(Simp(Dist(Times(Subtract(Times(ASymbol,b),Times(a,BSymbol)),Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),CN1),x),x),x),Simp(Dist(Times(Subtract(Times(BSymbol,c),Times(ASymbol,d)),Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),CN1),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(3493,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),m_),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Dist(Times(BSymbol,Power(d,CN1)),Integrate(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),m),x),x),x),Simp(Dist(Times(Subtract(Times(BSymbol,c),Times(ASymbol,d)),Power(d,CN1)),Integrate(Times(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),m),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),CN1)),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol,m),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(3494,Integrate(Times(Sqrt(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_)),x_Symbol),
    Condition(Plus(Simp(Times(CN2,BSymbol,Cos(Plus(e,Times(f,x))),Sqrt(Plus(a,Times(b,Sin(Plus(e,Times(f,x)))))),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),n),Power(Times(f,Plus(Times(C2,n),C3)),CN1)),x),Simp(Dist(Power(Plus(Times(C2,n),C3),CN1),Integrate(Times(Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),Plus(n,CN1)),Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),CN1D2),Simp(Plus(Times(a,ASymbol,c,Plus(Times(C2,n),C3)),Times(BSymbol,Plus(Times(b,c),Times(C2,a,d,n))),Times(Plus(Times(BSymbol,Plus(Times(a,c),Times(b,d)),Plus(Times(C2,n),C1)),Times(ASymbol,Plus(Times(b,c),Times(a,d)),Plus(Times(C2,n),C3))),Sin(Plus(e,Times(f,x)))),Times(Plus(Times(ASymbol,b,d,Plus(Times(C2,n),C3)),Times(BSymbol,Plus(Times(a,d),Times(C2,b,c,n)))),Sqr(Sin(Plus(e,Times(f,x)))))),x)),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0),EqQ(Sqr(n),C1D4)))),
IIntegrate(3495,Integrate(Times(Power($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),CN1D2),Power(Plus(a_,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Plus(A_,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),x_Symbol),
    Condition(Simp(Times(C4,ASymbol,Power(Times(f,Sqrt(Plus(a,b))),CN1),EllipticPi(CN1,Negate(ArcSin(Times(Cos(Plus(e,Times(f,x))),Power(Plus(C1,Sin(Plus(e,Times(f,x)))),CN1)))),Times(CN1,Subtract(a,b),Power(Plus(a,b),CN1)))),x),And(FreeQ(List(a,b,e,f,ASymbol,BSymbol),x),GtQ(b,C0),GtQ(Subtract(Sqr(b),Sqr(a)),C0),EqQ(ASymbol,BSymbol)))),
IIntegrate(3496,Integrate(Times(Power(Times(d_,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),CN1D2),Power(Plus(a_,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Plus(A_,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),x_Symbol),
    Condition(Simp(Dist(Times(Sqrt(Sin(Plus(e,Times(f,x)))),Power(Times(d,Sin(Plus(e,Times(f,x)))),CN1D2)),Integrate(Times(Plus(ASymbol,Times(BSymbol,Sin(Plus(e,Times(f,x))))),Power(Times(Sqrt(Sin(Plus(e,Times(f,x)))),Sqrt(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))))),CN1)),x),x),x),And(FreeQ(List(a,b,e,f,d,ASymbol,BSymbol),x),GtQ(b,C0),GtQ(Subtract(Sqr(b),Sqr(a)),C0),EqQ(ASymbol,BSymbol)))),
IIntegrate(3497,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),CN1D2)),x_Symbol),
    Condition(Subtract(Simp(Dist(Times(BSymbol,Power(d,CN1)),Integrate(Times(Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x)))))),Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),CN1D2)),x),x),x),Simp(Dist(Times(Subtract(Times(BSymbol,c),Times(ASymbol,d)),Power(d,CN1)),Integrate(Power(Times(Sqrt(Plus(a,Times(b,Sin(Plus(e,Times(f,x)))))),Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))))),CN1),x),x),x)),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(3498,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),m_),Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(a,Times(b,Sin(Plus(e,Times(f,x))))),m),Plus(ASymbol,Times(BSymbol,Sin(Plus(e,Times(f,x))))),Power(Plus(c,Times(d,Sin(Plus(e,Times(f,x))))),n)),x),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol,m,n),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(3499,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),m_DEFAULT),Power(Plus(A_DEFAULT,Times(B_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),p_),Power(Plus(c_,Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_DEFAULT)),x_Symbol),
    Condition(Simp(Dist(Times(Sqrt(Plus(a,Times(b,Sin(Plus(e,Times(f,x)))))),Sqrt(Plus(c,Times(d,Sin(Plus(e,Times(f,x)))))),Power(Times(f,Cos(Plus(e,Times(f,x)))),CN1)),Subst(Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,CN1D2)),Power(Plus(c,Times(d,x)),Plus(n,CN1D2)),Power(Plus(ASymbol,Times(BSymbol,x)),p)),x),x,Sin(Plus(e,Times(f,x)))),x),x),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol,m,n,p),x),EqQ(Plus(Times(b,c),Times(a,d)),C0),EqQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(3500,Integrate(Times(Power(Plus(A_DEFAULT,Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),B_DEFAULT)),p_),Power(Plus(Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_DEFAULT),Power(Plus(Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_),n_DEFAULT)),x_Symbol),
    Condition(Simp(Dist(Times(CN1,Sqrt(Plus(a,Times(b,Cos(Plus(e,Times(f,x)))))),Sqrt(Plus(c,Times(d,Cos(Plus(e,Times(f,x)))))),Power(Times(f,Sin(Plus(e,Times(f,x)))),CN1)),Subst(Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,CN1D2)),Power(Plus(c,Times(d,x)),Plus(n,CN1D2)),Power(Plus(ASymbol,Times(BSymbol,x)),p)),x),x,Cos(Plus(e,Times(f,x)))),x),x),And(FreeQ(List(a,b,c,d,e,f,ASymbol,BSymbol,m,n,p),x),EqQ(Plus(Times(b,c),Times(a,d)),C0),EqQ(Subtract(Sqr(a),Sqr(b)),C0))))
  );
}
