package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules323 { 
  public static IAST RULES = List( 
IIntegrate(6461,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,Power(x_,n_))),b_DEFAULT)),p_),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Integrate(Times(Power(x,m),Power(Plus(a,Times(b,ArcTanh(Power(Times(Power(x,n),c),CN1)))),p)),x),And(FreeQ(List(a,b,c,m),x),IGtQ(p,C1),ILtQ(n,C0)))),
IIntegrate(6462,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,Power(x_,n_))),b_DEFAULT)),p_),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(With(list(Set(k,Denominator(n))),Simp(Star(k,Subst(Integrate(Times(Power(x,Subtract(Times(k,Plus(m,C1)),C1)),Power(Plus(a,Times(b,ArcTanh(Times(c,Power(x,Times(k,n)))))),p)),x),x,Power(x,Power(k,CN1)))),x)),And(FreeQ(List(a,b,c,m),x),IGtQ(p,C1),FractionQ(n)))),
IIntegrate(6463,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,Power(x_,n_))),b_DEFAULT)),p_),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(With(list(Set(k,Denominator(n))),Simp(Star(k,Subst(Integrate(Times(Power(x,Subtract(Times(k,Plus(m,C1)),C1)),Power(Plus(a,Times(b,ArcCoth(Times(c,Power(x,Times(k,n)))))),p)),x),x,Power(x,Power(k,CN1)))),x)),And(FreeQ(List(a,b,c,m),x),IGtQ(p,C1),FractionQ(n)))),
IIntegrate(6464,Integrate(Times(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,Power(x_,n_DEFAULT))),b_DEFAULT)),Power(Times(d_,x_),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Times(d,x),Plus(m,C1)),Plus(a,Times(b,ArcTanh(Times(c,Power(x,n))))),Power(Times(d,Plus(m,C1)),CN1)),x),Simp(Star(Times(b,c,n,Power(Times(Power(d,n),Plus(m,C1)),CN1)),Integrate(Times(Power(Times(d,x),Plus(m,n)),Power(Subtract(C1,Times(Sqr(c),Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,m,n),x),IntegerQ(n),NeQ(m,CN1)))),
IIntegrate(6465,Integrate(Times(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,Power(x_,n_DEFAULT))),b_DEFAULT)),Power(Times(d_,x_),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Times(d,x),Plus(m,C1)),Plus(a,Times(b,ArcCoth(Times(c,Power(x,n))))),Power(Times(d,Plus(m,C1)),CN1)),x),Simp(Star(Times(b,c,n,Power(Times(Power(d,n),Plus(m,C1)),CN1)),Integrate(Times(Power(Times(d,x),Plus(m,n)),Power(Subtract(C1,Times(Sqr(c),Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,m,n),x),IntegerQ(n),NeQ(m,CN1)))),
IIntegrate(6466,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,Power(x_,n_DEFAULT))),b_DEFAULT)),p_DEFAULT),Power(Times(d_,x_),m_)),x_Symbol),
    Condition(Simp(Star(Times(Power(d,IntPart(m)),Power(Times(d,x),FracPart(m)),Power(Power(x,FracPart(m)),CN1)),Integrate(Times(Power(x,m),Power(Plus(a,Times(b,ArcTanh(Times(c,Power(x,n))))),p)),x)),x),And(FreeQ(List(a,b,c,d,m,n),x),IGtQ(p,C0),Or(EqQ(p,C1),RationalQ(m,n))))),
IIntegrate(6467,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,Power(x_,n_DEFAULT))),b_DEFAULT)),p_DEFAULT),Power(Times(d_,x_),m_)),x_Symbol),
    Condition(Simp(Star(Times(Power(d,IntPart(m)),Power(Times(d,x),FracPart(m)),Power(Power(x,FracPart(m)),CN1)),Integrate(Times(Power(x,m),Power(Plus(a,Times(b,ArcCoth(Times(c,Power(x,n))))),p)),x)),x),And(FreeQ(List(a,b,c,d,m,n),x),IGtQ(p,C0),Or(EqQ(p,C1),RationalQ(m,n))))),
IIntegrate(6468,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,Power(x_,n_DEFAULT))),b_DEFAULT)),p_DEFAULT),Power(Times(d_DEFAULT,x_),m_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Times(d,x),m),Power(Plus(a,Times(b,ArcTanh(Times(c,Power(x,n))))),p)),x),FreeQ(List(a,b,c,d,m,n,p),x))),
IIntegrate(6469,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,Power(x_,n_DEFAULT))),b_DEFAULT)),p_DEFAULT),Power(Times(d_DEFAULT,x_),m_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Times(d,x),m),Power(Plus(a,Times(b,ArcCoth(Times(c,Power(x,n))))),p)),x),FreeQ(List(a,b,c,d,m,n,p),x))),
IIntegrate(6470,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,x_)),b_DEFAULT)),p_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Power(Plus(a,Times(b,ArcTanh(Times(c,x)))),p),Log(Times(C2,Power(Plus(C1,Times(e,x,Power(d,CN1))),CN1))),Power(e,CN1)),x),Simp(Star(Times(b,c,p,Power(e,CN1)),Integrate(Times(Power(Plus(a,Times(b,ArcTanh(Times(c,x)))),Subtract(p,C1)),Log(Times(C2,Power(Plus(C1,Times(e,x,Power(d,CN1))),CN1))),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),IGtQ(p,C0),EqQ(Subtract(Times(Sqr(c),Sqr(d)),Sqr(e)),C0)))),
IIntegrate(6471,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,x_)),b_DEFAULT)),p_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Power(Plus(a,Times(b,ArcCoth(Times(c,x)))),p),Log(Times(C2,Power(Plus(C1,Times(e,x,Power(d,CN1))),CN1))),Power(e,CN1)),x),Simp(Star(Times(b,c,p,Power(e,CN1)),Integrate(Times(Power(Plus(a,Times(b,ArcCoth(Times(c,x)))),Subtract(p,C1)),Log(Times(C2,Power(Plus(C1,Times(e,x,Power(d,CN1))),CN1))),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e),x),IGtQ(p,C0),EqQ(Subtract(Times(Sqr(c),Sqr(d)),Sqr(e)),C0)))),
IIntegrate(6472,Integrate(Times(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,x_)),b_DEFAULT)),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Plus(a,Times(b,ArcTanh(Times(c,x)))),Log(Times(C2,Power(Plus(C1,Times(c,x)),CN1))),Power(e,CN1)),x),Simp(Times(Plus(a,Times(b,ArcTanh(Times(c,x)))),Log(Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1))),Power(e,CN1)),x),Simp(Star(Times(b,c,Power(e,CN1)),Integrate(Times(Log(Times(C2,Power(Plus(C1,Times(c,x)),CN1))),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x)),x),Negate(Simp(Star(Times(b,c,Power(e,CN1)),Integrate(Times(Log(Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1))),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Times(Sqr(c),Sqr(d)),Sqr(e)),C0)))),
IIntegrate(6473,Integrate(Times(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,x_)),b_DEFAULT)),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Plus(a,Times(b,ArcCoth(Times(c,x)))),Log(Times(C2,Power(Plus(C1,Times(c,x)),CN1))),Power(e,CN1)),x),Simp(Times(Plus(a,Times(b,ArcCoth(Times(c,x)))),Log(Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1))),Power(e,CN1)),x),Simp(Star(Times(b,c,Power(e,CN1)),Integrate(Times(Log(Times(C2,Power(Plus(C1,Times(c,x)),CN1))),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x)),x),Negate(Simp(Star(Times(b,c,Power(e,CN1)),Integrate(Times(Log(Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1))),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Times(Sqr(c),Sqr(d)),Sqr(e)),C0)))),
IIntegrate(6474,Integrate(Times(Sqr(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,x_)),b_DEFAULT))),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Sqr(Plus(a,Times(b,ArcTanh(Times(c,x))))),Log(Times(C2,Power(Plus(C1,Times(c,x)),CN1))),Power(e,CN1)),x),Simp(Times(Sqr(Plus(a,Times(b,ArcTanh(Times(c,x))))),Log(Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1))),Power(e,CN1)),x),Simp(Times(b,Plus(a,Times(b,ArcTanh(Times(c,x)))),PolyLog(C2,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(e,CN1)),x),Negate(Simp(Times(b,Plus(a,Times(b,ArcTanh(Times(c,x)))),PolyLog(C2,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(e,CN1)),x)),Simp(Times(Sqr(b),PolyLog(C3,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(Times(C2,e),CN1)),x),Negate(Simp(Times(Sqr(b),PolyLog(C3,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(Times(C2,e),CN1)),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Times(Sqr(c),Sqr(d)),Sqr(e)),C0)))),
IIntegrate(6475,Integrate(Times(Sqr(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,x_)),b_DEFAULT))),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Sqr(Plus(a,Times(b,ArcCoth(Times(c,x))))),Log(Times(C2,Power(Plus(C1,Times(c,x)),CN1))),Power(e,CN1)),x),Simp(Times(Sqr(Plus(a,Times(b,ArcCoth(Times(c,x))))),Log(Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1))),Power(e,CN1)),x),Simp(Times(b,Plus(a,Times(b,ArcCoth(Times(c,x)))),PolyLog(C2,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(e,CN1)),x),Negate(Simp(Times(b,Plus(a,Times(b,ArcCoth(Times(c,x)))),PolyLog(C2,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(e,CN1)),x)),Simp(Times(Sqr(b),PolyLog(C3,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(Times(C2,e),CN1)),x),Negate(Simp(Times(Sqr(b),PolyLog(C3,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(Times(C2,e),CN1)),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Times(Sqr(c),Sqr(d)),Sqr(e)),C0)))),
IIntegrate(6476,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,x_)),b_DEFAULT)),C3),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Power(Plus(a,Times(b,ArcTanh(Times(c,x)))),C3),Log(Times(C2,Power(Plus(C1,Times(c,x)),CN1))),Power(e,CN1)),x),Simp(Times(Power(Plus(a,Times(b,ArcTanh(Times(c,x)))),C3),Log(Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1))),Power(e,CN1)),x),Simp(Times(C3,b,Sqr(Plus(a,Times(b,ArcTanh(Times(c,x))))),PolyLog(C2,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(Times(C2,e),CN1)),x),Negate(Simp(Times(C3,b,Sqr(Plus(a,Times(b,ArcTanh(Times(c,x))))),PolyLog(C2,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(Times(C2,e),CN1)),x)),Simp(Times(C3,Sqr(b),Plus(a,Times(b,ArcTanh(Times(c,x)))),PolyLog(C3,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(Times(C2,e),CN1)),x),Negate(Simp(Times(C3,Sqr(b),Plus(a,Times(b,ArcTanh(Times(c,x)))),PolyLog(C3,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(Times(C2,e),CN1)),x)),Simp(Times(C3,Power(b,C3),PolyLog(C4,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(Times(C4,e),CN1)),x),Negate(Simp(Times(C3,Power(b,C3),PolyLog(C4,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(Times(C4,e),CN1)),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Times(Sqr(c),Sqr(d)),Sqr(e)),C0)))),
IIntegrate(6477,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,x_)),b_DEFAULT)),C3),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Power(Plus(a,Times(b,ArcCoth(Times(c,x)))),C3),Log(Times(C2,Power(Plus(C1,Times(c,x)),CN1))),Power(e,CN1)),x),Simp(Times(Power(Plus(a,Times(b,ArcCoth(Times(c,x)))),C3),Log(Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1))),Power(e,CN1)),x),Simp(Times(C3,b,Sqr(Plus(a,Times(b,ArcCoth(Times(c,x))))),PolyLog(C2,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(Times(C2,e),CN1)),x),Negate(Simp(Times(C3,b,Sqr(Plus(a,Times(b,ArcCoth(Times(c,x))))),PolyLog(C2,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(Times(C2,e),CN1)),x)),Simp(Times(C3,Sqr(b),Plus(a,Times(b,ArcCoth(Times(c,x)))),PolyLog(C3,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(Times(C2,e),CN1)),x),Negate(Simp(Times(C3,Sqr(b),Plus(a,Times(b,ArcCoth(Times(c,x)))),PolyLog(C3,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(Times(C2,e),CN1)),x)),Simp(Times(C3,Power(b,C3),PolyLog(C4,Subtract(C1,Times(C2,Power(Plus(C1,Times(c,x)),CN1)))),Power(Times(C4,e),CN1)),x),Negate(Simp(Times(C3,Power(b,C3),PolyLog(C4,Subtract(C1,Times(C2,c,Plus(d,Times(e,x)),Power(Times(Plus(Times(c,d),e),Plus(C1,Times(c,x))),CN1)))),Power(Times(C4,e),CN1)),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Times(Sqr(c),Sqr(d)),Sqr(e)),C0)))),
IIntegrate(6478,Integrate(Times(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,x_)),b_DEFAULT)),Power(Plus(d_,Times(e_DEFAULT,x_)),q_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(d,Times(e,x)),Plus(q,C1)),Plus(a,Times(b,ArcTanh(Times(c,x)))),Power(Times(e,Plus(q,C1)),CN1)),x),Simp(Star(Times(b,c,Power(Times(e,Plus(q,C1)),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Plus(q,C1)),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,q),x),NeQ(q,CN1)))),
IIntegrate(6479,Integrate(Times(Plus(a_DEFAULT,Times(ArcCoth(Times(c_DEFAULT,x_)),b_DEFAULT)),Power(Plus(d_,Times(e_DEFAULT,x_)),q_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(d,Times(e,x)),Plus(q,C1)),Plus(a,Times(b,ArcCoth(Times(c,x)))),Power(Times(e,Plus(q,C1)),CN1)),x),Simp(Star(Times(b,c,Power(Times(e,Plus(q,C1)),CN1)),Integrate(Times(Power(Plus(d,Times(e,x)),Plus(q,C1)),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,q),x),NeQ(q,CN1)))),
IIntegrate(6480,Integrate(Times(Power(Plus(a_DEFAULT,Times(ArcTanh(Times(c_DEFAULT,x_)),b_DEFAULT)),p_),Power(Plus(d_,Times(e_DEFAULT,x_)),q_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(d,Times(e,x)),Plus(q,C1)),Power(Plus(a,Times(b,ArcTanh(Times(c,x)))),p),Power(Times(e,Plus(q,C1)),CN1)),x),Simp(Star(Times(b,c,p,Power(Times(e,Plus(q,C1)),CN1)),Integrate(ExpandIntegrand(Power(Plus(a,Times(b,ArcTanh(Times(c,x)))),Subtract(p,C1)),Times(Power(Plus(d,Times(e,x)),Plus(q,C1)),Power(Subtract(C1,Times(Sqr(c),Sqr(x))),CN1)),x),x)),x)),And(FreeQ(List(a,b,c,d,e),x),IGtQ(p,C1),IntegerQ(q),NeQ(q,CN1))))
  );
}
