package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules110 { 
  public static IAST RULES = List( 
IIntegrate(2201,Integrate(Times($p("§px"),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(With(list(Set(m,Expon($s("§px"),x,Min))),Condition(Integrate(Times(Power(x,m),ExpandToSum(Times($s("§px"),Power(Power(x,m),CN1)),x),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p)),x),And(GtQ(m,C0),Not(MatchQ($s("§px"),Times(Power(x,m),u_DEFAULT)))))),And(FreeQ(List(a,b,c,p),x),PolyQ($s("§px"),x)))),
IIntegrate(2202,Integrate(Times($p("§pn"),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Module(list(Set(n,Expon($s("§pn"),x)),k),Plus(Integrate(Times(Sum(Times(Coeff($s("§pn"),x,Times(C2,k)),Power(x,Times(C2,k))),list(k,C0,Times(C1D2,n))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p)),x),Integrate(Times(x,Sum(Times(Coeff($s("§pn"),x,Plus(Times(C2,k),C1)),Power(x,Times(C2,k))),list(k,C0,Times(C1D2,Subtract(n,C1)))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p)),x))),And(FreeQ(List(a,b,c,p),x),PolyQ($s("§pn"),x),Not(PolyQ($s("§pn"),Sqr(x)))))),
IIntegrate(2203,Integrate(Times($p("§px"),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set(d,Coeff($s("§px"),x,C0)),Set(e,Coeff($s("§px"),x,C2)),Set(f,Coeff($s("§px"),x,C4))),Condition(Simp(Times(d,x,Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Power(a,CN1)),x),And(EqQ(Subtract(Times(a,e),Times(b,d,Plus(Times(C2,p),C3))),C0),EqQ(Subtract(Times(a,f),Times(c,d,Plus(Times(C4,p),C5))),C0)))),And(FreeQ(List(a,b,c,p),x),PolyQ($s("§px"),Sqr(x)),EqQ(Expon($s("§px"),x),C4)))),
IIntegrate(2204,Integrate(Times($p("§px"),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(With(List(Set(d,Coeff($s("§px"),x,C0)),Set(e,Coeff($s("§px"),x,C2)),Set(f,Coeff($s("§px"),x,C4)),Set(g,Coeff($s("§px"),x,C6))),Condition(Simp(Times(x,Plus(Times(C3,a,d),Times(Subtract(Times(a,e),Times(b,d,Plus(Times(C2,p),C3))),Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Power(Times(C3,Sqr(a)),CN1)),x),And(EqQ(Subtract(Times(C3,Sqr(a),g),Times(c,Plus(Times(C4,p),C7),Subtract(Times(a,e),Times(b,d,Plus(Times(C2,p),C3))))),C0),EqQ(Subtract(Subtract(Times(C3,Sqr(a),f),Times(C3,a,c,d,Plus(Times(C4,p),C5))),Times(b,Plus(Times(C2,p),C5),Subtract(Times(a,e),Times(b,d,Plus(Times(C2,p),C3))))),C0)))),And(FreeQ(List(a,b,c,p),x),PolyQ($s("§px"),Sqr(x)),EqQ(Expon($s("§px"),x),C6)))),
IIntegrate(2205,Integrate(Times($p("§px"),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times($s("§px"),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1)),x),x),And(FreeQ(list(a,b,c),x),PolyQ($s("§px"),Sqr(x)),Greater(Expon($s("§px"),Sqr(x)),C1)))),
IIntegrate(2206,Integrate(Times($p("§px"),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(With(list(Set(d,Coeff(PolynomialRemainder($s("§px"),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),x,C0)),Set(e,Coeff(PolynomialRemainder($s("§px"),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),x,C2))),Plus(Simp(Times(x,Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Subtract(Subtract(Times(a,b,e),Times(d,Subtract(Sqr(b),Times(C2,a,c)))),Times(c,Subtract(Times(b,d),Times(C2,a,e)),Sqr(x))),Power(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x),Simp(Star(Power(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),ExpandToSum(Plus(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),PolynomialQuotient($s("§px"),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x)),Times(Sqr(b),d,Plus(Times(C2,p),C3)),Times(CN1,C2,a,c,d,Plus(Times(C4,p),C5)),Times(CN1,a,b,e),Times(c,Plus(Times(C4,p),C7),Subtract(Times(b,d),Times(C2,a,e)),Sqr(x))),x)),x)),x))),And(FreeQ(list(a,b,c),x),PolyQ($s("§px"),Sqr(x)),Greater(Expon($s("§px"),Sqr(x)),C1),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1)))),
IIntegrate(2207,Integrate(Times($p("§px"),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(With(list(Set(n,Expon($s("§px"),Sqr(x))),Set(e,Coeff($s("§px"),Sqr(x),Expon($s("§px"),Sqr(x))))),Plus(Simp(Times(e,Power(x,Subtract(Times(C2,n),C3)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Power(Times(c,Plus(Times(C2,n),Times(C4,p),C1)),CN1)),x),Simp(Star(Power(Times(c,Plus(Times(C2,n),Times(C4,p),C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p),ExpandToSum(Subtract(Subtract(Subtract(Times(c,Plus(Times(C2,n),Times(C4,p),C1),$s("§px")),Times(a,e,Subtract(Times(C2,n),C3),Power(x,Subtract(Times(C2,n),C4)))),Times(b,e,Subtract(Plus(Times(C2,n),Times(C2,p)),C1),Power(x,Subtract(Times(C2,n),C2)))),Times(c,e,Plus(Times(C2,n),Times(C4,p),C1),Power(x,Times(C2,n)))),x)),x)),x))),And(FreeQ(List(a,b,c,p),x),PolyQ($s("§px"),Sqr(x)),Greater(Expon($s("§px"),Sqr(x)),C1),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(LtQ(p,CN1))))),
IIntegrate(2208,Integrate(Times($p("§p4x"),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(ASymbol,Coeff($s("§p4x"),x,C0)),Set(BSymbol,Coeff($s("§p4x"),x,C2)),Set(CSymbol,Coeff($s("§p4x"),x,C4))),Plus(Simp(Times(CSymbol,x,Power(Plus(d,Times(e,Sqr(x))),q),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4)))),Power(Times(c,Plus(Times(C2,q),C3)),CN1)),x),Simp(Star(Power(Times(c,Plus(Times(C2,q),C3)),CN1),Integrate(Times(Power(Plus(d,Times(e,Sqr(x))),Subtract(q,C1)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),Simp(Plus(Times(ASymbol,c,d,Plus(Times(C2,q),C3)),Times(CN1,a,CSymbol,d),Times(Subtract(Times(c,Plus(Times(BSymbol,d),Times(ASymbol,e)),Plus(Times(C2,q),C3)),Times(CSymbol,Plus(Times(C2,b,d),Times(a,e),Times(C2,a,e,q)))),Sqr(x)),Times(Subtract(Times(BSymbol,c,e,Plus(Times(C2,q),C3)),Times(C2,CSymbol,Plus(Times(b,e),Times(CN1,c,d,q),Times(b,e,q)))),Power(x,C4))),x)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),PolyQ($s("§p4x"),Sqr(x)),EqQ(Expon($s("§p4x"),x),C4),IGtQ(q,C0)))),
IIntegrate(2209,Integrate(Times($p("§p4x"),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(ASymbol,Coeff($s("§p4x"),x,C0)),Set(BSymbol,Coeff($s("§p4x"),x,C2)),Set(CSymbol,Coeff($s("§p4x"),x,C4))),Plus(Simp(Times(CSymbol,x,Power(Plus(d,Times(e,Sqr(x))),q),Sqrt(Plus(a,Times(c,Power(x,C4)))),Power(Times(c,Plus(Times(C2,q),C3)),CN1)),x),Simp(Star(Power(Times(c,Plus(Times(C2,q),C3)),CN1),Integrate(Times(Power(Plus(d,Times(e,Sqr(x))),Subtract(q,C1)),Power(Plus(a,Times(c,Power(x,C4))),CN1D2),Simp(Plus(Times(ASymbol,c,d,Plus(Times(C2,q),C3)),Times(CN1,a,CSymbol,d),Times(Subtract(Times(c,Plus(Times(BSymbol,d),Times(ASymbol,e)),Plus(Times(C2,q),C3)),Times(a,CSymbol,e,Plus(Times(C2,q),C1))),Sqr(x)),Times(Plus(Times(BSymbol,c,e,Plus(Times(C2,q),C3)),Times(C2,c,CSymbol,d,q)),Power(x,C4))),x)),x)),x))),And(FreeQ(List(a,c,d,e),x),PolyQ($s("§p4x"),Sqr(x)),EqQ(Expon($s("§p4x"),x),C4),IGtQ(q,C0)))),
IIntegrate(2210,Integrate(Times($p("§p4x"),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(ASymbol,Coeff($s("§p4x"),x,C0)),Set(BSymbol,Coeff($s("§p4x"),x,C2)),Set(CSymbol,Coeff($s("§p4x"),x,C4))),Plus(Simp(Times(CN1,Plus(Times(CSymbol,Sqr(d)),Times(CN1,BSymbol,d,e),Times(ASymbol,Sqr(e))),x,Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4)))),Power(Times(C2,d,Plus(q,C1),Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e)))),CN1)),x),Simp(Star(Power(Times(C2,d,Plus(q,C1),Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e)))),CN1),Integrate(Times(Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),Simp(Plus(Times(a,d,Subtract(Times(CSymbol,d),Times(BSymbol,e))),Times(ASymbol,Plus(Times(a,Sqr(e),Plus(Times(C2,q),C3)),Times(C2,d,Subtract(Times(c,d),Times(b,e)),Plus(q,C1)))),Times(CN1,C2,Subtract(Times(Subtract(Times(BSymbol,d),Times(ASymbol,e)),Subtract(Times(b,e,Plus(q,C2)),Times(c,d,Plus(q,C1)))),Times(CSymbol,d,Plus(Times(b,d),Times(a,e,Plus(q,C1))))),Sqr(x)),Times(c,Plus(Times(CSymbol,Sqr(d)),Times(CN1,BSymbol,d,e),Times(ASymbol,Sqr(e))),Plus(Times(C2,q),C5),Power(x,C4))),x)),x)),x))),And(FreeQ(List(a,b,c,d,e),x),PolyQ($s("§p4x"),Sqr(x)),LeQ(Expon($s("§p4x"),x),C4),ILtQ(q,CN1)))),
IIntegrate(2211,Integrate(Times($p("§p4x"),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(ASymbol,Coeff($s("§p4x"),x,C0)),Set(BSymbol,Coeff($s("§p4x"),x,C2)),Set(CSymbol,Coeff($s("§p4x"),x,C4))),Plus(Simp(Times(CN1,Plus(Times(CSymbol,Sqr(d)),Times(CN1,BSymbol,d,e),Times(ASymbol,Sqr(e))),x,Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Sqrt(Plus(a,Times(c,Power(x,C4)))),Power(Times(C2,d,Plus(q,C1),Plus(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1)),x),Simp(Star(Power(Times(C2,d,Plus(q,C1),Plus(Times(c,Sqr(d)),Times(a,Sqr(e)))),CN1),Integrate(Times(Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Power(Plus(a,Times(c,Power(x,C4))),CN1D2),Simp(Plus(Times(a,d,Subtract(Times(CSymbol,d),Times(BSymbol,e))),Times(ASymbol,Plus(Times(a,Sqr(e),Plus(Times(C2,q),C3)),Times(C2,c,Sqr(d),Plus(q,C1)))),Times(C2,d,Plus(Times(BSymbol,c,d),Times(CN1,ASymbol,c,e),Times(a,CSymbol,e)),Plus(q,C1),Sqr(x)),Times(c,Plus(Times(CSymbol,Sqr(d)),Times(CN1,BSymbol,d,e),Times(ASymbol,Sqr(e))),Plus(Times(C2,q),C5),Power(x,C4))),x)),x)),x))),And(FreeQ(List(a,c,d,e),x),PolyQ($s("§p4x"),Sqr(x)),LeQ(Expon($s("§p4x"),x),C4),ILtQ(q,CN1)))),
IIntegrate(2212,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Simp(Star(ASymbol,Subst(Integrate(Power(Subtract(d,Times(Subtract(Times(b,d),Times(C2,a,e)),Sqr(x))),CN1),x),x,Times(x,Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)))),x),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),EqQ(Plus(Times(BSymbol,d),Times(ASymbol,e)),C0)))),
IIntegrate(2213,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Simp(Star(ASymbol,Subst(Integrate(Power(Plus(d,Times(C2,a,e,Sqr(x))),CN1),x),x,Times(x,Power(Plus(a,Times(c,Power(x,C4))),CN1D2)))),x),And(FreeQ(List(a,c,d,e,ASymbol,BSymbol),x),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),EqQ(Plus(Times(BSymbol,d),Times(ASymbol,e)),C0)))),
IIntegrate(2214,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(Plus(Times(BSymbol,d),Times(ASymbol,e)),Power(Times(C2,d,e),CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(Subtract(Times(BSymbol,d),Times(ASymbol,e)),Power(Times(C2,d,e),CN1)),Integrate(Times(Subtract(d,Times(e,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NeQ(Plus(Times(BSymbol,d),Times(ASymbol,e)),C0)))),
IIntegrate(2215,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(Plus(Times(BSymbol,d),Times(ASymbol,e)),Power(Times(C2,d,e),CN1)),Integrate(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(Subtract(Times(BSymbol,d),Times(ASymbol,e)),Power(Times(C2,d,e),CN1)),Integrate(Times(Subtract(d,Times(e,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,ASymbol,BSymbol),x),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NeQ(Plus(Times(BSymbol,d),Times(ASymbol,e)),C0)))),
IIntegrate(2216,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Simp(Star(Times(Sqrt(Plus(ASymbol,Times(BSymbol,Sqr(x)))),Sqrt(Plus(Times(a,Power(ASymbol,CN1)),Times(c,Sqr(x),Power(BSymbol,CN1)))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),Integrate(Times(Sqrt(Plus(ASymbol,Times(BSymbol,Sqr(x)))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(Times(a,Power(ASymbol,CN1)),Times(c,Sqr(x),Power(BSymbol,CN1))))),CN1)),x)),x),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),EqQ(Plus(Times(c,Sqr(ASymbol)),Times(CN1,b,ASymbol,BSymbol),Times(a,Sqr(BSymbol))),C0)))),
IIntegrate(2217,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Simp(Star(Times(Sqrt(Plus(ASymbol,Times(BSymbol,Sqr(x)))),Sqrt(Plus(Times(a,Power(ASymbol,CN1)),Times(c,Sqr(x),Power(BSymbol,CN1)))),Power(Plus(a,Times(c,Power(x,C4))),CN1D2)),Integrate(Times(Sqrt(Plus(ASymbol,Times(BSymbol,Sqr(x)))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(Times(a,Power(ASymbol,CN1)),Times(c,Sqr(x),Power(BSymbol,CN1))))),CN1)),x)),x),And(FreeQ(List(a,c,d,e,ASymbol,BSymbol),x),EqQ(Plus(Times(c,Sqr(ASymbol)),Times(a,Sqr(BSymbol))),C0)))),
IIntegrate(2218,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Sqrt(Subtract(Sqr(b),Times(C4,a,c))))),Condition(Subtract(Simp(Star(Times(Subtract(Times(C2,a,BSymbol),Times(ASymbol,Plus(b,q))),Power(Subtract(Times(C2,a,e),Times(d,Plus(b,q))),CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(Subtract(Times(BSymbol,d),Times(ASymbol,e)),Power(Subtract(Times(C2,a,e),Times(d,Plus(b,q))),CN1)),Integrate(Times(Plus(Times(C2,a),Times(Plus(b,q),Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x)),x)),RationalQ(q))),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),GtQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),NeQ(Plus(Times(c,Sqr(ASymbol)),Times(CN1,b,ASymbol,BSymbol),Times(a,Sqr(BSymbol))),C0)))),
IIntegrate(2219,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Sqrt(Times(CN1,a,c)))),Condition(Subtract(Simp(Star(Times(Subtract(Times(a,BSymbol),Times(ASymbol,q)),Power(Subtract(Times(a,e),Times(d,q)),CN1)),Integrate(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x)),x),Simp(Star(Times(Subtract(Times(BSymbol,d),Times(ASymbol,e)),Power(Subtract(Times(a,e),Times(d,q)),CN1)),Integrate(Times(Plus(a,Times(q,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x)),x)),RationalQ(q))),And(FreeQ(List(a,c,d,e,ASymbol,BSymbol),x),GtQ(Times(CN1,a,c),C0),EqQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),NeQ(Plus(Times(c,Sqr(ASymbol)),Times(a,Sqr(BSymbol))),C0)))),
IIntegrate(2220,Integrate(Times(Plus(A_,Times(B_DEFAULT,Sqr(x_))),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(BSymbol,Power(ASymbol,CN1)),C2))),Plus(Simp(Times(CN1,Subtract(Times(BSymbol,d),Times(ASymbol,e)),ArcTan(Times(Rt(Plus(Negate(b),Times(c,d,Power(e,CN1)),Times(a,e,Power(d,CN1))),C2),x,Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2))),Power(Times(C2,d,e,Rt(Plus(Negate(b),Times(c,d,Power(e,CN1)),Times(a,e,Power(d,CN1))),C2)),CN1)),x),Simp(Times(Plus(Times(BSymbol,d),Times(ASymbol,e)),Plus(C1,Times(Sqr(q),Sqr(x))),Sqrt(Times(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Power(Times(a,Sqr(Plus(C1,Times(Sqr(q),Sqr(x))))),CN1))),Power(Times(C4,d,e,q,Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1),EllipticPi(Times(CN1,Sqr(Subtract(e,Times(d,Sqr(q)))),Power(Times(C4,d,e,Sqr(q)),CN1)),Times(C2,ArcTan(Times(q,x))),Subtract(C1D2,Times(b,Power(Times(C4,a,Sqr(q)),CN1))))),x))),And(FreeQ(List(a,b,c,d,e,ASymbol,BSymbol),x),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1))),EqQ(Subtract(Times(c,Sqr(ASymbol)),Times(a,Sqr(BSymbol))),C0),PosQ(Times(BSymbol,Power(ASymbol,CN1))),PosQ(Plus(Negate(b),Times(c,d,Power(e,CN1)),Times(a,e,Power(d,CN1)))))))
  );
}
