package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IExpr;
import org.matheclipse.core.interfaces.IAST;
import com.google.common.base.Supplier;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules184 { 
  public static IAST RULES = List( 
IIntegrate(3681,Integrate(Times(Power($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,CN1))),Power(Plus(a,Times(b,Sqr($s("ff")),Sqr(x))),p)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,e,f,p),x),IntegerQ(Times(C1D2,Plus(m,CN1)))))),
IIntegrate(3682,Integrate(Times(Power($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Tan(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Plus(a,Times(Plus(a,b),Sqr($s("ff")),Sqr(x))),p),Power(Power(Plus(C1,Times(Sqr($s("ff")),Sqr(x))),Plus(Times(C1D2,m),p,C1)),CN1)),x),x,Times(Tan(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,e,f),x),IntegerQ(Times(C1D2,m)),IntegerQ(p)))),
IIntegrate(3683,Integrate(Times(Power($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Sqrt(Sqr(Cos(Plus(e,Times(f,x))))),Power(Times(f,Cos(Plus(e,Times(f,x)))),CN1)),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,CN1))),Power(Plus(a,Times(b,Sqr($s("ff")),Sqr(x))),p)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,e,f,p),x),IntegerQ(Times(C1D2,m)),Not(IntegerQ(p))))),
IIntegrate(3684,Integrate(Times(Power(Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),m_),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Power(d,Plus(Times(C2,IntPart(Times(C1D2,Plus(m,CN1)))),C1)),Power(Times(d,Cos(Plus(e,Times(f,x)))),Times(C2,FracPart(Times(C1D2,Plus(m,CN1))))),Power(Times(f,Power(Sqr(Cos(Plus(e,Times(f,x)))),FracPart(Times(C1D2,Plus(m,CN1))))),CN1)),Subst(Integrate(Times(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,CN1))),Power(Plus(a,Times(b,Sqr($s("ff")),Sqr(x))),p)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,d,e,f,m,p),x),Not(IntegerQ(m))))),
IIntegrate(3685,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT),Power($($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sqr(Sin(Plus(e,Times(f,x)))),x))),Simp(Dist(Times(Power($s("ff"),Times(C1D2,Plus(m,C1))),Power(Times(C2,f),CN1)),Subst(Integrate(Times(Power(x,Times(C1D2,Plus(m,CN1))),Power(Plus(a,Times(b,$s("ff"),x)),p),Power(Power(Subtract(C1,Times($s("ff"),x)),Times(C1D2,Plus(m,C1))),CN1)),x),x,Times(Sqr(Sin(Plus(e,Times(f,x)))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,e,f,p),x),IntegerQ(Times(C1D2,Plus(m,CN1)))))),
IIntegrate(3686,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT),Power(Times(d_DEFAULT,$($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Tan(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Times(d,$s("ff"),x),m),Power(Plus(a,Times(Plus(a,b),Sqr($s("ff")),Sqr(x))),p),Power(Power(Plus(C1,Times(Sqr($s("ff")),Sqr(x))),Plus(p,C1)),CN1)),x),x,Times(Tan(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,d,e,f,m),x),IntegerQ(p)))),
IIntegrate(3687,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT),Power($($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times(Power($s("ff"),Plus(m,C1)),Sqrt(Sqr(Cos(Plus(e,Times(f,x))))),Power(Times(f,Cos(Plus(e,Times(f,x)))),CN1)),Subst(Integrate(Times(Power(x,m),Power(Plus(a,Times(b,Sqr($s("ff")),Sqr(x))),p),Power(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,C1))),CN1)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,e,f,p),x),IntegerQ(Times(C1D2,m)),Not(IntegerQ(p))))),
IIntegrate(3688,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT),Power(Times(d_DEFAULT,$($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Power(Times(d,Tan(Plus(e,Times(f,x)))),Plus(m,C1)),Power(Sqr(Cos(Plus(e,Times(f,x)))),Times(C1D2,Plus(m,C1))),Power(Times(d,f,Power(Sin(Plus(e,Times(f,x))),Plus(m,C1))),CN1)),Subst(Integrate(Times(Power(Times($s("ff"),x),m),Power(Plus(a,Times(b,Sqr($s("ff")),Sqr(x))),p),Power(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,C1))),CN1)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,d,e,f,m,p),x),Not(IntegerQ(m))))),
IIntegrate(3689,Integrate(Times(Power($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT),Power(Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Times(d,$s("ff"),x),n),Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,CN1))),Power(Plus(a,Times(b,Sqr($s("ff")),Sqr(x))),p)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,d,e,f,n,p),x),IntegerQ(Times(C1D2,Plus(m,CN1)))))),
IIntegrate(3690,Integrate(Times(Power($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_DEFAULT),Power(Times(c_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),m_),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Cos(Plus(e,Times(f,x))),x))),Simp(Dist(Times(CN1,$s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Times(c,$s("ff"),x),m),Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(n,CN1))),Power(Subtract(Plus(a,b),Times(b,Sqr($s("ff")),Sqr(x))),p)),x),x,Times(Cos(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,c,e,f,m,p),x),IntegerQ(Times(C1D2,Plus(n,CN1)))))),
IIntegrate(3691,Integrate(Times(Power($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_),Power($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Tan(Plus(e,Times(f,x))),x))),Simp(Dist(Times(Power($s("ff"),Plus(n,C1)),Power(f,CN1)),Subst(Integrate(Times(Power(x,n),Power(Plus(a,Times(Plus(a,b),Sqr($s("ff")),Sqr(x))),p),Power(Power(Plus(C1,Times(Sqr($s("ff")),Sqr(x))),Plus(Times(C1D2,Plus(m,n)),p,C1)),CN1)),x),x,Times(Tan(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,e,f),x),IntegerQ(Times(C1D2,m)),IntegerQ(Times(C1D2,n)),IntegerQ(p)))),
IIntegrate(3692,Integrate(Times(Power($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_),Power(Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Sqrt(Sqr(Cos(Plus(e,Times(f,x))))),Power(Times(f,Cos(Plus(e,Times(f,x)))),CN1)),Subst(Integrate(Times(Power(Times(d,$s("ff"),x),n),Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,CN1))),Power(Plus(a,Times(b,Sqr($s("ff")),Sqr(x))),p)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,d,e,f,n,p),x),IntegerQ(Times(C1D2,m))))),
IIntegrate(3693,Integrate(Times(Power(Times($($s("§cos"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),c_DEFAULT),m_),Power(Times(d_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))))),p_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Power(c,Plus(Times(C2,IntPart(Times(C1D2,Plus(m,CN1)))),C1)),Power(Times(c,Cos(Plus(e,Times(f,x)))),Times(C2,FracPart(Times(C1D2,Plus(m,CN1))))),Power(Times(f,Power(Sqr(Cos(Plus(e,Times(f,x)))),FracPart(Times(C1D2,Plus(m,CN1))))),CN1)),Subst(Integrate(Times(Power(Times(d,$s("ff"),x),n),Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,CN1))),Power(Plus(a,Times(b,Sqr($s("ff")),Sqr(x))),p)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),Not(IntegerQ(m))))),
IIntegrate(3694,Integrate(Power(Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),p_),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Cot(Plus(e,Times(f,x))),Power(Times(b,Sqr(Sin(Plus(e,Times(f,x))))),p),Power(Times(C2,f,p),CN1)),x),Simp(Dist(Times(b,Plus(Times(C2,p),CN1),Power(Times(C2,p),CN1)),Integrate(Power(Times(b,Sqr(Sin(Plus(e,Times(f,x))))),Plus(p,CN1)),x),x),x)),And(FreeQ(list(b,e,f),x),Not(IntegerQ(p)),GtQ(p,C1)))),
IIntegrate(3695,Integrate(Power(Times(b_DEFAULT,Sqr($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),p_),x_Symbol),
    Condition(Plus(Simp(Times(Cot(Plus(e,Times(f,x))),Power(Times(b,Sqr(Sin(Plus(e,Times(f,x))))),Plus(p,C1)),Power(Times(b,f,Plus(Times(C2,p),C1)),CN1)),x),Simp(Dist(Times(C2,Plus(p,C1),Power(Times(b,Plus(Times(C2,p),C1)),CN1)),Integrate(Power(Times(b,Sqr(Sin(Plus(e,Times(f,x))))),Plus(p,C1)),x),x),x)),And(FreeQ(list(b,e,f),x),Not(IntegerQ(p)),LtQ(p,CN1)))),
IIntegrate(3696,Integrate(Times(Power(Times(b_DEFAULT,Power($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_)),p_DEFAULT),Power($($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sqr(Sin(Plus(e,Times(f,x)))),x))),Simp(Dist(Times(Power($s("ff"),Times(C1D2,Plus(m,C1))),Power(Times(C2,f),CN1)),Subst(Integrate(Times(Power(x,Times(C1D2,Plus(m,CN1))),Power(Times(b,Power($s("ff"),Times(C1D2,n)),Power(x,Times(C1D2,n))),p),Power(Power(Subtract(C1,Times($s("ff"),x)),Times(C1D2,Plus(m,C1))),CN1)),x),x,Times(Sqr(Sin(Plus(e,Times(f,x)))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(b,e,f,p),x),IntegerQ(Times(C1D2,Plus(m,CN1))),IntegerQ(Times(C1D2,n))))),
IIntegrate(3697,Integrate(Times(Power(Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_)),p_DEFAULT),Power($($s("§tan"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),m_DEFAULT)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times(Power($s("ff"),Plus(m,C1)),Power(f,CN1)),Subst(Integrate(Times(Power(x,m),Power(Times(b,Power(Times(c,$s("ff"),x),n)),p),Power(Power(Subtract(C1,Times(Sqr($s("ff")),Sqr(x))),Times(C1D2,Plus(m,C1))),CN1)),x),x,Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(b,c,e,f,n,p),x),ILtQ(Times(C1D2,Plus(m,CN1)),C0)))),
IIntegrate(3698,Integrate(Times(u_DEFAULT,Power(Times(b_DEFAULT,Power($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),n_)),p_)),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Sin(Plus(e,Times(f,x))),x))),Simp(Dist(Times(Power(Times(b,Power($s("ff"),n)),IntPart(p)),Power(Times(b,Power(Sin(Plus(e,Times(f,x))),n)),FracPart(p)),Power(Power(Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1)),Times(n,FracPart(p))),CN1)),Integrate(Times(ActivateTrig(u),Power(Times(Sin(Plus(e,Times(f,x))),Power($s("ff"),CN1)),Times(n,p))),x),x),x)),And(FreeQ(List(b,e,f,n,p),x),Not(IntegerQ(p)),IntegerQ(n),Or(EqQ(u,C1),MatchQ(u,Condition(Power(Times(d_DEFAULT,$($p("§trig"),Plus(e,Times(f,x)))),m_DEFAULT),And(FreeQ(list(d,m),x),MemberQ(List($s("§sin"),$s("§cos"),$s("§tan"),$s("§cot"),$s("§sec"),$s("§csc")),$s("§trig"))))))))),
IIntegrate(3699,Integrate(Times(u_DEFAULT,Power(Times(b_DEFAULT,Power(Times(c_DEFAULT,$($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_)),p_)),x_Symbol),
    Condition(Simp(Dist(Times(Power(b,IntPart(p)),Power(Times(b,Power(Times(c,Sin(Plus(e,Times(f,x)))),n)),FracPart(p)),Power(Power(Times(c,Sin(Plus(e,Times(f,x)))),Times(n,FracPart(p))),CN1)),Integrate(Times(ActivateTrig(u),Power(Times(c,Sin(Plus(e,Times(f,x)))),Times(n,p))),x),x),x),And(FreeQ(List(b,c,e,f,n,p),x),Not(IntegerQ(p)),Not(IntegerQ(n)),Or(EqQ(u,C1),MatchQ(u,Condition(Power(Times(d_DEFAULT,$($p("§trig"),Plus(e,Times(f,x)))),m_DEFAULT),And(FreeQ(list(d,m),x),MemberQ(List($s("§sin"),$s("§cos"),$s("§tan"),$s("§cot"),$s("§sec"),$s("§csc")),$s("§trig"))))))))),
IIntegrate(3700,Integrate(Power(Plus(a_,Times(b_DEFAULT,Power($($s("§sin"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),C4))),p_DEFAULT),x_Symbol),
    Condition(With(list(Set($s("ff"),FreeFactors(Tan(Plus(e,Times(f,x))),x))),Simp(Dist(Times($s("ff"),Power(f,CN1)),Subst(Integrate(Times(Power(Plus(a,Times(C2,a,Sqr($s("ff")),Sqr(x)),Times(Plus(a,b),Power($s("ff"),C4),Power(x,C4))),p),Power(Power(Plus(C1,Times(Sqr($s("ff")),Sqr(x))),Plus(Times(C2,p),C1)),CN1)),x),x,Times(Tan(Plus(e,Times(f,x))),Power($s("ff"),CN1))),x),x)),And(FreeQ(List(a,b,e,f),x),IntegerQ(p))))
  );
}
