package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules5 { 
  public static IAST RULES = List( 
IIntegrate(101,Integrate(Times(Sqr(Plus(a_DEFAULT,Times(b_DEFAULT,x_))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Plus(Simp(Times(b,Plus(a,Times(b,x)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(d,f,Plus(n,p,C3)),CN1)),x),Simp(Star(Power(Times(d,f,Plus(n,p,C3)),CN1),Integrate(Times(Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p),Simp(Plus(Times(Sqr(a),d,f,Plus(n,p,C3)),Times(CN1,b,Plus(Times(b,c,e),Times(a,Plus(Times(d,e,Plus(n,C1)),Times(c,f,Plus(p,C1)))))),Times(b,Subtract(Times(a,d,f,Plus(n,p,C4)),Times(b,Plus(Times(d,e,Plus(n,C2)),Times(c,f,Plus(p,C2))))),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,n,p),x),NeQ(Plus(n,p,C3),C0)))),
IIntegrate(102,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),CN1D3),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),QQ(-2L,3L)),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),CN1)),x_),
    Condition(With(list(Set(q,Rt(Times(Subtract(Times(d,e),Times(c,f)),Power(Subtract(Times(b,e),Times(a,f)),CN1)),C3))),Plus(Simp(Times(CN1,CSqrt3,q,ArcTan(Plus(C1DSqrt3,Times(C2,q,Power(Plus(a,Times(b,x)),C1D3),Power(Times(CSqrt3,Power(Plus(c,Times(d,x)),C1D3)),CN1)))),Power(Subtract(Times(d,e),Times(c,f)),CN1)),x),Simp(Times(q,Log(Plus(e,Times(f,x))),Power(Times(C2,Subtract(Times(d,e),Times(c,f))),CN1)),x),Negate(Simp(Times(C3,q,Log(Subtract(Times(q,Power(Plus(a,Times(b,x)),C1D3)),Power(Plus(c,Times(d,x)),C1D3))),Power(Times(C2,Subtract(Times(d,e),Times(c,f))),CN1)),x)))),FreeQ(List(a,b,c,d,e,f),x))),
IIntegrate(103,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),CN1D2),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),CN1D2),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),CN1)),x_),
    Condition(Simp(Star(Times(b,f),Subst(Integrate(Power(Plus(Times(d,Sqr(Subtract(Times(b,e),Times(a,f)))),Times(b,Sqr(f),Sqr(x))),CN1),x),x,Times(Sqrt(Plus(a,Times(b,x))),Sqrt(Plus(c,Times(d,x)))))),x),And(FreeQ(List(a,b,c,d,e,f),x),EqQ(Subtract(Times(C2,b,d,e),Times(f,Plus(Times(b,c),Times(a,d)))),C0)))),
IIntegrate(104,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),CN1)),x_),
    Condition(With(list(Set(q,Denominator(m))),Simp(Star(q,Subst(Integrate(Times(Power(x,Subtract(Times(q,Plus(m,C1)),C1)),Power(Subtract(Subtract(Times(b,e),Times(a,f)),Times(Subtract(Times(d,e),Times(c,f)),Power(x,q))),CN1)),x),x,Times(Power(Plus(a,Times(b,x)),Power(q,CN1)),Power(Power(Plus(c,Times(d,x)),Power(q,CN1)),CN1)))),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ(Plus(m,n,C1),C0),RationalQ(n),LtQ(CN1,m,C0),SimplerQ(Plus(a,Times(b,x)),Plus(c,Times(d,x)))))),
IIntegrate(105,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Subtract(Simp(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,e),Times(a,f))),CN1)),x),Simp(Star(Times(n,Subtract(Times(d,e),Times(c,f)),Power(Times(Plus(m,C1),Subtract(Times(b,e),Times(a,f))),CN1)),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(e,Times(f,x)),p)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,m,p),x),EqQ(Plus(m,n,p,C2),C0),GtQ(n,C0),Or(SumSimplerQ(m,C1),Not(SumSimplerQ(p,C1))),NeQ(m,CN1)))),
IIntegrate(106,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Simp(Times(b,Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),EqQ(Simplify(Plus(m,n,p,C3)),C0),EqQ(Plus(Times(a,d,f,Plus(m,C1)),Times(b,c,f,Plus(n,C1)),Times(b,d,e,Plus(p,C1))),C0),NeQ(m,CN1)))),
IIntegrate(107,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Plus(Simp(Times(b,Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1)),x),Simp(Star(Times(Plus(Times(a,d,f,Plus(m,C1)),Times(b,c,f,Plus(n,C1)),Times(b,d,e,Plus(p,C1))),Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1)),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),EqQ(Simplify(Plus(m,n,p,C3)),C0),Or(LtQ(m,CN1),SumSimplerQ(m,C1))))),
IIntegrate(108,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Subtract(Simp(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p),Power(Times(b,Plus(m,C1)),CN1)),x),Simp(Star(Power(Times(b,Plus(m,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(e,Times(f,x)),Subtract(p,C1)),Simp(Plus(Times(d,e,n),Times(c,f,p),Times(d,f,Plus(n,p),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),LtQ(m,CN1),GtQ(n,C0),GtQ(p,C0),Or(IntegersQ(Times(C2,m),Times(C2,n),Times(C2,p)),IntegersQ(m,Plus(n,p)),IntegersQ(p,Plus(m,n)))))),
IIntegrate(109,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Plus(Simp(Times(Subtract(Times(b,c),Times(a,d)),Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(b,Subtract(Times(b,e),Times(a,f)),Plus(m,C1)),CN1)),x),Simp(Star(Power(Times(b,Subtract(Times(b,e),Times(a,f)),Plus(m,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Subtract(n,C2)),Power(Plus(e,Times(f,x)),p),Simp(Plus(Times(a,d,Plus(Times(d,e,Subtract(n,C1)),Times(c,f,Plus(p,C1)))),Times(b,c,Subtract(Times(d,e,Plus(m,Negate(n),C2)),Times(c,f,Plus(m,p,C2)))),Times(d,Plus(Times(a,d,f,Plus(n,p)),Times(b,Subtract(Times(d,e,Plus(m,C1)),Times(c,f,Plus(m,n,p,C1))))),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,p),x),LtQ(m,CN1),GtQ(n,C1),Or(IntegersQ(Times(C2,m),Times(C2,n),Times(C2,p)),IntegersQ(m,Plus(n,p)),IntegersQ(p,Plus(m,n)))))),
IIntegrate(110,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Subtract(Simp(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,e),Times(a,f))),CN1)),x),Simp(Star(Power(Times(Plus(m,C1),Subtract(Times(b,e),Times(a,f))),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(e,Times(f,x)),p),Simp(Plus(Times(d,e,n),Times(c,f,Plus(m,p,C2)),Times(d,f,Plus(m,n,p,C2),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,p),x),LtQ(m,CN1),GtQ(n,C0),Or(IntegersQ(Times(C2,m),Times(C2,n),Times(C2,p)),IntegersQ(m,Plus(n,p)),IntegersQ(p,Plus(m,n)))))),
IIntegrate(111,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Plus(Simp(Times(b,Power(Plus(a,Times(b,x)),Subtract(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(d,f,Plus(m,n,p,C1)),CN1)),x),Simp(Star(Power(Times(d,f,Plus(m,n,p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Subtract(m,C2)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p),Simp(Plus(Times(Sqr(a),d,f,Plus(m,n,p,C1)),Times(CN1,b,Plus(Times(b,c,e,Subtract(m,C1)),Times(a,Plus(Times(d,e,Plus(n,C1)),Times(c,f,Plus(p,C1)))))),Times(b,Subtract(Times(a,d,f,Plus(Times(C2,m),n,p)),Times(b,Plus(Times(d,e,Plus(m,n)),Times(c,f,Plus(m,p))))),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,n,p),x),GtQ(m,C1),NeQ(Plus(m,n,p,C1),C0),IntegerQ(m)))),
IIntegrate(112,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Subtract(Simp(Times(Power(Plus(a,Times(b,x)),m),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(f,Plus(m,n,p,C1)),CN1)),x),Simp(Star(Power(Times(f,Plus(m,n,p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Subtract(m,C1)),Power(Plus(c,Times(d,x)),Subtract(n,C1)),Power(Plus(e,Times(f,x)),p),Simp(Plus(Times(c,m,Subtract(Times(b,e),Times(a,f))),Times(a,n,Subtract(Times(d,e),Times(c,f))),Times(Plus(Times(d,m,Subtract(Times(b,e),Times(a,f))),Times(b,n,Subtract(Times(d,e),Times(c,f)))),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,p),x),GtQ(m,C0),GtQ(n,C0),NeQ(Plus(m,n,p,C1),C0),Or(IntegersQ(Times(C2,m),Times(C2,n),Times(C2,p)),Or(IntegersQ(m,Plus(n,p)),IntegersQ(p,Plus(m,n))))))),
IIntegrate(113,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Plus(Simp(Times(b,Power(Plus(a,Times(b,x)),Subtract(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(d,f,Plus(m,n,p,C1)),CN1)),x),Simp(Star(Power(Times(d,f,Plus(m,n,p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Subtract(m,C2)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p),Simp(Plus(Times(Sqr(a),d,f,Plus(m,n,p,C1)),Times(CN1,b,Plus(Times(b,c,e,Subtract(m,C1)),Times(a,Plus(Times(d,e,Plus(n,C1)),Times(c,f,Plus(p,C1)))))),Times(b,Subtract(Times(a,d,f,Plus(Times(C2,m),n,p)),Times(b,Plus(Times(d,e,Plus(m,n)),Times(c,f,Plus(m,p))))),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,n,p),x),GtQ(m,C1),NeQ(Plus(m,n,p,C1),C0),IntegersQ(Times(C2,m),Times(C2,n),Times(C2,p))))),
IIntegrate(114,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Plus(Simp(Times(b,Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1)),x),Simp(Star(Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p),Simp(Subtract(Subtract(Times(a,d,f,Plus(m,C1)),Times(b,Plus(Times(d,e,Plus(m,n,C2)),Times(c,f,Plus(m,p,C2))))),Times(b,d,f,Plus(m,n,p,C3),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,n,p),x),ILtQ(m,CN1),Or(IntegerQ(n),IntegersQ(Times(C2,n),Times(C2,p)),ILtQ(Plus(m,n,p,C3),C0))))),
IIntegrate(115,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),n_),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),p_)),x_),
    Condition(Plus(Simp(Times(b,Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),Plus(n,C1)),Power(Plus(e,Times(f,x)),Plus(p,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1)),x),Simp(Star(Power(Times(Plus(m,C1),Subtract(Times(b,c),Times(a,d)),Subtract(Times(b,e),Times(a,f))),CN1),Integrate(Times(Power(Plus(a,Times(b,x)),Plus(m,C1)),Power(Plus(c,Times(d,x)),n),Power(Plus(e,Times(f,x)),p),Simp(Subtract(Subtract(Times(a,d,f,Plus(m,C1)),Times(b,Plus(Times(d,e,Plus(m,n,C2)),Times(c,f,Plus(m,p,C2))))),Times(b,d,f,Plus(m,n,p,C3),x)),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,n,p),x),LtQ(m,CN1),IntegersQ(Times(C2,m),Times(C2,n),Times(C2,p))))),
IIntegrate(116,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),CN1),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),CN1D2),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),CN1D4)),x_),
    Condition(Simp(Star(CN4,Subst(Integrate(Times(Sqr(x),Power(Times(Subtract(Subtract(Times(b,e),Times(a,f)),Times(b,Power(x,C4))),Sqrt(Plus(c,Times(CN1,d,e,Power(f,CN1)),Times(d,Power(x,C4),Power(f,CN1))))),CN1)),x),x,Power(Plus(e,Times(f,x)),C1D4))),x),And(FreeQ(List(a,b,c,d,e,f),x),GtQ(Times(CN1,f,Power(Subtract(Times(d,e),Times(c,f)),CN1)),C0)))),
IIntegrate(117,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),CN1),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),CN1D2),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),CN1D4)),x_),
    Condition(Simp(Star(Times(Sqrt(Times(CN1,f,Plus(c,Times(d,x)),Power(Subtract(Times(d,e),Times(c,f)),CN1))),Power(Plus(c,Times(d,x)),CN1D2)),Integrate(Power(Times(Plus(a,Times(b,x)),Sqrt(Subtract(Times(CN1,c,f,Power(Subtract(Times(d,e),Times(c,f)),CN1)),Times(d,f,x,Power(Subtract(Times(d,e),Times(c,f)),CN1)))),Power(Plus(e,Times(f,x)),C1D4)),CN1),x)),x),And(FreeQ(List(a,b,c,d,e,f),x),Not(GtQ(Times(CN1,f,Power(Subtract(Times(d,e),Times(c,f)),CN1)),C0))))),
IIntegrate(118,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),CN1),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),CN1D2),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),QQ(-3L,4L))),x_),
    Condition(Simp(Star(CN4,Subst(Integrate(Power(Times(Subtract(Subtract(Times(b,e),Times(a,f)),Times(b,Power(x,C4))),Sqrt(Plus(c,Times(CN1,d,e,Power(f,CN1)),Times(d,Power(x,C4),Power(f,CN1))))),CN1),x),x,Power(Plus(e,Times(f,x)),C1D4))),x),And(FreeQ(List(a,b,c,d,e,f),x),GtQ(Times(CN1,f,Power(Subtract(Times(d,e),Times(c,f)),CN1)),C0)))),
IIntegrate(119,Integrate(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),CN1),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),CN1D2),Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),QQ(-3L,4L))),x_),
    Condition(Simp(Star(Times(Sqrt(Times(CN1,f,Plus(c,Times(d,x)),Power(Subtract(Times(d,e),Times(c,f)),CN1))),Power(Plus(c,Times(d,x)),CN1D2)),Integrate(Power(Times(Plus(a,Times(b,x)),Sqrt(Subtract(Times(CN1,c,f,Power(Subtract(Times(d,e),Times(c,f)),CN1)),Times(d,f,x,Power(Subtract(Times(d,e),Times(c,f)),CN1)))),Power(Plus(e,Times(f,x)),QQ(3L,4L))),CN1),x)),x),And(FreeQ(List(a,b,c,d,e,f),x),Not(GtQ(Times(CN1,f,Power(Subtract(Times(d,e),Times(c,f)),CN1)),C0))))),
IIntegrate(120,Integrate(Times(Power(Times(b_DEFAULT,x_),CN1D2),Power(Plus(c_,Times(d_DEFAULT,x_)),CN1D2),Sqrt(Plus(e_,Times(f_DEFAULT,x_)))),x_),
    Condition(Simp(Times(C2,Sqrt(e),Power(b,CN1),Rt(Times(CN1,b,Power(d,CN1)),C2),EllipticE(ArcSin(Times(Sqrt(Times(b,x)),Power(Times(Sqrt(c),Rt(Times(CN1,b,Power(d,CN1)),C2)),CN1))),Times(c,f,Power(Times(d,e),CN1)))),x),And(FreeQ(List(b,c,d,e,f),x),GtQ(c,C0),GtQ(e,C0),Not(LtQ(Times(CN1,b,Power(d,CN1)),C0)))))
  );
}
