package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules43 { 

	public static void initialize() {
		Initializer.init();
	}

	private static class Initializer  {

		private static void init() {
IIntegrate(2151,Int(Times(Power(Plus(c_,Times(d_DEFAULT,x_)),CN1),Plus(e_,Times(f_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,Power(x_,C3))),CN1D3)),x_Symbol),
    Condition(Plus(Simp(Times(CSqrt3,f,ArcTan(Times(Plus(C1,Times(C2,Rt(b,C3),Plus(Times(C2,c),Times(d,x)),Power(Times(d,Power(Plus(a,Times(b,Power(x,C3))),C1D3)),CN1))),C1DSqrt3)),Power(Times(Rt(b,C3),d),CN1)),x),Simp(Times(f,Log(Plus(c,Times(d,x))),Power(Times(Rt(b,C3),d),CN1)),x),Negate(Simp(Times(C3,f,Log(Subtract(Times(Rt(b,C3),Plus(Times(C2,c),Times(d,x))),Times(d,Power(Plus(a,Times(b,Power(x,C3))),C1D3)))),Power(Times(C2,Rt(b,C3),d),CN1)),x))),And(FreeQ(List(a,b,c,d,e,f),x),EqQ(Plus(Times(d,e),Times(c,f)),C0),EqQ(Subtract(Times(C2,b,Power(c,C3)),Times(a,Power(d,C3))),C0))));
IIntegrate(2152,Int(Times(Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),CN1),Plus(e_DEFAULT,Times(f_DEFAULT,x_)),Power(Plus(a_,Times(b_DEFAULT,Power(x_,C3))),CN1D3)),x_Symbol),
    Condition(Plus(Dist(Times(f,Power(d,CN1)),Int(Power(Plus(a,Times(b,Power(x,C3))),CN1D3),x),x),Dist(Times(Subtract(Times(d,e),Times(c,f)),Power(d,CN1)),Int(Power(Times(Plus(c,Times(d,x)),Power(Plus(a,Times(b,Power(x,C3))),C1D3)),CN1),x),x)),FreeQ(List(a,b,c,d,e,f),x)));
IIntegrate(2153,Int(Times(Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_DEFAULT))),q_),Power(Plus(a_,Times(b_DEFAULT,Power(x_,$p("nn",true)))),p_)),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(Plus(a,Times(b,Power(x,$s("nn")))),p),Power(Subtract(Times(c,Power(Subtract(Sqr(c),Times(Sqr(d),Power(x,Times(C2,n)))),CN1)),Times(d,Power(x,n),Power(Subtract(Sqr(c),Times(Sqr(d),Power(x,Times(C2,n)))),CN1))),Negate(q)),x),x),And(FreeQ(List(a,b,c,d,n,$s("nn"),p),x),Not(IntegerQ(p)),ILtQ(q,C0),IGtQ(Log(C2,Times($s("nn"),Power(n,CN1))),C0))));
IIntegrate(2154,Int(Times(Power(Times(e_DEFAULT,x_),m_DEFAULT),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_DEFAULT))),q_),Power(Plus(a_,Times(b_DEFAULT,Power(x_,$p("nn",true)))),p_)),x_Symbol),
    Condition(Dist(Times(Power(Times(e,x),m),Power(Power(x,m),CN1)),Int(ExpandIntegrand(Times(Power(x,m),Power(Plus(a,Times(b,Power(x,$s("nn")))),p)),Power(Subtract(Times(c,Power(Subtract(Sqr(c),Times(Sqr(d),Power(x,Times(C2,n)))),CN1)),Times(d,Power(x,n),Power(Subtract(Sqr(c),Times(Sqr(d),Power(x,Times(C2,n)))),CN1))),Negate(q)),x),x),x),And(FreeQ(List(a,b,c,d,e,m,n,$s("nn"),p),x),Not(IntegerQ(p)),ILtQ(q,C0),IGtQ(Log(C2,Times($s("nn"),Power(n,CN1))),C0))));
IIntegrate(2155,Int(Times(Power(x_,m_DEFAULT),Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_)),Times(e_DEFAULT,Sqrt(Plus(a_,Times(b_DEFAULT,Power(x_,n_)))))),CN1)),x_Symbol),
    Condition(Dist(Power(n,CN1),Subst(Int(Times(Power(x,Subtract(Times(Plus(m,C1),Power(n,CN1)),C1)),Power(Plus(c,Times(d,x),Times(e,Sqrt(Plus(a,Times(b,x))))),CN1)),x),x,Power(x,n)),x),And(FreeQ(List(a,b,c,d,e,m,n),x),EqQ(Subtract(Times(b,c),Times(a,d)),C0),IntegerQ(Times(Plus(m,C1),Power(n,CN1))))));
IIntegrate(2156,Int(Times(u_DEFAULT,Power(Plus(c_,Times(d_DEFAULT,Power(x_,n_)),Times(e_DEFAULT,Sqrt(Plus(a_,Times(b_DEFAULT,Power(x_,n_)))))),CN1)),x_Symbol),
    Condition(Subtract(Dist(c,Int(Times(u,Power(Plus(Sqr(c),Times(CN1,a,Sqr(e)),Times(c,d,Power(x,n))),CN1)),x),x),Dist(Times(a,e),Int(Times(u,Power(Times(Plus(Sqr(c),Times(CN1,a,Sqr(e)),Times(c,d,Power(x,n))),Sqrt(Plus(a,Times(b,Power(x,n))))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,n),x),EqQ(Subtract(Times(b,c),Times(a,d)),C0))));
IIntegrate(2157,Int(Power(u_,m_DEFAULT),x_Symbol),
    Condition(With(List(Set(c,Simplify(D(u,x)))),Dist(Power(c,CN1),Subst(Int(Power(x,m),x),x,u),x)),And(FreeQ(m,x),PiecewiseLinearQ(u,x))));
IIntegrate(2158,Int(Times(Power(u_,CN1),v_),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Subtract(Simp(Times(b,x,Power(a,CN1)),x),Dist(Times(Subtract(Times(b,u),Times(a,v)),Power(a,CN1)),Int(Power(u,CN1),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),PiecewiseLinearQ(u,v,x)));
IIntegrate(2159,Int(Times(Power(u_,CN1),Power(v_,n_)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Subtract(Simp(Times(Power(v,n),Power(Times(a,n),CN1)),x),Dist(Times(Subtract(Times(b,u),Times(a,v)),Power(a,CN1)),Int(Times(Power(v,Subtract(n,C1)),Power(u,CN1)),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(PiecewiseLinearQ(u,v,x),GtQ(n,C0),NeQ(n,C1))));
IIntegrate(2160,Int(Times(Power(u_,CN1),Power(v_,CN1)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Subtract(Dist(Times(b,Power(Subtract(Times(b,u),Times(a,v)),CN1)),Int(Power(v,CN1),x),x),Dist(Times(a,Power(Subtract(Times(b,u),Times(a,v)),CN1)),Int(Power(u,CN1),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),PiecewiseLinearQ(u,v,x)));
IIntegrate(2161,Int(Times(Power(u_,CN1),Power(v_,CN1D2)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Simp(Times(C2,ArcTan(Times(Sqrt(v),Power(Rt(Times(Subtract(Times(b,u),Times(a,v)),Power(a,CN1)),C2),CN1))),Power(Times(a,Rt(Times(Subtract(Times(b,u),Times(a,v)),Power(a,CN1)),C2)),CN1)),x),And(NeQ(Subtract(Times(b,u),Times(a,v)),C0),PosQ(Times(Subtract(Times(b,u),Times(a,v)),Power(a,CN1)))))),PiecewiseLinearQ(u,v,x)));
IIntegrate(2162,Int(Times(Power(u_,CN1),Power(v_,CN1D2)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Simp(Times(CN2,ArcTanh(Times(Sqrt(v),Power(Rt(Times(CN1,Subtract(Times(b,u),Times(a,v)),Power(a,CN1)),C2),CN1))),Power(Times(a,Rt(Times(CN1,Subtract(Times(b,u),Times(a,v)),Power(a,CN1)),C2)),CN1)),x),And(NeQ(Subtract(Times(b,u),Times(a,v)),C0),NegQ(Times(Subtract(Times(b,u),Times(a,v)),Power(a,CN1)))))),PiecewiseLinearQ(u,v,x)));
IIntegrate(2163,Int(Times(Power(u_,CN1),Power(v_,n_)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Subtract(Simp(Times(Power(v,Plus(n,C1)),Power(Times(Plus(n,C1),Subtract(Times(b,u),Times(a,v))),CN1)),x),Dist(Times(a,Plus(n,C1),Power(Times(Plus(n,C1),Subtract(Times(b,u),Times(a,v))),CN1)),Int(Times(Power(v,Plus(n,C1)),Power(u,CN1)),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(PiecewiseLinearQ(u,v,x),LtQ(n,CN1))));
IIntegrate(2164,Int(Times(Power(u_,CN1),Power(v_,n_)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Simp(Times(Power(v,Plus(n,C1)),Hypergeometric2F1(C1,Plus(n,C1),Plus(n,C2),Times(CN1,a,v,Power(Subtract(Times(b,u),Times(a,v)),CN1))),Power(Times(Plus(n,C1),Subtract(Times(b,u),Times(a,v))),CN1)),x),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(PiecewiseLinearQ(u,v,x),Not(IntegerQ(n)))));
IIntegrate(2165,Int(Times(Power(u_,CN1D2),Power(v_,CN1D2)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Simp(Times(C2,ArcTanh(Times(Rt(Times(a,b),C2),Sqrt(u),Power(Times(a,Sqrt(v)),CN1))),Power(Rt(Times(a,b),C2),CN1)),x),And(NeQ(Subtract(Times(b,u),Times(a,v)),C0),PosQ(Times(a,b))))),PiecewiseLinearQ(u,v,x)));
IIntegrate(2166,Int(Times(Power(u_,CN1D2),Power(v_,CN1D2)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Simp(Times(C2,ArcTan(Times(Rt(Times(CN1,a,b),C2),Sqrt(u),Power(Times(a,Sqrt(v)),CN1))),Power(Rt(Times(CN1,a,b),C2),CN1)),x),And(NeQ(Subtract(Times(b,u),Times(a,v)),C0),NegQ(Times(a,b))))),PiecewiseLinearQ(u,v,x)));
IIntegrate(2167,Int(Times(Power(u_,m_),Power(v_,n_)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Negate(Simp(Times(Power(u,Plus(m,C1)),Power(v,Plus(n,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,u),Times(a,v))),CN1)),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(FreeQ(List(m,n),x),PiecewiseLinearQ(u,v,x),EqQ(Plus(m,n,C2),C0),NeQ(m,CN1))));
IIntegrate(2168,Int(Times(Power(u_,m_),Power(v_,n_DEFAULT)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Subtract(Simp(Times(Power(u,Plus(m,C1)),Power(v,n),Power(Times(a,Plus(m,C1)),CN1)),x),Dist(Times(b,n,Power(Times(a,Plus(m,C1)),CN1)),Int(Times(Power(u,Plus(m,C1)),Power(v,Subtract(n,C1))),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(FreeQ(List(m,n),x),PiecewiseLinearQ(u,v,x),NeQ(m,CN1),Or(And(LtQ(m,CN1),GtQ(n,C0),Not(And(ILtQ(Plus(m,n),CN2),Or(FractionQ(m),GeQ(Plus(Times(C2,n),m,C1),C0))))),And(IGtQ(n,C0),IGtQ(m,C0),LeQ(n,m)),And(IGtQ(n,C0),Not(IntegerQ(m))),And(ILtQ(m,C0),Not(IntegerQ(n)))))));
IIntegrate(2169,Int(Times(Power(u_,m_),Power(v_,n_DEFAULT)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Subtract(Simp(Times(Power(u,Plus(m,C1)),Power(v,n),Power(Times(a,Plus(m,n,C1)),CN1)),x),Dist(Times(n,Subtract(Times(b,u),Times(a,v)),Power(Times(a,Plus(m,n,C1)),CN1)),Int(Times(Power(u,m),Power(v,Subtract(n,C1))),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(PiecewiseLinearQ(u,v,x),NeQ(Plus(m,n,C2),C0),GtQ(n,C0),NeQ(Plus(m,n,C1),C0),Not(And(IGtQ(m,C0),Or(Not(IntegerQ(n)),LtQ(C0,m,n)))),Not(ILtQ(Plus(m,n),CN2)))));
IIntegrate(2170,Int(Times(Power(u_,m_),Power(v_,n_)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Subtract(Simp(Times(Power(u,Plus(m,C1)),Power(v,n),Power(Times(a,Plus(m,n,C1)),CN1)),x),Dist(Times(n,Subtract(Times(b,u),Times(a,v)),Power(Times(a,Plus(m,n,C1)),CN1)),Int(Times(Power(u,m),Power(v,Simplify(Subtract(n,C1)))),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(PiecewiseLinearQ(u,v,x),NeQ(Plus(m,n,C1),C0),Not(RationalQ(n)),SumSimplerQ(n,CN1))));
IIntegrate(2171,Int(Times(Power(u_,m_),Power(v_,n_)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Plus(Negate(Simp(Times(Power(u,Plus(m,C1)),Power(v,Plus(n,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,u),Times(a,v))),CN1)),x)),Dist(Times(b,Plus(m,n,C2),Power(Times(Plus(m,C1),Subtract(Times(b,u),Times(a,v))),CN1)),Int(Times(Power(u,Plus(m,C1)),Power(v,n)),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(PiecewiseLinearQ(u,v,x),NeQ(Plus(m,n,C2),C0),LtQ(m,CN1))));
IIntegrate(2172,Int(Times(Power(u_,m_),Power(v_,n_)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Plus(Negate(Simp(Times(Power(u,Plus(m,C1)),Power(v,Plus(n,C1)),Power(Times(Plus(m,C1),Subtract(Times(b,u),Times(a,v))),CN1)),x)),Dist(Times(b,Plus(m,n,C2),Power(Times(Plus(m,C1),Subtract(Times(b,u),Times(a,v))),CN1)),Int(Times(Power(u,Simplify(Plus(m,C1))),Power(v,n)),x),x)),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(PiecewiseLinearQ(u,v,x),Not(RationalQ(m)),SumSimplerQ(m,C1))));
IIntegrate(2173,Int(Times(Power(u_,m_),Power(v_,n_)),x_Symbol),
    Condition(With(List(Set(a,Simplify(D(u,x))),Set(b,Simplify(D(v,x)))),Condition(Simp(Times(Power(u,m),Power(v,Plus(n,C1)),Hypergeometric2F1(Negate(m),Plus(n,C1),Plus(n,C2),Times(CN1,a,v,Power(Subtract(Times(b,u),Times(a,v)),CN1))),Power(Times(b,Plus(n,C1),Power(Times(b,u,Power(Subtract(Times(b,u),Times(a,v)),CN1)),m)),CN1)),x),NeQ(Subtract(Times(b,u),Times(a,v)),C0))),And(PiecewiseLinearQ(u,v,x),Not(IntegerQ(m)),Not(IntegerQ(n)))));
IIntegrate(2174,Int(Times(Log(Plus(a_DEFAULT,Times(b_DEFAULT,x_))),Power(u_,n_DEFAULT)),x_Symbol),
    Condition(With(List(Set(c,Simplify(D(u,x)))),Plus(Simp(Times(Power(u,n),Plus(a,Times(b,x)),Log(Plus(a,Times(b,x))),Power(b,CN1)),x),Negate(Dist(Times(c,n,Power(b,CN1)),Int(Times(Power(u,Subtract(n,C1)),Plus(a,Times(b,x)),Log(Plus(a,Times(b,x)))),x),x)),Negate(Int(Power(u,n),x)))),And(FreeQ(List(a,b),x),PiecewiseLinearQ(u,x),Not(LinearQ(u,x)),GtQ(n,C0))));
IIntegrate(2175,Int(Times(Log(Plus(a_DEFAULT,Times(b_DEFAULT,x_))),Power(u_,n_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(With(List(Set(c,Simplify(D(u,x)))),Plus(Simp(Times(Power(u,n),Power(Plus(a,Times(b,x)),Plus(m,C1)),Log(Plus(a,Times(b,x))),Power(Times(b,Plus(m,C1)),CN1)),x),Negate(Dist(Power(Plus(m,C1),CN1),Int(Times(Power(u,n),Power(Plus(a,Times(b,x)),m)),x),x)),Negate(Dist(Times(c,n,Power(Times(b,Plus(m,C1)),CN1)),Int(Times(Power(u,Subtract(n,C1)),Power(Plus(a,Times(b,x)),Plus(m,C1)),Log(Plus(a,Times(b,x)))),x),x)))),And(FreeQ(List(a,b,m),x),PiecewiseLinearQ(u,x),Not(LinearQ(u,x)),GtQ(n,C0),NeQ(m,CN1))));
IIntegrate(2176,Int(Times(Power(Times(b_DEFAULT,Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(c,Times(d,x)),m),Power(Times(b,Power(FSymbol,Times(g,Plus(e,Times(f,x))))),n),Power(Times(f,g,n,Log(FSymbol)),CN1)),x),Dist(Times(d,m,Power(Times(f,g,n,Log(FSymbol)),CN1)),Int(Times(Power(Plus(c,Times(d,x)),Subtract(m,C1)),Power(Times(b,Power(FSymbol,Times(g,Plus(e,Times(f,x))))),n)),x),x)),And(FreeQ(List(FSymbol,b,c,d,e,f,g,n),x),GtQ(m,C0),IntegerQ(Times(C2,m)),Not(SameQ(False,True)))));
IIntegrate(2177,Int(Times(Power(Times(b_DEFAULT,Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(c,Times(d,x)),Plus(m,C1)),Power(Times(b,Power(FSymbol,Times(g,Plus(e,Times(f,x))))),n),Power(Times(d,Plus(m,C1)),CN1)),x),Dist(Times(f,g,n,Log(FSymbol),Power(Times(d,Plus(m,C1)),CN1)),Int(Times(Power(Plus(c,Times(d,x)),Plus(m,C1)),Power(Times(b,Power(FSymbol,Times(g,Plus(e,Times(f,x))))),n)),x),x)),And(FreeQ(List(FSymbol,b,c,d,e,f,g,n),x),LtQ(m,CN1),IntegerQ(Times(C2,m)),Not(SameQ(False,True)))));
IIntegrate(2178,Int(Times(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),CN1)),x_Symbol),
    Condition(Simp(Times(Power(FSymbol,Times(g,Subtract(e,Times(c,f,Power(d,CN1))))),ExpIntegralEi(Times(f,g,Plus(c,Times(d,x)),Log(FSymbol),Power(d,CN1))),Power(d,CN1)),x),And(FreeQ(List(FSymbol,c,d,e,f,g),x),Not(SameQ(False,True)))));
IIntegrate(2179,Int(Times(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Simp(Times(Power(Negate(d),m),Power(FSymbol,Times(g,Subtract(e,Times(c,f,Power(d,CN1))))),Gamma(Plus(m,C1),Times(CN1,f,g,Log(FSymbol),Plus(c,Times(d,x)),Power(d,CN1))),Power(Times(Power(f,Plus(m,C1)),Power(g,Plus(m,C1)),Power(Log(FSymbol),Plus(m,C1))),CN1)),x),And(FreeQ(List(FSymbol,c,d,e,f,g),x),IntegerQ(m))));
IIntegrate(2180,Int(Times(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),CN1D2)),x_Symbol),
    Condition(Dist(Times(C2,Power(d,CN1)),Subst(Int(Power(FSymbol,Plus(Times(g,Subtract(e,Times(c,f,Power(d,CN1)))),Times(f,g,Sqr(x),Power(d,CN1)))),x),x,Sqrt(Plus(c,Times(d,x)))),x),And(FreeQ(List(FSymbol,c,d,e,f,g),x),Not(SameQ(False,True)))));
IIntegrate(2181,Int(Times(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_)),x_Symbol),
    Condition(Negate(Simp(Times(Power(FSymbol,Times(g,Subtract(e,Times(c,f,Power(d,CN1))))),Power(Plus(c,Times(d,x)),FracPart(m)),Gamma(Plus(m,C1),Times(CN1,f,g,Log(FSymbol),Power(d,CN1),Plus(c,Times(d,x)))),Power(Times(d,Power(Times(CN1,f,g,Log(FSymbol),Power(d,CN1)),Plus(IntPart(m),C1)),Power(Times(CN1,f,g,Log(FSymbol),Plus(c,Times(d,x)),Power(d,CN1)),FracPart(m))),CN1)),x)),And(FreeQ(List(FSymbol,c,d,e,f,g,m),x),Not(IntegerQ(m)))));
IIntegrate(2182,Int(Times(Power(Times(b_DEFAULT,Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_))))),n_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Dist(Times(Power(Times(b,Power(FSymbol,Times(g,Plus(e,Times(f,x))))),n),Power(Power(FSymbol,Times(g,n,Plus(e,Times(f,x)))),CN1)),Int(Times(Power(Plus(c,Times(d,x)),m),Power(FSymbol,Times(g,n,Plus(e,Times(f,x))))),x),x),FreeQ(List(FSymbol,b,c,d,e,f,g,m,n),x)));
IIntegrate(2183,Int(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(Plus(c,Times(d,x)),m),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),p),x),x),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,m,n),x),IGtQ(p,C0))));
IIntegrate(2184,Int(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),CN1),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(c,Times(d,x)),Plus(m,C1)),Power(Times(a,d,Plus(m,C1)),CN1)),x),Dist(Times(b,Power(a,CN1)),Int(Times(Power(Plus(c,Times(d,x)),m),Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),CN1)),x),x)),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,n),x),IGtQ(m,C0))));
IIntegrate(2185,Int(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),p_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Subtract(Dist(Power(a,CN1),Int(Times(Power(Plus(c,Times(d,x)),m),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),Plus(p,C1))),x),x),Dist(Times(b,Power(a,CN1)),Int(Times(Power(Plus(c,Times(d,x)),m),Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),p)),x),x)),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,n),x),ILtQ(p,C0),IGtQ(m,C0))));
IIntegrate(2186,Int(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),p_),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(With(List(Set(u,IntHide(Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),p),x))),Subtract(Dist(Power(Plus(c,Times(d,x)),m),u,x),Dist(Times(d,m),Int(Times(Power(Plus(c,Times(d,x)),Subtract(m,C1)),u),x),x))),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,n),x),IGtQ(m,C0),LtQ(p,CN1))));
IIntegrate(2187,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,v_)),n_DEFAULT))),p_DEFAULT),Power(u_,m_DEFAULT)),x_Symbol),
    Condition(Int(Times(Power(NormalizePowerOfLinear(u,x),m),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,ExpandToSum(v,x))),n))),p)),x),And(FreeQ(List(FSymbol,a,b,g,n,p),x),LinearQ(v,x),PowerOfLinearQ(u,x),Not(And(LinearMatchQ(v,x),PowerOfLinearMatchQ(u,x))),IntegerQ(m))));
IIntegrate(2188,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,v_)),n_DEFAULT))),p_DEFAULT),Power(u_,m_DEFAULT)),x_Symbol),
    Condition(Module(List(Set($s("uu"),NormalizePowerOfLinear(u,x)),z),Simp(CompoundExpression(Set(z,If(And(PowerQ($s("uu")),FreeQ(Part($s("uu"),C2),x)),Power(Part($s("uu"),C1),Times(m,Part($s("uu"),C2))),Power($s("uu"),m))),Times(Power($s("uu"),m),Int(Times(z,Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,ExpandToSum(v,x))),n))),p)),x),Power(z,CN1))),x)),And(FreeQ(List(FSymbol,a,b,g,m,n,p),x),LinearQ(v,x),PowerOfLinearQ(u,x),Not(And(LinearMatchQ(v,x),PowerOfLinearMatchQ(u,x))),Not(IntegerQ(m)))));
IIntegrate(2189,Int(Times(Power(Plus(a_,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),p),Power(Plus(c,Times(d,x)),m)),x),FreeQ(List(a,b,c,d,e,f,g,m,n,p),x)));
IIntegrate(2190,Int(Times(Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),CN1),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(c,Times(d,x)),m),Log(Plus(C1,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n),Power(a,CN1)))),Power(Times(b,f,g,n,Log(FSymbol)),CN1)),x),Dist(Times(d,m,Power(Times(b,f,g,n,Log(FSymbol)),CN1)),Int(Times(Power(Plus(c,Times(d,x)),Subtract(m,C1)),Log(Plus(C1,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n),Power(a,CN1))))),x),x)),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,n),x),IGtQ(m,C0))));
IIntegrate(2191,Int(Times(Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(Plus(c,Times(d,x)),m),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),Plus(p,C1)),Power(Times(b,f,g,n,Plus(p,C1),Log(FSymbol)),CN1)),x),Dist(Times(d,m,Power(Times(b,f,g,n,Plus(p,C1),Log(FSymbol)),CN1)),Int(Times(Power(Plus(c,Times(d,x)),Subtract(m,C1)),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),Plus(p,C1))),x),x)),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,m,n,p),x),NeQ(p,CN1))));
IIntegrate(2192,Int(Times(Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),p_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),p),Power(Plus(c,Times(d,x)),m)),x),FreeQ(List(FSymbol,a,b,c,d,e,f,g,m,n,p),x)));
IIntegrate(2193,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,Power(Power(F_,Times(g_DEFAULT,Plus(e_DEFAULT,Times(f_DEFAULT,x_)))),n_DEFAULT))),p_DEFAULT),Power(Times(k_DEFAULT,Power(G_,Times(j_DEFAULT,Plus(h_DEFAULT,Times(i_DEFAULT,x_))))),q_DEFAULT),Power(Plus(c_DEFAULT,Times(d_DEFAULT,x_)),m_DEFAULT)),x_Symbol),
    Condition(Dist(Times(Power(Times(k,Power(GSymbol,Times(j,Plus(h,Times(i,x))))),q),Power(Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n),CN1)),Int(Times(Power(Plus(c,Times(d,x)),m),Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n),Power(Plus(a,Times(b,Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n))),p)),x),x),And(FreeQ(List(FSymbol,a,b,c,d,e,f,g,h,i,j,k,m,n,p,q),x),EqQ(Subtract(Times(f,g,n,Log(FSymbol)),Times(i,j,q,Log(GSymbol))),C0),NeQ(Subtract(Power(Times(k,Power(GSymbol,Times(j,Plus(h,Times(i,x))))),q),Power(Power(FSymbol,Times(g,Plus(e,Times(f,x)))),n)),C0))));
IIntegrate(2194,Int(Power(Power(F_,Times(c_DEFAULT,Plus(a_DEFAULT,Times(b_DEFAULT,x_)))),n_DEFAULT),x_Symbol),
    Condition(Simp(Times(Power(Power(FSymbol,Times(c,Plus(a,Times(b,x)))),n),Power(Times(b,c,n,Log(FSymbol)),CN1)),x),FreeQ(List(FSymbol,a,b,c,n),x)));
IIntegrate(2195,Int(Times(Power(F_,Times(c_DEFAULT,v_)),u_),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(u,Power(FSymbol,Times(c,ExpandToSum(v,x)))),x),x),And(FreeQ(List(FSymbol,c),x),PolynomialQ(u,x),LinearQ(v,x),SameQ(False,True))));
IIntegrate(2196,Int(Times(Power(F_,Times(c_DEFAULT,v_)),u_),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(FSymbol,Times(c,ExpandToSum(v,x))),u,x),x),And(FreeQ(List(FSymbol,c),x),PolynomialQ(u,x),LinearQ(v,x),Not(SameQ(False,True)))));
IIntegrate(2197,Int(Times(Power(F_,Times(c_DEFAULT,v_)),Power(u_,m_DEFAULT),w_),x_Symbol),
    Condition(With(List(Set(b,Coefficient(v,x,C1)),Set(d,Coefficient(u,x,C0)),Set(e,Coefficient(u,x,C1)),Set(f,Coefficient(w,x,C0)),Set(g,Coefficient(w,x,C1))),Condition(Simp(Times(g,Power(u,Plus(m,C1)),Power(FSymbol,Times(c,v)),Power(Times(b,c,e,Log(FSymbol)),CN1)),x),EqQ(Subtract(Times(e,g,Plus(m,C1)),Times(b,c,Subtract(Times(e,f),Times(d,g)),Log(FSymbol))),C0))),And(FreeQ(List(FSymbol,c,m),x),LinearQ(List(u,v,w),x))));
IIntegrate(2198,Int(Times(Power(F_,Times(c_DEFAULT,v_)),Power(u_,m_DEFAULT),w_),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(w,Power(NormalizePowerOfLinear(u,x),m),Power(FSymbol,Times(c,ExpandToSum(v,x)))),x),x),And(FreeQ(List(FSymbol,c),x),PolynomialQ(w,x),LinearQ(v,x),PowerOfLinearQ(u,x),IntegerQ(m),SameQ(False,True))));
IIntegrate(2199,Int(Times(Power(F_,Times(c_DEFAULT,v_)),Power(u_,m_DEFAULT),w_),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(FSymbol,Times(c,ExpandToSum(v,x))),Times(w,Power(NormalizePowerOfLinear(u,x),m)),x),x),And(FreeQ(List(FSymbol,c),x),PolynomialQ(w,x),LinearQ(v,x),PowerOfLinearQ(u,x),IntegerQ(m),Not(SameQ(False,True)))));
IIntegrate(2200,Int(Times(Power(F_,Times(c_DEFAULT,v_)),Power(u_,m_DEFAULT),w_),x_Symbol),
    Condition(Module(List(Set($s("uu"),NormalizePowerOfLinear(u,x)),z),Simp(CompoundExpression(Set(z,If(And(PowerQ($s("uu")),FreeQ(Part($s("uu"),C2),x)),Power(Part($s("uu"),C1),Times(m,Part($s("uu"),C2))),Power($s("uu"),m))),Times(Power($s("uu"),m),Int(ExpandIntegrand(Times(w,z,Power(FSymbol,Times(c,ExpandToSum(v,x)))),x),x),Power(z,CN1))),x)),And(FreeQ(List(FSymbol,c,m),x),PolynomialQ(w,x),LinearQ(v,x),PowerOfLinearQ(u,x),Not(IntegerQ(m)))));
  }
}
}
