package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules26 { 

	public static void initialize() {
		Initializer.init();
	}

	private static class Initializer  {

		private static void init() {
IIntegrate(1301,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Plus(Dist(Times(Sqr(e),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q)),x),x),Dist(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1),Int(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Simp(Subtract(Subtract(Times(c,d),Times(b,e)),Times(c,e,Sqr(x))),x),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,f,m),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(q)),LtQ(q,CN1))));
IIntegrate(1302,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Plus(Dist(Times(Sqr(e),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q)),x),x),Dist(Times(c,Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),Plus(q,C1)),Subtract(d,Times(e,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,f,m),x),Not(IntegerQ(q)),LtQ(q,CN1))));
IIntegrate(1303,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(Plus(d,Times(e,Sqr(x))),q),Times(Power(Times(f,x),m),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1)),x),x),And(FreeQ(List(a,b,c,d,e,f,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(q)),IntegerQ(m))));
IIntegrate(1304,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(Plus(d,Times(e,Sqr(x))),q),Times(Power(Times(f,x),m),Power(Plus(a,Times(c,Power(x,C4))),CN1)),x),x),And(FreeQ(List(a,c,d,e,f,q),x),Not(IntegerQ(q)),IntegerQ(m))));
IIntegrate(1305,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1),x),x),And(FreeQ(List(a,b,c,d,e,f,m,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(q)),Not(IntegerQ(m)))));
IIntegrate(1306,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q)),Power(Plus(a,Times(c,Power(x,C4))),CN1),x),x),And(FreeQ(List(a,c,d,e,f,m,q),x),Not(IntegerQ(q)),Not(IntegerQ(m)))));
IIntegrate(1307,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(With(List(Set(r,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Dist(Times(C2,c,Power(r,CN1)),Int(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(b,Negate(r),Times(C2,c,Sqr(x))),CN1)),x),x),Dist(Times(C2,c,Power(r,CN1)),Int(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(b,r,Times(C2,c,Sqr(x))),CN1)),x),x))),And(FreeQ(List(a,b,c,d,e,f,m,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0))));
IIntegrate(1308,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1)),x_Symbol),
    Condition(With(List(Set(r,Rt(Times(CN1,a,c),C2))),Subtract(Negate(Dist(Times(c,Power(Times(C2,r),CN1)),Int(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Subtract(r,Times(c,Sqr(x))),CN1)),x),x)),Dist(Times(c,Power(Times(C2,r),CN1)),Int(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(r,Times(c,Sqr(x))),CN1)),x),x))),FreeQ(List(a,c,d,e,f,m,q),x)));
IIntegrate(1309,Int(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(Plus(Dist(Power(d,CN2),Int(Times(Power(Times(f,x),m),Plus(Times(a,d),Times(Subtract(Times(b,d),Times(a,e)),Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Subtract(p,C1))),x),x),Dist(Times(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Power(Times(Sqr(d),Power(f,C4)),CN1)),Int(Times(Power(Times(f,x),Plus(m,C4)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Subtract(p,C1)),Power(Plus(d,Times(e,Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),GtQ(p,C0),LtQ(m,CN2))));
IIntegrate(1310,Int(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(Plus(Dist(Times(a,Power(d,CN2)),Int(Times(Power(Times(f,x),m),Subtract(d,Times(e,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),Subtract(p,C1))),x),x),Dist(Times(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(Times(Sqr(d),Power(f,C4)),CN1)),Int(Times(Power(Times(f,x),Plus(m,C4)),Power(Plus(a,Times(c,Power(x,C4))),Subtract(p,C1)),Power(Plus(d,Times(e,Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,f),x),GtQ(p,C0),LtQ(m,CN2))));
IIntegrate(1311,Int(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(Subtract(Dist(Power(Times(d,e),CN1),Int(Times(Power(Times(f,x),m),Plus(Times(a,e),Times(c,d,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Subtract(p,C1))),x),x),Dist(Times(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Power(Times(d,e,Sqr(f)),CN1)),Int(Times(Power(Times(f,x),Plus(m,C2)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Subtract(p,C1)),Power(Plus(d,Times(e,Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),GtQ(p,C0),LtQ(m,C0))));
IIntegrate(1312,Int(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(Subtract(Dist(Power(Times(d,e),CN1),Int(Times(Power(Times(f,x),m),Plus(Times(a,e),Times(c,d,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),Subtract(p,C1))),x),x),Dist(Times(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(Times(d,e,Sqr(f)),CN1)),Int(Times(Power(Times(f,x),Plus(m,C2)),Power(Plus(a,Times(c,Power(x,C4))),Subtract(p,C1)),Power(Plus(d,Times(e,Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,f),x),GtQ(p,C0),LtQ(m,C0))));
IIntegrate(1313,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Negate(Dist(Times(Power(f,C4),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),Subtract(m,C4)),Plus(Times(a,d),Times(Subtract(Times(b,d),Times(a,e)),Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p)),x),x)),Dist(Times(Sqr(d),Power(f,C4),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),Subtract(m,C4)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Power(Plus(d,Times(e,Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1),GtQ(m,C2))));
IIntegrate(1314,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Plus(Negate(Dist(Times(a,Power(f,C4),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),Subtract(m,C4)),Subtract(d,Times(e,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),p)),x),x)),Dist(Times(Sqr(d),Power(f,C4),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),Subtract(m,C4)),Power(Plus(a,Times(c,Power(x,C4))),Plus(p,C1)),Power(Plus(d,Times(e,Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,f),x),LtQ(p,CN1),GtQ(m,C2))));
IIntegrate(1315,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_DEFAULT,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Subtract(Dist(Times(Sqr(f),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),Subtract(m,C2)),Plus(Times(a,e),Times(c,d,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p)),x),x),Dist(Times(d,e,Sqr(f),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),Subtract(m,C2)),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Power(Plus(d,Times(e,Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1),GtQ(m,C0))));
IIntegrate(1316,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Subtract(Dist(Times(Sqr(f),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),Subtract(m,C2)),Plus(Times(a,e),Times(c,d,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),p)),x),x),Dist(Times(d,e,Sqr(f),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Power(Times(f,x),Subtract(m,C2)),Power(Plus(a,Times(c,Power(x,C4))),Plus(p,C1)),Power(Plus(d,Times(e,Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,f),x),LtQ(p,CN1),GtQ(m,C0))));
IIntegrate(1317,Int(Times(Sqr(x_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Subtract(Dist(Times(d,Power(Times(C2,d,e),CN1)),Int(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x),x),Dist(Times(d,Power(Times(C2,d,e),CN1)),Int(Times(Subtract(d,Times(e,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1))),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1318,Int(Times(Sqr(x_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Subtract(Dist(Times(d,Power(Times(C2,d,e),CN1)),Int(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x),x),Dist(Times(d,Power(Times(C2,d,e),CN1)),Int(Times(Subtract(d,Times(e,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x),x)),And(FreeQ(List(a,c,d,e),x),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1))),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1319,Int(Times(Sqr(x_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Times(c,Power(a,CN1)),C2))),Plus(Negate(Dist(Times(a,Plus(e,Times(d,q)),Power(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x),x)),Dist(Times(a,d,Plus(e,Times(d,q)),Power(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Plus(C1,Times(q,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1))),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1320,Int(Times(Sqr(x_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Times(c,Power(a,CN1)),C2))),Plus(Negate(Dist(Times(a,Plus(e,Times(d,q)),Power(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x),x)),Dist(Times(a,d,Plus(e,Times(d,q)),Power(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Plus(C1,Times(q,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x),x))),And(FreeQ(List(a,c,d,e),x),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),PosQ(Times(c,Power(a,CN1))),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1321,Int(Times(Power(x_,C4),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Plus(Negate(Dist(Power(e,CN2),Int(Times(Subtract(d,Times(e,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x),x)),Dist(Times(Sqr(d),Power(e,CN2)),Int(Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1),x),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),PosQ(Times(c,Power(a,CN1))),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1322,Int(Times(Power(x_,C4),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Plus(Negate(Dist(Power(e,CN2),Int(Times(Subtract(d,Times(e,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1D2)),x),x)),Dist(Times(Sqr(d),Power(e,CN2)),Int(Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1),x),x)),And(FreeQ(List(a,c,d,e),x),PosQ(Times(c,Power(a,CN1))),EqQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1323,Int(Times(Power(x_,C4),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Times(c,Power(a,CN1)),C2))),Condition(Plus(Negate(Dist(Power(Times(e,q),CN1),Int(Times(Subtract(C1,Times(q,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x),x)),Dist(Times(Sqr(d),Power(Times(e,Subtract(e,Times(d,q))),CN1)),Int(Times(Plus(C1,Times(q,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x),x)),EqQ(Subtract(Times(C2,c,d),Times(a,e,q)),C0))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),PosQ(Times(c,Power(a,CN1))),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1324,Int(Times(Power(x_,C4),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Times(c,Power(a,CN1)),C2))),Condition(Plus(Negate(Dist(Power(Times(e,q),CN1),Int(Times(Subtract(C1,Times(q,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1D2)),x),x)),Dist(Times(Sqr(d),Power(Times(e,Subtract(e,Times(d,q))),CN1)),Int(Times(Plus(C1,Times(q,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x),x)),EqQ(Subtract(Times(C2,c,d),Times(a,e,q)),C0))),And(FreeQ(List(a,c,d,e),x),PosQ(Times(c,Power(a,CN1))),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1325,Int(Times(Power(x_,C4),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Times(c,Power(a,CN1)),C2))),Plus(Negate(Dist(Times(Subtract(Times(C2,c,d),Times(a,e,q)),Power(Times(c,e,Subtract(e,Times(d,q))),CN1)),Int(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2),x),x)),Negate(Dist(Power(Times(e,q),CN1),Int(Times(Subtract(C1,Times(q,Sqr(x))),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),CN1D2)),x),x)),Dist(Times(Sqr(d),Power(Times(e,Subtract(e,Times(d,q))),CN1)),Int(Times(Plus(C1,Times(q,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),PosQ(Times(c,Power(a,CN1))),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1326,Int(Times(Power(x_,C4),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Times(c,Power(a,CN1)),C2))),Plus(Negate(Dist(Times(Subtract(Times(C2,c,d),Times(a,e,q)),Power(Times(c,e,Subtract(e,Times(d,q))),CN1)),Int(Power(Plus(a,Times(c,Power(x,C4))),CN1D2),x),x)),Negate(Dist(Power(Times(e,q),CN1),Int(Times(Subtract(C1,Times(q,Sqr(x))),Power(Plus(a,Times(c,Power(x,C4))),CN1D2)),x),x)),Dist(Times(Sqr(d),Power(Times(e,Subtract(e,Times(d,q))),CN1)),Int(Times(Plus(C1,Times(q,Sqr(x))),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x),x))),And(FreeQ(List(a,c,d,e),x),PosQ(Times(c,Power(a,CN1))),NeQ(Subtract(Times(c,Sqr(d)),Times(a,Sqr(e))),C0))));
IIntegrate(1327,Int(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(x,Subtract(m,C5)),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4)))),Power(Times(c,e,Subtract(m,C3)),CN1)),x),Dist(Power(Times(c,e,Subtract(m,C3)),CN1),Int(Times(Power(x,Subtract(m,C6)),Simp(Plus(Times(a,d,Subtract(m,C5)),Times(Plus(Times(a,e,Subtract(m,C5)),Times(b,d,Subtract(m,C4))),Sqr(x)),Times(Plus(Times(b,e,Subtract(m,C4)),Times(c,d,Subtract(m,C3))),Power(x,C4))),x),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(Times(C1D2,m),C2))));
IIntegrate(1328,Int(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(x,Subtract(m,C5)),Sqrt(Plus(a,Times(c,Power(x,C4)))),Power(Times(c,e,Subtract(m,C3)),CN1)),x),Dist(Power(Times(c,e,Subtract(m,C3)),CN1),Int(Times(Power(x,Subtract(m,C6)),Simp(Plus(Times(a,d,Subtract(m,C5)),Times(a,e,Subtract(m,C5),Sqr(x)),Times(c,d,Subtract(m,C3),Power(x,C4))),x),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x),x)),And(FreeQ(List(a,c,d,e),x),IGtQ(Times(C1D2,m),C2))));
IIntegrate(1329,Int(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(x,Plus(m,C1)),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4)))),Power(Times(a,d,Plus(m,C1)),CN1)),x),Dist(Power(Times(a,d,Plus(m,C1)),CN1),Int(Times(Power(x,Plus(m,C2)),Simp(Plus(Times(a,e,Plus(m,C1)),Times(b,d,Plus(m,C2)),Times(Plus(Times(b,e,Plus(m,C2)),Times(c,d,Plus(m,C3))),Sqr(x)),Times(c,e,Plus(m,C3),Power(x,C4))),x),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),ILtQ(Times(C1D2,m),C0))));
IIntegrate(1330,Int(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(x,Plus(m,C1)),Sqrt(Plus(a,Times(c,Power(x,C4)))),Power(Times(a,d,Plus(m,C1)),CN1)),x),Dist(Power(Times(a,d,Plus(m,C1)),CN1),Int(Times(Power(x,Plus(m,C2)),Simp(Plus(Times(a,e,Plus(m,C1)),Times(c,d,Plus(m,C3),Sqr(x)),Times(c,e,Plus(m,C3),Power(x,C4))),x),Power(Times(Plus(d,Times(e,Sqr(x))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),x),x)),And(FreeQ(List(a,c,d,e),x),ILtQ(Times(C1D2,m),C0))));
IIntegrate(1331,Int(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1D2),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Dist(Times(Power(x,C3),Sqrt(Plus(e,Times(d,Power(x,CN2)))),Sqrt(Plus(c,Times(b,Power(x,CN2)),Times(a,Power(x,CN4)))),Power(Times(Sqrt(Plus(d,Times(e,Sqr(x)))),Sqrt(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))))),CN1)),Int(Times(Power(x,Subtract(m,C3)),Power(Times(Sqrt(Plus(e,Times(d,Power(x,CN2)))),Sqrt(Plus(c,Times(b,Power(x,CN2)),Times(a,Power(x,CN4))))),CN1)),x),x),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IntegerQ(Times(C1D2,m)))));
IIntegrate(1332,Int(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),CN1D2),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),CN1D2)),x_Symbol),
    Condition(Dist(Times(Power(x,C3),Sqrt(Plus(e,Times(d,Power(x,CN2)))),Sqrt(Plus(c,Times(a,Power(x,CN4)))),Power(Times(Sqrt(Plus(d,Times(e,Sqr(x)))),Sqrt(Plus(a,Times(c,Power(x,C4))))),CN1)),Int(Times(Power(x,Subtract(m,C3)),Power(Times(Sqrt(Plus(e,Times(d,Power(x,CN2)))),Sqrt(Plus(c,Times(a,Power(x,CN4))))),CN1)),x),x),And(FreeQ(List(a,c,d,e),x),IntegerQ(Times(C1D2,m)))));
IIntegrate(1333,Int(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(With(List(Set(f,Coeff(PolynomialRemainder(Times(Power(x,m),Power(Plus(d,Times(e,Sqr(x))),q)),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),x,C0)),Set(g,Coeff(PolynomialRemainder(Times(Power(x,m),Power(Plus(d,Times(e,Sqr(x))),q)),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),x,C2))),Plus(Simp(Times(x,Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Subtract(Subtract(Times(a,b,g),Times(f,Subtract(Sqr(b),Times(C2,a,c)))),Times(c,Subtract(Times(b,f),Times(C2,a,g)),Sqr(x))),Power(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x),Dist(Power(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Int(Times(Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Simp(ExpandToSum(Plus(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),PolynomialQuotient(Times(Power(x,m),Power(Plus(d,Times(e,Sqr(x))),q)),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x)),Times(Sqr(b),f,Plus(Times(C2,p),C3)),Times(CN1,C2,a,c,f,Plus(Times(C4,p),C5)),Times(CN1,a,b,g),Times(c,Plus(Times(C4,p),C7),Subtract(Times(b,f),Times(C2,a,g)),Sqr(x))),x),x)),x),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1),IGtQ(q,C1),IGtQ(Times(C1D2,m),C0))));
IIntegrate(1334,Int(Times(Power(x_,m_),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(With(List(Set(f,Coeff(PolynomialRemainder(Times(Power(x,m),Power(Plus(d,Times(e,Sqr(x))),q)),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),x,C0)),Set(g,Coeff(PolynomialRemainder(Times(Power(x,m),Power(Plus(d,Times(e,Sqr(x))),q)),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),x,C2))),Plus(Simp(Times(x,Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Subtract(Subtract(Times(a,b,g),Times(f,Subtract(Sqr(b),Times(C2,a,c)))),Times(c,Subtract(Times(b,f),Times(C2,a,g)),Sqr(x))),Power(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x),Dist(Power(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Int(Times(Power(x,m),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),Plus(p,C1)),Simp(ExpandToSum(Plus(Times(C2,a,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c)),PolynomialQuotient(Times(Power(x,m),Power(Plus(d,Times(e,Sqr(x))),q)),Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),x),Power(Power(x,m),CN1)),Times(Subtract(Subtract(Times(Sqr(b),f,Plus(Times(C2,p),C3)),Times(C2,a,c,f,Plus(Times(C4,p),C5))),Times(a,b,g)),Power(Power(x,m),CN1)),Times(c,Plus(Times(C4,p),C7),Subtract(Times(b,f),Times(C2,a,g)),Power(x,Subtract(C2,m)))),x),x)),x),x))),And(FreeQ(List(a,b,c,d,e),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1),IGtQ(q,C1),ILtQ(Times(C1D2,m),C0))));
IIntegrate(1335,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p)),x),x),And(FreeQ(List(a,b,c,d,e,f,m,p,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Or(IGtQ(p,C0),IGtQ(q,C0),IntegersQ(m,q)))));
IIntegrate(1336,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(a,Times(c,Power(x,C4))),p)),x),x),And(FreeQ(List(a,c,d,e,f,m,p,q),x),Or(IGtQ(p,C0),IGtQ(q,C0),IntegersQ(m,q)))));
IIntegrate(1337,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_)),x_Symbol),
    Condition(Dist(Times(Power(Times(f,x),m),Power(Power(x,m),CN1)),Int(ExpandIntegrand(Times(Power(x,m),Power(Plus(a,Times(c,Power(x,C4))),p)),Power(Subtract(Times(d,Power(Subtract(Sqr(d),Times(Sqr(e),Power(x,C4))),CN1)),Times(e,Sqr(x),Power(Subtract(Sqr(d),Times(Sqr(e),Power(x,C4))),CN1))),Negate(q)),x),x),x),And(FreeQ(List(a,c,d,e,f,m,p),x),Not(IntegerQ(p)),ILtQ(q,C0))));
IIntegrate(1338,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,Sqr(x_)),Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(a,Times(b,Sqr(x)),Times(c,Power(x,C4))),p)),x),FreeQ(List(a,b,c,d,e,f,m,p,q),x)));
IIntegrate(1339,Int(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Sqr(x_))),q_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,C4))),p_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Sqr(x))),q),Power(Plus(a,Times(c,Power(x,C4))),p)),x),FreeQ(List(a,c,d,e,f,m,p,q),x)));
IIntegrate(1340,Int(Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_DEFAULT),x_Symbol),
    Condition(Int(Times(Power(x,Times(C2,n,p)),Power(Plus(c,Times(b,Power(Power(x,n),CN1)),Times(a,Power(Power(x,Times(C2,n)),CN1))),p)),x),And(FreeQ(List(a,b,c),x),EqQ($s("n2"),Times(C2,n)),LtQ(n,C0),IntegerQ(p))));
IIntegrate(1341,Int(Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_),x_Symbol),
    Condition(With(List(Set(k,Denominator(n))),Dist(k,Subst(Int(Times(Power(x,Subtract(k,C1)),Power(Plus(a,Times(b,Power(x,Times(k,n))),Times(c,Power(x,Times(C2,k,n)))),p)),x),x,Power(x,Power(k,CN1))),x)),And(FreeQ(List(a,b,c,p),x),EqQ($s("n2"),Times(C2,n)),FractionQ(n))));
IIntegrate(1342,Int(Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_),x_Symbol),
    Condition(Negate(Subst(Int(Times(Power(Plus(a,Times(b,Power(Power(x,n),CN1)),Times(c,Power(Power(x,Times(C2,n)),CN1))),p),Power(x,CN2)),x),x,Power(x,CN1))),And(FreeQ(List(a,b,c,p),x),EqQ($s("n2"),Times(C2,n)),ILtQ(n,C0))));
IIntegrate(1343,Int(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_DEFAULT)),Times(c_DEFAULT,Power(x_,$p("n2",true)))),p_),x_Symbol),
    Condition(Dist(Times(Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),p),Power(Power(Plus(b,Times(C2,c,Power(x,n))),Times(C2,p)),CN1)),Int(Power(Plus(b,Times(C2,c,Power(x,n))),Times(C2,p)),x),x),And(FreeQ(List(a,b,c,n,p),x),EqQ($s("n2"),Times(C2,n)),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0))));
IIntegrate(1344,Int(Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),p),x),x),And(FreeQ(List(a,b,c,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(p,C0))));
IIntegrate(1345,Int(Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_),x_Symbol),
    Condition(Plus(Negate(Simp(Times(x,Plus(Sqr(b),Times(CN1,C2,a,c),Times(b,c,Power(x,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Plus(p,C1)),Power(Times(a,n,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1)),x)),Dist(Power(Times(a,n,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),CN1),Int(Times(Plus(Sqr(b),Times(CN1,C2,a,c),Times(n,Plus(p,C1),Subtract(Sqr(b),Times(C4,a,c))),Times(b,c,Plus(Times(n,Plus(Times(C2,p),C3)),C1),Power(x,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Plus(p,C1))),x),x)),And(FreeQ(List(a,b,c,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),ILtQ(p,CN1))));
IIntegrate(1346,Int(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1),x_Symbol),
    Condition(With(List(Set(q,Rt(Times(a,Power(c,CN1)),C2))),With(List(Set(r,Rt(Subtract(Times(C2,q),Times(b,Power(c,CN1))),C2))),Plus(Dist(Power(Times(C2,c,q,r),CN1),Int(Times(Subtract(r,Power(x,Times(C1D2,n))),Power(Plus(q,Times(CN1,r,Power(x,Times(C1D2,n))),Power(x,n)),CN1)),x),x),Dist(Power(Times(C2,c,q,r),CN1),Int(Times(Plus(r,Power(x,Times(C1D2,n))),Power(Plus(q,Times(r,Power(x,Times(C1D2,n))),Power(x,n)),CN1)),x),x)))),And(FreeQ(List(a,b,c),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(Times(C1D2,n),C0),NegQ(Subtract(Sqr(b),Times(C4,a,c))))));
IIntegrate(1347,Int(Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1),x_Symbol),
    Condition(With(List(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Dist(Times(c,Power(q,CN1)),Int(Power(Plus(Times(C1D2,b),Times(CN1,C1D2,q),Times(c,Power(x,n))),CN1),x),x),Dist(Times(c,Power(q,CN1)),Int(Power(Plus(Times(C1D2,b),Times(C1D2,q),Times(c,Power(x,n))),CN1),x),x))),And(FreeQ(List(a,b,c),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0))));
IIntegrate(1348,Int(Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_),x_Symbol),
    Condition(Dist(Times(Power(a,IntPart(p)),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),FracPart(p)),Power(Times(Power(Plus(C1,Times(C2,c,Power(x,n),Power(Plus(b,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2)),CN1))),FracPart(p)),Power(Plus(C1,Times(C2,c,Power(x,n),Power(Subtract(b,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2)),CN1))),FracPart(p))),CN1)),Int(Times(Power(Plus(C1,Times(C2,c,Power(x,n),Power(Plus(b,Sqrt(Subtract(Sqr(b),Times(C4,a,c)))),CN1))),p),Power(Plus(C1,Times(C2,c,Power(x,n),Power(Subtract(b,Sqrt(Subtract(Sqr(b),Times(C4,a,c)))),CN1))),p)),x),x),And(FreeQ(List(a,b,c,n,p),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(p)))));
IIntegrate(1349,Int(Power(Plus(a_,Times(c_DEFAULT,Power(u_,$p("n2",true))),Times(b_DEFAULT,Power(u_,n_))),p_),x_Symbol),
    Condition(Dist(Power(Coefficient(u,x,C1),CN1),Subst(Int(Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),p),x),x,u),x),And(FreeQ(List(a,b,c,n,p),x),EqQ($s("n2"),Times(C2,n)),LinearQ(u,x),NeQ(u,x))));
IIntegrate(1350,Int(Power(Plus(a_,Times(c_DEFAULT,Power(x_,n_DEFAULT)),Times(b_DEFAULT,Power(x_,$p("mn")))),p_DEFAULT),x_Symbol),
    Condition(Int(Times(Power(Plus(b,Times(a,Power(x,n)),Times(c,Power(x,Times(C2,n)))),p),Power(Power(x,Times(n,p)),CN1)),x),And(FreeQ(List(a,b,c,n),x),EqQ($s("mn"),Negate(n)),IntegerQ(p),PosQ(n))));
  }
}
}
