package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules144 { 
  public static IAST RULES = List( 
IIntegrate(2881,Integrate(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),p_DEFAULT),Plus(f_DEFAULT,Times(Log(Times(h_DEFAULT,Power(Plus(i_DEFAULT,Times(j_DEFAULT,x_)),m_DEFAULT))),g_DEFAULT)),Power(Plus(k_DEFAULT,Times(l_DEFAULT,x_)),r_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(e,CN1),Subst(Integrate(Times(Power(Times(k,x,Power(d,CN1)),r),Power(Plus(a,Times(b,Log(Times(c,Power(x,n))))),p),Plus(f,Times(g,Log(Times(h,Power(Plus(Times(Subtract(Times(e,i),Times(d,j)),Power(e,CN1)),Times(j,x,Power(e,CN1))),m)))))),x),x,Plus(d,Times(e,x)))),x),And(FreeQ(List(a,b,c,d,e,f,g,h,i,j,k,l,n,p,r),x),EqQ(Subtract(Times(e,k),Times(d,l)),C0)))),
IIntegrate(2882,Integrate(Times(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),Plus(f_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),g_DEFAULT)),Power(x_,CN1)),x_Symbol),
    Condition(Subtract(Simp(Times(Log(x),Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Plus(f,Times(g,Log(Times(c,Power(Plus(d,Times(e,x)),n)))))),x),Simp(Star(Times(e,n),Integrate(Times(Log(x),Plus(Times(b,f),Times(a,g),Times(C2,b,g,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Power(Plus(d,Times(e,x)),CN1)),x)),x)),FreeQ(List(a,b,c,d,e,f,g,n),x))),
IIntegrate(2883,Integrate(Times(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),Plus(f_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),g_DEFAULT)),Power(x_,m_DEFAULT)),x_Symbol),
    Condition(Subtract(Simp(Times(Power(x,Plus(m,C1)),Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Plus(f,Times(g,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Power(Plus(m,C1),CN1)),x),Simp(Star(Times(e,n,Power(Plus(m,C1),CN1)),Integrate(Times(Power(x,Plus(m,C1)),Plus(Times(b,f),Times(a,g),Times(C2,b,g,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Power(Plus(d,Times(e,x)),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,n,m),x),NeQ(m,CN1)))),
IIntegrate(2884,Integrate(Times(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),Plus(f_DEFAULT,Times(Log(Times(h_DEFAULT,Power(Plus(i_DEFAULT,Times(j_DEFAULT,x_)),m_DEFAULT))),g_DEFAULT)),Power(x_,CN1)),x_Symbol),
    Condition(Plus(Simp(Times(Log(x),Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Plus(f,Times(g,Log(Times(h,Power(Plus(i,Times(j,x)),m)))))),x),Negate(Simp(Star(Times(e,g,m),Integrate(Times(Log(x),Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Power(Plus(d,Times(e,x)),CN1)),x)),x)),Negate(Simp(Star(Times(b,j,n),Integrate(Times(Log(x),Plus(f,Times(g,Log(Times(h,Power(Plus(i,Times(j,x)),m))))),Power(Plus(i,Times(j,x)),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,e,f,g,h,i,j,m,n),x),EqQ(Subtract(Times(e,i),Times(d,j)),C0)))),
IIntegrate(2885,Integrate(Times(Log(Plus(a_,Times(b_DEFAULT,x_))),Log(Plus(c_,Times(d_DEFAULT,x_))),Power(x_,CN1)),x_Symbol),
    Condition(Plus(Simp(Times(Log(Times(CN1,b,x,Power(a,CN1))),Log(Plus(a,Times(b,x))),Log(Plus(c,Times(d,x)))),x),Simp(Times(C1D2,Plus(Log(Times(CN1,b,x,Power(a,CN1))),Negate(Log(Times(CN1,Subtract(Times(b,c),Times(a,d)),x,Power(Times(a,Plus(c,Times(d,x))),CN1)))),Log(Times(Subtract(Times(b,c),Times(a,d)),Power(Times(b,Plus(c,Times(d,x))),CN1)))),Sqr(Log(Times(a,Plus(c,Times(d,x)),Power(Times(c,Plus(a,Times(b,x))),CN1))))),x),Negate(Simp(Times(C1D2,Subtract(Log(Times(CN1,b,x,Power(a,CN1))),Log(Times(CN1,d,x,Power(c,CN1)))),Sqr(Plus(Log(Plus(a,Times(b,x))),Log(Times(a,Plus(c,Times(d,x)),Power(Times(c,Plus(a,Times(b,x))),CN1)))))),x)),Simp(Times(Subtract(Log(Plus(c,Times(d,x))),Log(Times(a,Plus(c,Times(d,x)),Power(Times(c,Plus(a,Times(b,x))),CN1)))),PolyLog(C2,Plus(C1,Times(b,x,Power(a,CN1))))),x),Simp(Times(Plus(Log(Plus(a,Times(b,x))),Log(Times(a,Plus(c,Times(d,x)),Power(Times(c,Plus(a,Times(b,x))),CN1)))),PolyLog(C2,Plus(C1,Times(d,x,Power(c,CN1))))),x),Simp(Times(Log(Times(a,Plus(c,Times(d,x)),Power(Times(c,Plus(a,Times(b,x))),CN1))),PolyLog(C2,Times(c,Plus(a,Times(b,x)),Power(Times(a,Plus(c,Times(d,x))),CN1)))),x),Negate(Simp(Times(Log(Times(a,Plus(c,Times(d,x)),Power(Times(c,Plus(a,Times(b,x))),CN1))),PolyLog(C2,Times(d,Plus(a,Times(b,x)),Power(Times(b,Plus(c,Times(d,x))),CN1)))),x)),Negate(Simp(PolyLog(C3,Plus(C1,Times(b,x,Power(a,CN1)))),x)),Negate(Simp(PolyLog(C3,Plus(C1,Times(d,x,Power(c,CN1)))),x)),Simp(PolyLog(C3,Times(c,Plus(a,Times(b,x)),Power(Times(a,Plus(c,Times(d,x))),CN1))),x),Negate(Simp(PolyLog(C3,Times(d,Plus(a,Times(b,x)),Power(Times(b,Plus(c,Times(d,x))),CN1))),x))),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(2886,Integrate(Times(Log(v_),Log(w_),Power(x_,CN1)),x_Symbol),
    Condition(Integrate(Times(Log(ExpandToSum(v,x)),Log(ExpandToSum(w,x)),Power(x,CN1)),x),And(LinearQ(list(v,w),x),Not(LinearMatchQ(list(v,w),x))))),
IIntegrate(2887,Integrate(Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),Log(Times(h_DEFAULT,Power(Plus(i_DEFAULT,Times(j_DEFAULT,x_)),m_DEFAULT))),Power(x_,CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(m,Integrate(Times(Log(Plus(i,Times(j,x))),Log(Times(c,Power(Plus(d,Times(e,x)),n))),Power(x,CN1)),x)),x),Simp(Star(Subtract(Times(m,Log(Plus(i,Times(j,x)))),Log(Times(h,Power(Plus(i,Times(j,x)),m)))),Integrate(Times(Log(Times(c,Power(Plus(d,Times(e,x)),n))),Power(x,CN1)),x)),x)),And(FreeQ(List(c,d,e,h,i,j,m,n),x),NeQ(Subtract(Times(e,i),Times(d,j)),C0),NeQ(Plus(i,Times(j,x)),Times(h,Power(Plus(i,Times(j,x)),m)))))),
IIntegrate(2888,Integrate(Times(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),Plus(Times(Log(Times(h_DEFAULT,Power(Plus(i_DEFAULT,Times(j_DEFAULT,x_)),m_DEFAULT))),g_DEFAULT),f_),Power(x_,CN1)),x_Symbol),
    Condition(Plus(Simp(Star(f,Integrate(Times(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Power(x,CN1)),x)),x),Simp(Star(g,Integrate(Times(Log(Times(h,Power(Plus(i,Times(j,x)),m))),Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Power(x,CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,g,h,i,j,m,n),x),NeQ(Subtract(Times(e,i),Times(d,j)),C0)))),
IIntegrate(2889,Integrate(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),p_DEFAULT),Plus(f_DEFAULT,Times(Log(Times(h_DEFAULT,Power(Plus(i_DEFAULT,Times(j_DEFAULT,x_)),m_DEFAULT))),g_DEFAULT)),Power(x_,r_DEFAULT)),x_Symbol),
    Condition(Plus(Simp(Times(Power(x,Plus(r,C1)),Power(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),p),Plus(f,Times(g,Log(Times(h,Power(Plus(i,Times(j,x)),m))))),Power(Plus(r,C1),CN1)),x),Negate(Simp(Star(Times(g,j,m,Power(Plus(r,C1),CN1)),Integrate(Times(Power(x,Plus(r,C1)),Power(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),p),Power(Plus(i,Times(j,x)),CN1)),x)),x)),Negate(Simp(Star(Times(b,e,n,p,Power(Plus(r,C1),CN1)),Integrate(Times(Power(x,Plus(r,C1)),Power(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),Subtract(p,C1)),Plus(f,Times(g,Log(Times(h,Power(Plus(i,Times(j,x)),m))))),Power(Plus(d,Times(e,x)),CN1)),x)),x))),And(FreeQ(List(a,b,c,d,e,f,g,h,i,j,m,n),x),IGtQ(p,C0),IntegerQ(r),Or(EqQ(p,C1),GtQ(r,C0)),NeQ(r,CN1)))),
IIntegrate(2890,Integrate(Times(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),Plus(f_DEFAULT,Times(Log(Times(h_DEFAULT,Power(Plus(i_DEFAULT,Times(j_DEFAULT,x_)),m_DEFAULT))),g_DEFAULT)),Power(Plus(k_,Times(l_DEFAULT,x_)),r_DEFAULT)),x_Symbol),
    Condition(Simp(Star(Power(l,CN1),Subst(Integrate(Times(Power(x,r),Plus(a,Times(b,Log(Times(c,Power(Plus(Times(CN1,Subtract(Times(e,k),Times(d,l)),Power(l,CN1)),Times(e,x,Power(l,CN1))),n))))),Plus(f,Times(g,Log(Times(h,Power(Plus(Times(CN1,Subtract(Times(j,k),Times(i,l)),Power(l,CN1)),Times(j,x,Power(l,CN1))),m)))))),x),x,Plus(k,Times(l,x)))),x),And(FreeQ(List(a,b,c,d,e,f,g,h,i,j,k,l,m,n),x),IntegerQ(r)))),
IIntegrate(2891,Integrate(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),p_DEFAULT),Power(Plus(f_DEFAULT,Times(Log(Times(h_DEFAULT,Power(Plus(i_DEFAULT,Times(j_DEFAULT,x_)),m_DEFAULT))),g_DEFAULT)),q_DEFAULT),Power(Plus(k_DEFAULT,Times(l_DEFAULT,x_)),r_DEFAULT)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(k,Times(l,x)),r),Power(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),p),Power(Plus(f,Times(g,Log(Times(h,Power(Plus(i,Times(j,x)),m))))),q)),x),FreeQ(List(a,b,c,d,e,f,g,h,i,j,k,l,m,n,p,q,r),x))),
IIntegrate(2892,Integrate(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),p_DEFAULT),Power(Plus(f_,Times(g_DEFAULT,x_)),CN1),PolyLog(k_,Plus(h_,Times(i_DEFAULT,x_)))),x_Symbol),
    Condition(Simp(Star(Power(g,CN1),Subst(Integrate(Times(PolyLog(k,Times(h,x,Power(d,CN1))),Power(Plus(a,Times(b,Log(Times(c,Power(x,n))))),p),Power(x,CN1)),x),x,Plus(d,Times(e,x)))),x),And(FreeQ(List(a,b,c,d,e,f,g,h,i,k,n),x),EqQ(Subtract(Times(e,f),Times(d,g)),C0),EqQ(Subtract(Times(g,h),Times(f,i)),C0),IGtQ(p,C0)))),
IIntegrate(2893,Integrate(Times(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,x_)),n_DEFAULT))),b_DEFAULT)),$p("§px",true),$(F_,Times(f_DEFAULT,Plus(g_DEFAULT,Times(h_DEFAULT,x_))))),x_Symbol),
    Condition(With(list(Set(u,IntHide(Times($s("§px"),F(Times(f,Plus(g,Times(h,x))))),x))),Subtract(Simp(Star(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,x)),n))))),u),x),Simp(Star(Times(b,e,n),Integrate(SimplifyIntegrand(Times(u,Power(Plus(d,Times(e,x)),CN1)),x),x)),x))),And(FreeQ(List(a,b,c,d,e,f,g,h,n),x),PolynomialQ($s("§px"),x),MemberQ(List(ArcSin,ArcCos,ArcTan,ArcCot,ArcSinh,ArcCosh,ArcTanh,ArcCoth),FSymbol)))),
IIntegrate(2894,Integrate(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(v_,n_DEFAULT))),b_DEFAULT)),p_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Integrate(Times(u,Power(Plus(a,Times(b,Log(Times(c,Power(ExpandToSum(v,x),n))))),p)),x),And(FreeQ(List(a,b,c,n,p),x),LinearQ(v,x),Not(LinearMatchQ(v,x)),Not(And(EqQ(n,C1),MatchQ(Times(c,v),Condition(Times(e_DEFAULT,Plus(f_,Times(g_DEFAULT,x))),FreeQ(list(e,f,g),x)))))))),
IIntegrate(2895,Integrate(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Times(d_DEFAULT,Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),m_DEFAULT)),n_))),b_DEFAULT)),p_DEFAULT),u_DEFAULT),x_Symbol),
    Condition(Subst(Integrate(Times(u,Power(Plus(a,Times(b,Log(Times(c,Power(d,n),Power(Plus(e,Times(f,x)),Times(m,n)))))),p)),x),Times(c,Power(d,n),Power(Plus(e,Times(f,x)),Times(m,n))),Times(c,Power(Times(d,Power(Plus(e,Times(f,x)),m)),n))),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),Not(IntegerQ(n)),Not(And(EqQ(d,C1),EqQ(m,C1))),IntegralFreeQ(IntHide(Times(u,Power(Plus(a,Times(b,Log(Times(c,Power(d,n),Power(Plus(e,Times(f,x)),Times(m,n)))))),p)),x))))),
IIntegrate(2896,Integrate(Times(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Times(d_DEFAULT,Power(Plus(e_DEFAULT,Times(f_DEFAULT,x_)),m_DEFAULT)),n_))),b_DEFAULT)),p_DEFAULT),$p("§afx")),x_Symbol),
    Condition(Unintegrable(Times($s("§afx"),Power(Plus(a,Times(b,Log(Times(c,Power(Times(d,Power(Plus(e,Times(f,x)),m)),n))))),p)),x),And(FreeQ(List(a,b,c,d,e,f,m,n,p),x),AlgebraicFunctionQ($s("§afx"),x,True)))),
IIntegrate(2897,Integrate(Times(Log(u_),Power($p("§pq"),m_DEFAULT)),x_Symbol),
    Condition(With(list(Set(CSymbol,FullSimplify(Times(Power($s("§pq"),m),Subtract(C1,u),Power(D(u,x),CN1))))),Condition(Simp(Times(CSymbol,PolyLog(C2,Subtract(C1,u))),x),FreeQ(CSymbol,x))),And(IntegerQ(m),PolyQ($s("§pq"),x),RationalFunctionQ(u,x),LeQ(Part(RationalFunctionExponents(u,x),C2),Expon($s("§pq"),x))))),
IIntegrate(2898,Integrate(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),p_DEFAULT))),x_Symbol),
    Condition(Subtract(Simp(Times(x,Log(Times(c,Power(Plus(d,Times(e,Power(x,n))),p)))),x),Simp(Star(Times(e,n,p),Integrate(Times(Power(x,n),Power(Plus(d,Times(e,Power(x,n))),CN1)),x)),x)),FreeQ(List(c,d,e,n,p),x))),
IIntegrate(2899,Integrate(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,Power(x_,CN1))),p_DEFAULT))),b_DEFAULT)),q_),x_Symbol),
    Condition(Plus(Simp(Times(Plus(e,Times(d,x)),Power(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,Power(x,CN1))),p))))),q),Power(d,CN1)),x),Simp(Star(Times(b,e,p,q,Power(d,CN1)),Integrate(Times(Power(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,Power(x,CN1))),p))))),Subtract(q,C1)),Power(x,CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,p),x),IGtQ(q,C0)))),
IIntegrate(2900,Integrate(Power(Plus(a_DEFAULT,Times(Log(Times(c_DEFAULT,Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),p_DEFAULT))),b_DEFAULT)),q_),x_Symbol),
    Condition(Subtract(Simp(Times(x,Power(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,Power(x,n))),p))))),q)),x),Simp(Star(Times(b,e,n,p,q),Integrate(Times(Power(x,n),Power(Plus(a,Times(b,Log(Times(c,Power(Plus(d,Times(e,Power(x,n))),p))))),Subtract(q,C1)),Power(Plus(d,Times(e,Power(x,n))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,n,p),x),IGtQ(q,C0),Or(EqQ(q,C1),IntegerQ(n)))))
  );
}
