package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules92 { 
  public static IAST RULES = List( 
IIntegrate(1841,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(Power(f,Times(C2,n)),Power(c,CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,Times(C2,n))),Power(Plus(d,Times(e,Power(x,n))),q)),x)),x),Simp(Star(Times(a,Power(f,Times(C2,n)),Power(c,CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,Times(C2,n))),Power(Plus(d,Times(e,Power(x,n))),q),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f,q),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),Not(IntegerQ(q)),GtQ(m,Subtract(Times(C2,n),C1))))),
IIntegrate(1842,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(e,Power(f,n),Power(c,CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,n)),Power(Plus(d,Times(e,Power(x,n))),Subtract(q,C1))),x)),x),Simp(Star(Times(Power(f,n),Power(c,CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,n)),Power(Plus(d,Times(e,Power(x,n))),Subtract(q,C1)),Simp(Subtract(Times(a,e),Times(Subtract(Times(c,d),Times(b,e)),Power(x,n))),x),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),Not(IntegerQ(q)),GtQ(q,C0),GtQ(m,Subtract(n,C1)),LeQ(m,Subtract(Times(C2,n),C1))))),
IIntegrate(1843,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(e,Power(f,n),Power(c,CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,n)),Power(Plus(d,Times(e,Power(x,n))),Subtract(q,C1))),x)),x),Simp(Star(Times(Power(f,n),Power(c,CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,n)),Power(Plus(d,Times(e,Power(x,n))),Subtract(q,C1)),Simp(Subtract(Times(a,e),Times(c,d,Power(x,n))),x),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),Not(IntegerQ(q)),GtQ(q,C0),GtQ(m,Subtract(n,C1)),LeQ(m,Subtract(Times(C2,n),C1))))),
IIntegrate(1844,Integrate(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(d,Power(a,CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Power(x,n))),Subtract(q,C1))),x)),x),Simp(Star(Power(Times(a,Power(f,n)),CN1),Integrate(Times(Power(Times(f,x),Plus(m,n)),Power(Plus(d,Times(e,Power(x,n))),Subtract(q,C1)),Simp(Plus(Times(b,d),Times(CN1,a,e),Times(c,d,Power(x,n))),x),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),Not(IntegerQ(q)),GtQ(q,C0),LtQ(m,C0)))),
IIntegrate(1845,Integrate(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(d,Power(a,CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Power(x,n))),Subtract(q,C1))),x)),x),Simp(Star(Power(Times(a,Power(f,n)),CN1),Integrate(Times(Power(Times(f,x),Plus(m,n)),Power(Plus(d,Times(e,Power(x,n))),Subtract(q,C1)),Simp(Subtract(Times(a,e),Times(c,d,Power(x,n))),x),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),Not(IntegerQ(q)),GtQ(q,C0),LtQ(m,C0)))),
IIntegrate(1846,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(Sqr(d),Power(f,Times(C2,n)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,Times(C2,n))),Power(Plus(d,Times(e,Power(x,n))),q)),x)),x),Simp(Star(Times(Power(f,Times(C2,n)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,Times(C2,n))),Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Simp(Plus(Times(a,d),Times(Subtract(Times(b,d),Times(a,e)),Power(x,n))),x),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),Not(IntegerQ(q)),LtQ(q,CN1),GtQ(m,Subtract(Times(C2,n),C1))))),
IIntegrate(1847,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(Sqr(d),Power(f,Times(C2,n)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,Times(C2,n))),Power(Plus(d,Times(e,Power(x,n))),q)),x)),x),Simp(Star(Times(a,Power(f,Times(C2,n)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,Times(C2,n))),Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Subtract(d,Times(e,Power(x,n))),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),Not(IntegerQ(q)),LtQ(q,CN1),GtQ(m,Subtract(Times(C2,n),C1))))),
IIntegrate(1848,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,d,e,Power(f,n),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,n)),Power(Plus(d,Times(e,Power(x,n))),q)),x)),x),Simp(Star(Times(Power(f,n),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,n)),Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Simp(Plus(Times(a,e),Times(c,d,Power(x,n))),x),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),Not(IntegerQ(q)),LtQ(q,CN1),GtQ(m,Subtract(n,C1)),LeQ(m,Subtract(Times(C2,n),C1))))),
IIntegrate(1849,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,d,e,Power(f,n),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,n)),Power(Plus(d,Times(e,Power(x,n))),q)),x)),x),Simp(Star(Times(Power(f,n),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,n)),Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Simp(Plus(Times(a,e),Times(c,d,Power(x,n))),x),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),Not(IntegerQ(q)),LtQ(q,CN1),GtQ(m,Subtract(n,C1)),LeQ(m,Subtract(Times(C2,n),C1))))),
IIntegrate(1850,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Power(Plus(a_,Times(b_DEFAULT,Power(x_,n_)),Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Sqr(e),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Power(x,n))),q)),x)),x),Simp(Star(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Simp(Subtract(Subtract(Times(c,d),Times(b,e)),Times(c,e,Power(x,n))),x),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f,m),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),Not(IntegerQ(q)),LtQ(q,CN1)))),
IIntegrate(1851,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2")))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(Sqr(e),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Power(x,n))),q)),x)),x),Simp(Star(Times(c,Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Power(x,n))),Plus(q,C1)),Subtract(d,Times(e,Power(x,n))),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f,m),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),Not(IntegerQ(q)),LtQ(q,CN1)))),
IIntegrate(1852,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),CN1),Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Power(Plus(d,Times(e,Power(x,n))),q),Times(Power(Times(f,x),m),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1)),x),x),And(FreeQ(List(a,b,c,d,e,f,q,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),Not(IntegerQ(q)),IntegerQ(m)))),
IIntegrate(1853,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),CN1),Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Power(Plus(d,Times(e,Power(x,n))),q),Times(Power(Times(f,x),m),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1)),x),x),And(FreeQ(List(a,c,d,e,f,q,n),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),Not(IntegerQ(q)),IntegerQ(m)))),
IIntegrate(1854,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),CN1),Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Power(x,n))),q)),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),CN1),x),x),And(FreeQ(List(a,b,c,d,e,f,m,q,n),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),Not(IntegerQ(q)),Not(IntegerQ(m))))),
IIntegrate(1855,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),CN1),Power(Plus(d_,Times(e_DEFAULT,Power(x_,n_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Times(f,x),m),Power(Plus(d,Times(e,Power(x,n))),q)),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),CN1),x),x),And(FreeQ(List(a,c,d,e,f,m,q,n),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),Not(IntegerQ(q)),Not(IntegerQ(m))))),
IIntegrate(1856,Integrate(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(a_DEFAULT,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Power(d,CN2),Integrate(Times(Power(Times(f,x),m),Plus(Times(a,d),Times(Subtract(Times(b,d),Times(a,e)),Power(x,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Subtract(p,C1))),x)),x),Simp(Star(Times(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Power(Times(Sqr(d),Power(f,Times(C2,n))),CN1)),Integrate(Times(Power(Times(f,x),Plus(m,Times(C2,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Subtract(p,C1)),Power(Plus(d,Times(e,Power(x,n))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),GtQ(p,C0),LtQ(m,Negate(n))))),
IIntegrate(1857,Integrate(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),p_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(a,Power(d,CN2)),Integrate(Times(Power(Times(f,x),m),Subtract(d,Times(e,Power(x,n))),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),Subtract(p,C1))),x)),x),Simp(Star(Times(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(Times(Sqr(d),Power(f,Times(C2,n))),CN1)),Integrate(Times(Power(Times(f,x),Plus(m,Times(C2,n))),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),Subtract(p,C1)),Power(Plus(d,Times(e,Power(x,n))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),GtQ(p,C0),LtQ(m,Negate(n))))),
IIntegrate(1858,Integrate(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(a_DEFAULT,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Power(Times(d,e),CN1),Integrate(Times(Power(Times(f,x),m),Plus(Times(a,e),Times(c,d,Power(x,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Subtract(p,C1))),x)),x),Simp(Star(Times(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Power(Times(d,e,Power(f,n)),CN1)),Integrate(Times(Power(Times(f,x),Plus(m,n)),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Subtract(p,C1)),Power(Plus(d,Times(e,Power(x,n))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),GtQ(p,C0),LtQ(m,C0)))),
IIntegrate(1859,Integrate(Times(Power(Times(f_DEFAULT,x_),m_),Power(Plus(a_,Times(c_DEFAULT,Power(x_,$p("n2",true)))),p_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Power(Times(d,e),CN1),Integrate(Times(Power(Times(f,x),m),Plus(Times(a,e),Times(c,d,Power(x,n))),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),Subtract(p,C1))),x)),x),Simp(Star(Times(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(Times(d,e,Power(f,n)),CN1)),Integrate(Times(Power(Times(f,x),Plus(m,n)),Power(Plus(a,Times(c,Power(x,Times(C2,n)))),Subtract(p,C1)),Power(Plus(d,Times(e,Power(x,n))),CN1)),x)),x)),And(FreeQ(List(a,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),IGtQ(n,C0),GtQ(p,C0),LtQ(m,C0)))),
IIntegrate(1860,Integrate(Times(Power(Times(f_DEFAULT,x_),m_DEFAULT),Power(Plus(a_DEFAULT,Times(c_DEFAULT,Power(x_,$p("n2",true))),Times(b_DEFAULT,Power(x_,n_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,Power(x_,n_))),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(CN1,Power(f,Times(C2,n)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,Times(C2,n))),Plus(Times(a,d),Times(Subtract(Times(b,d),Times(a,e)),Power(x,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),p)),x)),x),Simp(Star(Times(Sqr(d),Power(f,Times(C2,n)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Integrate(Times(Power(Times(f,x),Subtract(m,Times(C2,n))),Power(Plus(a,Times(b,Power(x,n)),Times(c,Power(x,Times(C2,n)))),Plus(p,C1)),Power(Plus(d,Times(e,Power(x,n))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ($s("n2"),Times(C2,n)),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),IGtQ(n,C0),LtQ(p,CN1),GtQ(m,n))))
  );
}
