package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="http://www.apmaths.uwo.ca/~arich/">Rubi -
 * rule-based integrator</a>.
 *  
 */
public class IntRules19 { 

	public static void initialize() {
		Initializer.init();
	}

	private static class Initializer  {

		private static void init() {
IIntegrate(951,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Plus(Simp(Times(Power(c,p),Power(Plus(d,Times(e,x)),Plus(m,Times(C2,p))),Power(Plus(f,Times(g,x)),Plus(n,C1)),Power(Times(g,Power(e,Times(C2,p)),Plus(m,n,Times(C2,p),C1)),CN1)),x),Dist(Power(Times(g,Power(e,Times(C2,p)),Plus(m,n,Times(C2,p),C1)),CN1),Int(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),ExpandToSum(Subtract(Times(g,Plus(m,n,Times(C2,p),C1),Subtract(Times(Power(e,Times(C2,p)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),Times(Power(c,p),Power(Plus(d,Times(e,x)),Times(C2,p))))),Times(Power(c,p),Subtract(Times(e,f),Times(d,g)),Plus(m,Times(C2,p)),Power(Plus(d,Times(e,x)),Subtract(Times(C2,p),C1)))),x)),x),x)),And(FreeQ(List(a,b,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IGtQ(p,C0),NeQ(Plus(m,n,Times(C2,p),C1),C0),Or(IntegerQ(n),Not(IntegerQ(m))))));
IIntegrate(952,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Plus(Simp(Times(Power(c,p),Power(Plus(d,Times(e,x)),Plus(m,Times(C2,p))),Power(Plus(f,Times(g,x)),Plus(n,C1)),Power(Times(g,Power(e,Times(C2,p)),Plus(m,n,Times(C2,p),C1)),CN1)),x),Dist(Power(Times(g,Power(e,Times(C2,p)),Plus(m,n,Times(C2,p),C1)),CN1),Int(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),ExpandToSum(Subtract(Times(g,Plus(m,n,Times(C2,p),C1),Subtract(Times(Power(e,Times(C2,p)),Power(Plus(a,Times(c,Sqr(x))),p)),Times(Power(c,p),Power(Plus(d,Times(e,x)),Times(C2,p))))),Times(Power(c,p),Subtract(Times(e,f),Times(d,g)),Plus(m,Times(C2,p)),Power(Plus(d,Times(e,x)),Subtract(Times(C2,p),C1)))),x)),x),x)),And(FreeQ(List(a,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IGtQ(p,C0),NeQ(Plus(m,n,Times(C2,p),C1),C0),Or(IntegerQ(n),Not(IntegerQ(m))))));
IIntegrate(953,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Dist(Times(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),Power(Times(e,Subtract(Times(e,f),Times(d,g))),CN1)),Int(Times(Power(Plus(f,Times(g,x)),Plus(n,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C1)),Power(Plus(d,Times(e,x)),CN1)),x),x),Dist(Power(Times(e,Subtract(Times(e,f),Times(d,g))),CN1),Int(Times(Power(Plus(f,Times(g,x)),n),Subtract(Plus(Times(c,d,f),Times(CN1,b,e,f),Times(a,e,g)),Times(c,Subtract(Times(e,f),Times(d,g)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C1))),x),x)),And(FreeQ(List(a,b,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),Not(IntegerQ(n)),Not(IntegerQ(p)),GtQ(p,C0),LtQ(n,CN1))));
IIntegrate(954,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Dist(Times(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),Power(Times(e,Subtract(Times(e,f),Times(d,g))),CN1)),Int(Times(Power(Plus(f,Times(g,x)),Plus(n,C1)),Power(Plus(a,Times(c,Sqr(x))),Subtract(p,C1)),Power(Plus(d,Times(e,x)),CN1)),x),x),Dist(Power(Times(e,Subtract(Times(e,f),Times(d,g))),CN1),Int(Times(Power(Plus(f,Times(g,x)),n),Subtract(Plus(Times(c,d,f),Times(a,e,g)),Times(c,Subtract(Times(e,f),Times(d,g)),x)),Power(Plus(a,Times(c,Sqr(x))),Subtract(p,C1))),x),x)),And(FreeQ(List(a,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),Not(IntegerQ(n)),Not(IntegerQ(p)),GtQ(p,C0),LtQ(n,CN1))));
IIntegrate(955,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Dist(Times(e,Subtract(Times(e,f),Times(d,g)),Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1)),Int(Times(Power(Plus(f,Times(g,x)),Subtract(n,C1)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x)),CN1)),x),x),Dist(Power(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),CN1),Int(Times(Power(Plus(f,Times(g,x)),Subtract(n,C1)),Subtract(Plus(Times(c,d,f),Times(CN1,b,e,f),Times(a,e,g)),Times(c,Subtract(Times(e,f),Times(d,g)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),x)),And(FreeQ(List(a,b,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),Not(IntegerQ(n)),Not(IntegerQ(p)),LtQ(p,CN1),GtQ(n,C0))));
IIntegrate(956,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Plus(Dist(Times(e,Subtract(Times(e,f),Times(d,g)),Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1)),Int(Times(Power(Plus(f,Times(g,x)),Subtract(n,C1)),Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x)),CN1)),x),x),Dist(Power(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),CN1),Int(Times(Power(Plus(f,Times(g,x)),Subtract(n,C1)),Subtract(Plus(Times(c,d,f),Times(a,e,g)),Times(c,Subtract(Times(e,f),Times(d,g)),x)),Power(Plus(a,Times(c,Sqr(x))),p)),x),x)),And(FreeQ(List(a,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),Not(IntegerQ(n)),Not(IntegerQ(p)),LtQ(p,CN1),GtQ(n,C0))));
IIntegrate(957,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(Times(Sqrt(Plus(f,Times(g,x))),Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x))))),CN1),Times(Power(Plus(f,Times(g,x)),Plus(n,C1D2)),Power(Plus(d,Times(e,x)),CN1)),x),x),And(FreeQ(List(a,b,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),IntegerQ(Plus(n,C1D2)))));
IIntegrate(958,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),CN1),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Int(ExpandIntegrand(Power(Times(Sqrt(Plus(f,Times(g,x))),Sqrt(Plus(a,Times(c,Sqr(x))))),CN1),Times(Power(Plus(f,Times(g,x)),Plus(n,C1D2)),Power(Plus(d,Times(e,x)),CN1)),x),x),And(FreeQ(List(a,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),IntegerQ(Plus(n,C1D2)))));
IIntegrate(959,Int(Times(Power(Times(g_DEFAULT,x_),n_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,x_)),CN1),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Subtract(Dist(Times(d,Power(Times(g,x),n),Power(Power(x,n),CN1)),Int(Times(Power(x,n),Power(Plus(a,Times(c,Sqr(x))),p),Power(Subtract(Sqr(d),Times(Sqr(e),Sqr(x))),CN1)),x),x),Dist(Times(e,Power(Times(g,x),n),Power(Power(x,n),CN1)),Int(Times(Power(x,Plus(n,C1)),Power(Plus(a,Times(c,Sqr(x))),p),Power(Subtract(Sqr(d),Times(Sqr(e),Sqr(x))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,g,n,p),x),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),Not(IntegerQ(p)),Not(IntegersQ(n,Times(C2,p))))));
IIntegrate(960,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),x),And(FreeQ(List(a,b,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(CN1,b,d,e),Times(a,Sqr(e))),C0),Or(IntegerQ(p),And(ILtQ(m,C0),ILtQ(n,C0))),Not(Or(IGtQ(m,C0),IGtQ(n,C0))))));
IIntegrate(961,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_DEFAULT)),x_Symbol),
    Condition(Int(ExpandIntegrand(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),Power(Plus(a,Times(c,Sqr(x))),p)),x),x),And(FreeQ(List(a,c,d,e,f,g),x),NeQ(Subtract(Times(e,f),Times(d,g)),C0),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),Or(IntegerQ(p),And(ILtQ(m,C0),ILtQ(n,C0))),Not(Or(IGtQ(m,C0),IGtQ(n,C0))))));
IIntegrate(962,Int(Times(Power(Times(g_DEFAULT,x_),n_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,x_)),m_),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Dist(Times(Power(Times(g,x),n),Power(Power(x,n),CN1)),Int(ExpandIntegrand(Times(Power(x,n),Power(Plus(a,Times(c,Sqr(x))),p)),Power(Subtract(Times(d,Power(Subtract(Sqr(d),Times(Sqr(e),Sqr(x))),CN1)),Times(e,x,Power(Subtract(Sqr(d),Times(Sqr(e),Sqr(x))),CN1))),Negate(m)),x),x),x),And(FreeQ(List(a,c,d,e,g,n,p),x),NeQ(Plus(Times(c,Sqr(d)),Times(a,Sqr(e))),C0),ILtQ(m,C0),Not(IntegerQ(p)),Not(IntegerQ(n)))));
IIntegrate(963,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),And(FreeQ(List(a,b,c,d,e,f,g,m,n,p),x),Not(Or(IGtQ(m,C0),IGtQ(n,C0))))));
IIntegrate(964,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_)),m_),Power(Plus(f_DEFAULT,Times(g_DEFAULT,x_)),n_),Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),Power(Plus(a,Times(c,Sqr(x))),p)),x),And(FreeQ(List(a,c,d,e,f,g,m,n,p),x),Not(Or(IGtQ(m,C0),IGtQ(n,C0))))));
IIntegrate(965,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,u_)),m_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,u_)),n_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,u_),Times(c_DEFAULT,Sqr(u_))),p_DEFAULT)),x_Symbol),
    Condition(Dist(Power(Coefficient(u,x,C1),CN1),Subst(Int(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p)),x),x,u),x),And(FreeQ(List(a,b,c,d,e,f,g,m,n,p),x),LinearQ(u,x),NeQ(u,x))));
IIntegrate(966,Int(Times(Power(Plus(d_DEFAULT,Times(e_DEFAULT,u_)),m_DEFAULT),Power(Plus(f_DEFAULT,Times(g_DEFAULT,u_)),n_DEFAULT),Power(Plus(a_,Times(c_DEFAULT,Sqr(u_))),p_DEFAULT)),x_Symbol),
    Condition(Dist(Power(Coefficient(u,x,C1),CN1),Subst(Int(Times(Power(Plus(d,Times(e,x)),m),Power(Plus(f,Times(g,x)),n),Power(Plus(a,Times(c,Sqr(x))),p)),x),x,u),x),And(FreeQ(List(a,c,d,e,f,g,m,n,p),x),LinearQ(u,x),NeQ(u,x))));
IIntegrate(967,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_DEFAULT)),x_Symbol),
    Condition(Dist(Power(Times(c,Power(f,CN1)),p),Int(Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(p,q)),x),x),And(FreeQ(List(a,b,c,d,e,f,p,q),x),EqQ(Subtract(Times(c,d),Times(a,f)),C0),EqQ(Subtract(Times(b,d),Times(a,e)),C0),Or(IntegerQ(p),GtQ(Times(c,Power(f,CN1)),C0)),Or(Not(IntegerQ(q)),LessEqual(LeafCount(Plus(d,Times(e,x),Times(f,Sqr(x)))),LeafCount(Plus(a,Times(b,x),Times(c,Sqr(x)))))))));
IIntegrate(968,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_DEFAULT)),x_Symbol),
    Condition(Dist(Times(Power(a,IntPart(p)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),FracPart(p)),Power(Times(Power(d,IntPart(p)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),FracPart(p))),CN1)),Int(Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(p,q)),x),x),And(FreeQ(List(a,b,c,d,e,f,p,q),x),EqQ(Subtract(Times(c,d),Times(a,f)),C0),EqQ(Subtract(Times(b,d),Times(a,e)),C0),Not(IntegerQ(p)),Not(IntegerQ(q)),Not(GtQ(Times(c,Power(f,CN1)),C0)))));
IIntegrate(969,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_DEFAULT)),x_Symbol),
    Condition(Dist(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),FracPart(p)),Power(Times(Power(Times(C4,c),IntPart(p)),Power(Plus(b,Times(C2,c,x)),Times(C2,FracPart(p)))),CN1)),Int(Times(Power(Plus(b,Times(C2,c,x)),Times(C2,p)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),x),And(FreeQ(List(a,b,c,d,e,f,p,q),x),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(p)))));
IIntegrate(970,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),q_DEFAULT)),x_Symbol),
    Condition(Dist(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),FracPart(p)),Power(Times(Power(Times(C4,c),IntPart(p)),Power(Plus(b,Times(C2,c,x)),Times(C2,FracPart(p)))),CN1)),Int(Times(Power(Plus(b,Times(C2,c,x)),Times(C2,p)),Power(Plus(d,Times(f,Sqr(x))),q)),x),x),And(FreeQ(List(a,b,c,d,f,p,q),x),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0),Not(IntegerQ(p)))));
IIntegrate(971,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(b,Times(C2,c,x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(p,C1)),CN1)),x),Dist(Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(p,C1)),CN1),Int(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Subtract(q,C1)),Simp(Plus(Times(C2,c,d,Plus(Times(C2,p),C3)),Times(b,e,q),Times(Plus(Times(C2,b,f,q),Times(C2,c,e,Plus(Times(C2,p),q,C3))),x),Times(C2,c,f,Plus(Times(C2,p),Times(C2,q),C3),Sqr(x))),x)),x),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),LtQ(p,CN1),GtQ(q,C0),Not(IGtQ(q,C0)))));
IIntegrate(972,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(b,Times(C2,c,x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(f,Sqr(x))),q),Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(p,C1)),CN1)),x),Dist(Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(p,C1)),CN1),Int(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(f,Sqr(x))),Subtract(q,C1)),Simp(Plus(Times(C2,c,d,Plus(Times(C2,p),C3)),Times(C2,b,f,q,x),Times(C2,c,f,Plus(Times(C2,p),Times(C2,q),C3),Sqr(x))),x)),x),x)),And(FreeQ(List(a,b,c,d,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1),GtQ(q,C0),Not(IGtQ(q,C0)))));
IIntegrate(973,Int(Times(Power(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(C2,c,x,Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Power(Times(CN4,a,c,Plus(p,C1)),CN1)),x),Dist(Power(Times(CN4,a,c,Plus(p,C1)),CN1),Int(Times(Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Subtract(q,C1)),Simp(Plus(Times(C2,c,d,Plus(Times(C2,p),C3)),Times(C2,c,e,Plus(Times(C2,p),q,C3),x),Times(C2,c,f,Plus(Times(C2,p),Times(C2,q),C3),Sqr(x))),x)),x),x)),And(FreeQ(List(a,c,d,e,f),x),NeQ(Subtract(Sqr(e),Times(C4,d,f))),LtQ(p,CN1),GtQ(q,C0),Not(IGtQ(q,C0)))));
IIntegrate(974,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(Times(C2,a,Sqr(c),e),Times(CN1,Sqr(b),c,e),Times(Power(b,C3),f),Times(b,c,Subtract(Times(c,d),Times(C3,a,f))),Times(c,Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,Plus(Times(b,e),Times(C2,a,f)))),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(q,C1)),Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),Plus(p,C1)),CN1)),x),Dist(Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),Plus(p,C1)),CN1),Int(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Simp(Plus(Times(C2,c,Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),Plus(p,C1)),Times(CN1,Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,Plus(Times(b,e),Times(C2,a,f)))),Subtract(Times(a,f,Plus(p,C1)),Times(c,d,Plus(p,C2)))),Times(CN1,e,Subtract(Subtract(Subtract(Times(Sqr(b),c,e),Times(C2,a,Sqr(c),e)),Times(Power(b,C3),f)),Times(b,c,Subtract(Times(c,d),Times(C3,a,f)))),Plus(p,q,C2)),Times(Subtract(Times(C2,f,Plus(Times(C2,a,Sqr(c),e),Times(CN1,Sqr(b),c,e),Times(Power(b,C3),f),Times(b,c,Subtract(Times(c,d),Times(C3,a,f)))),Plus(p,q,C2)),Times(Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,Plus(Times(b,e),Times(C2,a,f)))),Subtract(Times(b,f,Plus(p,C1)),Times(c,e,Plus(Times(C2,p),q,C4))))),x),Times(c,f,Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,Plus(Times(b,e),Times(C2,a,f)))),Plus(Times(C2,p),Times(C2,q),C5),Sqr(x))),x)),x),x)),And(FreeQ(List(a,b,c,d,e,f,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),LtQ(p,CN1),NeQ(Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),C0),Not(And(Not(IntegerQ(p)),ILtQ(q,CN1))),Not(IGtQ(q,C0)))));
IIntegrate(975,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(Times(Power(b,C3),f),Times(b,c,Subtract(Times(c,d),Times(C3,a,f))),Times(c,Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,C2,a,f)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(f,Sqr(x))),Plus(q,C1)),Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(Times(Sqr(b),d,f),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),CN1)),x),Dist(Power(Times(Subtract(Sqr(b),Times(C4,a,c)),Plus(Times(Sqr(b),d,f),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),CN1),Int(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(f,Sqr(x))),q),Simp(Plus(Times(C2,c,Plus(Times(Sqr(b),d,f),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),Times(CN1,Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,C2,a,f)),Subtract(Times(a,f,Plus(p,C1)),Times(c,d,Plus(p,C2)))),Times(Subtract(Times(C2,f,Plus(Times(Power(b,C3),f),Times(b,c,Subtract(Times(c,d),Times(C3,a,f)))),Plus(p,q,C2)),Times(Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,C2,a,f)),b,f,Plus(p,C1))),x),Times(c,f,Subtract(Plus(Times(C2,Sqr(c),d),Times(Sqr(b),f)),Times(c,C2,a,f)),Plus(Times(C2,p),Times(C2,q),C5),Sqr(x))),x)),x),x)),And(FreeQ(List(a,b,c,d,f,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),LtQ(p,CN1),NeQ(Plus(Times(Sqr(b),d,f),Sqr(Subtract(Times(c,d),Times(a,f)))),C0),Not(And(Not(IntegerQ(p)),ILtQ(q,CN1))),Not(IGtQ(q,C0)))));
IIntegrate(976,Int(Times(Power(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(Times(C2,a,Sqr(c),e),Times(c,Subtract(Times(C2,Sqr(c),d),Times(c,C2,a,f)),x)),Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(q,C1)),Power(Times(CN4,a,c,Plus(Times(a,c,Sqr(e)),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),CN1)),x),Dist(Power(Times(CN4,a,c,Plus(Times(a,c,Sqr(e)),Sqr(Subtract(Times(c,d),Times(a,f)))),Plus(p,C1)),CN1),Int(Times(Power(Plus(a,Times(c,Sqr(x))),Plus(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Simp(Plus(Times(C2,c,Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(CN1,a,e,c,e)),Plus(p,C1)),Times(CN1,Subtract(Times(C2,Sqr(c),d),Times(c,C2,a,f)),Subtract(Times(a,f,Plus(p,C1)),Times(c,d,Plus(p,C2)))),Times(CN1,e,CN2,a,Sqr(c),e,Plus(p,q,C2)),Times(Subtract(Times(C2,f,C2,a,Sqr(c),e,Plus(p,q,C2)),Times(Subtract(Times(C2,Sqr(c),d),Times(c,C2,a,f)),CN1,c,e,Plus(Times(C2,p),q,C4))),x),Times(c,f,Subtract(Times(C2,Sqr(c),d),Times(c,C2,a,f)),Plus(Times(C2,p),Times(C2,q),C5),Sqr(x))),x)),x),x)),And(FreeQ(List(a,c,d,e,f,q),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),LtQ(p,CN1),NeQ(Plus(Times(a,c,Sqr(e)),Sqr(Subtract(Times(c,d),Times(a,f)))),C0),Not(And(Not(IntegerQ(p)),ILtQ(q,CN1))),Not(IGtQ(q,C0)))));
IIntegrate(977,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(Times(b,f,Plus(Times(C3,p),Times(C2,q))),Times(CN1,c,e,Plus(Times(C2,p),q)),Times(C2,c,f,Plus(p,q),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(q,C1)),Power(Times(C2,Sqr(f),Plus(p,q),Plus(Times(C2,p),Times(C2,q),C1)),CN1)),x),Dist(Power(Times(C2,Sqr(f),Plus(p,q),Plus(Times(C2,p),Times(C2,q),C1)),CN1),Int(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C2)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Simp(Plus(Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)),Subtract(C1,p),Plus(Times(C2,p),q)),Times(CN1,Plus(p,q),Subtract(Times(Sqr(b),d,f,Subtract(C1,p)),Times(a,Plus(Times(f,Subtract(Times(b,e),Times(C2,a,f)),Plus(Times(C2,p),Times(C2,q),C1)),Times(c,Subtract(Times(C2,d,f),Times(Sqr(e),Plus(Times(C2,p),q)))))))),Times(Subtract(Times(C2,Subtract(Times(c,d),Times(a,f)),Subtract(Times(c,e),Times(b,f)),Subtract(C1,p),Plus(Times(C2,p),q)),Times(Plus(p,q),Plus(Times(Subtract(Sqr(b),Times(C4,a,c)),e,f,Subtract(C1,p)),Times(b,Plus(Times(c,Subtract(Sqr(e),Times(C4,d,f)),Plus(Times(C2,p),q)),Times(f,Plus(Times(C2,c,d),Times(CN1,b,e),Times(C2,a,f)),Plus(Times(C2,p),Times(C2,q),C1))))))),x),Times(Plus(Times(Sqr(Subtract(Times(c,e),Times(b,f))),Subtract(C1,p),p),Times(c,Plus(p,q),Subtract(Times(f,Subtract(Times(b,e),Times(C2,a,f)),Subtract(Plus(Times(C4,p),Times(C2,q)),C1)),Times(c,Plus(Times(C2,d,f,Subtract(C1,Times(C2,p))),Times(Sqr(e),Subtract(Plus(Times(C3,p),q),C1))))))),Sqr(x))),x)),x),x)),And(FreeQ(List(a,b,c,d,e,f,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),GtQ(p,C1),NeQ(Plus(p,q),C0),NeQ(Plus(Times(C2,p),Times(C2,q),C1),C0),Not(IGtQ(p,C0)),Not(IGtQ(q,C0)))));
IIntegrate(978,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Plus(Times(b,Plus(Times(C3,p),Times(C2,q))),Times(C2,c,Plus(p,q),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C1)),Power(Plus(d,Times(f,Sqr(x))),Plus(q,C1)),Power(Times(C2,f,Plus(p,q),Plus(Times(C2,p),Times(C2,q),C1)),CN1)),x),Dist(Power(Times(C2,f,Plus(p,q),Plus(Times(C2,p),Times(C2,q),C1)),CN1),Int(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),Subtract(p,C2)),Power(Plus(d,Times(f,Sqr(x))),q),Simp(Plus(Times(Sqr(b),d,Subtract(p,C1),Plus(Times(C2,p),q)),Times(CN1,Plus(p,q),Subtract(Times(Sqr(b),d,Subtract(C1,p)),Times(C2,a,Subtract(Times(c,d),Times(a,f,Plus(Times(C2,p),Times(C2,q),C1)))))),Times(CN1,Subtract(Times(C2,b,Subtract(Times(c,d),Times(a,f)),Subtract(C1,p),Plus(Times(C2,p),q)),Times(C2,Plus(p,q),b,Subtract(Times(C2,c,d,Plus(Times(C2,p),q)),Times(Plus(Times(c,d),Times(a,f)),Plus(Times(C2,p),Times(C2,q),C1))))),x),Times(Plus(Times(Sqr(b),f,p,Subtract(C1,p)),Times(C2,c,Plus(p,q),Subtract(Times(c,d,Subtract(Times(C2,p),C1)),Times(a,f,Subtract(Plus(Times(C4,p),Times(C2,q)),C1))))),Sqr(x))),x)),x),x)),And(FreeQ(List(a,b,c,d,f,q),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),GtQ(p,C1),NeQ(Plus(p,q),C0),NeQ(Plus(Times(C2,p),Times(C2,q),C1),C0),Not(IGtQ(p,C0)),Not(IGtQ(q,C0)))));
IIntegrate(979,Int(Times(Power(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Negate(Simp(Times(c,Subtract(Times(e,Plus(Times(C2,p),q)),Times(C2,f,Plus(p,q),x)),Power(Plus(a,Times(c,Sqr(x))),Subtract(p,C1)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(q,C1)),Power(Times(C2,Sqr(f),Plus(p,q),Plus(Times(C2,p),Times(C2,q),C1)),CN1)),x)),Dist(Power(Times(C2,Sqr(f),Plus(p,q),Plus(Times(C2,p),Times(C2,q),C1)),CN1),Int(Times(Power(Plus(a,Times(c,Sqr(x))),Subtract(p,C2)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q),Simp(Plus(Times(CN1,a,c,Sqr(e),Subtract(C1,p),Plus(Times(C2,p),q)),Times(a,Plus(p,q),Plus(Times(CN2,a,Sqr(f),Plus(Times(C2,p),Times(C2,q),C1)),Times(c,Subtract(Times(C2,d,f),Times(Sqr(e),Plus(Times(C2,p),q)))))),Times(Plus(Times(C2,Subtract(Times(c,d),Times(a,f)),c,e,Subtract(C1,p),Plus(Times(C2,p),q)),Times(C4,a,c,e,f,Subtract(C1,p),Plus(p,q))),x),Times(Subtract(Times(p,Sqr(c),Sqr(e),Subtract(C1,p)),Times(c,Plus(p,q),Plus(Times(C2,a,Sqr(f),Subtract(Plus(Times(C4,p),Times(C2,q)),C1)),Times(c,Plus(Times(C2,d,f,Subtract(C1,Times(C2,p))),Times(Sqr(e),Subtract(Plus(Times(C3,p),q),C1))))))),Sqr(x))),x)),x),x)),And(FreeQ(List(a,c,d,e,f,q),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),GtQ(p,C1),NeQ(Plus(p,q),C0),NeQ(Plus(Times(C2,p),Times(C2,q),C1),C0),Not(IGtQ(p,C0)),Not(IGtQ(q,C0)))));
IIntegrate(980,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(List(Set(q,Plus(Times(Sqr(c),Sqr(d)),Times(CN1,b,c,d,e),Times(a,c,Sqr(e)),Times(Sqr(b),d,f),Times(CN1,C2,a,c,d,f),Times(CN1,a,b,e,f),Times(Sqr(a),Sqr(f))))),Condition(Plus(Dist(Power(q,CN1),Int(Times(Subtract(Subtract(Plus(Times(Sqr(c),d),Times(CN1,b,c,e),Times(Sqr(b),f)),Times(a,c,f)),Times(Subtract(Times(Sqr(c),e),Times(b,c,f)),x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x),x),Dist(Power(q,CN1),Int(Times(Plus(Times(c,Sqr(e)),Times(CN1,c,d,f),Times(CN1,b,e,f),Times(a,Sqr(f)),Times(Subtract(Times(c,e,f),Times(b,Sqr(f))),x)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),CN1)),x),x)),NeQ(q,C0))),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0))));
IIntegrate(981,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(List(Set(q,Plus(Times(Sqr(c),Sqr(d)),Times(Sqr(b),d,f),Times(CN1,C2,a,c,d,f),Times(Sqr(a),Sqr(f))))),Condition(Subtract(Dist(Power(q,CN1),Int(Times(Plus(Times(Sqr(c),d),Times(Sqr(b),f),Times(CN1,a,c,f),Times(b,c,f,x)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1)),x),x),Dist(Power(q,CN1),Int(Times(Plus(Times(c,d,f),Times(CN1,a,Sqr(f)),Times(b,Sqr(f),x)),Power(Plus(d,Times(f,Sqr(x))),CN1)),x),x)),NeQ(q,C0))),And(FreeQ(List(a,b,c,d,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0))));
IIntegrate(982,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Dist(Times(CN2,e),Subst(Int(Power(Subtract(Times(e,Subtract(Times(b,e),Times(C4,a,f))),Times(Subtract(Times(b,d),Times(a,e)),Sqr(x))),CN1),x),x,Times(Plus(e,Times(C2,f,x)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),CN1D2))),x),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),EqQ(Subtract(Times(c,e),Times(b,f)),C0))));
IIntegrate(983,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Dist(Times(C2,c,Power(q,CN1)),Int(Power(Times(Plus(b,Negate(q),Times(C2,c,x)),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x),x),Dist(Times(C2,c,Power(q,CN1)),Int(Power(Times(Plus(b,q,Times(C2,c,x)),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x),x))),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),NeQ(Subtract(Times(c,e),Times(b,f)),C0),PosQ(Subtract(Sqr(b),Times(C4,a,c))))));
IIntegrate(984,Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Plus(Dist(C1D2,Int(Power(Times(Subtract(a,Times(Rt(Times(CN1,a,c),C2),x)),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x),x),Dist(C1D2,Int(Power(Times(Plus(a,Times(Rt(Times(CN1,a,c),C2),x)),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x),x)),And(FreeQ(List(a,c,d,e,f),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),PosQ(Times(CN1,a,c)))));
IIntegrate(985,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Subtract(Dist(Times(C2,c,Power(q,CN1)),Int(Power(Times(Plus(b,Negate(q),Times(C2,c,x)),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1),x),x),Dist(Times(C2,c,Power(q,CN1)),Int(Power(Times(Plus(b,q,Times(C2,c,x)),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1),x),x))),And(FreeQ(List(a,b,c,d,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),PosQ(Subtract(Sqr(b),Times(C4,a,c))))));
IIntegrate(986,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Subtract(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Subtract(Times(b,d),Times(a,e)),Subtract(Times(c,e),Times(b,f)))),C2))),Subtract(Dist(Power(Times(C2,q),CN1),Int(Times(Plus(Times(c,d),Times(CN1,a,f),q,Times(Subtract(Times(c,e),Times(b,f)),x)),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x),x),Dist(Power(Times(C2,q),CN1),Int(Times(Plus(Times(c,d),Times(CN1,a,f),Negate(q),Times(Subtract(Times(c,e),Times(b,f)),x)),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x),x))),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),NeQ(Subtract(Times(c,e),Times(b,f)),C0),NegQ(Subtract(Sqr(b),Times(C4,a,c))))));
IIntegrate(987,Int(Times(Power(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Plus(Sqr(Subtract(Times(c,d),Times(a,f))),Times(a,c,Sqr(e))),C2))),Subtract(Dist(Power(Times(C2,q),CN1),Int(Times(Plus(Times(c,d),Times(CN1,a,f),q,Times(c,e,x)),Power(Times(Plus(a,Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x),x),Dist(Power(Times(C2,q),CN1),Int(Times(Plus(Times(c,d),Times(CN1,a,f),Negate(q),Times(c,e,x)),Power(Times(Plus(a,Times(c,Sqr(x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1)),x),x))),And(FreeQ(List(a,c,d,e,f),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0),NegQ(Times(CN1,a,c)))));
IIntegrate(988,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1),Power(Plus(d_DEFAULT,Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(List(Set(q,Rt(Plus(Sqr(Subtract(Times(c,d),Times(a,f))),Times(Sqr(b),d,f)),C2))),Subtract(Dist(Power(Times(C2,q),CN1),Int(Times(Plus(Times(c,d),Times(CN1,a,f),q,Times(CN1,b,f,x)),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1)),x),x),Dist(Power(Times(C2,q),CN1),Int(Times(Plus(Times(c,d),Times(CN1,a,f),Negate(q),Times(CN1,b,f,x)),Power(Times(Plus(a,Times(b,x),Times(c,Sqr(x))),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1)),x),x))),And(FreeQ(List(a,b,c,d,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NegQ(Subtract(Sqr(b),Times(C4,a,c))))));
IIntegrate(989,Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_)))),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Subtract(Dist(Times(c,Power(f,CN1)),Int(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1D2),x),x),Dist(Power(f,CN1),Int(Times(Plus(Times(c,d),Times(CN1,a,f),Times(Subtract(Times(c,e),Times(b,f)),x)),Power(Times(Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))),Plus(d,Times(e,x),Times(f,Sqr(x)))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0))));
IIntegrate(990,Int(Times(Sqrt(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_)))),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Subtract(Dist(Times(c,Power(f,CN1)),Int(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1D2),x),x),Dist(Power(f,CN1),Int(Times(Subtract(Subtract(Times(c,d),Times(a,f)),Times(b,f,x)),Power(Times(Sqrt(Plus(a,Times(b,x),Times(c,Sqr(x)))),Plus(d,Times(f,Sqr(x)))),CN1)),x),x)),And(FreeQ(List(a,b,c,d,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0))));
IIntegrate(991,Int(Times(Sqrt(Plus(a_,Times(c_DEFAULT,Sqr(x_)))),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Subtract(Dist(Times(c,Power(f,CN1)),Int(Power(Plus(a,Times(c,Sqr(x))),CN1D2),x),x),Dist(Power(f,CN1),Int(Times(Plus(Times(c,d),Times(CN1,a,f),Times(c,e,x)),Power(Times(Sqrt(Plus(a,Times(c,Sqr(x)))),Plus(d,Times(e,x),Times(f,Sqr(x)))),CN1)),x),x)),And(FreeQ(List(a,c,d,e,f),x),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0))));
IIntegrate(992,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1D2),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(List(Set(r,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Dist(Times(Sqrt(Plus(b,r,Times(C2,c,x))),Sqrt(Plus(Times(C2,a),Times(Plus(b,r),x))),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1D2)),Int(Power(Times(Sqrt(Plus(b,r,Times(C2,c,x))),Sqrt(Plus(Times(C2,a),Times(Plus(b,r),x))),Sqrt(Plus(d,Times(e,x),Times(f,Sqr(x))))),CN1),x),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0),NeQ(Subtract(Sqr(e),Times(C4,d,f)),C0))));
IIntegrate(993,Int(Times(Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),CN1D2),Power(Plus(d_,Times(f_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(With(List(Set(r,Rt(Subtract(Sqr(b),Times(C4,a,c)),C2))),Dist(Times(Sqrt(Plus(b,r,Times(C2,c,x))),Sqrt(Plus(Times(C2,a),Times(Plus(b,r),x))),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),CN1D2)),Int(Power(Times(Sqrt(Plus(b,r,Times(C2,c,x))),Sqrt(Plus(Times(C2,a),Times(Plus(b,r),x))),Sqrt(Plus(d,Times(f,Sqr(x))))),CN1),x),x)),And(FreeQ(List(a,b,c,d,f),x),NeQ(Subtract(Sqr(b),Times(C4,a,c)),C0))));
IIntegrate(994,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),And(FreeQ(List(a,b,c,d,e,f,p,q),x),Not(IGtQ(p,C0)),Not(IGtQ(q,C0)))));
IIntegrate(995,Int(Times(Power(Plus(a_,Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_DEFAULT,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Unintegrable(Times(Power(Plus(a,Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),And(FreeQ(List(a,c,d,e,f,p,q),x),Not(IGtQ(p,C0)),Not(IGtQ(q,C0)))));
IIntegrate(996,Int(Times(Power(Plus(a_DEFAULT,Times(b_DEFAULT,u_),Times(c_DEFAULT,Sqr(u_))),p_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,u_),Times(f_DEFAULT,Sqr(u_))),q_DEFAULT)),x_Symbol),
    Condition(Dist(Power(Coefficient(u,x,C1),CN1),Subst(Int(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),x,u),x),And(FreeQ(List(a,b,c,d,e,f,p,q),x),LinearQ(u,x),NeQ(u,x))));
IIntegrate(997,Int(Times(Power(Plus(a_DEFAULT,Times(c_DEFAULT,Sqr(u_))),p_DEFAULT),Power(Plus(d_DEFAULT,Times(e_DEFAULT,u_),Times(f_DEFAULT,Sqr(u_))),q_DEFAULT)),x_Symbol),
    Condition(Dist(Power(Coefficient(u,x,C1),CN1),Subst(Int(Times(Power(Plus(a,Times(c,Sqr(x))),p),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),x,u),x),And(FreeQ(List(a,c,d,e,f,p,q),x),LinearQ(u,x),NeQ(u,x))));
IIntegrate(998,Int(Times(Power(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Dist(Power(Times(c,Power(f,CN1)),p),Int(Times(Power(Plus(g,Times(h,x)),m),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(p,q))),x),x),And(FreeQ(List(a,b,c,d,e,f,g,h,p,q),x),EqQ(Subtract(Times(c,d),Times(a,f)),C0),EqQ(Subtract(Times(b,d),Times(a,e)),C0),Or(IntegerQ(p),GtQ(Times(c,Power(f,CN1)),C0)),Or(Not(IntegerQ(q)),LessEqual(LeafCount(Plus(d,Times(e,x),Times(f,Sqr(x)))),LeafCount(Plus(a,Times(b,x),Times(c,Sqr(x)))))))));
IIntegrate(999,Int(Times(Power(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Dist(Times(Power(a,IntPart(p)),Power(Plus(a,Times(b,x),Times(c,Sqr(x))),FracPart(p)),Power(Times(Power(d,IntPart(p)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),FracPart(p))),CN1)),Int(Times(Power(Plus(g,Times(h,x)),m),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),Plus(p,q))),x),x),And(FreeQ(List(a,b,c,d,e,f,g,h,p,q),x),EqQ(Subtract(Times(c,d),Times(a,f)),C0),EqQ(Subtract(Times(b,d),Times(a,e)),C0),Not(IntegerQ(p)),Not(IntegerQ(q)),Not(GtQ(Times(c,Power(f,CN1)),C0)))));
IIntegrate(1000,Int(Times(Power(Plus(g_DEFAULT,Times(h_DEFAULT,x_)),m_DEFAULT),Power(Plus(a_,Times(b_DEFAULT,x_),Times(c_DEFAULT,Sqr(x_))),p_),Power(Plus(d_,Times(e_DEFAULT,x_),Times(f_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Dist(Times(Power(Plus(a,Times(b,x),Times(c,Sqr(x))),FracPart(p)),Power(Times(Power(Times(C4,c),IntPart(p)),Power(Plus(b,Times(C2,c,x)),Times(C2,FracPart(p)))),CN1)),Int(Times(Power(Plus(g,Times(h,x)),m),Power(Plus(b,Times(C2,c,x)),Times(C2,p)),Power(Plus(d,Times(e,x),Times(f,Sqr(x))),q)),x),x),And(FreeQ(List(a,b,c,d,e,f,g,h,m,p,q),x),EqQ(Subtract(Sqr(b),Times(C4,a,c)),C0))));
  }
}
}
