package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules15 { 
  public static IAST RULES = List( 
IIntegrate(301,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_DEFAULT),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(b,Power(d,CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x))),Subtract(p,C1)),x)),x),Simp(Star(Times(Subtract(Times(b,c),Times(a,d)),Power(d,CN1)),Integrate(Times(Power(Plus(a,Times(b,Sqr(x))),Subtract(p,C1)),Power(Plus(c,Times(d,Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),GtQ(p,C0),Or(EqQ(p,C1D2),EqQ(Denominator(p),C4),And(EqQ(p,QQ(2L,3L)),EqQ(Plus(Times(b,c),Times(C3,a,d)),C0)))))),
IIntegrate(302,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x))),p),x)),x),Simp(Star(Times(d,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Times(Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Plus(c,Times(d,Sqr(x))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(p,CN1),EqQ(Denominator(p),C4),Or(EqQ(p,QQ(-5L,4L)),EqQ(p,QQ(-7L,4L)))))),
IIntegrate(303,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(b,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Power(Plus(a,Times(b,Sqr(x))),CN1),x)),x),Simp(Star(Times(d,Power(Subtract(Times(b,c),Times(a,d)),CN1)),Integrate(Power(Plus(c,Times(d,Sqr(x))),CN1),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(304,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D3),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(b,Power(a,CN1)),C2))),Plus(Simp(Times(q,ArcTanh(Times(CSqrt3,Power(Times(q,x),CN1))),Power(Times(C2,Power(C2,QQ(2L,3L)),CSqrt3,Power(a,C1D3),d),CN1)),x),Negate(Simp(Times(q,ArcTan(Times(Power(a,C1D3),q,x,Power(Plus(Power(a,C1D3),Times(Power(C2,C1D3),Power(Plus(a,Times(b,Sqr(x))),C1D3))),CN1))),Power(Times(C2,Power(C2,QQ(2L,3L)),Power(a,C1D3),d),CN1)),x)),Simp(Times(q,ArcTan(Times(q,x)),Power(Times(C6,Power(C2,QQ(2L,3L)),Power(a,C1D3),d),CN1)),x),Simp(Times(q,ArcTanh(Times(CSqrt3,Subtract(Power(a,C1D3),Times(Power(C2,C1D3),Power(Plus(a,Times(b,Sqr(x))),C1D3))),Power(Times(Power(a,C1D3),q,x),CN1))),Power(Times(C2,Power(C2,QQ(2L,3L)),CSqrt3,Power(a,C1D3),d),CN1)),x))),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(Times(b,c),Times(C3,a,d)),C0),PosQ(Times(b,Power(a,CN1)))))),
IIntegrate(305,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D3),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,b,Power(a,CN1)),C2))),Plus(Simp(Times(q,ArcTan(Times(CSqrt3,Power(Times(q,x),CN1))),Power(Times(C2,Power(C2,QQ(2L,3L)),CSqrt3,Power(a,C1D3),d),CN1)),x),Simp(Times(q,ArcTanh(Times(Power(a,C1D3),q,x,Power(Plus(Power(a,C1D3),Times(Power(C2,C1D3),Power(Plus(a,Times(b,Sqr(x))),C1D3))),CN1))),Power(Times(C2,Power(C2,QQ(2L,3L)),Power(a,C1D3),d),CN1)),x),Negate(Simp(Times(q,ArcTanh(Times(q,x)),Power(Times(C6,Power(C2,QQ(2L,3L)),Power(a,C1D3),d),CN1)),x)),Simp(Times(q,ArcTan(Times(CSqrt3,Subtract(Power(a,C1D3),Times(Power(C2,C1D3),Power(Plus(a,Times(b,Sqr(x))),C1D3))),Power(Times(Power(a,C1D3),q,x),CN1))),Power(Times(C2,Power(C2,QQ(2L,3L)),CSqrt3,Power(a,C1D3),d),CN1)),x))),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Plus(Times(b,c),Times(C3,a,d)),C0),NegQ(Times(b,Power(a,CN1)))))),
IIntegrate(306,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D3),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(b,Power(a,CN1)),C2))),Plus(Simp(Times(q,ArcTan(Times(q,C1D3,x)),Power(Times(ZZ(12L),Rt(a,C3),d),CN1)),x),Simp(Times(q,ArcTan(Times(Sqr(Subtract(Rt(a,C3),Power(Plus(a,Times(b,Sqr(x))),C1D3))),Power(Times(C3,Sqr(Rt(a,C3)),q,x),CN1))),Power(Times(ZZ(12L),Rt(a,C3),d),CN1)),x),Negate(Simp(Times(q,ArcTanh(Times(CSqrt3,Subtract(Rt(a,C3),Power(Plus(a,Times(b,Sqr(x))),C1D3)),Power(Times(Rt(a,C3),q,x),CN1))),Power(Times(C4,CSqrt3,Rt(a,C3),d),CN1)),x)))),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Subtract(Times(b,c),Times(C9,a,d)),C0),PosQ(Times(b,Power(a,CN1)))))),
IIntegrate(307,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D3),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,b,Power(a,CN1)),C2))),Plus(Simp(Times(CN1,q,ArcTanh(Times(q,C1D3,x)),Power(Times(ZZ(12L),Rt(a,C3),d),CN1)),x),Simp(Times(q,ArcTanh(Times(Sqr(Subtract(Rt(a,C3),Power(Plus(a,Times(b,Sqr(x))),C1D3))),Power(Times(C3,Sqr(Rt(a,C3)),q,x),CN1))),Power(Times(ZZ(12L),Rt(a,C3),d),CN1)),x),Negate(Simp(Times(q,ArcTan(Times(CSqrt3,Subtract(Rt(a,C3),Power(Plus(a,Times(b,Sqr(x))),C1D3)),Power(Times(Rt(a,C3),q,x),CN1))),Power(Times(C4,CSqrt3,Rt(a,C3),d),CN1)),x)))),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Subtract(Times(b,c),Times(C9,a,d)),C0),NegQ(Times(b,Power(a,CN1)))))),
IIntegrate(308,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D4),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(Sqr(b),Power(a,CN1)),C4))),Subtract(Simp(Times(CN1,b,Power(Times(C2,a,d,q),CN1),ArcTan(Times(Plus(b,Times(Sqr(q),Sqrt(Plus(a,Times(b,Sqr(x)))))),Power(Times(Power(q,C3),x,Power(Plus(a,Times(b,Sqr(x))),C1D4)),CN1)))),x),Simp(Times(b,Power(Times(C2,a,d,q),CN1),ArcTanh(Times(Subtract(b,Times(Sqr(q),Sqrt(Plus(a,Times(b,Sqr(x)))))),Power(Times(Power(q,C3),x,Power(Plus(a,Times(b,Sqr(x))),C1D4)),CN1)))),x))),And(FreeQ(List(a,b,c,d),x),EqQ(Subtract(Times(b,c),Times(C2,a,d)),C0),PosQ(Times(Sqr(b),Power(a,CN1)))))),
IIntegrate(309,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D4),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(With(list(Set(q,Rt(Times(CN1,Sqr(b),Power(a,CN1)),C4))),Plus(Simp(Times(b,Power(Times(C2,CSqrt2,a,d,q),CN1),ArcTan(Times(q,x,Power(Times(CSqrt2,Power(Plus(a,Times(b,Sqr(x))),C1D4)),CN1)))),x),Simp(Times(b,Power(Times(C2,CSqrt2,a,d,q),CN1),ArcTanh(Times(q,x,Power(Times(CSqrt2,Power(Plus(a,Times(b,Sqr(x))),C1D4)),CN1)))),x))),And(FreeQ(List(a,b,c,d),x),EqQ(Subtract(Times(b,c),Times(C2,a,d)),C0),NegQ(Times(Sqr(b),Power(a,CN1)))))),
IIntegrate(310,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D4),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Simp(Star(Times(C2,Sqrt(Times(CN1,b,Sqr(x),Power(a,CN1))),Power(x,CN1)),Subst(Integrate(Times(Sqr(x),Power(Times(Sqrt(Subtract(C1,Times(Power(x,C4),Power(a,CN1)))),Plus(Times(b,c),Times(CN1,a,d),Times(d,Power(x,C4)))),CN1)),x),x,Power(Plus(a,Times(b,Sqr(x))),C1D4))),x),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(311,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),QQ(-3L,4L)),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Power(c,CN1),Integrate(Power(Plus(a,Times(b,Sqr(x))),QQ(-3L,4L)),x)),x),Simp(Star(Times(d,Power(c,CN1)),Integrate(Times(Sqr(x),Power(Times(Power(Plus(a,Times(b,Sqr(x))),QQ(3L,4L)),Plus(c,Times(d,Sqr(x)))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d),x),EqQ(Subtract(Times(b,c),Times(C2,a,d)),C0)))),
IIntegrate(312,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),QQ(-3L,4L)),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1)),x_Symbol),
    Condition(Simp(Star(Times(Sqrt(Times(CN1,b,Sqr(x),Power(a,CN1))),Power(Times(C2,x),CN1)),Subst(Integrate(Power(Times(Sqrt(Times(CN1,b,x,Power(a,CN1))),Power(Plus(a,Times(b,x)),QQ(3L,4L)),Plus(c,Times(d,x))),CN1),x),x,Sqr(x))),x),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(313,Integrate(Times(Sqrt(Plus(a_,Times(b_DEFAULT,Sqr(x_)))),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),QQ(-3L,2L))),x_Symbol),
    Condition(Simp(Times(Sqrt(Plus(a,Times(b,Sqr(x)))),Power(Times(c,Rt(Times(d,Power(c,CN1)),C2),Sqrt(Plus(c,Times(d,Sqr(x)))),Sqrt(Times(c,Plus(a,Times(b,Sqr(x))),Power(Times(a,Plus(c,Times(d,Sqr(x)))),CN1)))),CN1),EllipticE(ArcTan(Times(Rt(Times(d,Power(c,CN1)),C2),x)),Subtract(C1,Times(b,c,Power(Times(a,d),CN1))))),x),And(FreeQ(List(a,b,c,d),x),PosQ(Times(b,Power(a,CN1))),PosQ(Times(d,Power(c,CN1)))))),
IIntegrate(314,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,x,Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Plus(c,Times(d,Sqr(x))),q),Power(Times(C2,a,Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(C2,a,Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Plus(c,Times(d,Sqr(x))),Subtract(q,C1)),Simp(Plus(Times(c,Plus(Times(C2,p),C3)),Times(d,Plus(Times(C2,Plus(p,q,C1)),C1),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(p,CN1),LtQ(C0,q,C1),IntBinomialQ(a,b,c,d,C2,p,q,x)))),
IIntegrate(315,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Subtract(Simp(Times(Subtract(Times(a,d),Times(c,b)),x,Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Plus(c,Times(d,Sqr(x))),Subtract(q,C1)),Power(Times(C2,a,b,Plus(p,C1)),CN1)),x),Simp(Star(Power(Times(C2,a,b,Plus(p,C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Plus(c,Times(d,Sqr(x))),Subtract(q,C2)),Simp(Plus(Times(c,Subtract(Times(a,d),Times(c,b,Plus(Times(C2,p),C3)))),Times(d,Subtract(Times(a,d,Plus(Times(C2,Subtract(q,C1)),C1)),Times(b,c,Plus(Times(C2,Plus(p,q)),C1))),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(p,CN1),GtQ(q,C1),IntBinomialQ(a,b,c,d,C2,p,q,x)))),
IIntegrate(316,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,x,Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Plus(c,Times(d,Sqr(x))),Plus(q,C1)),Power(Times(C2,a,Plus(p,C1),Subtract(Times(b,c),Times(a,d))),CN1)),x),Simp(Star(Power(Times(C2,a,Plus(p,C1),Subtract(Times(b,c),Times(a,d))),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Plus(c,Times(d,Sqr(x))),q),Simp(Plus(Times(b,c),Times(C2,Plus(p,C1),Subtract(Times(b,c),Times(a,d))),Times(d,b,Plus(Times(C2,Plus(p,q,C2)),C1),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d,q),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(p,CN1),Not(And(Not(IntegerQ(p)),IntegerQ(q),LtQ(q,CN1))),IntBinomialQ(a,b,c,d,C2,p,q,x)))),
IIntegrate(317,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Integrate(ExpandIntegrand(Times(Power(Plus(a,Times(b,Sqr(x))),p),Power(Plus(c,Times(d,Sqr(x))),q)),x),x),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),IntegersQ(p,q),GtQ(Plus(p,q),C0)))),
IIntegrate(318,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(d,x,Power(Plus(a,Times(b,Sqr(x))),Plus(p,C1)),Power(Plus(c,Times(d,Sqr(x))),Subtract(q,C1)),Power(Times(b,Plus(Times(C2,Plus(p,q)),C1)),CN1)),x),Simp(Star(Power(Times(b,Plus(Times(C2,Plus(p,q)),C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Sqr(x))),p),Power(Plus(c,Times(d,Sqr(x))),Subtract(q,C2)),Simp(Plus(Times(c,Subtract(Times(b,c,Plus(Times(C2,Plus(p,q)),C1)),Times(a,d))),Times(d,Subtract(Times(b,c,Plus(Times(C2,Subtract(Plus(p,Times(C2,q)),C1)),C1)),Times(a,d,Plus(Times(C2,Subtract(q,C1)),C1))),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d,p),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),GtQ(q,C1),NeQ(Plus(Times(C2,Plus(p,q)),C1),C0),Not(IGtQ(p,C1)),IntBinomialQ(a,b,c,d,C2,p,q,x)))),
IIntegrate(319,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),p_),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),q_)),x_Symbol),
    Condition(Plus(Simp(Times(x,Power(Plus(a,Times(b,Sqr(x))),p),Power(Plus(c,Times(d,Sqr(x))),q),Power(Plus(Times(C2,Plus(p,q)),C1),CN1)),x),Simp(Star(Times(C2,Power(Plus(Times(C2,Plus(p,q)),C1),CN1)),Integrate(Times(Power(Plus(a,Times(b,Sqr(x))),Subtract(p,C1)),Power(Plus(c,Times(d,Sqr(x))),Subtract(q,C1)),Simp(Plus(Times(a,c,Plus(p,q)),Times(Plus(Times(q,Subtract(Times(b,c),Times(a,d))),Times(a,d,Plus(p,q))),Sqr(x))),x)),x)),x)),And(FreeQ(List(a,b,c,d),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),GtQ(q,C0),GtQ(p,C0),IntBinomialQ(a,b,c,d,C2,p,q,x)))),
IIntegrate(320,Integrate(Times(Power(Plus(a_,Times(b_DEFAULT,Sqr(x_))),CN1D2),Power(Plus(c_,Times(d_DEFAULT,Sqr(x_))),CN1D2)),x_Symbol),
    Condition(Simp(Times(Sqrt(Plus(a,Times(b,Sqr(x)))),Power(Times(a,Rt(Times(d,Power(c,CN1)),C2),Sqrt(Plus(c,Times(d,Sqr(x)))),Sqrt(Times(c,Plus(a,Times(b,Sqr(x))),Power(Times(a,Plus(c,Times(d,Sqr(x)))),CN1)))),CN1),EllipticF(ArcTan(Times(Rt(Times(d,Power(c,CN1)),C2),x)),Subtract(C1,Times(b,c,Power(Times(a,d),CN1))))),x),And(FreeQ(List(a,b,c,d),x),PosQ(Times(d,Power(c,CN1))),PosQ(Times(b,Power(a,CN1))),Not(SimplerSqrtQ(Times(b,Power(a,CN1)),Times(d,Power(c,CN1)))))))
  );
}
