package org.matheclipse.core.integrate.rubi;


import static org.matheclipse.core.expression.F.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctionCtors.*;
import static org.matheclipse.core.integrate.rubi.UtilityFunctions.*;
import org.matheclipse.core.interfaces.IAST;

/** 
 * IndefiniteIntegrationRules from the <a href="https://rulebasedintegration.org/">Rubi -
 * rule-based integrator</a>.
 *  
 */
class IntRules220 { 
  public static IAST RULES = List( 
IIntegrate(4401,Integrate(Times(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Times(a,c,x),x),Simp(Star(Times(b,d),Integrate(Sqr(Csc(Plus(e,Times(f,x)))),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),EqQ(Plus(Times(b,c),Times(a,d)),C0)))),
IIntegrate(4402,Integrate(Times(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Times(a,c,x),x),Simp(Star(Times(b,d),Integrate(Sqr(Csc(Plus(e,Times(f,x)))),x)),x),Simp(Star(Plus(Times(b,c),Times(a,d)),Integrate(Csc(Plus(e,Times(f,x))),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Plus(Times(b,c),Times(a,d)),C0)))),
IIntegrate(4403,Integrate(Times(Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Star(c,Integrate(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),x)),x),Simp(Star(d,Integrate(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Csc(Plus(e,Times(f,x)))),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4404,Integrate(Times(Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Star(Times(a,c),Integrate(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2),x)),x),Integrate(Times(Csc(Plus(e,Times(f,x))),Plus(Times(b,c),Times(a,d),Times(b,d,Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4405,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,d,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Power(Times(f,m),CN1)),x),Simp(Star(Power(m,CN1),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Simp(Plus(Times(a,c,m),Times(Plus(Times(b,c,m),Times(a,d,Subtract(Times(C2,m),C1))),Csc(Plus(e,Times(f,x))))),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),GtQ(m,C1),EqQ(Subtract(Sqr(a),Sqr(b)),C0),IntegerQ(Times(C2,m))))),
IIntegrate(4406,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,b,d,Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C1)),Power(Times(f,m),CN1)),x),Simp(Star(Power(m,CN1),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Subtract(m,C2)),Simp(Plus(Times(Sqr(a),c,m),Times(Plus(Times(Sqr(b),d,Subtract(m,C1)),Times(C2,a,b,c,m),Times(Sqr(a),d,m)),Csc(Plus(e,Times(f,x)))),Times(b,Plus(Times(b,c,m),Times(a,d,Subtract(Times(C2,m),C1))),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),GtQ(m,C1),NeQ(Subtract(Sqr(a),Sqr(b)),C0),IntegerQ(Times(C2,m))))),
IIntegrate(4407,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Subtract(Simp(Times(c,x,Power(a,CN1)),x),Simp(Star(Times(Subtract(Times(b,c),Times(a,d)),Power(a,CN1)),Integrate(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0)))),
IIntegrate(4408,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1D2),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Subtract(Simp(Star(Times(c,Power(a,CN1)),Integrate(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),x)),x),Simp(Star(Times(Subtract(Times(b,c),Times(a,d)),Power(a,CN1)),Integrate(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4409,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1D2),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Star(c,Integrate(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2),x)),x),Simp(Star(d,Integrate(Times(Csc(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4410,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Times(CN1,Subtract(Times(b,c),Times(a,d)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Power(Times(b,f,Plus(Times(C2,m),C1)),CN1)),x),Simp(Star(Power(Times(Sqr(a),Plus(Times(C2,m),C1)),CN1),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Subtract(Times(a,c,Plus(Times(C2,m),C1)),Times(Subtract(Times(b,c),Times(a,d)),Plus(m,C1),Csc(Plus(e,Times(f,x))))),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(m,CN1),EqQ(Subtract(Sqr(a),Sqr(b)),C0),IntegerQ(Times(C2,m))))),
IIntegrate(4411,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Times(b,Subtract(Times(b,c),Times(a,d)),Cot(Plus(e,Times(f,x))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Power(Times(a,f,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1)),x),Simp(Star(Power(Times(a,Plus(m,C1),Subtract(Sqr(a),Sqr(b))),CN1),Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),Plus(m,C1)),Simp(Plus(Times(c,Subtract(Sqr(a),Sqr(b)),Plus(m,C1)),Times(CN1,a,Subtract(Times(b,c),Times(a,d)),Plus(m,C1),Csc(Plus(e,Times(f,x)))),Times(b,Subtract(Times(b,c),Times(a,d)),Plus(m,C2),Sqr(Csc(Plus(e,Times(f,x)))))),x)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),LtQ(m,CN1),NeQ(Subtract(Sqr(a),Sqr(b)),C0),IntegerQ(Times(C2,m))))),
IIntegrate(4412,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),m_),Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_)),x_Symbol),
    Condition(Plus(Simp(Star(c,Integrate(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),x)),x),Simp(Star(d,Integrate(Times(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),m),Csc(Plus(e,Times(f,x)))),x)),x)),And(FreeQ(List(a,b,c,d,e,f,m),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),Not(IntegerQ(Times(C2,m)))))),
IIntegrate(4413,Integrate(Times(Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Power(c,CN1),Integrate(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),x)),x),Simp(Star(Times(d,Power(c,CN1)),Integrate(Times(Csc(Plus(e,Times(f,x))),Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Power(Plus(c,Times(d,Csc(Plus(e,Times(f,x))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),Or(EqQ(Subtract(Sqr(a),Sqr(b)),C0),EqQ(Subtract(Sqr(c),Sqr(d)),C0))))),
IIntegrate(4414,Integrate(Times(Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(a,Power(c,CN1)),Integrate(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2),x)),x),Simp(Star(Times(Subtract(Times(b,c),Times(a,d)),Power(c,CN1)),Integrate(Times(Csc(Plus(e,Times(f,x))),Power(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Plus(c,Times(d,Csc(Plus(e,Times(f,x)))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(4415,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),QQ(3L,2L)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Times(a,Power(c,CN1)),Integrate(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),x)),x),Simp(Star(Times(Subtract(Times(b,c),Times(a,d)),Power(c,CN1)),Integrate(Times(Csc(Plus(e,Times(f,x))),Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Power(Plus(c,Times(d,Csc(Plus(e,Times(f,x))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),Or(EqQ(Subtract(Sqr(a),Sqr(b)),C0),EqQ(Subtract(Sqr(c),Sqr(d)),C0))))),
IIntegrate(4416,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),QQ(3L,2L)),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Power(Times(c,d),CN1),Integrate(Times(Plus(Times(Sqr(a),d),Times(Sqr(b),c,Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x),Simp(Star(Times(Sqr(Subtract(Times(b,c),Times(a,d))),Power(Times(c,d),CN1)),Integrate(Times(Csc(Plus(e,Times(f,x))),Power(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Plus(c,Times(d,Csc(Plus(e,Times(f,x)))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0),NeQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(4417,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1D2),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_),CN1)),x_Symbol),
    Condition(Plus(Simp(Star(Power(Times(c,Subtract(Times(b,c),Times(a,d))),CN1),Integrate(Times(Subtract(Subtract(Times(b,c),Times(a,d)),Times(b,d,Csc(Plus(e,Times(f,x))))),Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x),Simp(Star(Times(Sqr(d),Power(Times(c,Subtract(Times(b,c),Times(a,d))),CN1)),Integrate(Times(Csc(Plus(e,Times(f,x))),Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Power(Plus(c,Times(d,Csc(Plus(e,Times(f,x))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),Or(EqQ(Subtract(Sqr(a),Sqr(b)),C0),EqQ(Subtract(Sqr(c),Sqr(d)),C0))))),
IIntegrate(4418,Integrate(Times(Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_),CN1D2),Power(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_),CN1)),x_Symbol),
    Condition(Subtract(Simp(Star(Power(c,CN1),Integrate(Power(Plus(a,Times(b,Csc(Plus(e,Times(f,x))))),CN1D2),x)),x),Simp(Star(Times(d,Power(c,CN1)),Integrate(Times(Csc(Plus(e,Times(f,x))),Power(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Plus(c,Times(d,Csc(Plus(e,Times(f,x)))))),CN1)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),NeQ(Subtract(Sqr(a),Sqr(b)),C0)))),
IIntegrate(4419,Integrate(Times(Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_))),x_Symbol),
    Condition(Simp(Star(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Sqrt(Plus(c,Times(d,Csc(Plus(e,Times(f,x)))))),Power(Cot(Plus(e,Times(f,x))),CN1)),Integrate(Cot(Plus(e,Times(f,x))),x)),x),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0),EqQ(Subtract(Sqr(a),Sqr(b)),C0),EqQ(Subtract(Sqr(c),Sqr(d)),C0)))),
IIntegrate(4420,Integrate(Times(Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),b_DEFAULT),a_)),Sqrt(Plus(Times($($s("§csc"),Plus(e_DEFAULT,Times(f_DEFAULT,x_))),d_DEFAULT),c_))),x_Symbol),
    Condition(Plus(Simp(Star(c,Integrate(Times(Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Power(Plus(c,Times(d,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x),Simp(Star(d,Integrate(Times(Csc(Plus(e,Times(f,x))),Sqrt(Plus(a,Times(b,Csc(Plus(e,Times(f,x)))))),Power(Plus(c,Times(d,Csc(Plus(e,Times(f,x))))),CN1D2)),x)),x)),And(FreeQ(List(a,b,c,d,e,f),x),NeQ(Subtract(Times(b,c),Times(a,d)),C0))))
  );
}
