package org.matheclipse.core.reflection.system.rulesets;

import static org.matheclipse.core.expression.F.*;
import org.matheclipse.core.interfaces.ISymbol;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.patternmatching.Matcher;

/**
 * <p>Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.</p>
 * <p>See GIT repository at: <a href="https://github.com/axkr/symja_android_library">github.com/axkr/symja_android_library under the tools directory</a>.</p>
 */
public interface ProductRules {
public static Matcher init1() {
  Matcher matcher = new Matcher();    // Product(x_Symbol,{x_,0,m_,s_}):=0/;0<m
matcher.caseOf(Product(x_Symbol,List(x_,C0,m_,s_)),
      Condition(C0,Less(C0,m)));
    // Product(1-4*x_^2/(1-4*i_+4*i_^2),{i_Symbol,1,Infinity}):=Cos(Pi*x)/;FreeQ(x,i)
matcher.caseOf(Product(Plus(C1,Times(CN4,Power(Plus(C1,Times(CN4,i_),Times(C4,Sqr(i_))),CN1),Sqr(x_))),list(i_Symbol,C1,oo)),
      Condition(Cos(Times(Pi,x)),FreeQ(x,i)));
    // Product(1-x_^2/i_^2,{i_Symbol,1,Infinity}):=Sin(Pi*x)/(Pi*x)/;FreeQ(x,i)
matcher.caseOf(Product(Plus(C1,Times(CN1,Power(i_,CN2),Sqr(x_))),list(i_Symbol,C1,oo)),
      Condition(Times(Power(Times(Pi,x),CN1),Sin(Times(Pi,x))),FreeQ(x,i)));
return matcher;
}
}
