package org.matheclipse.core.reflection.system.rules;

import static org.matheclipse.core.expression.F.Abs;
import static org.matheclipse.core.expression.F.ArcTan;
import static org.matheclipse.core.expression.F.CComplexInfinity;
import static org.matheclipse.core.expression.F.CPiHalf;
import static org.matheclipse.core.expression.F.Conjugate;
import static org.matheclipse.core.expression.F.IInit;
import static org.matheclipse.core.expression.F.ISet;
import static org.matheclipse.core.expression.F.ISetDelayed;
import static org.matheclipse.core.expression.F.List;
import static org.matheclipse.core.expression.F.x_;
import static org.matheclipse.core.expression.S.Abs;
import static org.matheclipse.core.expression.S.E;
import static org.matheclipse.core.expression.S.Pi;
import static org.matheclipse.core.expression.S.Undefined;
import static org.matheclipse.core.expression.S.x;
import org.matheclipse.core.interfaces.IAST;

/**
 * <p>
 * Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.
 * </p>
 * <p>
 * See GIT repository at:
 * <a href="https://github.com/axkr/symja_android_library">github.com/axkr/symja_android_library
 * under the tools directory</a>.
 * </p>
 */
public interface AbsRules {
  /**
   * <ul>
   * <li>index 0 - number of equal rules in <code>RULES</code></li>
   * </ul>
   */
  final public static int[] SIZES = {4, 1};

  final public static IAST RULES = List(IInit(Abs, SIZES),
      // Abs(Undefined)=Undefined
      ISet(Abs(Undefined), Undefined),
      // Abs(ArcTan(ComplexInfinity))=Pi/2
      ISet(Abs(ArcTan(CComplexInfinity)), CPiHalf),
      // Abs(E)=E
      ISet(Abs(E), E),
      // Abs(Pi)=Pi
      ISet(Abs(Pi), Pi),
      // Abs(Conjugate(x_)):=Abs(x)
      ISetDelayed(Abs(Conjugate(x_)), Abs(x)));
}
