package org.matheclipse.core.reflection.system.rules;

import static org.matheclipse.core.expression.F.*;
import org.matheclipse.core.interfaces.IAST;

/**
 * <p>Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.</p>
 * <p>See GIT repository at: <a href="https://github.com/axkr/symja_android_library">github.com/axkr/symja_android_library under the tools directory</a>.</p>
 */
public interface AbsRules {
  /**
   * <ul>
   * <li>index 0 - number of equal rules in <code>RULES</code></li>
	 * </ul>
	 */
  final public static int[] SIZES = { 3, 1 };

  final public static IAST RULES = List(
    IInit(Abs, SIZES),
    // Abs(ArcTan(ComplexInfinity))=Pi/2
    ISet(Abs(ArcTan(CComplexInfinity)),
      Times(C1D2,Pi)),
    // Abs(E)=E
    ISet(Abs(E),
      E),
    // Abs(Pi)=Pi
    ISet(Abs(Pi),
      Pi),
    // Abs(Conjugate(x_)):=Abs(x)
    ISetDelayed(Abs(Conjugate(x_)),
      Abs(x))
  );
}
