package org.matheclipse.core.reflection.system.rules;

import static org.matheclipse.core.expression.F.*;
import org.matheclipse.core.interfaces.ISymbol;
import org.matheclipse.core.interfaces.IAST;
import org.matheclipse.core.patternmatching.Matcher;

/**
 * <p>Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.</p>
 * <p>See GIT repository at: <a href="https://github.com/axkr/symja_android_library">github.com/axkr/symja_android_library under the tools directory</a>.</p>
 */
public interface Hypergeometric2F1Rules {
  /**
   * <ul>
   * <li>index 0 - number of equal rules in <code>RULES</code></li>
	 * </ul>
	 */
  final public static int[] SIZES = { 3, 94 };

  final public static IAST RULES = List(
    IInit(Hypergeometric2F1, SIZES),
    // Hypergeometric2F1(0,b_,c_,z_)=1
    ISet(Hypergeometric2F1(C0,b_,c_,z_),
      C1),
    // Hypergeometric2F1(a_,0,c_,z_)=1
    ISet(Hypergeometric2F1(a_,C0,c_,z_),
      C1),
    // Hypergeometric2F1(a_,b_,c_,0)=1
    ISet(Hypergeometric2F1(a_,b_,c_,C0),
      C1),
    // Hypergeometric2F1(-1/2,3/2,-11/2,z_):=(33-2*z*(105+8*z*(-35+2*z*(25+4*z*(-5+2*z)))))/(33*(1-z)^(13/2))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(-11L,2L),z_),
      Times(Power(Times(ZZ(33L),Power(Subtract(C1,z),QQ(13L,2L))),CN1),Plus(ZZ(33L),Times(CN2,z,Plus(ZZ(105L),Times(C8,z,Plus(ZZ(-35L),Times(C2,z,Plus(ZZ(25L),Times(C4,z,Plus(CN5,Times(C2,z)))))))))))),
    // Hypergeometric2F1(-1/2,3/2,-9/2,z_):=(21+16*(-1+z)*z*(7+8*(-1+z)*z))/(21*(1-z)^(11/2))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(-9L,2L),z_),
      Times(Power(Times(ZZ(21L),Power(Subtract(C1,z),QQ(11L,2L))),CN1),Plus(ZZ(21L),Times(ZZ(16L),Plus(CN1,z),z,Plus(C7,Times(C8,Plus(CN1,z),z)))))),
    // Hypergeometric2F1(-1/2,3/2,-7/2,z_):=(7-2*z*(15+8*z*(-3+2*z)))/(7*(1-z)^(9/2))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(-7L,2L),z_),
      Times(Power(Times(C7,Power(Subtract(C1,z),QQ(9L,2L))),CN1),Plus(C7,Times(CN2,z,Plus(ZZ(15L),Times(C8,z,Plus(CN3,Times(C2,z)))))))),
    // Hypergeometric2F1(-1/2,3/2,-5/2,z_):=(5+16*(-1+z)*z)/(5*(1-z)^(7/2))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(-5L,2L),z_),
      Times(Power(Times(C5,Power(Subtract(C1,z),QQ(7L,2L))),CN1),Plus(C5,Times(ZZ(16L),Plus(CN1,z),z)))),
    // Hypergeometric2F1(-1/2,3/2,-3/2,z_):=(1-2*z)/(1-z)^(5/2)
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(-3L,2L),z_),
      Times(Power(Subtract(C1,z),QQ(-5L,2L)),Plus(C1,Times(CN2,z)))),
    // Hypergeometric2F1(-1/2,3/2,-1/2,z_):=1/(1-z)^(3/2)
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),CN1D2,z_),
      Power(Subtract(C1,z),QQ(-3L,2L))),
    // Hypergeometric2F1(-1/2,3/2,1/2,z_):=(1-2*z)/Sqrt(1-z)
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),C1D2,z_),
      Times(Power(Subtract(C1,z),CN1D2),Plus(C1,Times(CN2,z)))),
    // Hypergeometric2F1(-1/2,3/2,1,z_):=(2*(2*EllipticE(z)-EllipticK(z)))/Pi
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),C1,z_),
      Times(C2,Power(Pi,CN1),Subtract(Times(C2,EllipticE(z)),EllipticK(z)))),
    // Hypergeometric2F1(-1/2,3/2,3/2,z_):=Sqrt(1-z)
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(3L,2L),z_),
      Sqrt(Subtract(C1,z))),
    // Hypergeometric2F1(-1/2,3/2,2,z_):=(4*((-1+2*z)*EllipticE(z)-(-1+z)*EllipticK(z)))/(3*Pi*z)
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),C2,z_),
      Times(C4,Power(Times(C3,Pi,z),CN1),Plus(Times(Plus(CN1,Times(C2,z)),EllipticE(z)),Times(CN1,Plus(CN1,z),EllipticK(z))))),
    // Hypergeometric2F1(-1/2,3/2,5/2,z_):=(3*(Sqrt(1-z)*Sqrt(z)*(-1+2*z)+ArcSin(Sqrt(z))))/(8*z^(3/2))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(5L,2L),z_),
      Times(C3,Power(Times(C8,Power(z,QQ(3L,2L))),CN1),Plus(Times(Sqrt(Subtract(C1,z)),Sqrt(z),Plus(CN1,Times(C2,z))),ArcSin(Sqrt(z))))),
    // Hypergeometric2F1(-1/2,3/2,3,z_):=(16*(2*(1-z+z^2)*EllipticE(z)-(2-3*z+z^2)*EllipticK(z)))/(15*Pi*z^2)
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),C3,z_),
      Times(Power(Times(ZZ(15L),Pi,Sqr(z)),CN1),ZZ(16L),Plus(Times(C2,Plus(C1,Negate(z),Sqr(z)),EllipticE(z)),Times(CN1,Plus(C2,Times(CN3,z),Sqr(z)),EllipticK(z))))),
    // Hypergeometric2F1(-1/2,3/2,7/2,z_):=5/(32*z^(5/2))*(Sqrt(1-z)*Sqrt(z)*(3-4*z+4*z^2)+(-3+6*z)*ArcSin(Sqrt(z)))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(7L,2L),z_),
      Times(C5,Power(Times(ZZ(32L),Power(z,QQ(5L,2L))),CN1),Plus(Times(Sqrt(Subtract(C1,z)),Sqrt(z),Plus(C3,Times(CN4,z),Times(C4,Sqr(z)))),Times(Plus(CN3,Times(C6,z)),ArcSin(Sqrt(z)))))),
    // Hypergeometric2F1(-1/2,3/2,4,z_):=32/(105*Pi*z^3)*((-8+19*z-9*z^2+6*z^3)*EllipticE(z)+(8-23*z+18*z^2-3*z^3)*EllipticK(z))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),C4,z_),
      Times(ZZ(32L),Power(Times(ZZ(105L),Pi,Power(z,C3)),CN1),Plus(Times(Plus(CN8,Times(ZZ(19L),z),Times(CN9,Sqr(z)),Times(C6,Power(z,C3))),EllipticE(z)),Times(Plus(C8,Times(ZZ(-23L),z),Times(ZZ(18L),Sqr(z)),Times(CN3,Power(z,C3))),EllipticK(z))))),
    // Hypergeometric2F1(-1/2,3/2,9/2,z_):=(35*(Sqrt(-(-1+z)*z)*(-1+2*z)*(15+8*(-1+z)*z)+3*(5+16*(-1+z)*z)*ArcSin(Sqrt(z))))/(1024*z^(7/2))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(9L,2L),z_),
      Times(Power(Times(ZZ(1024L),Power(z,QQ(7L,2L))),CN1),ZZ(35L),Plus(Times(Sqrt(Times(CN1,Plus(CN1,z),z)),Plus(CN1,Times(C2,z)),Plus(ZZ(15L),Times(C8,Plus(CN1,z),z))),Times(C3,Plus(C5,Times(ZZ(16L),Plus(CN1,z),z)),ArcSin(Sqrt(z)))))),
    // Hypergeometric2F1(-1/2,3/2,5,z_):=(256*(2*(8+(-1+z)*z*(28+5*(-1+z)*z))*EllipticE(z)+(-16+z*(64+z*(-93-5*(-10+z)*z)))*EllipticK(z)))/(1575*Pi*z^4)
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),C5,z_),
      Times(Power(Times(ZZ(1575L),Pi,Power(z,C4)),CN1),ZZ(256L),Plus(Times(C2,Plus(C8,Times(Plus(CN1,z),z,Plus(ZZ(28L),Times(C5,Plus(CN1,z),z)))),EllipticE(z)),Times(Plus(ZZ(-16L),Times(z,Plus(ZZ(64L),Times(z,Plus(ZZ(-93L),Times(CN5,Plus(CN10,z),z)))))),EllipticK(z))))),
    // Hypergeometric2F1(-1/2,3/2,11/2,z_):=(21*(Sqrt(-(-1+z)*z)*(105+4*(-1+z)*z*(95+24*(-1+z)*z))+15*(-7+2*z*(15+8*z*(-3+2*z)))*ArcSin(Sqrt(z))))/(4096*z^(9/2))
    ISetDelayed(Hypergeometric2F1(CN1D2,QQ(3L,2L),QQ(11L,2L),z_),
      Times(Power(Times(ZZ(4096L),Power(z,QQ(9L,2L))),CN1),ZZ(21L),Plus(Times(Sqrt(Times(CN1,Plus(CN1,z),z)),Plus(ZZ(105L),Times(C4,Plus(CN1,z),z,Plus(ZZ(95L),Times(ZZ(24L),Plus(CN1,z),z))))),Times(ZZ(15L),Plus(CN7,Times(C2,z,Plus(ZZ(15L),Times(C8,z,Plus(CN3,Times(C2,z)))))),ArcSin(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,1/2,-11/2,z_):=(231+8*(-1+z)*z*(189+16*(-1+z)*z*(21+8*(-1+z)*z)))/(231*(1-z)^(13/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,QQ(-11L,2L),z_),
      Times(Power(Times(ZZ(231L),Power(Subtract(C1,z),QQ(13L,2L))),CN1),Plus(ZZ(231L),Times(C8,Plus(CN1,z),z,Plus(ZZ(189L),Times(ZZ(16L),Plus(CN1,z),z,Plus(ZZ(21L),Times(C8,Plus(CN1,z),z)))))))),
    // Hypergeometric2F1(1/2,1/2,-9/2,z_):=(-(-1+2*z)*(63+32*(-1+z)*z*(7+4*(-1+z)*z)))/(63*(1-z)^(11/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,QQ(-9L,2L),z_),
      Times(CN1,Power(Times(ZZ(63L),Power(Subtract(C1,z),QQ(11L,2L))),CN1),Plus(CN1,Times(C2,z)),Plus(ZZ(63L),Times(ZZ(32L),Plus(CN1,z),z,Plus(C7,Times(C4,Plus(CN1,z),z)))))),
    // Hypergeometric2F1(1/2,1/2,-7/2,z_):=(35+32*(-1+z)*z*(5+4*(-1+z)*z))/(35*(1-z)^(9/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,QQ(-7L,2L),z_),
      Times(Power(Times(ZZ(35L),Power(Subtract(C1,z),QQ(9L,2L))),CN1),Plus(ZZ(35L),Times(ZZ(32L),Plus(CN1,z),z,Plus(C5,Times(C4,Plus(CN1,z),z)))))),
    // Hypergeometric2F1(1/2,1/2,-5/2,z_):=(-(-1+2*z)*(5+8*(-1+z)*z))/(5*(1-z)^(7/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,QQ(-5L,2L),z_),
      Times(CN1,Power(Times(C5,Power(Subtract(C1,z),QQ(7L,2L))),CN1),Plus(CN1,Times(C2,z)),Plus(C5,Times(C8,Plus(CN1,z),z)))),
    // Hypergeometric2F1(1/2,1/2,-3/2,z_):=(3+8*(-1+z)*z)/(3*(1-z)^(5/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,QQ(-3L,2L),z_),
      Times(Power(Times(C3,Power(Subtract(C1,z),QQ(5L,2L))),CN1),Plus(C3,Times(C8,Plus(CN1,z),z)))),
    // Hypergeometric2F1(1/2,1/2,-1/2,z_):=(1-2*z)/(1-z)^(3/2)
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,CN1D2,z_),
      Times(Power(Subtract(C1,z),QQ(-3L,2L)),Plus(C1,Times(CN2,z)))),
    // Hypergeometric2F1(1/2,1/2,1/2,z_):=1/Sqrt(1-z)
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,C1D2,z_),
      Power(Subtract(C1,z),CN1D2)),
    // Hypergeometric2F1(1/2,1/2,1,z_):=(2*EllipticK(z))/Pi
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,C1,z_),
      Times(C2,Power(Pi,CN1),EllipticK(z))),
    // Hypergeometric2F1(1/2,1/2,3/2,z_):=ArcSin(Sqrt(z))/Sqrt(z)
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,QQ(3L,2L),z_),
      Times(Power(z,CN1D2),ArcSin(Sqrt(z)))),
    // Hypergeometric2F1(1/2,1/2,2,z_):=(4*(EllipticE(z)+(-1+z)*EllipticK(z)))/(Pi*z)
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,C2,z_),
      Times(C4,Power(Times(Pi,z),CN1),Plus(EllipticE(z),Times(Plus(CN1,z),EllipticK(z))))),
    // Hypergeometric2F1(1/2,1/2,5/2,z_):=(3*(Sqrt(z)*Sqrt(1-z)+(-1+2*z)*ArcSin(Sqrt(z))))/(4*z^(3/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,QQ(5L,2L),z_),
      Times(C3,Power(Times(C4,Power(z,QQ(3L,2L))),CN1),Plus(Times(Sqrt(z),Sqrt(Subtract(C1,z))),Times(Plus(CN1,Times(C2,z)),ArcSin(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,1/2,3,z_):=16/(9*Pi*z^2)*((-2+4*z)*EllipticE(z)+(2-5*z+3*z^2)*EllipticK(z))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,C3,z_),
      Times(ZZ(16L),Power(Times(C9,Pi,Sqr(z)),CN1),Plus(Times(Plus(CN2,Times(C4,z)),EllipticE(z)),Times(Plus(C2,Times(CN5,z),Times(C3,Sqr(z))),EllipticK(z))))),
    // Hypergeometric2F1(1/2,1/2,7/2,z_):=15/(64*z^(5/2))*(3*Sqrt(1-z)*Sqrt(z)*(-1+2*z)+(3-8*z+8*z^2)*ArcSin(Sqrt(z)))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,QQ(7L,2L),z_),
      Times(ZZ(15L),Power(Times(ZZ(64L),Power(z,QQ(5L,2L))),CN1),Plus(Times(C3,Sqrt(Subtract(C1,z)),Sqrt(z),Plus(CN1,Times(C2,z))),Times(Plus(C3,Times(CN8,z),Times(C8,Sqr(z))),ArcSin(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,1/2,4,z_):=32/(75*Pi*z^3)*((8-23*z+23*z^2)*EllipticE(z)+(-8+27*z-34*z^2+15*z^3)*EllipticK(z))
    ISetDelayed(Hypergeometric2F1(C1D2,C1D2,C4,z_),
      Times(ZZ(32L),Power(Times(ZZ(75L),Pi,Power(z,C3)),CN1),Plus(Times(Plus(C8,Times(ZZ(-23L),z),Times(ZZ(23L),Sqr(z))),EllipticE(z)),Times(Plus(CN8,Times(ZZ(27L),z),Times(ZZ(-34L),Sqr(z)),Times(ZZ(15L),Power(z,C3))),EllipticK(z))))),
    // Hypergeometric2F1(1/2,1,-11/2,z_):=-(231+13*z*(-126+11*z*(35+3*z*(-20+7*z*(3+(-2+z)*z)))))/(231*(-1+z)^7)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(-11L,2L),z_),
      Times(CN1,Power(Times(ZZ(231L),Power(Plus(CN1,z),C7)),CN1),Plus(ZZ(231L),Times(ZZ(13L),z,Plus(ZZ(-126L),Times(ZZ(11L),z,Plus(ZZ(35L),Times(C3,z,Plus(ZZ(-20L),Times(C7,z,Plus(C3,Times(Plus(CN2,z),z)))))))))))),
    // Hypergeometric2F1(1/2,1,-9/2,z_):=(63-11*z*(35+3*z*(-30+7*z*(6+z*(-5+3*z)))))/(63*(-1+z)^6)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(-9L,2L),z_),
      Times(Power(Times(ZZ(63L),Power(Plus(CN1,z),C6)),CN1),Plus(ZZ(63L),Times(ZZ(-11L),z,Plus(ZZ(35L),Times(C3,z,Plus(ZZ(-30L),Times(C7,z,Plus(C6,Times(z,Plus(CN5,Times(C3,z)))))))))))),
    // Hypergeometric2F1(1/2,1,-7/2,z_):=(-35+3*z*(60-7*z*(18+5*z*(-4+3*z))))/(35*(-1+z)^5)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(-7L,2L),z_),
      Times(Power(Times(ZZ(35L),Power(Plus(CN1,z),C5)),CN1),Plus(ZZ(-35L),Times(C3,z,Plus(ZZ(60L),Times(CN7,z,Plus(ZZ(18L),Times(C5,z,Plus(CN4,Times(C3,z)))))))))),
    // Hypergeometric2F1(1/2,1,-5/2,z_):=(5-7*z*(3+5*(-1+z)*z))/(5*(-1+z)^4)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(-5L,2L),z_),
      Times(Power(Times(C5,Power(Plus(CN1,z),C4)),CN1),Plus(C5,Times(CN7,z,Plus(C3,Times(C5,Plus(CN1,z),z)))))),
    // Hypergeometric2F1(1/2,1,-3/2,z_):=(-3+5*(2-3*z)*z)/(3*(-1+z)^3)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(-3L,2L),z_),
      Times(Power(Times(C3,Power(Plus(CN1,z),C3)),CN1),Plus(CN3,Times(C5,Plus(C2,Times(CN3,z)),z)))),
    // Hypergeometric2F1(1/2,1,-1/2,z_):=(1-3*z)/(-1+z)^2
    ISetDelayed(Hypergeometric2F1(C1D2,C1,CN1D2,z_),
      Times(Power(Plus(CN1,z),CN2),Plus(C1,Times(CN3,z)))),
    // Hypergeometric2F1(1/2,1,1/2,z_):=1/(1-z)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,C1D2,z_),
      Power(Subtract(C1,z),CN1)),
    // Hypergeometric2F1(1/2,1,1,z_):=1/Sqrt(1-z)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,C1,z_),
      Power(Subtract(C1,z),CN1D2)),
    // Hypergeometric2F1(1/2,1,3/2,z_):=ArcTanh(Sqrt(z))/Sqrt(z)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(3L,2L),z_),
      Times(Power(z,CN1D2),ArcTanh(Sqrt(z)))),
    // Hypergeometric2F1(1/2,1,2,z_):=(2-2*Sqrt(1-z))/z
    ISetDelayed(Hypergeometric2F1(C1D2,C1,C2,z_),
      Times(Plus(C2,Times(CN2,Sqrt(Subtract(C1,z)))),Power(z,CN1))),
    // Hypergeometric2F1(1/2,1,5/2,z_):=(3*(Sqrt(z)+(-1+z)*ArcTanh(Sqrt(z))))/(2*z^(3/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(5L,2L),z_),
      Times(C3,Power(Times(C2,Power(z,QQ(3L,2L))),CN1),Plus(Sqrt(z),Times(Plus(CN1,z),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,1,3,z_):=((-1)*4*(2-2*Sqrt(1-z)+(-3+2*Sqrt(1-z))*z))/(3*z^2)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,C3,z_),
      Times(CN1,C4,Plus(C2,Times(CN2,Sqrt(Subtract(C1,z))),Times(Plus(CN3,Times(C2,Sqrt(Subtract(C1,z)))),z)),Power(Times(C3,Sqr(z)),CN1))),
    // Hypergeometric2F1(1/2,1,7/2,z_):=(5*(Sqrt(z)*(-3+5*z)+3*(-1+z)^2*ArcTanh(Sqrt(z))))/(8*z^(5/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(7L,2L),z_),
      Times(C5,Power(Times(C8,Power(z,QQ(5L,2L))),CN1),Plus(Times(Sqrt(z),Plus(CN3,Times(C5,z))),Times(C3,Sqr(Plus(CN1,z)),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,1,4,z_):=(2*(-8*(1-z)^(5/2)-20*z+15*z^2+8))/(5*z^3)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,C4,z_),
      Times(C2,Plus(Times(CN8,Power(Subtract(C1,z),QQ(5L,2L))),Times(ZZ(-20L),z),Times(ZZ(15L),Sqr(z)),C8),Power(Times(C5,Power(z,C3)),CN1))),
    // Hypergeometric2F1(1/2,1,9/2,z_):=(7*(Sqrt(z)*(15+z*(-40+33*z))+15*(-1+z)^3*ArcTanh(Sqrt(z))))/(48*z^(7/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(9L,2L),z_),
      Times(C7,Power(Times(ZZ(48L),Power(z,QQ(7L,2L))),CN1),Plus(Times(Sqrt(z),Plus(ZZ(15L),Times(z,Plus(ZZ(-40L),Times(ZZ(33L),z))))),Times(ZZ(15L),Power(Plus(CN1,z),C3),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,1,5,z_):=-8*(-16*(-1+Sqrt(1-z))+z*(8*(-7+6*Sqrt(1-z))+z*(70-48*Sqrt(1-z)+(-35+16*Sqrt(1-z))*z)))/(35*z^4)
    ISetDelayed(Hypergeometric2F1(C1D2,C1,C5,z_),
      Times(CN1,C8,Plus(Times(ZZ(-16L),Plus(CN1,Sqrt(Subtract(C1,z)))),Times(z,Plus(Times(C8,Plus(CN7,Times(C6,Sqrt(Subtract(C1,z))))),Times(z,Plus(ZZ(70L),Times(ZZ(-48L),Sqrt(Subtract(C1,z))),Times(Plus(ZZ(-35L),Times(ZZ(16L),Sqrt(Subtract(C1,z)))),z)))))),Power(Times(ZZ(35L),Power(z,C4)),CN1))),
    // Hypergeometric2F1(1/2,1,11/2,z_):=(3*Sqrt(z)*(-105+z*(385+z*(-511+279*z)))+315*(-1+z)^4*ArcTanh(Sqrt(z)))/(128*z^(9/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C1,QQ(11L,2L),z_),
      Times(Power(Times(ZZ(128L),Power(z,QQ(9L,2L))),CN1),Plus(Times(C3,Sqrt(z),Plus(ZZ(-105L),Times(z,Plus(ZZ(385L),Times(z,Plus(ZZ(-511L),Times(ZZ(279L),z))))))),Times(ZZ(315L),Power(Plus(CN1,z),C4),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,2,-11/2,z_):=(231+z*(-1890+13*z*(525+11*z*(-100+3*z*(45+7*z*(-6+5*z))))))/(231*(-1+z)^8)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(-11L,2L),z_),
      Times(Power(Times(ZZ(231L),Power(Plus(CN1,z),C8)),CN1),Plus(ZZ(231L),Times(z,Plus(ZZ(-1890L),Times(ZZ(13L),z,Plus(ZZ(525L),Times(ZZ(11L),z,Plus(ZZ(-100L),Times(C3,z,Plus(ZZ(45L),Times(C7,z,Plus(CN6,Times(C5,z)))))))))))))),
    // Hypergeometric2F1(1/2,2,-9/2,z_):=(-63+13*z*(35+11*z*(-10+3*z*(6+7*(-1+z)*z))))/(63*(-1+z)^7)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(-9L,2L),z_),
      Times(Power(Times(ZZ(63L),Power(Plus(CN1,z),C7)),CN1),Plus(ZZ(-63L),Times(ZZ(13L),z,Plus(ZZ(35L),Times(ZZ(11L),z,Plus(CN10,Times(C3,z,Plus(C6,Times(C7,Plus(CN1,z),z)))))))))),
    // Hypergeometric2F1(1/2,2,-7/2,z_):=(35+11*z*(-20+3*z*(18+7*z*(-4+5*z))))/(35*(-1+z)^6)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(-7L,2L),z_),
      Times(Power(Times(ZZ(35L),Power(Plus(CN1,z),C6)),CN1),Plus(ZZ(35L),Times(ZZ(11L),z,Plus(ZZ(-20L),Times(C3,z,Plus(ZZ(18L),Times(C7,z,Plus(CN4,Times(C5,z)))))))))),
    // Hypergeometric2F1(1/2,2,-5/2,z_):=(-5+3*z*(9+7*z*(-3+5*z)))/(5*(-1+z)^5)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(-5L,2L),z_),
      Times(Power(Times(C5,Power(Plus(CN1,z),C5)),CN1),Plus(CN5,Times(C3,z,Plus(C9,Times(C7,z,Plus(CN3,Times(C5,z)))))))),
    // Hypergeometric2F1(1/2,2,-3/2,z_):=(3+7*z*(-2+5*z))/(3*(-1+z)^4)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(-3L,2L),z_),
      Times(Power(Times(C3,Power(Plus(CN1,z),C4)),CN1),Plus(C3,Times(C7,z,Plus(CN2,Times(C5,z)))))),
    // Hypergeometric2F1(1/2,2,-1/2,z_):=(-1+5*z)/(-1+z)^3
    ISetDelayed(Hypergeometric2F1(C1D2,C2,CN1D2,z_),
      Times(Power(Plus(CN1,z),CN3),Plus(CN1,Times(C5,z)))),
    // Hypergeometric2F1(1/2,2,1/2,z_):=1/(-1+z)^2
    ISetDelayed(Hypergeometric2F1(C1D2,C2,C1D2,z_),
      Power(Plus(CN1,z),CN2)),
    // Hypergeometric2F1(1/2,2,1,z_):=(2-z)/(2*(1-z)^(3/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C2,C1,z_),
      Times(Power(Times(C2,Power(Subtract(C1,z),QQ(3L,2L))),CN1),Subtract(C2,z))),
    // Hypergeometric2F1(1/2,2,3/2,z_):=1/2*(1/(1-z)+ArcTanh(Sqrt(z))/Sqrt(z))
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(3L,2L),z_),
      Times(C1D2,Plus(Power(Subtract(C1,z),CN1),Times(Power(z,CN1D2),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,2,2,z_):=1/Sqrt(1-z)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,C2,z_),
      Power(Subtract(C1,z),CN1D2)),
    // Hypergeometric2F1(1/2,2,5/2,z_):=-3/(4*z)+(3*(1+z)*ArcTanh(Sqrt(z)))/(4*z^(3/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(5L,2L),z_),
      Plus(Times(CN1,C3,Power(Times(C4,z),CN1)),Times(C3,Plus(C1,z),Power(Times(C4,Power(z,QQ(3L,2L))),CN1),ArcTanh(Sqrt(z))))),
    // Hypergeometric2F1(1/2,2,3,z_):=(4*(2-Sqrt(1-z)*(2+z)))/(3*z^2)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,C3,z_),
      Times(C4,Plus(C2,Times(CN1,Sqrt(Subtract(C1,z)),Plus(C2,z))),Power(Times(C3,Sqr(z)),CN1))),
    // Hypergeometric2F1(1/2,2,7/2,z_):=(15*(-(-3+z)*Sqrt(z)+(-3+2*z+z^2)*ArcTanh(Sqrt(z))))/(16*z^(5/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(7L,2L),z_),
      Times(ZZ(15L),Power(Times(ZZ(16L),Power(z,QQ(5L,2L))),CN1),Plus(Times(CN1,Plus(CN3,z),Sqrt(z)),Times(Plus(CN3,Times(C2,z),Sqr(z)),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,2,4,z_):=(8*(-4+4*Sqrt(1-z)+(5-3*Sqrt(1-z))*z-Sqrt(1-z)*z^2))/(5*z^3)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,C4,z_),
      Times(C8,Plus(CN4,Times(C4,Sqrt(Subtract(C1,z))),Times(Plus(C5,Times(CN3,Sqrt(Subtract(C1,z)))),z),Times(CN1,Sqrt(Subtract(C1,z)),Sqr(z))),Power(Times(C5,Power(z,C3)),CN1))),
    // Hypergeometric2F1(1/2,2,9/2,z_):=(35*(Sqrt(z)*(15+z*(22+3*z))+3*(-5+z)*(1+z)^2*ArcTan(Sqrt(z))))/(96*z^(7/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(9L,2L),z_),
      Times(ZZ(35L),Power(Times(ZZ(96L),Power(z,QQ(7L,2L))),CN1),Plus(Times(Sqrt(z),Plus(ZZ(15L),Times(z,Plus(ZZ(22L),Times(C3,z))))),Times(C3,Plus(CN5,z),Sqr(Plus(C1,z)),ArcTan(Sqrt(z)))))),
    // Hypergeometric2F1(1/2,2,5,z_):=((-1)*16*(24*(-1+Sqrt(1-z))+z*(56-44*Sqrt(1-z)+z*(-35+16*Sqrt(1-z)+4*Sqrt(1-z)*z))))/(35*z^4)
    ISetDelayed(Hypergeometric2F1(C1D2,C2,C5,z_),
      Times(CN1,ZZ(16L),Plus(Times(ZZ(24L),Plus(CN1,Sqrt(Subtract(C1,z)))),Times(z,Plus(ZZ(56L),Times(ZZ(-44L),Sqrt(Subtract(C1,z))),Times(z,Plus(ZZ(-35L),Times(ZZ(16L),Sqrt(Subtract(C1,z))),Times(C4,Sqrt(Subtract(C1,z)),z)))))),Power(Times(ZZ(35L),Power(z,C4)),CN1))),
    // Hypergeometric2F1(1/2,2,11/2,z_):=(21*(Sqrt(z)*(105+z*(-265+(191-15*z)*z))+15*(-1+z)^3*(7+z)*ArcTanh(Sqrt(z))))/(256*z^(9/2))
    ISetDelayed(Hypergeometric2F1(C1D2,C2,QQ(11L,2L),z_),
      Times(ZZ(21L),Power(Times(ZZ(256L),Power(z,QQ(9L,2L))),CN1),Plus(Times(Sqrt(z),Plus(ZZ(105L),Times(z,Plus(ZZ(-265L),Times(Plus(ZZ(191L),Times(ZZ(-15L),z)),z))))),Times(ZZ(15L),Power(Plus(CN1,z),C3),Plus(C7,z),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1,3/2,-5/2,z_):=(-5+7*z*(4+5*z(-2+z*(4+z))))/(5*(-1+z)^5)
    ISetDelayed(Hypergeometric2F1(C1,QQ(3L,2L),QQ(-5L,2L),z_),
      Times(Power(Times(C5,Power(Plus(CN1,z),C5)),CN1),Plus(CN5,Times(C7,z,Plus(C4,Times(C5,$(z,Plus(CN2,Times(z,Plus(C4,z)))))))))),
    // Hypergeometric2F1(1,3/2,-3/2,z_):=(1+5*z(-1+z*(3+z)))/(-1+z)^4
    ISetDelayed(Hypergeometric2F1(C1,QQ(3L,2L),QQ(-3L,2L),z_),
      Times(Power(Plus(CN1,z),CN4),Plus(C1,Times(C5,$(z,Plus(CN1,Times(z,Plus(C3,z)))))))),
    // Hypergeometric2F1(1,3/2,-1/2,z_):=(-1+6*z+3*z^2)/(-1+z)^3
    ISetDelayed(Hypergeometric2F1(C1,QQ(3L,2L),CN1D2,z_),
      Times(Power(Plus(CN1,z),CN3),Plus(CN1,Times(C6,z),Times(C3,Sqr(z))))),
    // Hypergeometric2F1(1,3/2,1/2,z_):=(1+z)/(-1+z)^2
    ISetDelayed(Hypergeometric2F1(C1,QQ(3L,2L),C1D2,z_),
      Times(Power(Plus(CN1,z),CN2),Plus(C1,z))),
    // Hypergeometric2F1(1,3/2,1,z_):=1/(1-z)^(3/2)
    ISetDelayed(Hypergeometric2F1(C1,QQ(3L,2L),C1,z_),
      Power(Subtract(C1,z),QQ(-3L,2L))),
    // Hypergeometric2F1(1,3/2,3/2,z_):=(2*(1-Sqrt(1-z)))/(z*Sqrt(1-z))
    ISetDelayed(Hypergeometric2F1(C1,QQ(3L,2L),QQ(3L,2L),z_),
      Times(C2,Power(Times(z,Sqrt(Subtract(C1,z))),CN1),Subtract(C1,Sqrt(Subtract(C1,z))))),
    // Hypergeometric2F1(1,3/2,2,z_):=1/(1-z)^(3/2)
    ISetDelayed(Hypergeometric2F1(C1,QQ(3L,2L),C2,z_),
      Power(Subtract(C1,z),QQ(-3L,2L))),
    // Hypergeometric2F1(1,3/2,5/2,z_):=-3/z+(3*ArcTanh(Sqrt(z)))/z^(3/2)
    ISetDelayed(Hypergeometric2F1(C1,QQ(3L,2L),QQ(5L,2L),z_),
      Plus(Times(CN1,C3,Power(z,CN1)),Times(C3,Power(z,QQ(-3L,2L)),ArcTanh(Sqrt(z))))),
    // Hypergeometric2F1(1,7/2,-11/2,z_):=(55+13*z*(-45+11*z*(20+z*(-60+z*(126+z*(-210+z*(420+z*(180+(-15+z)*z))))))))/(55*(-1+z)^10)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(-11L,2L),z_),
      Times(Power(Times(ZZ(55L),Power(Plus(CN1,z),C10)),CN1),Plus(ZZ(55L),Times(ZZ(13L),z,Plus(ZZ(-45L),Times(ZZ(11L),z,Plus(ZZ(20L),Times(z,Plus(ZZ(-60L),Times(z,Plus(ZZ(126L),Times(z,Plus(ZZ(-210L),Times(z,Plus(ZZ(420L),Times(z,Plus(ZZ(180L),Times(Plus(ZZ(-15L),z),z)))))))))))))))))),
    // Hypergeometric2F1(1,7/2,-9/2,z_):=(-45+11*z*(40+3*z*(-60+z*(168+z*(-350+z*(840+z*(420+z*(-40+3*z))))))))/(45*(-1+z)^9)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(-9L,2L),z_),
      Times(Power(Times(ZZ(45L),Power(Plus(CN1,z),C9)),CN1),Plus(ZZ(-45L),Times(ZZ(11L),z,Plus(ZZ(40L),Times(C3,z,Plus(ZZ(-60L),Times(z,Plus(ZZ(168L),Times(z,Plus(ZZ(-350L),Times(z,Plus(ZZ(840L),Times(z,Plus(ZZ(420L),Times(z,Plus(ZZ(-40L),Times(C3,z)))))))))))))))))),
    // Hypergeometric2F1(1,7/2,-7/2,z_):=(5+3*z*(-15+z*(63+z*(-175+z*(525+z*(315+z*(-35+3*z)))))))/(5*(-1+z)^8)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(-7L,2L),z_),
      Times(Power(Times(C5,Power(Plus(CN1,z),C8)),CN1),Plus(C5,Times(C3,z,Plus(ZZ(-15L),Times(z,Plus(ZZ(63L),Times(z,Plus(ZZ(-175L),Times(z,Plus(ZZ(525L),Times(z,Plus(ZZ(315L),Times(z,Plus(ZZ(-35L),Times(C3,z)))))))))))))))),
    // Hypergeometric2F1(1,7/2,-5/2,z_):=(-5+7*z*(6+z*(-25+z*(100+z*(75+(-10+z)*z)))))/(5*(-1+z)^7)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(-5L,2L),z_),
      Times(Power(Times(C5,Power(Plus(CN1,z),C7)),CN1),Plus(CN5,Times(C7,z,Plus(C6,Times(z,Plus(ZZ(-25L),Times(z,Plus(ZZ(100L),Times(z,Plus(ZZ(75L),Times(Plus(CN10,z),z)))))))))))),
    // Hypergeometric2F1(1,7/2,-3/2,z_):=((1+z)*(3+z*(-28+z*(178+z*(-28+3*z)))))/(3*(-1+z)^6)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(-3L,2L),z_),
      Times(Power(Times(C3,Power(Plus(CN1,z),C6)),CN1),Plus(C1,z),Plus(C3,Times(z,Plus(ZZ(-28L),Times(z,Plus(ZZ(178L),Times(z,Plus(ZZ(-28L),Times(C3,z)))))))))),
    // Hypergeometric2F1(1,7/2,-1/2,z_):=(-5+60*z+90*z^2-20*z^3+3*z^4)/(5*(-1+z)^5)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),CN1D2,z_),
      Times(Power(Times(C5,Power(Plus(CN1,z),C5)),CN1),Plus(CN5,Times(ZZ(60L),z),Times(ZZ(90L),Sqr(z)),Times(ZZ(-20L),Power(z,C3)),Times(C3,Power(z,C4))))),
    // Hypergeometric2F1(1,7/2,1/2,z_):=(5+15*z-5*z^2+z^3)/(5*(-1+z)^4)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),C1D2,z_),
      Times(Power(Times(C5,Power(Plus(CN1,z),C4)),CN1),Plus(C5,Times(ZZ(15L),z),Times(CN5,Sqr(z)),Power(z,C3)))),
    // Hypergeometric2F1(1,7/2,1,z_):=1/(1-z)^(7/2)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),C1,z_),
      Power(Subtract(C1,z),QQ(-7L,2L))),
    // Hypergeometric2F1(1,7/2,3/2,z_):=(-15+10*z-3*z^2)/(15*(-1+z)^3)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(3L,2L),z_),
      Times(Power(Times(ZZ(15L),Power(Plus(CN1,z),C3)),CN1),Plus(ZZ(-15L),Times(C10,z),Times(CN3,Sqr(z))))),
    // Hypergeometric2F1(1,7/2,2,z_):=(2*(1-(1-z)^(5/2)))/(5*(1-z)^(5/2)*z)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),C2,z_),
      Times(C2,Subtract(C1,Power(Subtract(C1,z),QQ(5L,2L))),Power(Times(C5,Power(Subtract(C1,z),QQ(5L,2L)),z),CN1))),
    // Hypergeometric2F1(1,7/2,5/2,z_):=(5-3*z)/(5*(-1+z)^2)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(5L,2L),z_),
      Times(Power(Times(C5,Sqr(Plus(CN1,z))),CN1),Plus(C5,Times(CN3,z)))),
    // Hypergeometric2F1(1,7/2,3,z_):=(4*(2-(1-z)^(3/2)*(2+3*z)))/(15*(1-z)^(3/2)*z^2)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),C3,z_),
      Times(C4,Plus(C2,Times(CN1,Power(Subtract(C1,z),QQ(3L,2L)),Plus(C2,Times(C3,z)))),Power(Times(ZZ(15L),Power(Subtract(C1,z),QQ(3L,2L)),Sqr(z)),CN1))),
    // Hypergeometric2F1(1,7/2,7/2,z_):=1/(1-z)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(7L,2L),z_),
      Power(Subtract(C1,z),CN1)),
    // Hypergeometric2F1(1,7/2,4,z_):=(2*(8-Sqrt(1-z)*(8+4*z+3*z^2)))/(5*Sqrt(1-z)*z^3)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),C4,z_),
      Times(C2,Plus(C8,Times(CN1,Sqrt(Subtract(C1,z)),Plus(C8,Times(C4,z),Times(C3,Sqr(z))))),Power(Times(C5,Sqrt(Subtract(C1,z)),Power(z,C3)),CN1))),
    // Hypergeometric2F1(1,7/2,9/2,z_):=(7*(-15*Sqrt(z)-5*z^(3/2)-3*z^(5/2)+15*ArcTanh(Sqrt(z))))/(15*z^(7/2))
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(9L,2L),z_),
      Times(C7,Power(Times(ZZ(15L),Power(z,QQ(7L,2L))),CN1),Plus(Times(ZZ(-15L),Sqrt(z)),Times(CN5,Power(z,QQ(3L,2L))),Times(CN3,Power(z,QQ(5L,2L))),Times(ZZ(15L),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1,7/2,5,z_):=((-1)*8*(16*(-1+Sqrt(1-z))+z*(8+z*(2+z))))/(5*z^4)
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),C5,z_),
      Times(CN1,C8,Plus(Times(ZZ(16L),Plus(CN1,Sqrt(Subtract(C1,z)))),Times(z,Plus(C8,Times(z,Plus(C2,z))))),Power(Times(C5,Power(z,C4)),CN1))),
    // Hypergeometric2F1(1,7/2,11/2,z_):=(-3*Sqrt(z)*(-105+2*z*(35+z*(7+3*z)))+315*(-1+z)*ArcTanh(Sqrt(z)))/(10*z^(9/2))
    ISetDelayed(Hypergeometric2F1(C1,QQ(7L,2L),QQ(11L,2L),z_),
      Times(Power(Times(C10,Power(z,QQ(9L,2L))),CN1),Plus(Times(CN3,Sqrt(z),Plus(ZZ(-105L),Times(C2,z,Plus(ZZ(35L),Times(z,Plus(C7,Times(C3,z))))))),Times(ZZ(315L),Plus(CN1,z),ArcTanh(Sqrt(z)))))),
    // Hypergeometric2F1(1,1,2,z_):=-Log(1-z)/z
    ISetDelayed(Hypergeometric2F1(C1,C1,C2,z_),
      Times(CN1,Power(z,CN1),Log(Subtract(C1,z)))),
    // Hypergeometric2F1(1,b_,2,z_):=-(-1+(1-z)^b+z)/((1-z)^b*(-1+b)*z)
    ISetDelayed(Hypergeometric2F1(C1,b_,C2,z_),
      Times(CN1,Plus(CN1,Power(Subtract(C1,z),b),z),Power(Times(Power(Subtract(C1,z),b),Plus(CN1,b),z),CN1))),
    // Hypergeometric2F1(1,2,3/2,z_):=(Sqrt(z)*Sqrt(1-z)+ArcSin(Sqrt(z)))/(2*(1-z)^(3/2)*Sqrt(z))
    ISetDelayed(Hypergeometric2F1(C1,C2,QQ(3L,2L),z_),
      Times(Power(Times(C2,Power(Subtract(C1,z),QQ(3L,2L)),Sqrt(z)),CN1),Plus(Times(Sqrt(z),Sqrt(Subtract(C1,z))),ArcSin(Sqrt(z))))),
    // Hypergeometric2F1(3/2,2,5/2,a_.*z_^n_.):=((-1)*3*(Sqrt(a)*z^(n/2)-ArcTanh(Sqrt(a)*z^(n/2))+a*z^n*ArcTanh(Sqrt(a)*z^(n/2))))/(z^(1/2*3*n)*2*a^(3/2)*(-1+a*z^n))
    ISetDelayed(Hypergeometric2F1(QQ(3L,2L),C2,QQ(5L,2L),Times(a_DEFAULT,Power(z_,n_DEFAULT))),
      Times(CN1,C3,Power(Times(Power(z,Times(C1D2,C3,n)),C2,Power(a,QQ(3L,2L)),Plus(CN1,Times(a,Power(z,n)))),CN1),Plus(Times(Sqrt(a),Power(z,Times(C1D2,n))),Negate(ArcTanh(Times(Sqrt(a),Power(z,Times(C1D2,n))))),Times(a,Power(z,n),ArcTanh(Times(Sqrt(a),Power(z,Times(C1D2,n)))))))),
    // Hypergeometric2F1(m_Integer,n_Integer,2,1):=CatalanNumber(-n)/;n<0&&m==n+1
    ISetDelayed(Hypergeometric2F1($p(m, Integer),$p(n, Integer),C2,C1),
      Condition(CatalanNumber(Negate(n)),And(Less(n,C0),Equal(m,Plus(n,C1))))),
    // Hypergeometric2F1(a_,b_,c_,1):=(Gamma(c)*Gamma(-a-b+c))/(Gamma(-a+c)*Gamma(-b+c))/;Re(-a-b+c)>0
    ISetDelayed(Hypergeometric2F1(a_,b_,c_,C1),
      Condition(Times(Gamma(c),Power(Times(Gamma(Plus(Negate(a),c)),Gamma(Plus(Negate(b),c))),CN1),Gamma(Plus(Negate(a),Negate(b),c))),Greater(Re(Plus(Negate(a),Negate(b),c)),C0))),
    // Hypergeometric2F1(a_,b_,c_,z_):=(-1/(-1+b)+b/(-1+b)+z/(-1+b)+z*a/(-1+b)-b/(-1+b)*z)/(1-z)^(1+a)/;NumberQ(b)&&NumberQ(c)&&!(IntegerQ(c)&&c<0)&&PossibleZeroQ(-1+b-c)
    ISetDelayed(Hypergeometric2F1(a_,b_,c_,z_),
      Condition(Times(Power(Subtract(C1,z),Subtract(CN1,a)),Plus(Negate(Power(Plus(CN1,b),CN1)),Times(Power(Plus(CN1,b),CN1),b),Times(Power(Plus(CN1,b),CN1),z),Times(z,a,Power(Plus(CN1,b),CN1)),Times(CN1,Power(Plus(CN1,b),CN1),b,z))),And(And(NumberQ(b),NumberQ(c)),Not(And(IntegerQ(c),Less(c,C0))),PossibleZeroQ(Plus(CN1,b,Negate(c)))))),
    // Hypergeometric2F1(b_,a_,c_,z_):=(-1/(-1+b)+b/(-1+b)+z/(-1+b)+z*a/(-1+b)-b/(-1+b)*z)/(1-z)^(1+a)/;NumberQ(b)&&NumberQ(c)&&!(IntegerQ(c)&&c<0)&&PossibleZeroQ(-1+b-c)
    ISetDelayed(Hypergeometric2F1(b_,a_,c_,z_),
      Condition(Times(Power(Subtract(C1,z),Subtract(CN1,a)),Plus(Negate(Power(Plus(CN1,b),CN1)),Times(Power(Plus(CN1,b),CN1),b),Times(Power(Plus(CN1,b),CN1),z),Times(z,a,Power(Plus(CN1,b),CN1)),Times(CN1,Power(Plus(CN1,b),CN1),b,z))),And(And(NumberQ(b),NumberQ(c)),Not(And(IntegerQ(c),Less(c,C0))),PossibleZeroQ(Plus(CN1,b,Negate(c))))))
  );
}
