package org.matheclipse.core.reflection.system.rules;

import static org.matheclipse.core.expression.F.*;
import org.matheclipse.core.interfaces.IAST;

/**
 * Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.<br />
 * See GIT repository at: <a href="https://bitbucket.org/axelclk/symjaunittests">https://bitbucket.org/axelclk/symjaunittests</a>.
 */
public interface LogRules {
  final public static IAST RULES = List(
    Set(Log(C1),
      C0),
    Set(Log(E),
      C1),
    SetDelayed(Log(Power(E,$p(x,IntegerQ))),
      x),
    SetDelayed(Log(Power(E,$p(x,Rational))),
      x),
    Set(Log(Power(E,CI)),
      CI),
    Set(Log(Exp(CNI)),
      CNI),
    Set(Log(C0),
      CNInfinity),
    SetDelayed(Log(a_,E),
      Power(Log(a),CN1)),
    SetDelayed(Log(a_,Power(E,$p(m,IntegerQ))),
      Times(m,Power(Log(a),CN1))),
    SetDelayed(Log(a_,C0),
      Times(CN1,CInfinity,Power(Log(a),CN1))),
    Set(Log(a_,C1),
      C0),
    SetDelayed(Log(a_,CN1),
      Times(CI,Pi,Power(Log(a),CN1))),
    SetDelayed(Log(E,z_),
      Log(z)),
    Set(Log(C0,z_),
      C0),
    Set(Log(C1,z_),
      CComplexInfinity),
    SetDelayed(Log(CN1,z_),
      Times(CN1,CI,Power(Pi,CN1),Log(z))),
    Set(Log(a_,C1),
      Indeterminate)
  );
}