package org.matheclipse.core.reflection.system.rules;

import static org.matheclipse.core.expression.F.*;
import org.matheclipse.core.interfaces.IAST;

/**
 * <p>Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.</p>
 * <p>See GIT repository at: <a href="https://bitbucket.org/axelclk/symja_android_library">bitbucket.org/axelclk/symja_android_library under the tools directory</a>.</p>
 */
public interface ProductRules {
  final public static IAST RULES = List(
    // Product(x_Symbol,{x_,0,m_}):=0
    ISetDelayed(Product($p(x,Symbol),List(x_,C0,m_)),
      C0),
    // Product(x_Symbol,{x_,0,m_,s_}):=0
    ISetDelayed(Product($p(x,Symbol),List(x_,C0,m_,s_)),
      C0),
    // Product(x_Symbol,{x_,1,m_}):=m!/;FreeQ(x,m)
    ISetDelayed(Product($p(x,Symbol),List(x_,C1,m_)),
      Condition(Factorial(m),FreeQ(x,m)))
  );
}
