package org.matheclipse.core.reflection.system.rules;

import static org.matheclipse.core.expression.F.*;
import org.matheclipse.core.interfaces.IAST;

/**
 * Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.<br />
 * See GIT repository at: <a href="https://bitbucket.org/axelclk/symjaunittests">https://bitbucket.org/axelclk/symjaunittests</a>.
 */
public interface SecRules {
  final public static IAST RULES = List(
    ISet(Sec(C0),
      C1),
    ISet(Sec(Times(QQ(1L,12L),Pi)),
      Plus(Times(CN1,Sqrt(C2)),Sqrt(ZZ(6L)))),
    ISet(Sec(Times(QQ(1L,10L),Pi)),
      Sqrt(Plus(C2,Times(CN2,Power(C5,CN1D2))))),
    ISet(Sec(Times(QQ(1L,8L),Pi)),
      Times(C2,Power(Plus(C2,Sqrt(C2)),CN1D2))),
    ISet(Sec(Times(QQ(1L,6L),Pi)),
      Times(C2,Power(C3,CN1D2))),
    ISet(Sec(Times(QQ(1L,5L),Pi)),
      Plus(CN1,Sqrt(C5))),
    ISet(Sec(Times(C1D4,Pi)),
      Sqrt(C2)),
    ISet(Sec(Times(C1D2,Pi)),
      CComplexInfinity),
    ISet(Sec(Times(C1D3,Pi)),
      C2),
    ISet(Sec(Times(QQ(2L,3L),Pi)),
      CN2),
    ISet(Sec(Pi),
      CN1),
    ISet(Sec(Times(QQ(5L,4L),Pi)),
      Times(CN1,Sqrt(C2))),
    ISet(Sec(Times(QQ(4L,3L),Pi)),
      CN2),
    ISet(Sec(Times(QQ(3L,2L),Pi)),
      CComplexInfinity),
    ISet(Sec(Times(QQ(8L,5L),Pi)),
      Plus(C1,Sqrt(C5))),
    ISet(Sec(Times(QQ(5L,3L),Pi)),
      C2),
    ISet(Sec(Times(QQ(9L,5L),Pi)),
      Plus(CN1,Sqrt(C5))),
    ISet(Sec(Times(QQ(11L,6L),Pi)),
      Times(C2,Power(C3,CN1D2))),
    ISet(Sec(Times(QQ(23L,12L),Pi)),
      Plus(Times(CN1,Sqrt(C2)),Sqrt(ZZ(6L)))),
    ISet(Sec(Times(C2,Pi)),
      C1),
    ISet(Sec(Times(CI,CInfinity)),
      C0),
    ISet(Sec(Times(CNI,CInfinity)),
      C0),
    ISet(Sec(CComplexInfinity),
      Indeterminate)
  );
}