package org.matheclipse.core.reflection.system.rules;

import static org.matheclipse.core.expression.F.C0;
import static org.matheclipse.core.expression.F.C1D2;
import static org.matheclipse.core.expression.F.C2;
import static org.matheclipse.core.expression.F.CN1;
import static org.matheclipse.core.expression.F.CN1D2;
import static org.matheclipse.core.expression.F.Cosh;
import static org.matheclipse.core.expression.F.IInit;
import static org.matheclipse.core.expression.F.ISet;
import static org.matheclipse.core.expression.F.ISetDelayed;
import static org.matheclipse.core.expression.F.List;
import static org.matheclipse.core.expression.F.Plus;
import static org.matheclipse.core.expression.F.Power;
import static org.matheclipse.core.expression.F.Sinh;
import static org.matheclipse.core.expression.F.Sqrt;
import static org.matheclipse.core.expression.F.StruveL;
import static org.matheclipse.core.expression.F.Times;
import static org.matheclipse.core.expression.F.x_;
import static org.matheclipse.core.expression.F.y_;
import static org.matheclipse.core.expression.F.z_;
import static org.matheclipse.core.expression.S.Pi;
import static org.matheclipse.core.expression.S.StruveL;
import static org.matheclipse.core.expression.S.Undefined;
import static org.matheclipse.core.expression.S.z;
import org.matheclipse.core.interfaces.IAST;

/**
 * <p>
 * Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.
 * </p>
 * <p>
 * See GIT repository at:
 * <a href="https://github.com/axkr/symja_android_library">github.com/axkr/symja_android_library
 * under the tools directory</a>.
 * </p>
 */
public interface StruveLRules {
  /**
   * <ul>
   * <li>index 0 - number of equal rules in <code>RULES</code></li>
   * </ul>
   */
  final public static int[] SIZES = {1, 3};

  final public static IAST RULES = List(IInit(StruveL, SIZES),
      // StruveL(-1,0)=Times(2/Pi)
      ISet(StruveL(CN1, C0), Times(C2, Power(Pi, CN1))),
      // StruveL(-1/2,z_):=Sqrt(2/(Pi*z))*Sinh(z)
      ISetDelayed(StruveL(CN1D2, z_), Times(Sqrt(Times(C2, Power(Times(Pi, z), CN1))), Sinh(z))),
      // StruveL(1/2,z_):=Sqrt(2/(Pi*z))*(-1+Cosh(z))
      ISetDelayed(StruveL(C1D2, z_),
          Times(Sqrt(Times(C2, Power(Times(Pi, z), CN1))), Plus(CN1, Cosh(z)))),
      // StruveL(Undefined,y_):=Undefined
      ISetDelayed(StruveL(Undefined, y_), Undefined),
      // StruveL(x_,Undefined):=Undefined
      ISetDelayed(StruveL(x_, Undefined), Undefined));
}
