package org.matheclipse.core.reflection.system.rules;

import static org.matheclipse.core.expression.F.*;
import org.matheclipse.core.interfaces.IAST;

/**
 * <p>Generated by <code>org.matheclipse.core.preprocessor.RulePreprocessor</code>.</p>
 * <p>See GIT repository at: <a href="https://github.com/axkr/symja_android_library">github.com/axkr/symja_android_library under the tools directory</a>.</p>
 */
public interface WhittakerWRules {
  final public static IAST RULES = List(
    // WhittakerW(k_,0,0):=0
    ISetDelayed(WhittakerW(k_,C0,C0),
      C0),
    // WhittakerW(k_,1,0):=1/Gamma(1-k)
    ISetDelayed(WhittakerW(k_,C1,C0),
      Power(Gamma(Subtract(C1,k)),CN1))
  );
}
